// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'en'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const enObjects: NonNullable<TranslationData['objects']> = {
  sys_position: {
    label: "Position",
    pluralLabel: "Positions",
    description: "Position definitions — flat capability-distribution groups (ADR-0090 D3)",
    fields: {
      label: {
        label: "Display Name"
      },
      name: {
        label: "API Name",
        help: "Unique machine name for the position (e.g. admin, editor, viewer)"
      },
      description: {
        label: "Description"
      },
      permissions: {
        label: "Permissions",
        help: "JSON-serialized array of permission strings"
      },
      active: {
        label: "Active"
      },
      is_default: {
        label: "Default Position",
        help: "Automatically assigned to new users"
      },
      managed_by: {
        label: "Managed By",
        help: "Record provenance: platform (built-in) / package (declared) / admin (tenant-created).",
        options: {
          platform: "Platform",
          package: "Package",
          admin: "Admin"
        }
      },
      id: {
        label: "Position ID"
      },
      created_at: {
        label: "Created At"
      },
      updated_at: {
        label: "Updated At"
      }
    },
    _views: {
      active: {
        label: "Active"
      },
      default_positions: {
        label: "Default"
      },
      custom: {
        label: "Custom"
      },
      all_positions: {
        label: "All"
      }
    },
    _actions: {
      activate_position: {
        label: "Activate Position",
        successMessage: "Position activated"
      },
      deactivate_position: {
        label: "Deactivate Position",
        confirmText: "Deactivate this position? Users with the position keep their assignment but the position stops granting permissions until re-activated.",
        successMessage: "Position deactivated"
      },
      set_default_position: {
        label: "Set as Default",
        confirmText: "Make this the default position for new users? Existing users are unaffected.",
        successMessage: "Default position updated"
      },
      clone_position: {
        label: "Clone Position",
        successMessage: "Position cloned"
      }
    }
  },
  sys_capability: {
    label: "Capability",
    pluralLabel: "Capabilities",
    description: "Authorization capability definitions referenced by name from permission sets and resource requirements.",
    fields: {
      managed_by: {
        label: "Managed By",
        help: "Record provenance: platform / package (shipped, not user-deletable) / admin (created in Setup).",
        options: {
          platform: "Platform",
          package: "Package",
          admin: "Admin"
        }
      },
      scope: {
        label: "Scope",
        options: {
          platform: "Platform",
          org: "Organization"
        }
      }
    }
  },
  sys_permission_set: {
    label: "Permission Set",
    pluralLabel: "Permission Sets",
    description: "Named permission groupings for fine-grained access control",
    fields: {
      label: {
        label: "Display Name"
      },
      name: {
        label: "API Name",
        help: "Unique machine name for the permission set"
      },
      description: {
        label: "Description"
      },
      object_permissions: {
        label: "Object Permissions",
        help: "JSON-serialized object-level CRUD permissions"
      },
      field_permissions: {
        label: "Field Permissions",
        help: "JSON-serialized field-level read/write permissions"
      },
      system_permissions: {
        label: "System Permissions",
        help: "JSON-serialized array of system capability names (e.g. [\"setup.access\",\"studio.access\",\"manage_users\"])"
      },
      row_level_security: {
        label: "Row-Level Security",
        help: "JSON-serialized array of row-level security policies (USING/CHECK clauses)"
      },
      tab_permissions: {
        label: "Tab Permissions",
        help: "JSON-serialized map of app tab visibility (visible | hidden | default_on | default_off)"
      },
      active: {
        label: "Active"
      },
      managed_by: {
        label: "Managed By",
        help: "Record provenance: platform (shipped) / package (packaged) / admin (env-authored).",
        options: {
          platform: "Platform",
          package: "Package",
          admin: "Admin"
        }
      },
      id: {
        label: "Permission Set ID"
      },
      created_at: {
        label: "Created At"
      },
      updated_at: {
        label: "Updated At"
      }
    },
    _views: {
      active: {
        label: "Active"
      },
      inactive: {
        label: "Inactive"
      },
      all_permsets: {
        label: "All"
      }
    },
    _actions: {
      activate_permission_set: {
        label: "Activate",
        successMessage: "Permission set activated"
      },
      deactivate_permission_set: {
        label: "Deactivate",
        confirmText: "Deactivate this permission set? Existing assignments stay in place but stop granting access until re-activated.",
        successMessage: "Permission set deactivated"
      },
      clone_permission_set: {
        label: "Clone",
        successMessage: "Permission set cloned"
      }
    }
  },
  sys_user_permission_set: {
    label: "User Permission Set",
    pluralLabel: "User Permission Sets",
    description: "Direct assignment of a permission set to a user (optionally scoped to an organization).",
    fields: {
      id: {
        label: "Assignment ID",
        help: "UUID of the assignment."
      },
      user_id: {
        label: "User",
        help: "Foreign key to sys_user."
      },
      permission_set_id: {
        label: "Permission Set",
        help: "Foreign key to sys_permission_set."
      },
      organization_id: {
        label: "Organization",
        help: "Optional organization scope. NULL = applies in every org context."
      },
      granted_by: {
        label: "Granted By",
        help: "User who granted this permission set."
      },
      created_at: {
        label: "Created At"
      },
      updated_at: {
        label: "Updated At"
      }
    }
  },
  sys_position_permission_set: {
    label: "Position Permission Set",
    pluralLabel: "Position Permission Sets",
    description: "Binds a permission set to a position.",
    fields: {
      id: {
        label: "Binding ID",
        help: "UUID of the position-permission-set binding."
      },
      position_id: {
        label: "Position",
        help: "Foreign key to sys_position."
      },
      permission_set_id: {
        label: "Permission Set",
        help: "Foreign key to sys_permission_set."
      },
      created_at: {
        label: "Created At"
      },
      updated_at: {
        label: "Updated At"
      }
    }
  }
};
