// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'zh-CN'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 * Merge only fills gaps: correcting a source label/description does not
 * push the correction into a leaf here that already holds a translation —
 * a present-but-stale string is not a gap, so it is left as-is. Re-translate
 * it by hand when its source changes; nothing here or in `os i18n check`
 * tells a leaf a translator updated on purpose from one nobody has looked
 * at since the source moved.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const zhCNObjects: NonNullable<TranslationData['objects']> = {
  sys_position: {
    label: "岗位",
    pluralLabel: "岗位",
    description: "用于 RBAC 访问控制的岗位定义",
    fields: {
      label: {
        label: "显示名称"
      },
      name: {
        label: "API 名称",
        help: "岗位的机器名称，在每个组织内唯一（例如 sales_manager、hr_specialist）"
      },
      description: {
        label: "描述"
      },
      permissions: {
        label: "权限",
        help: "权限字符串数组的 JSON 序列化内容"
      },
      active: {
        label: "启用"
      },
      is_default: {
        label: "默认岗位",
        help: "自动分配给新用户"
      },
      delegatable: {
        label: "可委派",
        help: "ADR-0091 D3：持有者可自助委派该岗位，且有时限。"
      },
      managed_by: {
        label: "管理来源",
        help: "记录来源：platform（平台内置）/ package（应用包声明）/ admin（租户创建）。",
        options: {
          platform: "平台",
          package: "应用包",
          admin: "管理员"
        }
      },
      id: {
        label: "岗位 ID"
      },
      created_at: {
        label: "创建时间"
      },
      updated_at: {
        label: "更新时间"
      }
    },
    _views: {
      active: {
        label: "启用"
      },
      default_positions: {
        label: "默认"
      },
      custom: {
        label: "自定义"
      },
      all_positions: {
        label: "全部"
      }
    },
    _actions: {
      activate_position: {
        label: "激活岗位",
        successMessage: "岗位已激活"
      },
      deactivate_position: {
        label: "停用岗位",
        confirmText: "确定要停用此岗位吗？拥有该岗位的用户仍保留其分配，但在重新激活之前该岗位将不再授予权限。",
        successMessage: "岗位已停用"
      },
      set_default_position: {
        label: "设为默认",
        confirmText: "将此岗位设为新用户的默认岗位吗？现有用户不受影响。",
        successMessage: "已更新默认岗位"
      },
      clone_position: {
        label: "克隆岗位",
        successMessage: "已克隆岗位",
        params: {
          label: {
            label: "新显示名称"
          },
          name: {
            label: "新 API 名称",
            helpText: "snake_case 机器名称，在每个组织内唯一"
          }
        }
      }
    }
  },
  sys_capability: {
    label: "能力",
    pluralLabel: "能力",
    description: "授权能力定义，由权限集和资源需求按名称引用。",
    fields: {
      label: {
        label: "显示名称"
      },
      name: {
        label: "API 名称",
        help: "唯一的能力键，由 systemPermissions / requiredPermissions 按名称引用（如 manage_users、setup.access）。"
      },
      description: {
        label: "描述"
      },
      scope: {
        label: "范围",
        help: "platform = 平台级权能；org = 限定于某个组织。",
        options: {
          platform: "平台",
          org: "组织"
        }
      },
      managed_by: {
        label: "管理来源",
        help: "记录来源：platform / package（随包发布，不可用户删除）/ admin（在设置中创建）。",
        options: {
          platform: "平台",
          package: "应用包",
          admin: "管理员"
        }
      },
      package_id: {
        label: "所属应用包",
        help: "发布该能力的应用包（为空表示平台内置或管理员创建）。"
      },
      active: {
        label: "启用",
        help: "目录/可见性标记，用于筛选和查看。它对授权没有任何影响：权限集的授予与资源的 requiredPermissions 都按字符串匹配能力名称，从不读取该行，因此清除它不会撤销任何权限。"
      },
      id: {
        label: "能力 ID"
      },
      created_at: {
        label: "创建时间"
      },
      updated_at: {
        label: "更新时间"
      }
    },
    _views: {
      platform: {
        label: "平台"
      },
      org: {
        label: "组织"
      },
      all_capabilities: {
        label: "全部"
      }
    },
    _actions: {
      activate_capability: {
        label: "激活",
        successMessage: "已启用能力"
      },
      deactivate_capability: {
        label: "停用",
        confirmText: "停用该能力？这只是目录标记，用于在 Setup 中筛选和查看。授权不受影响——授予该能力的权限集，以及要求该能力的资源，都按名称匹配，仍会照常解析。",
        successMessage: "已停用能力"
      }
    }
  },
  sys_permission_set: {
    label: "权限集",
    pluralLabel: "权限集",
    description: "用于精细化访问控制的命名权限分组",
    fields: {
      label: {
        label: "显示名称"
      },
      name: {
        label: "API 名称",
        help: "权限集的机器名称，在每个组织内唯一"
      },
      description: {
        label: "描述"
      },
      object_permissions: {
        label: "对象权限",
        help: "对象级 CRUD 权限的 JSON 序列化内容"
      },
      field_permissions: {
        label: "字段权限",
        help: "字段级读写权限的 JSON 序列化内容"
      },
      system_permissions: {
        label: "系统权限",
        help: "系统能力名称的 JSON 序列化数组（例如 [\"setup.access\",\"studio.access\",\"manage_users\"]）"
      },
      row_level_security: {
        label: "行级安全",
        help: "行级安全策略的 JSON 序列化数组（USING/CHECK 子句）"
      },
      tab_permissions: {
        label: "标签页权限",
        help: "应用标签页可见性的 JSON 序列化映射（visible | hidden | default_on | default_off）"
      },
      admin_scope: {
        label: "委派管理范围",
        help: "[ADR-0090 D12] JSON 序列化的 AdminScope：{ businessUnit, includeSubtree, manageAssignments, manageBindings, authorEnvironmentSets, assignablePermissionSets[] }。持有该权限集会使用户成为所声明业务单元子树内的「受限范围」管理员，由委派管理写入门禁强制执行。"
      },
      active: {
        label: "启用"
      },
      package_id: {
        label: "所属应用包",
        help: "发布该权限集的应用包（为空表示环境内编写）。由 bootstrapDeclaredPermissions 填充，使应用包的卸载/升级行为有明确定义。"
      },
      managed_by: {
        label: "管理来源",
        help: "记录来源：platform（平台发布）/ package（应用包发布）/ admin（环境自建）。",
        options: {
          platform: "平台",
          package: "应用包",
          admin: "管理员"
        }
      },
      customized: {
        label: "已定制",
        help: "该打包权限集存在环境定制覆盖层（ADR-0094）。重置它（通过数据入口删除）即可回到随包发布的基线。"
      },
      id: {
        label: "权限集 ID"
      },
      created_at: {
        label: "创建时间"
      },
      updated_at: {
        label: "更新时间"
      }
    },
    _views: {
      active: {
        label: "启用"
      },
      inactive: {
        label: "停用"
      },
      all_permsets: {
        label: "全部"
      }
    },
    _actions: {
      activate_permission_set: {
        label: "激活",
        successMessage: "权限集已激活"
      },
      deactivate_permission_set: {
        label: "停用",
        confirmText: "确定要停用此权限集吗？现有分配仍将保留，但在重新激活之前将不再授予访问权限。",
        successMessage: "权限集已停用"
      },
      clone_permission_set: {
        label: "克隆",
        successMessage: "已克隆权限集",
        params: {
          label: {
            label: "新显示名称"
          },
          name: {
            label: "新 API 名称",
            helpText: "snake_case 机器名称，在每个组织内唯一"
          }
        }
      }
    }
  },
  sys_user_permission_set: {
    label: "用户权限集",
    pluralLabel: "用户权限集",
    description: "将权限集直接分配给用户（可按组织范围限定）。",
    fields: {
      id: {
        label: "分配 ID",
        help: "该分配记录的 UUID。"
      },
      user_id: {
        label: "用户",
        help: "指向 sys_user 的外键。"
      },
      permission_set_id: {
        label: "权限集",
        help: "指向 sys_permission_set 的外键。"
      },
      organization_id: {
        label: "组织",
        help: "可选的组织范围。NULL = 在所有组织上下文中都生效。"
      },
      granted_by: {
        label: "授权人",
        help: "授予该权限集的用户。"
      },
      valid_from: {
        label: "生效时间",
        help: "[ADR-0091 D1] 在此时刻之前授予无效。为空 = 立即生效。在解析时以 fail-closed 方式强制执行（D2）——绝不依赖后台任务。"
      },
      valid_until: {
        label: "失效时间",
        help: "[ADR-0091 D1] 授权自该时刻起（含）失效（半开区间 [from, until)，UTC）。为空表示永不过期。紧急提权（D4）和智能体授权（D6）必填。在解析时强制执行（D2）。"
      },
      reason: {
        label: "原因",
        help: "[ADR-0091 D1] 该授权存在的原因。自由文本；委派（D3）和紧急提权（D4）记录必填。智能体授权在此记录任务/运行归属（D6）。"
      },
      delegated_from: {
        label: "委派自",
        help: "[ADR-0091 D3] 该记录所承载权限的委派人。设置了 delegated_from 的记录本身不可再委派，也不可自助续期。"
      },
      last_certified_at: {
        label: "最近认证时间",
        help: "[ADR-0091 D5] 为未来的访问权限重新认证(定期复核)流程预留:届时用于记录此授予最近一次被认证的时间。当前该列是惰性的:平台不会写入它,也没有任何代码读取它——没有任何解析路径、门禁或 lint 会参考它,也没有任何地方据此推导出「从未认证」或「认证已过期」。因此为空只表示该流程尚不存在,并不表示此授予未经复核。"
      },
      certified_by: {
        label: "认证人",
        help: "[ADR-0091 D5] 同样为未来的访问权限重新认证流程预留:届时用于记录认证此授予的复核人。当前该列是惰性的:平台既不写入也不读取它。客户端在此写入的值只是一条未经验证的备注——平台不会对它做任何校验,也不会据此授予任何权限。"
      },
      created_at: {
        label: "创建时间"
      },
      updated_at: {
        label: "更新时间"
      }
    }
  },
  sys_position_permission_set: {
    label: "岗位权限集",
    pluralLabel: "岗位权限集",
    description: "将权限集绑定到岗位。",
    fields: {
      id: {
        label: "绑定 ID",
        help: "岗位-权限集绑定记录的 UUID。"
      },
      position_id: {
        label: "岗位",
        help: "指向 sys_position 的外键。"
      },
      permission_set_id: {
        label: "权限集",
        help: "指向 sys_permission_set 的外键。"
      },
      created_at: {
        label: "创建时间"
      },
      updated_at: {
        label: "更新时间"
      }
    }
  },
  sys_user_position: {
    label: "用户岗位",
    pluralLabel: "用户岗位",
    description: "将岗位（sys_position.name）分配给用户。由平台管理（ADR-0057 D4、ADR-0090 D3）。",
    fields: {
      id: {
        label: "分配 ID",
        help: "用户-岗位分配的 UUID。"
      },
      user_id: {
        label: "用户",
        help: "指向 sys_user 的外键。"
      },
      position: {
        label: "岗位",
        help: "岗位机器名（引用 sys_position.name）。"
      },
      business_unit_id: {
        label: "业务单元",
        help: "[ADR-0090 附录] 分配级 BU 锚点：此岗位分配适用的范围。作为 readScope/writeScope 的深度锚点、委派管理边界（D12）和审计事实。为空 = 未锚定（遗留/租户级）；委派管理员必须将分配锚定在其子树内。"
      },
      organization_id: {
        label: "组织",
        help: "拥有此分配的租户；为空 = 全局（跨租户）。"
      },
      granted_by: {
        label: "授予人",
        help: "授予此岗位分配的用户（委派写入时由委派管理门标记）。"
      },
      valid_from: {
        label: "生效时间",
        help: "[ADR-0091 D1] 在此时刻之前授予无效。为空 = 立即生效。在解析时以 fail-closed 方式强制执行（D2）——绝不依赖后台任务。"
      },
      valid_until: {
        label: "失效时间",
        help: "[ADR-0091 D1] 在此时刻及之后授予无效（半开区间 [from, until)，UTC）。为空 = 永不过期。委派行必填（D3）。在解析时强制执行（D2）。"
      },
      reason: {
        label: "原因",
        help: "[ADR-0091 D1] 此授予存在的原因。自由文本；委派（D3）和紧急破窗（D4）行必填。"
      },
      delegated_from: {
        label: "委派自",
        help: "[ADR-0091 D3] 此行所承载权限的委派人（职务代理）。设置了 delegated_from 的行本身不可再委派、不可自续期——双向切断链条。"
      },
      last_certified_at: {
        label: "最近认证时间",
        help: "[ADR-0091 D5] 为未来的访问权限重新认证(定期复核)流程预留:届时用于记录此授予最近一次被认证的时间。当前该列是惰性的:平台不会写入它,也没有任何代码读取它——没有任何解析路径、门禁或 lint 会参考它,也没有任何地方据此推导出「从未认证」或「认证已过期」。因此为空只表示该流程尚不存在,并不表示此授予未经复核。"
      },
      certified_by: {
        label: "认证人",
        help: "[ADR-0091 D5] 同样为未来的访问权限重新认证流程预留:届时用于记录认证此授予的复核人。当前该列是惰性的:平台既不写入也不读取它。客户端在此写入的值只是一条未经验证的备注——平台不会对它做任何校验,也不会据此授予任何权限。"
      },
      created_at: {
        label: "创建时间"
      },
      updated_at: {
        label: "更新时间"
      }
    }
  }
};
