// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'ja-JP'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 * Merge only fills gaps: correcting a source label/description does not
 * push the correction into a leaf here that already holds a translation —
 * a present-but-stale string is not a gap, so it is left as-is. Re-translate
 * it by hand when its source changes; nothing here or in `os i18n check`
 * tells a leaf a translator updated on purpose from one nobody has looked
 * at since the source moved.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const jaJPObjects: NonNullable<TranslationData['objects']> = {
  sys_file: {
    label: "システムファイル",
    pluralLabel: "システムファイル",
    description: "ストレージサービスのファイルメタデータ(fileId ↔ key マッピング)",
    fields: {
      id: {
        label: "ファイル ID"
      },
      key: {
        label: "ストレージキー"
      },
      name: {
        label: "ファイル名"
      },
      mime_type: {
        label: "MIME タイプ"
      },
      size: {
        label: "サイズ(バイト)"
      },
      scope: {
        label: "スコープ",
        options: {
          user: "ユーザー",
          tenant: "テナント",
          public: "公開",
          private: "非公開",
          temp: "一時",
          attachments: "添付ファイル"
        }
      },
      bucket: {
        label: "バケット"
      },
      acl: {
        label: "ACL",
        options: {
          private: "非公開",
          public_read: "公開読み取り"
        }
      },
      status: {
        label: "ステータス",
        options: {
          pending: "アップロード待ち",
          committed: "コミット済み",
          deleted: "削除済み"
        }
      },
      etag: {
        label: "ETag"
      },
      owner_id: {
        label: "所有者 ID",
        help: "ファイルをアップロードしたユーザー（作成者であり、フィールド参照の所有者ではありません）"
      },
      ref_object: {
        label: "参照元オブジェクト",
        help: "このファイルを保持するフィールドを持つレコードのオブジェクト短縮名"
      },
      ref_id: {
        label: "参照元レコード",
        help: "このファイルを保持するフィールドを持つレコードの主キー"
      },
      ref_field: {
        label: "参照元フィールド",
        help: "このファイル ID を保持する、所有レコード側のフィールド名"
      },
      metadata: {
        label: "メタデータ(JSON)"
      },
      created_at: {
        label: "作成日時"
      },
      updated_at: {
        label: "更新日時"
      },
      deleted_at: {
        label: "削除日時",
        help: "トゥームストーンのタイムスタンプ——添付スコープのファイルへの最後の sys_attachment 参照が削除されたときに設定され、猶予期間の後にライフサイクル TTL が行(および sys_file リープガード経由でストレージバイト)を回収します。存続中の行は NULL。"
      }
    }
  },
  sys_upload_session: {
    label: "システムアップロードセッション",
    pluralLabel: "システムアップロードセッション",
    description: "service-storage が追跡する再開可能なマルチパートアップロードセッション",
    fields: {
      id: {
        label: "アップロードセッション ID"
      },
      file_id: {
        label: "ファイル ID"
      },
      key: {
        label: "ストレージキー"
      },
      filename: {
        label: "ファイル名"
      },
      mime_type: {
        label: "MIME タイプ"
      },
      total_size: {
        label: "合計サイズ(バイト)"
      },
      chunk_size: {
        label: "チャンクサイズ(バイト)"
      },
      total_chunks: {
        label: "チャンク総数"
      },
      uploaded_chunks: {
        label: "アップロード済みチャンク数"
      },
      uploaded_size: {
        label: "アップロード済みサイズ(バイト)"
      },
      parts: {
        label: "アップロード済みパート(JSON)"
      },
      resume_token: {
        label: "再開トークン"
      },
      backend_upload_id: {
        label: "バックエンドアップロード ID"
      },
      scope: {
        label: "スコープ"
      },
      bucket: {
        label: "バケット"
      },
      metadata: {
        label: "メタデータ(JSON)"
      },
      status: {
        label: "ステータス",
        options: {
          in_progress: "進行中",
          completing: "完了処理中",
          completed: "完了",
          failed: "失敗",
          expired: "期限切れ"
        }
      },
      started_at: {
        label: "開始日時"
      },
      expires_at: {
        label: "有効期限"
      },
      updated_at: {
        label: "更新日時"
      }
    }
  }
};
