// Copyright (c) 2026 ObjectStack. Licensed under the Apache-2.0 license.

import type { SemanticMigration } from '../../types.js';

export const entry: SemanticMigration = {
  id: 'automation-runs-cursor-retired',
  // No backticks in `surface` — build-upgrade-guide.ts renders it inside a
  // code span AND a table cell.
  surface:
    'api.listRuns cursor — the pagination query parameter of '
    + 'GET /api/automation/:name/runs declared by ListRunsRequestSchema, its slot on '
    + 'IAutomationService.listRuns, and its option on all three @objectstack/client run-list '
    + 'surfaces (automation.runs.list, automation.listRuns, environment().automation.listRuns). '
    + 'The limit parameter of the same door is NOT part of this retirement and is unchanged, '
    + 'default(20) included',
  replacement:
    'a wider `limit` — this door does read it, bounded to 1..100, and it is spent as the run '
    + "store's history window. There is no replacement for `cursor` itself, deliberately: "
    + 'nothing ever minted one, so no caller holds a value to carry over, and the response '
    + '`nextCursor` it would have paired with has never been emitted. Read the response '
    + '`hasMore` to learn whether the window was short — it is now computed from the engine '
    + 'rather than the constant `false` it used to be, so for the first time it answers the '
    + 'question a caller reaching for a cursor was actually asking',
  reason:
    'ADR-0049 enforce-or-remove (director seat, decision batch #204 item 2, maintainer '
    + '「204 同意」 2026-09-21, letter C of three for this door; letter A — build a cursor '
    + 'protocol for a 100-row window — and letter B — retire the key and leave the '
    + '`hasMore` lie standing — were both considered and refused). `cursor` was declared on '
    + 'the request, VALIDATED at the boundary, forwarded into a `cursor?: string` slot on '
    + 'the service contract, and read by no implementation: the engine never looked at the '
    + 'option, and no emit site has ever written the response half `nextCursor`, so a caller '
    + 'looping until the cursor ran out re-read the first and only window forever with no '
    + 'error. '
    + '⭐ The `limit` half of this door was NOT retired, and the distinction is the ruling, '
    + 'not an oversight. The sibling `/packages` door retired its `limit` with its `cursor` '
    + '(#17667, decision batch #126 item 1) because nothing read it; the parent ruling '
    + 'explicitly does not transfer here. On this door `limit` is read end to end — the '
    + 'boundary enforces the declared 1..100 range off the schema itself, the service takes '
    + 'it as an option, and the engine spends it as `RunStore.listHistory`\'s window — and '
    + "the Console's flow-runs page sends it today. Retiring it would have been a "
    + 'regression, and its `.default(20)` stays with it. '
    + 'The same card computes `hasMore`, which is the half a bare retirement would have left '
    + 'lying. `GET /api/automation/:name/runs` shipped a literal `hasMore: false` beside a '
    + 'list the engine had already truncated with `.slice(0, limit)`, so a caller asking for '
    + 'one row of a thousand was handed one row and told that was all of them. The engine '
    + 'now reports truncation to the door through a new optional contract member, '
    + '`IAutomationService.listRunsPage`, which returns `{ runs, hasMore }`: it over-reads '
    + 'its history source by exactly one row and compares the merged, filtered, ordered set '
    + 'to the caller\'s window. The over-read is what makes the answer sound — '
    + '`runs.length === limit` cannot tell a flow with exactly `limit` runs from one with '
    + 'ten thousand, and `RunStore.listHistory`\'s signature is deliberately unchanged '
    + 'because over-reading is expressible in the `limit` it already takes. '
    + 'There IS a tombstone: the request schema is non-strict, so a bare deletion would have '
    + 'made Zod SILENTLY STRIP whatever a generated client kept sending — a clean parse and '
    + "a parameter that never takes effect, which is this card's own defect re-created one "
    + 'layer down (ADR-0104). `cursor` is therefore a `retiredKey()`, typed `never` for tsc '
    + 'and raising the prescription at any parse, and is registered in '
    + 'RETIRED_KEYS_BY_MAJOR[18]. There is NO D2 conversion: a conversion rewrites an '
    + 'authored source or a stored `sys_metadata` row, and this shape is HTTP-only — nobody '
    + 'authors a `ListRunsRequest` and nothing persists one. The `os migrate meta` house '
    + 'sentence is therefore correctly absent from the prescription. There is no '
    + '`acceptRetiredDefaultResidue` stage either: `cursor` carried no default, so it '
    + 'materialized into no artifact and there is no residue to accept. '
    + 'The SDK half is part of the retirement rather than a follow-up: `@objectstack/client` '
    + 'declared `cursor` and appended it on all three run-list surfaces, so retiring the key '
    + 'in the schema alone would have left the one generated client this repo ships typing it '
    + '`string` and sending it into a route that silently drops it — the ADR-0104 shape the '
    + 'tombstone exists to prevent, re-created one layer down. The same call was made when '
    + '#6361 retired the notifications `cursor`: the client dropped the option and recorded '
    + 'the removal in its docblock. ADR-0049 / ADR-0087, #19543.',
  acceptanceCriteria:
    'No caller sends `cursor` to `GET /api/automation/:name/runs`, and that is true of every '
    + 'channel this repo ships rather than of the schema alone. Writing it on a '
    + '`ListRunsRequest` is a `tsc` error (the input type is `never`), and any value reaching a '
    + 'parse raises the prescription rather than a generic unrecognized-key issue. The option is '
    + 'gone from `IAutomationService.listRuns`, so an implementation can no longer declare a slot '
    + 'for it. ⭐ It is also gone from the SDK, which is the channel most callers actually reach '
    + 'this door through: `@objectstack/client` no longer declares `cursor` on '
    + '`automation.runs.list`, `automation.listRuns` or '
    + '`client.environment(id).automation.listRuns`, and no longer appends `?cursor=` on any of '
    + 'the three — so the key cannot be smuggled past the retired schema by an untyped caller. '
    + 'Without that half the retirement would have re-created its own defect one layer down: '
    + 'the schema typing the key `never` while the shipped client typed it `string` and sent it, '
    + 'silently dropped by a route that no longer reads it (ADR-0104). '
    + '⚠️ ONE wire behaviour CHANGES and must be verified as such, because it reverses a '
    + 'decision recorded under #7300: a repeated `?cursor=a&cursor=b` used to answer '
    + '`400 VALIDATION_FAILED` with a `details.fields[]` entry naming `cursor`, and now '
    + 'answers `200` with the key ignored like any other unrecognised query name. #7300 '
    + 'validated the key rather than deciding it, so that a future cursor implementation '
    + 'would not be the one to discover the type was unenforced; this ruling decides it '
    + 'instead — there will be no cursor implementation on this door — so the refusal would '
    + 'be validating a key the contract no longer has. This route declares no closed query '
    + 'set (AGENTS.md route-ownership rule 5), so an unrecognised name has never been refused here '
    + 'on its own account. '
    + '⚠️ `hasMore` also changes, from a constant to an answer: a request whose window is '
    + 'shorter than the matching run set now receives `hasMore: true` where it previously '
    + 'received `false`. A caller that treated `false` as "this is the whole history" was '
    + 'always wrong and is now told so. ⚠️ Read the new `false` with one qualification: '
    + 'unfiltered it is exact, but under `?status=` it means "no further match inside the '
    + 'window that was scanned" rather than "none exists", because the durable history '
    + 'source has no status slot and the window is taken before the filter is applied. '
    + 'Pushing the filter down is a store-contract change this card did not scope. '
    + '`nextCursor` stays absent — nothing mints one — and '
    + '`limit` behaves exactly as it did, including its `.default(20)`. '
    + 'A deployment whose automation service does not implement `listRunsPage` answers `501` '
    + 'naming the member, and ⛔ never a `200` carrying an invented `hasMore`.',
};
