// Copyright (c) 2026 ObjectStack. Licensed under the Apache-2.0 license.

import type { SemanticMigration } from '../../types.js';

export const entry: SemanticMigration = {
  id: 'dashboard-widget-dimensionless-multi-measure-refused',
  surface: 'dashboard widget measure arity WITHOUT a dimension — `dashboard.widgets[].values` '
    + '(`DashboardWidgetSchema.values`) on a widget whose `dimensions` is absent or empty and whose '
    + '`type` is one of the seven chart types that declare no rendering for several measures: '
    + '`pie` / `donut` / `funnel` / `scatter` / `radar` / `treemap` / `sankey`',
  replacement: 'Pick a visual that renders several measures, or split the widget. With no '
    + 'dimension, `type: \'table\'` renders a row of measures and a bar-family type (`bar` / '
    + '`column` / `horizontal-bar`) renders one bar per measure; both keep the unbounded `values` '
    + 'they have always had. The full set of types that render several measures on a dimensionless '
    + 'widget is the exported constant `DASHBOARD_WIDGET_MULTI_MEASURE_TYPES` — at this release '
    + '`table`, `pivot`, `bar`, `column`, `horizontal-bar`, `line`, `area` and `combo` — and the '
    + 'refusal prints it from that constant. Or keep the type and give each measure its OWN widget: a '
    + 'new `id`, the same `dataset`, that one measure in `values`, and its own `layout` if the '
    + 'dashboard pins grid positions. ⛔ The migration does not do this for you and no conversion '
    + 'could: whether a dimensionless two-measure pie meant a table, a bar chart or two pies is an '
    + 'authoring choice, and N widgets need N ids and N boxes on a 12-column grid, which is a LAYOUT '
    + 'decision about a dashboard the registry has never seen.',
  reason:
    'Maintainer ruling D, on objectui\'s finding that a widget silently drops every measure after '
    + 'the first, applying the maintainer\'s standing rule 「协议不正确的应该先修改协议」 — the '
    + 'protocol is fixed where it admits measures a widget type cannot render. Its first application '
    + 'bounded the metric FAMILY to one measure (`dashboard-widget-metric-family-multi-measure-refused`); '
    + 'this entry applies the same principle to the chart types. Measured in objectui by the dev who '
    + 'delivered the multi-measure renderings for `table` / `pivot` and the bar, line, area and combo '
    + 'families: the other seven `ChartTypeSchema` members, given no dimension and two or more '
    + 'measures, render `values[0]` and drop the rest — the dataset query selects and computes every '
    + 'measure, and all but the first are thrown away. Every door accepted the document, because '
    + '`values` is `z.array(z.string()).min(1)` with no upper bound outside the metric family. That '
    + 'is the declared≠delivered shape ADR-0049 exists to end. The census before the change found '
    + 'zero authored dimensionless multi-measure widgets of any type in the platform\'s examples or in '
    + 'objectui\'s example apps, so this ships at once with no deprecation window: there is no window '
    + 'in which a queried-and-discarded measure does anything. Relaxing later is free and needs no '
    + 'second migration — if one of the seven gains a declared multi-measure rendering (a radar of '
    + 'measures, a funnel of measure stages) it joins the constant, while leaving the key unbounded '
    + 'costs an author a widget that silently drops what they declared. ⛔ This change does not '
    + 'invent those renderings.',
  acceptanceCriteria:
    '⚠️ WHICH DOOR: the refusal is the spec\'s, and it reaches every door that parses the spec '
    + 'schema — measured on `defineStack`, which throws naming the widget; on `os validate`, which '
    + 'loads the configuration through `defineStack` and fails there with that same issue; on the '
    + 'stack schema and the `dashboard` metadata-type schema; and on the metadata save path, where '
    + 'an ACTIVE save and a DRAFT save of such a dashboard both answer `422 INVALID_METADATA` at '
    + '`widgets[N].values` and persist nothing. It is NOT refused by objectui\'s client-side '
    + 'authoring door until that door chains the new export: `@object-ui/types` builds its '
    + '`DashboardWidgetSchema` from a `.shape` spread of the spec\'s, which carries the FIELDS and '
    + 'drops every object-level check, so its editor keeps accepting a dimensionless two-measure '
    + '`pie` and the author meets the refusal at publish. ⇒ Do not read a green editor as a clean '
    + 'dashboard; re-parse through the spec. '
    + '⚠️ AND THE TODO CANNOT NAME YOUR MEASURES: a `SemanticMigration` is static prose emitted once '
    + 'per hop, with no per-document interpolation and no filtering by whether the stack carries the '
    + 'shape, so `os migrate meta` prints THIS paragraph, not a list of your widgets. The refusal is '
    + 'what names them, per widget, on the re-parse — drive the fix off `os validate`, not off the '
    + 'migrate output. '
    + 'WHAT IS REFUSED, exactly: ONE `custom` issue at `widgets[N].values`, naming the widget\'s '
    + '`id`, the number of measures and the authored `type`, when `dimensions` is absent or an empty '
    + 'array, `values` carries two or more measures, and `type` is `pie`, `donut`, `funnel`, '
    + '`scatter`, `radar`, `treemap` or `sankey`. The check is the exported '
    + '`checkDashboardWidgetChartMeasureArity` (exported as '
    + '`checkDashboardWidgetDimensionlessMeasureArity` until '
    + '`dashboard-widget-single-series-multi-measure-refused` gave it a second arm and renamed it), and '
    + 'the set it reads is the exported '
    + '`DASHBOARD_WIDGET_MULTI_MEASURE_TYPES` — one list, which the check, the refusal text and the '
    + '`values` doc string all read. '
    + 'WHAT IS NOT, so this is not read as complete: the same seven types WITH a dimension are '
    + 'outside THIS entry — `scatter` and `radar` keep accepting several measures with a dimension, and '
    + '`pie` / `donut` / `funnel` / `treemap` / `sankey` are refused with a dimension too, by '
    + '`dashboard-widget-single-series-multi-measure-refused`; one measure parses on every type; every type in '
    + '`DASHBOARD_WIDGET_MULTI_MEASURE_TYPES` keeps accepting any number of measures with no '
    + 'dimension; the metric family (`metric` / `kpi` / `gauge` / `solid-gauge` / `bullet`, and a '
    + 'widget that declares no `type`, which resolves to `metric`) keeps its OWN refusal, unchanged '
    + 'and still ONE issue — that check refuses a second measure at any dimensionality, and this one '
    + 'steps aside for the family rather than adding a second issue on the same `values`; an EMPTY '
    + '`values` keeps the field\'s own `too_small`; a `type` outside `ChartTypeSchema` reports the '
    + 'TYPE refusal alone (zod treats that `invalid_value` as aborting and skips object-level checks), '
    + 'and called directly on a wider type enum the export judges only the types the spec declares; '
    + 'and whether each measure EXISTS in the bound dataset is still unreachable from this schema. '
    + 'VERIFY by re-parsing each dashboard: a dashboard that had one dimensionless two-measure `pie` '
    + 'should end with a `table` or bar-family widget carrying both measures, or with two widgets of '
    + 'one measure each — check the rendered grid afterwards, because the second measure is a number '
    + 'the dashboard was ALREADY paying to compute and had never shown.',
};
