// Copyright (c) 2026 ObjectStack. Licensed under the Apache-2.0 license.

import type { SemanticMigration } from '../../types.js';

export const entry: SemanticMigration = {
  id: 'dashboard-widget-single-series-multi-measure-refused',
  surface: 'dashboard widget measure arity WITH a dimension on a single-series chart type — '
    + '`dashboard.widgets[].values` (`DashboardWidgetSchema.values`) on a widget whose `dimensions` '
    + 'declares one or more dimensions and whose `type` is `pie`, `donut`, `funnel`, `treemap` or '
    + '`sankey`; and the check export `checkDashboardWidgetDimensionlessMeasureArity` (from '
    + '`@objectstack/spec/ui`), renamed `checkDashboardWidgetChartMeasureArity`',
  replacement: 'Keep ONE measure on the widget, or pick a visual that renders several. With a '
    + 'dimension, `type: \'table\'` renders a column per measure and a bar-family type (`bar` / '
    + '`column` / `horizontal-bar`) renders one bar per measure in each category; both keep the '
    + 'unbounded `values` they have always had. Or keep the type and give each measure its OWN '
    + 'widget: a new `id`, the same `dataset` and `dimensions`, that one measure in `values`, and its '
    + 'own `layout` if the dashboard pins grid positions. ⛔ The migration does not do this for you '
    + 'and no conversion could: whether a two-measure pie by stage meant a table, a grouped bar chart '
    + 'or two pies is an authoring choice, and N widgets need N ids and N boxes on a 12-column grid, '
    + 'which is a LAYOUT decision about a dashboard the registry has never seen. A mirror that '
    + 'chained the old check export by name imports `checkDashboardWidgetChartMeasureArity` instead: '
    + 'same signature, same attachment point, and it refuses everything the old name refused.',
  reason:
    'Triage\'s ruling on objectui\'s finding that a dimensioned pie draws only its first measure: '
    + 'the spec refuses, the renderer does not invent. It extends '
    + '`dashboard-widget-dimensionless-multi-measure-refused`, which applied maintainer ruling D '
    + '(「协议不正确的应该先修改协议」) to a widget with NO dimension, to the dimensioned arm for '
    + 'the five types that draw one series whatever the dimension. Measured in objectui\'s shared '
    + 'chart renderer: the `pie` / `donut`, `funnel`, `treemap` and `sankey` arms each bind the '
    + 'first series and read no other, so `{ type: \'pie\', dimensions: [\'stage\'], values: '
    + '[\'revenue\', \'cost\'] }` drew one slice per stage for `revenue` and no trace of `cost` — the '
    + 'dataset query selects and computes every measure, and all but the first are thrown away. '
    + 'Every door accepted the document, because the dimensionless rule stepped aside for any '
    + 'widget that declared a dimension. That is the declared≠delivered shape ADR-0049 exists to '
    + 'end. A pie of several measures has zero measured pull, so no rendering is invented for it. '
    + 'The census before the change found zero authored dimensioned multi-measure widgets of the five '
    + 'types in the platform\'s examples, its first-party dashboards or objectui\'s example apps, so '
    + 'this ships at once with no deprecation window. Relaxing later is free and needs no second '
    + 'migration — a type whose renderer gains a declared rendering for several measures with a '
    + 'dimension leaves the single-series set — while leaving the shape accepted costs an author a '
    + 'widget that silently drops what they declared. The check export is renamed in the same change '
    + 'because its old name said a widget with a dimension was outside it, which stopped being true; '
    + 'no first-party consumer chained it under that name.',
  acceptanceCriteria:
    '⚠️ WHICH DOOR: the refusal is the spec\'s, attached at the same point as the dimensionless rule, '
    + 'so it reaches every door that parses the spec schema — measured on `defineStack`, which throws '
    + 'naming the widget, and on the stack schema, the dashboard schema and the `dashboard` '
    + 'metadata-type schema, each refusing at `widgets[N].values`. It is NOT refused by objectui\'s '
    + 'client-side authoring door until that door chains the export: `@object-ui/types` builds its '
    + '`DashboardWidgetSchema` from a `.shape` spread of the spec\'s, which carries the FIELDS and '
    + 'drops every object-level check, so its editor keeps accepting a dimensioned two-measure `pie` '
    + 'and the author meets the refusal at publish. ⇒ Do not read a green editor as a clean '
    + 'dashboard; re-parse through the spec. '
    + '⚠️ AND THE TODO CANNOT NAME YOUR MEASURES: a `SemanticMigration` is static prose emitted once '
    + 'per hop, with no per-document interpolation and no filtering by whether the stack carries the '
    + 'shape, so `os migrate meta` prints THIS paragraph, not a list of your widgets. The refusal is '
    + 'what names them, per widget, on the re-parse — drive the fix off `os validate`, not off the '
    + 'migrate output. '
    + 'WHAT IS REFUSED, exactly: ONE `custom` issue at `widgets[N].values`, naming the widget\'s '
    + '`id`, the number of measures and the authored `type`, and saying the type draws one series '
    + 'whatever its `dimensions`, when `dimensions` declares at least one dimension, `values` carries '
    + 'two or more measures, and `type` is `pie`, `donut`, `funnel`, `treemap` or `sankey`. The check '
    + 'is the exported `checkDashboardWidgetChartMeasureArity` — the dimensionless rule\'s own check, '
    + 'with a second arm; the single-series set it reads is not exported, and the refusal prints it. '
    + 'WHAT IS NOT, so this is not read as complete: `scatter` and `radar` WITH a dimension keep '
    + 'accepting several measures exactly as before (the ruling named the five: `radar` draws every '
    + 'series, and `scatter` says on the chart that it draws one); every type in '
    + '`DASHBOARD_WIDGET_MULTI_MEASURE_TYPES` keeps accepting any number of measures with a dimension; '
    + 'one measure parses on every type; a DIMENSIONLESS widget of the five keeps the dimensionless '
    + 'refusal, word for word and still ONE issue; the metric family (`metric` / `kpi` / `gauge` / '
    + '`solid-gauge` / `bullet`, and a widget that declares no `type`, which resolves to `metric`) '
    + 'keeps its OWN refusal, unchanged; an EMPTY `values` keeps the field\'s own `too_small`; a '
    + '`type` outside `ChartTypeSchema` reports the TYPE refusal alone, and called directly on a '
    + 'wider type enum the export judges only the types the spec declares; and whether each measure '
    + 'EXISTS in the bound dataset is still unreachable from this schema. '
    + 'VERIFY by re-parsing each dashboard: a dashboard that had one two-measure `pie` by stage should '
    + 'end with a `table` or bar-family widget carrying both measures, or with two widgets of one '
    + 'measure each — check the rendered grid afterwards, because the second measure is a number the '
    + 'dashboard was ALREADY paying to compute and had never shown.',
};
