// Copyright (c) 2026 ObjectStack. Licensed under the Apache-2.0 license.

import type { SemanticMigration } from '../../types.js';

// No backticks in `surface` — build-upgrade-guide.ts renders it inside a code
// span already, and a nested backtick would close it.
export const entry: SemanticMigration = {
  id: 'evaluated-expression-slots-source-required',
  surface:
    'every EVALUATED expression slot in the spec — the 36 declaring positions the #15811 census '
    + 'enumerated by identity, not by a name scan: the formula Field.expression; the predicate '
    + 'keys visibleWhen / visibleOn / readonlyWhen / requiredWhen / visibility / disabledWhen / '
    + 'visible / disabled / condition / when, on Field, SelectOption, InlineGridColumn, '
    + 'ScriptValidation, CrossFieldValidation, ConditionalValidation, Hook, ObjectFieldGroup, '
    + 'RowCrudActionOverride, CriteriaSharingRule, PluginPermission.filter, MultiVersionSupport '
    + 'routing, Action and ActionParam (including each param option), BaseNavItem, BulkActionDef, '
    + 'PageComponent, PageTabs items, RecordAlert, ListViewShape, FormFieldBase, FormSection, the '
    + 'settings-manifest Specifier and manifest visible, the ServiceLevelIndicator successCriteria '
    + 'union member and the TraceSamplingConfig composite condition union member — authored either '
    + 'as an expression envelope carrying only ast ({ dialect: \'cel\', ast: … } with no source), '
    + 'or with a source that is blank after trimming, through the envelope key '
    + '({ dialect: \'cel\', source: \'   \' }) or the bare-string shorthand for it. ⚠️ At the '
    + 'TraceSamplingConfig composite condition slot the reachable set is WIDER than those two '
    + 'spellings, because the structured-filter arm beside the expression arm narrowed with it: a '
    + 'bare record accepted { dialect: \'cel\', ast } as an ordinary filter, which made the rule '
    + 'inert there, so that arm now declines ANY object carrying a dialect key. Six shapes the '
    + 'base accepted through that arm alone are refused at that slot: { dialect: \'cel\' }, '
    + '{ dialect: \'js\', source: \'x\' }, { dialect: \'nope\', source: \'x\' }, '
    + '{ dialect: \'cel\', source: 5 }, '
    + '{ dialect: \'cel\', source: \'x\', meta: { rationale: 5 } } and '
    + '{ dialect: \'zzz\', foo: 1 }. A structured filter carrying no dialect key is accepted '
    + 'exactly as before. The published '
    + 'TypeScript interface RowCrudPredicates narrows with the two slots it mirrors. Reachable '
    + 'wherever metadata is authored or stored: defineStack sources, an exported stack passed to '
    + 'objectstack validate, a POST body on any of these metadata types, and a row already sitting '
    + 'in sys_metadata',
  replacement:
    'a non-blank `source`. ⭐ For an `ast`-only envelope the recovery is MECHANICAL and lossless '
    + 'for `cel`, which is the one dialect in this population that has an AST at all: '
    + '`printCelAst(ast)` from `@objectstack/formula` (#15811, the inverse of `parseCelToAst`) '
    + 'prints the AST back to surface syntax, and the recovered string is the new `source` — keep '
    + 'the `ast` beside it if you want, an `ast` BESIDE a string `source` is untouched and stays '
    + 'admitted everywhere. ⚠️ Lossless is about MEANING, not bytes: the printer re-renders from '
    + 'the parse tree, so single-quoted literals come back double-quoted '
    + '(`record.p == \'x\'` → `record.p == "x"`) and parentheses the parser dropped do not come '
    + 'back. It answers `null` — never a guess — for an `ast` it cannot round-trip through the '
    + 'platform\'s own bounded parser; that `null` is the hand-migration case. '
    + 'For a BLANK `source` there is nothing to print from, so this entry delegates the judgment, '
    + 'and it is the same fork #15807 named: author the predicate the slot was meant to carry, or '
    + 'REMOVE the key entirely. ⚠️ Those two are not interchangeable and the choice is per slot, '
    + 'not per file. A refused predicate reached its evaluator and faulted, and what the fault DID '
    + 'differs by slot: on the fail-closed ones (`ObjectFieldGroup.visibleWhen`, '
    + '`RowCrudActionOverride.visibleWhen`, `BulkActionDef.visible`, the two settings-manifest '
    + '`visible` slots) it HID or EXCLUDED, so removing the key REVEALS what was hidden; on the '
    + 'fail-soft ones (the rest) it left the gate open, so removing the key preserves what was '
    + 'happening. Removing to clear the refusal is therefore safe on one half of the population '
    + 'and a silent disclosure on the other',
  reason:
    'Card #15811, ruled 2026-09-12 (director seat, decision batch #122 item 2): the rule #15430 '
    + 'set for the flow-node ledger and #15807 carried to `FlowEdgeSchema.condition` generalises '
    + 'to every other slot an engine evaluates. Each of those slots now composes '
    + '`EvaluatedExpressionInputSchema` instead of `ExpressionInputSchema`, so an evaluated slot '
    + 'is held to what the engine can actually run. The engine reads `source` alone '
    + '(`cel-engine.ts` `evaluate`: "AST-only evaluation not yet supported; persist `source`"), so '
    + 'both refused spellings landed in its fault arm on every release that carried them — and '
    + 'measured at the chokepoint, the engine never silently SUCCEEDS on either: it returns a '
    + '`parse` fault, and what happened next was decided entirely by the slot\'s fail policy. '
    + 'Nothing between the author\'s keystroke and that fault said a word — the authoring lint '
    + '`validateVisibilityPredicates` measured 0 findings on an `ast`-only envelope and 0 on a '
    + 'blank `source`, against two control legs that each measured 1. The refusal is one rule with '
    + 'one sentence, `EVALUATED_EXPRESSION_SOURCE_REQUIRED`. '
    + '⚠️ `ExpressionSchema` / `ExpressionInputSchema` are deliberately NOT narrowed and neither is '
    + 'their alias `PredicateInputSchema`: they are the PERSISTENCE contract (`source` OR `ast`) '
    + 'and stay wide by the same ruling\'s item 2. The narrowing is at the evaluated slots only. '
    + '⚠️ Why this is a D3 entry and not a D2 conversion, even though a printer now exists. The '
    + 'conversion layer lives in `packages/spec`, which is dependency-free by Prime Directive #2 '
    + 'and carries no engine — `packages/formula`\'s own `normalize.ts` header states the same '
    + 'boundary from the other side ("Spec layer cannot do step 2 because it must remain '
    + 'dependency-free; this package owns the engine import"). A conversion that had to call the '
    + 'CEL printer could not live where conversions live, and a conversion that guessed without '
    + 'one would be the platform inventing a predicate. So the printer ships as a named, tested '
    + 'export the migration PRESCRIBES, and the judgment the printer cannot make — a blank '
    + '`source`, an opaque `ast` that does not round-trip, any future dialect with no printer — '
    + 'stays here as the structured TODO, naming the object, field and slot. '
    + '⚠️ And for a row ALREADY STORED the consequence is wider than the key. '
    + '`applyConversionsToStoredItem` replays the conversion chain on rehydration, but no '
    + 'conversion can supply a `source` that was never written, so a stored row carrying either '
    + 'spelling now fails its schema parse at the seam that loads it rather than parsing and '
    + 'faulting later. That is the intended direction — the refusal moves from run time, where it '
    + 'was invisible on the fail-soft slots and destructive on the fail-closed ones, to load time, '
    + 'where it names the row. ADR-0087, ADR-0058, ADR-0049.',
  acceptanceCriteria:
    'Sweep every authored metadata source and every `sys_metadata` row for the two spellings on '
    + 'the slots named in `surface`: an expression envelope with no `source` key, and a `source` '
    + '(or bare-string shorthand) that is empty after trimming. ⚠️ Sweep by SLOT, not by key name '
    + '— `visible` is on this list for actions, action params, nav items, bulk actions, record '
    + 'alerts and settings manifests, and is NOT an expression slot elsewhere; and three of the '
    + 'positions are union members (`RecordAlertProps.visible`, '
    + '`ServiceLevelIndicator.successCriteria`, `TraceSamplingConfig.composite[].condition`). On '
    + 'TWO of those three the sibling arm is untouched: `RecordAlertProps.visible` still takes a '
    + 'boolean literal, and `ServiceLevelIndicator.successCriteria` still takes its structured '
    + '`{ threshold, operator, percentile? }` object — including one that carries a `dialect` '
    + 'key. ⚠️ On the third, `TraceSamplingConfig.composite[].condition`, the sibling arm '
    + 'narrows WITH the expression arm and that is deliberate: a bare record accepted '
    + '`{ dialect: \'cel\', ast }` as an ordinary filter, so the rule was inert there. The sweep '
    + 'at that ONE slot is therefore wider — flag every `condition` object carrying a `dialect` '
    + 'key, not only the two spellings above; if it is a structured filter, drop the `dialect` '
    + 'key, and if it is an expression it needs a dialect this platform evaluates AND a non-blank '
    + '`source`. For each hit: if it carries an `ast`, run '
    + '`printCelAst(ast)`; a string result IS the migration and needs no judgment beyond reading '
    + 'it back. A `null` result, or a blank `source`, is the hand-migration case — decide per the '
    + '`replacement` note whether the slot was meant to carry a predicate (author the `source`) or '
    + 'to be ungated (remove the key), and ⛔ do not default to removal on a fail-closed slot, '
    + 'where removal reveals rather than preserves. Two proofs. (1) `objectstack validate` is '
    + 'clean on a stack authored in config files: each offender is located by path with the '
    + '`EVALUATED_EXPRESSION_SOURCE_REQUIRED` sentence — one `invalid_union` issue at the slot for '
    + 'an `ast`-only envelope or a blank bare string, one `custom` issue at `source` for a blank '
    + '`source` inside an envelope. There is no CLI verb that lowers a stored row back into a '
    + 'config file, so this proof does not reach metadata that exists only in `sys_metadata`. '
    + '(2) For stored rows, load the tenant and confirm every metadata item of the affected types '
    + 'still rehydrates: a row carrying either spelling now fails its parse at the load seam and '
    + 'is reported there, naming the object, the field and the slot. A row whose every evaluated '
    + 'slot carries a non-blank `source` parses byte-identically to before — the narrowing removes '
    + 'accepted shapes and adds none.',
};
