// Copyright (c) 2026 ObjectStack. Licensed under the Apache-2.0 license.

import type { SemanticMigration } from '../../types.js';

export const entry: SemanticMigration = {
  id: 'element-data-source-and-object-block-filter-rule-array',
  surface:
    'Page-component `dataSource.filter` (`ElementDataSourceSchema`, the binding every '
    + 'data-bound element carries) and the `filter` prop of the four `object-*` blocks in '
    + '`ComponentPropsMap` — `object-grid`, `object-metric`, `object-kanban`, `object-calendar` '
    + '(the FORM: the MongoDB-style `FilterConditionSchema` record at the binding, and the '
    + 'accept-anything `z.unknown()` at the four block doors, vs the `ViewFilterRule` array)',
  replacement:
    '`z.array(ViewFilterRuleSchema)` at all five doors — the rule array '
    + '`[{ field, operator, value }, ...]` every other `filter` door in the map already carries '
    + '(`record:related_list`, its Add-affordance picker, `element:number`, '
    + '`element:record_picker`). A record-form filter `{ status: \'active\' }` becomes '
    + '`[{ field: \'status\', operator: \'equals\', value: \'active\' }]`; an operator object '
    + '`{ status: { $ne: \'done\' } }` becomes '
    + '`[{ field: \'status\', operator: \'not_equals\', value: \'done\' }]`; several keys become '
    + 'several rules (they AND). An ObjectQL AST tuple array '
    + '`[[\'owner_id\', \'=\', \'{current_user_id}\']]` — which the `z.unknown()` block doors '
    + 'also took — becomes `[{ field: \'owner_id\', operator: \'equals\', value: '
    + '\'{current_user_id}\' }]`; the value placeholders and date macros are unchanged. Legacy '
    + 'operator shorthands (`eq`, `ne`, `gt`, `notIn`, …) are accepted and normalized on parse. '
    + 'The dashboard widget `filter` (`dashboard.zod.ts`) is a different family, judged on its '
    + 'own, and is not moved by this entry; `object-grid.defaultFilters` is a different key and is not named '
    + 'by the ruling this entry records.',
  reason:
    'One filter orthography platform-wide (the maintainer\'s 2026-08-25 ruling, option B: a '
    + 'filter door takes the `ViewFilterRule` array rather than keeping a record-shaped '
    + 'exception every author and AI would have to remember) reached two more locations the '
    + 'ComponentPropsMap census could not see (ruled 2026-09-06, option A: converge the binding '
    + 'and the four block doors family-wide, under one entry, rather than record an exception). The binding-level '
    + '`dataSource.filter` alone still said `FilterConditionSchema`: it refused the array the '
    + 'consumer\'s own pins author at that key, and `element:record_picker` carried two '
    + 'orthographies at two keys (`properties.filter` the rule array, `dataSource.filter` the '
    + 'record) resolved through one `??` in the renderer — the shape in which a dropped or '
    + 'misread filter returns the wrong rows without an error. The four `object-*` doors said '
    + '`z.unknown()`: a read-point record derived from the renderers on 2026-08-13, when the '
    + '`object-*` blocks first got props schemas in the map, '
    + 'twelve days before the ruling, not an exception to it — so an author following the '
    + 'showcase wrote the record and an author following the manifest wrote an array, and each '
    + 'got a silent success receipt while the html tier already declared `array` for the grid '
    + 'and the metric. The record\'s `$and` / `$or` / `$not` keys were misread by every gate '
    + 'block anyway (the console\'s filter converter had no branch for them), so the exception would have preserved a capability the '
    + 'consumer does not honour. Sequenced measurement-first, as the family had to be: at the '
    + 'objectui pin `a472b07` the `object-metric` aggregate path posted an array `where` that '
    + '`POST /analytics/query` refused with 400 on every array form, so the converge '
    + 'was parked behind a bump of that pin; at the pin this repo builds against (`53ded82b`) '
    + 'the adapter lowers an authored array through `translateFilterArray` and '
    + 'the spec\'s own `parseFilterAST` sink before the wire, `ObjectGrid.tsx` lowers a rule '
    + 'array through `toFilterNode`, `ObjectKanban.tsx` / `ObjectCalendar.tsx` hand it verbatim '
    + 'to `$filter` where `convertQueryParams` lowers it, and the binding\'s composition seam '
    + 'AND-combines it with the named view\'s rules through `mergeFilterNodes`. The ruled '
    + 'migration check ran with the change: the in-repo sweep found four spec test fixtures '
    + 'at the binding (`page.test.ts`, all record form), five showcase authors at the block '
    + 'doors (`my-work.page.ts`, `index.ts`: four records on `object-metric`, one AST tuple '
    + 'array on `object-grid`) and three lint fixtures — every one rewritten to the rule array '
    + 'in the same change, and zero outside those files; this entry carries the prescription '
    + 'for authors outside the repo. '
    + 'Metadata AT REST: the mappable part of the table above is a D2 conversion, '
    + '`page-component-filter-record-to-rule-array` (ruled 2026-09-12, option B: convert what '
    + 'maps losslessly and name what does not, rather than leave every stored row to its next '
    + 'save or flatten combinators), so '
    + '`os migrate meta --stored` (the pass over a deployment\'s `sys_metadata` rows) rewrites '
    + 'a stored page whose `filter` is a flat record, an operator object whose operators the '
    + 'rule vocabulary spells, several such keys, or a single-level AST tuple array, and every '
    + 'stored-row read replays the same rewrite until it does. It is retired from the load '
    + 'path: an author writing the record form is still refused at the `filter` door. ⚠️ A '
    + 'filter carrying `$and` / `$or` / `$not` is left exactly as stored — the rule array '
    + 'only ANDs, and flattening a combinator changes which rows the page selects — and so is '
    + 'any filter with a part that has no lossless rule spelling: a `null` value (the renderer '
    + 'skips that key, so it constrains nothing today, where a rule would test IS NULL), an '
    + 'operator such as `$null` / `$exists` or an AST `like`, an array or object comparand in '
    + 'equality position, or an AST `and` / `or` group. None of this depends on where a '
    + 'block\'s rows come from: a filter on a component whose rows are inline (`data: { '
    + 'provider: \'value\' }`, a `data` array, or `staticData`) — the binding\'s included — is '
    + 'rewritten or left exactly as it would be on a block that queries an object, because the '
    + '`object-map`, `object-tree`, `object-calendar` and `object-gantt` blocks of the objectui '
    + 'version this release pins match a rule array against those rows and select the rows the '
    + 'stored form selected. A row left as stored keeps loading unchanged '
    + '(`applyConversionsToStoredItem` replays the chain without validating, by its own '
    + 'contract), and its `filter` door refuses the form: at `dataSource.filter` on the page\'s '
    + 'next save; at a block\'s `properties.filter` — like `properties.defaultFilters`, a key of '
    + 'the open `properties` bag — only as the component-props gate\'s advisory finding '
    + '(os validate, os build, os lint), since a re-save through the metadata API is not '
    + 'refused there. For a combinator record that refusal names the combinator and says why no '
    + 'rule spells it. `os migrate meta --stored` lists each such filter as a TODO under its '
    + 'row, naming the block and what blocks the rewrite (a value that is not a record or AST '
    + 'form at all — a bare string or number one of the former `z.unknown()` doors took — is '
    + 'neither converted nor reported, and a row carrying nothing else reads as already on '
    + 'protocol); a row whose only finding is such a TODO is reported `skipped`, and the run\'s '
    + 'exit code does not change for it.',
  acceptanceCriteria:
    '`ElementDataSourceSchema.safeParse({ object, filter: [{ field: \'status\', operator: '
    + '\'equals\', value: \'active\' }] })` succeeds and the parsed `filter` is the same rule '
    + 'array; `ComponentPropsMap[\'object-grid\' | \'object-metric\' | \'object-kanban\' | '
    + '\'object-calendar\'].safeParse({ filter: <that array> })` raises no issue at `filter`; '
    + 'a record-form `filter: { status: \'active\' }` is refused at the `filter` path of all '
    + 'five doors (`invalid_type`, expected array), and an AST tuple array is refused at '
    + '`filter.0` (expected object). No `filter` door in `ComponentPropsMap` accepts the '
    + 'record any more (the twin of the census pin that asks whether any `filter` door still '
    + 'refuses the array). At runtime each block and the '
    + 'binding select exactly the rows the array selects — the same filter a list view '
    + 'renders — including the `object-metric` aggregate tile, whose analytics `where` is the '
    + 'lowered condition. Downstream (objectui, after a released spec version reaches the '
    + 'pin): the seventeen `dataSource.filter` test authors at the pin (fifteen tuple arrays, '
    + 'two records) become off-spec fixtures and `ElementDataSourceConfig.filter`\'s '
    + '"three shapes" note narrows — objectui cards filed by the seat, not blocked on here.',
};
