// Copyright (c) 2026 ObjectStack. Licensed under the Apache-2.0 license.

import type { SemanticMigration } from '../../types.js';

export const entry: SemanticMigration = {
  id: 'kernel-package-lifecycle-durations-unit-in-key',
  // No backticks in `surface` — build-upgrade-guide.ts renders it inside a
  // code span AND a table cell.
  surface: 'the three package and version lifecycle durations whose name carried no unit: '
    + 'UpgradePlan.estimatedDuration (kernel/package-upgrade.zod.ts), '
    + 'PackageDependencyResolutionResult.resolvedIn (kernel/plugin-security.zod.ts) and '
    + 'MultiVersionSupport.rollout.duration (kernel/plugin-versioning.zod.ts)',
  replacement: 'estimatedDurationSeconds, resolvedInMs and durationMs — rename each key; every '
    + 'value is unchanged',
  reason:
    'Maintainer ruling B on #14478 (2026-09-02, decision batch #43): the unit of a duration-shaped z.number() lives in the key NAME or in a unit-carrying value, never only in the describe prose, and no existing offender is grandfathered. '
    + 'These three are one entry because they are one story told to one audience — a package '
    + 'being planned, resolved and rolled out — and because the group is precisely where the '
    + 'unit SPLITS: estimatedDuration is SECONDS while resolvedIn and rollout.duration are '
    + 'MILLISECONDS, three adjacent measurements of the same install, two units, none of them '
    + 'named. A reader who learned the unit from one of these three learned it wrongly for the '
    + 'other two. The rollout case adds a second confusion of its own: duration sat directly '
    + 'beside the unit-less percentage, so one block carried a proportion and a span as '
    + 'indistinguishable bare numbers; percentage keeps its name, because a proportion has no '
    + 'time unit to carry. All three are retiredKey() tombstones; no shape here is strict, so '
    + 'a bare deletion would strip in silence. Why a semantic entry and not a D2 conversion: '
    + 'an UpgradePlan is GENERATED by IPackageService.planUpgrade() before an upgrade runs, a '
    + 'PackageDependencyResolutionResult is emitted by a resolution run, and MultiVersionSupport '
    + 'is a version-routing argument a host constructs — none is a stack collection member or '
    + 'a stored sys_metadata row, so the conversion chain has no seam that would see one. That '
    + 'is what ruling B prescribes for a key that is not authorable metadata. #15678, #14478, '
    + 'ADR-0087.',
  acceptanceCriteria:
    'Every IPackageService.planUpgrade() implementation returns estimatedDurationSeconds and '
    + 'every caller reads it under that name; every dependency-resolution producer returns '
    + 'resolvedInMs; every multi-version rollout literal spells durationMs. Authoring any old '
    + 'spelling fails to compile (input type `never`) and fails to parse with the rename '
    + 'prescription. Behaviour is unchanged in every case, and the unit split is the thing to '
    + 'check by hand rather than by search-and-replace: estimatedDurationSeconds: 120 is two '
    + 'MINUTES, while durationMs: 3600000 is one HOUR — a mechanical rename that moved a value '
    + 'between the two would be a thousand-fold error the parse cannot catch, since both '
    + 'bounds accept any non-negative integer.',
};
