// Copyright (c) 2026 ObjectStack. Licensed under the Apache-2.0 license.

import type { SemanticMigration } from '../../types.js';

export const entry: SemanticMigration = {
  id: 'schedule-flow-acting-organization-required',
  surface:
    'The START NODE `config.organization` key of every time-triggered flow — a `type: '
    + "'schedule'` flow carrying a `config.schedule` cadence, and the `timeRelative` sweep "
    + 'that carries its cadence in the same slot (`FlowTriggerKind` `schedule` / '
    + '`time_relative`) — TOGETHER WITH the deployment variable that decides whether such a '
    + 'flow arms at all, `OS_AUTOMATION_SCHEDULED_WORK_ENABLED`. Nothing is renamed, retired '
    + 'or re-typed: the start node\'s `config` is an OPEN record (ADR-0018), so the key is an '
    + 'ADDITION to a slot that already accepted it, and every flow that parses today parses '
    + 'byte-identically after the change. What narrows is the BIND-time accept set and the '
    + 'RUN-time data plane — and what the 2026-09-12 amendment narrows further is WHERE that '
    + 'narrowing applies: the declaration is required under a walled tenancy posture '
    + '(`group` / `isolated`) only, and no time-triggered flow arms anywhere until the '
    + 'deployment switches package-authored scheduled work on.',
  replacement:
    'Two deployment decisions, in this order. (1) DECIDE WHETHER THIS DEPLOYMENT RUNS '
    + 'PACKAGE-AUTHORED SCHEDULED WORK AT ALL: `OS_AUTOMATION_SCHEDULED_WORK_ENABLED=true` '
    + 'arms time-triggered flows and packaged `defineJob` cron jobs; unset — the global '
    + 'default, in every posture and every kernel — arms neither, and every such flow is '
    + 'listed by `getTriggerBindingAudit()`, the CLI startup summary and Studio as DISABLED '
    + 'BY DEPLOYMENT POLICY rather than as a binding failure. Platform-internal jobs '
    + '(approvals escalation, the lifecycle Reaper, the messaging dispatch loop, membership '
    + 'backfill) are NOT gated by it: the boundary is "authored by a package", not "runs on '
    + 'the job service". (2) ONLY IF THE SWITCH IS ON AND THE POSTURE IS WALLED, declare the '
    + 'organization each flow runs as, on the start node beside the cadence: '
    + "`config: { schedule: { … }, organization: '<sys_organization.id>' }`. There is "
    + 'deliberately NO fan-out — a sweep wanted in N organizations is N flows, one per '
    + 'organization — and deliberately no fallback: nothing on this path ever chooses an '
    + 'organization, because a wrong `organization_id` is silently authoritative to every '
    + 'report, export and cleanup that filters by organization, while a refusal is visible '
    + 'at boot and names its flow. Under the `single` posture with the switch on, declare '
    + 'NOTHING: the run carries no organization and every tenant-scoped insert beneath it '
    + 'resolves the deployment\'s one organization through the #8844 guard. ⚠️ Three '
    + 'consequences apply to a WALLED deployment that splits one flow into N, and each is '
    + 'deployment work: (1) rows whose tenant column is NULL stay visible to a scoped read '
    + '(`org = :tenant OR org IS NULL`), so after the split each such row is matched ONCE '
    + 'PER FLOW — N runs and N notifications for one row, each acting as a different '
    + 'organization; (2) the dispatch-claim key embeds the flow name '
    + '(`schedule:<flowName>:<window>`, `time-relative:<flowName>:<scope>:<recordId>`), so '
    + "renaming one flow into N abandons the current window's claims and a window already "
    + 'delivered under the old name can deliver once more under the new ones; (3) a run '
    + 'SUSPENDED before the upgrade rehydrates its context from `context_json`, which '
    + 'carries no `tenantId`, so it resumes org-less — drain or accept in-flight suspended '
    + 'runs rather than assuming the upgrade confines them retroactively.',
  reason:
    'Two maintainer rulings, both verbatim and untranslated, in the order they were given. '
    + '2026-09-08: '
    + '「多组织定时任务本来只能在组织内运行，应该带组织ID，不允许跨组织的定时任务。」 A time-triggered '
    + 'run is launched from a job tick and a job tick carries no identity, so the run reached '
    + 'the tenancy guard with nothing to offer it: the notification wrote '
    + '`organization_id = NULL`, every tenant-scoped row beneath it was refused, and the tick '
    + 'still summarised itself as healthy. 2026-09-12, on the same surface: '
    + '「schedule 是风险很大的模型，尤其在云端，无算是单独多租户还是每库一租户，可能造成极大的资源浪费。'
    + '对于单租户或着集团版私有部署，我觉得不需要做限制。定时任务 如果不好处理，现在也没想清楚，'
    + '有没有可能定义为一个环境变量，根据环境变量控制？」 and 「group 默认也关，云端每库一租户全局默认关」. '
    + 'Whether clock-driven work is affordable is a fact about the DEPLOYMENT — its database, '
    + 'its tenants, its budget — that no author can know and no metadata key should ask them '
    + 'for, so the gate is a deployment variable read at boot and the global default is OFF. '
    + 'Where the switch is on, the 2026-09-08 ruling stands unchanged under a wall and is '
    + 'moot under `single`, which holds exactly one organization and therefore has no '
    + 'cross-organization task to forbid. ⛔ NOT losslessly convertible, and the reason is '
    + 'that both remedies are values only the deployment holds: an organization id is minted '
    + 'per install at runtime and the switch is an operator decision about cost, so there is '
    + 'no authored artifact and no stored representation a transform could rewrite — '
    + '`objectstack migrate meta` cannot know which organization a given sweep belongs to, '
    + 'nor whether this deployment wants scheduled work at all, and inventing either is '
    + 'precisely what the rulings forbid. Registered under ADR-0087 D3 rather than left '
    + 'silent because the change DOES carry a prescription — "decide the switch, then declare '
    + 'one flow per organization under a wall" is deployment work a human must do, which is '
    + 'what D3 says a structured TODO is for. The direct precedent is '
    + '`rest-requireauth-default-flip` (protocol 12): behaviour-only, no shape moved, a '
    + 'deployment judgement no transform can make, registered anyway.',
  acceptanceCriteria:
    'The deployment has DECIDED the switch, and the decision is visible: `os doctor` prints '
    + 'the effective `OS_AUTOMATION_SCHEDULED_WORK_ENABLED` value. A deployment that leaves '
    + 'it unset — the default — accepts that no packaged time-triggered flow and no packaged '
    + '`defineJob` runs, and confirms that every such flow appears in '
    + '`getTriggerBindingAudit()` and the CLI startup summary with the reason DISABLED BY '
    + 'DEPLOYMENT POLICY and NOT as "binding failed"; no boot line reads '
    + '`[schedule] NOT BOUND` / `[time-relative] NOT BOUND`, because nothing was refused for '
    + 'a declaration. A deployment that sets it to `true` under posture `single` confirms '
    + 'that its time-triggered flows are armed while declaring no `config.organization`, and '
    + 'that the runs they launch carry none. A deployment that sets it to `true` under a '
    + 'walled posture (`group` / `isolated`) confirms that every `schedule` / `time_relative` '
    + 'flow in the stack declares a non-empty `config.organization` on its start node, that '
    + 'boot logs no `NOT BOUND` line, that `getFlowRuntimeStates()` reports `bound: true` and '
    + 'that `getTriggerBindingAudit()` lists no time-triggered flow — and, where it ran ONE '
    + 'flow across all organizations, that it has split it into one flow per organization and '
    + 're-checked the three consequences above (NULL-tenant rows, abandoned dispatch claims, '
    + 'suspended runs). ⛔ There is NO authoring-time lint for the declaration: it was '
    + 'retired with this amendment because neither the switch nor the posture is knowable '
    + 'from a stack, so `os lint` reporting nothing is the criterion being met, not a check '
    + 'that was skipped. ⚠️ `@objectstack/driver-memory` has NO legal configuration for a '
    + 'time-triggered flow that touches per-organization data under a wall: it refuses any '
    + 'call handed a tenant scope (`MEMORY_MULTI_TENANT_UNSUPPORTED`), so a declared flow is '
    + 'refused per call while an undeclared one is not armed at all. Multi-organization '
    + 'deployments use `@objectstack/driver-sql`.',
};
