// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

import { describe, it, expect } from 'vitest';
import { ObjectTranslationDataSchema, TranslationDataSchema, type TranslationBundle } from './translation.zod';
import { GetFieldLabelsResponseSchema, GetLocalesResponseSchema } from '../api/protocol.zod';
import {
  resolveViewLabel,
  resolveViewDescription,
  resolveActionLabel,
  resolveActionConfirm,
  resolveActionSuccess,
  resolveActionResultDialog,
  translateAction,
  translateMetadataDocument,
  resolveObjectFieldLabels,
  toLocaleDescriptors,
  normalizeSupportedLocales,
} from './i18n-resolver';
// #4854 — the served view document is whatever THIS composer emits, so the
// fixture below is generated by it rather than transcribed from a bug report.
import { expandViewContainer } from '../ui/view.zod';

describe('ObjectTranslationDataSchema (_views/_actions extensions)', () => {
  it('accepts _views entries', () => {
    const data = ObjectTranslationDataSchema.parse({
      label: '客户',
      _views: {
        all_accounts: { label: '全部客户', description: '所有客户列表' },
        my_accounts: { label: '我的客户' },
      },
    });
    expect(data._views?.all_accounts.label).toBe('全部客户');
    expect(data._views?.all_accounts.description).toBe('所有客户列表');
    expect(data._views?.my_accounts.label).toBe('我的客户');
  });

  it('accepts _actions entries with confirm + success', () => {
    const data = ObjectTranslationDataSchema.parse({
      label: '线索',
      _actions: {
        convert_lead: {
          label: '转化线索',
          confirmText: '确定要转化此线索吗？',
          successMessage: '线索转化成功！',
        },
      },
    });
    expect(data._actions?.convert_lead.label).toBe('转化线索');
    expect(data._actions?.convert_lead.confirmText).toBe('确定要转化此线索吗？');
    expect(data._actions?.convert_lead.successMessage).toBe('线索转化成功！');
  });

  it('accepts _actions entries with a resultDialog node (dotted field paths stay literal keys)', () => {
    const data = ObjectTranslationDataSchema.parse({
      label: '用户',
      _actions: {
        create_user: {
          label: '创建用户',
          resultDialog: {
            title: '用户已创建',
            description: '请立即复制临时密码——它只显示一次，不会被存储。',
            acknowledge: '我已保存该密码',
            fields: {
              'user.email': '邮箱',
              temporaryPassword: '临时密码',
            },
          },
        },
      },
    });
    expect(data._actions?.create_user.resultDialog?.title).toBe('用户已创建');
    expect(data._actions?.create_user.resultDialog?.fields?.['user.email']).toBe('邮箱');
    expect(data._actions?.create_user.resultDialog?.fields?.temporaryPassword).toBe('临时密码');
  });
});

describe('TranslationDataSchema globalActions', () => {
  it('accepts globalActions', () => {
    const data = TranslationDataSchema.parse({
      globalActions: {
        log_call: { label: '记录通话', successMessage: '通话已记录！' },
        export_csv: { label: '导出 CSV' },
      },
    });
    expect(data.globalActions?.log_call.label).toBe('记录通话');
    expect(data.globalActions?.export_csv.label).toBe('导出 CSV');
  });
});

const bundle: TranslationBundle = {
  en: {
    objects: {
      account: {
        label: 'Account',
        _views: {
          all_accounts: { label: 'All Accounts', description: 'Every account' },
        },
        _actions: {
          merge_accounts: {
            label: 'Merge Accounts',
            confirmText: 'Merge selected accounts?',
            successMessage: 'Accounts merged.',
          },
        },
      },
    },
    globalActions: {
      export_csv: { label: 'Export CSV', successMessage: 'Export ready.' },
    },
  },
  'zh-CN': {
    objects: {
      account: {
        label: '客户',
        _views: { all_accounts: { label: '全部客户', description: '所有客户' } },
        _actions: {
          merge_accounts: {
            label: '合并客户',
            confirmText: '确认合并选中的客户？',
            successMessage: '客户已合并。',
          },
        },
      },
    },
    globalActions: {
      export_csv: { label: '导出 CSV', successMessage: '导出完成。' },
    },
  },
};

describe('resolveViewLabel', () => {
  it('returns translated label for the active locale', () => {
    expect(
      resolveViewLabel(
        bundle,
        { name: 'all_accounts', label: 'All Accounts', objectName: 'account' },
        { locale: 'zh-CN' },
      ),
    ).toBe('全部客户');
  });

  it('falls back through fallbackChain to en', () => {
    expect(
      resolveViewLabel(
        bundle,
        { name: 'all_accounts', label: 'All Accounts', objectName: 'account' },
        { locale: 'fr-FR', fallbackChain: ['en'] },
      ),
    ).toBe('All Accounts');
  });

  it('falls back to literal label when no bundle entry exists', () => {
    expect(
      resolveViewLabel(
        bundle,
        { name: 'unknown_view', label: 'Unknown View', objectName: 'account' },
        { locale: 'zh-CN' },
      ),
    ).toBe('Unknown View');
  });

  it('uses data.object when objectName is missing', () => {
    expect(
      resolveViewLabel(
        bundle,
        { name: 'all_accounts', label: 'All Accounts', data: { object: 'account' } },
        { locale: 'zh-CN' },
      ),
    ).toBe('全部客户');
  });

  it('returns label when bundle is undefined', () => {
    expect(
      resolveViewLabel(undefined, {
        name: 'all_accounts',
        label: 'All Accounts',
        objectName: 'account',
      }),
    ).toBe('All Accounts');
  });
});

describe('resolveViewDescription', () => {
  it('returns translated description', () => {
    expect(
      resolveViewDescription(
        bundle,
        { name: 'all_accounts', objectName: 'account' },
        { locale: 'zh-CN' },
      ),
    ).toBe('所有客户');
  });

  it('falls back to literal description', () => {
    expect(
      resolveViewDescription(
        bundle,
        { name: 'unknown', objectName: 'account', description: 'literal' },
        { locale: 'zh-CN' },
      ),
    ).toBe('literal');
  });
});

/**
 * #4854 — the shape the RUNTIME actually serves.
 *
 * `GET /api/v1/meta/view?object=account` returns the `ExpandedViewItem`s that
 * `expandViewContainer` produces and the ObjectQL engine registers verbatim;
 * `RestServer` filters them on `viewKind && object === <object>` and hands each
 * one to `translateMetadataDocument('view', …)`. That document carries the
 * object at top-level `object` (NOT `objectName`, NOT `data.object`) and a
 * `name` namespaced to `<object>.<viewKey>`, while translations key on the bare
 * `<viewKey>` — so both halves of the old lookup missed and every view label
 * fell back to its English literal.
 *
 * The fixture is DERIVED from the composer rather than hand-copied, so it
 * cannot drift from the serving path: if `expandViewContainer` ever changes how
 * it spells identity, these expectations change with it instead of silently
 * describing a shape the runtime no longer produces.
 */
describe('resolveViewLabel — served view-document shape (#4854)', () => {
  const container = {
    listViews: {
      all_accounts: {
        label: 'All Accounts',
        type: 'grid' as const,
        data: { provider: 'object' as const, object: 'account' },
        columns: [{ field: 'name' }],
      },
      // Same object, no `_views` entry in the bundle — the negative control.
      recent_accounts: {
        label: 'Recent Accounts',
        type: 'grid' as const,
        data: { provider: 'object' as const, object: 'account' },
        columns: [{ field: 'name' }],
      },
    },
    // A default form carries no `data` at all, so top-level `object` is the
    // ONLY field that can identify its object.
    form: {
      type: 'simple' as const,
      sections: [{ label: 'Details', fields: [{ field: 'name' }] }],
    },
  };

  const served = expandViewContainer('account', container);
  const byName = (name: string) => {
    const item = served.find((v) => v.name === name);
    if (!item) throw new Error(`fixture missing ${name}; got ${served.map((v) => v.name).join(', ')}`);
    return item as unknown as Parameters<typeof resolveViewLabel>[1];
  };

  it('composes the identity this test is pinned to', () => {
    const item = byName('account.all_accounts') as any;
    // The two fields the resolver used to read are absent from a real document.
    expect(item.objectName).toBeUndefined();
    expect(item.data).toBeUndefined();
    // The two it must read instead.
    expect(item.object).toBe('account');
    expect(item.name).toBe('account.all_accounts');
    // The bare key lives ONLY in the namespaced name — not in `config.name`.
    expect(item.config?.name).toBeUndefined();
  });

  it('resolves a translation from top-level `object` + the bare view key', () => {
    expect(resolveViewLabel(bundle, byName('account.all_accounts'), { locale: 'zh-CN' }))
      .toBe('全部客户');
  });

  it('resolves the description the same way', () => {
    expect(resolveViewDescription(bundle, byName('account.all_accounts'), { locale: 'zh-CN' }))
      .toBe('所有客户');
  });

  it('falls back through the locale chain to en', () => {
    expect(
      resolveViewLabel(bundle, byName('account.all_accounts'), {
        locale: 'fr-FR',
        fallbackChain: ['en'],
      }),
    ).toBe('All Accounts');
  });

  it('falls back to the literal label when the object has no matching _views entry', () => {
    expect(resolveViewLabel(bundle, byName('account.recent_accounts'), { locale: 'zh-CN' }))
      .toBe('Recent Accounts');
  });

  it('resolves an object whose config carries no `data` (default form)', () => {
    const form = served.find((v) => v.viewKind === 'form')!;
    expect((form.config as any).data).toBeUndefined();
    // No `_views` entry for it — but it must reach the lookup on top-level
    // `object` instead of bailing at the `!objectName` guard, i.e. fall back to
    // the literal name rather than to `undefined`.
    expect(resolveViewLabel(bundle, form as any, { locale: 'zh-CN' })).toBe(form.name);
  });

  it('translates through the REST boundary entry point', () => {
    const out = translateMetadataDocument('view', byName('account.all_accounts'), bundle, {
      locale: 'zh-CN',
    });
    expect(out.label).toBe('全部客户');
    // Identity and payload survive translation untouched.
    expect(out.name).toBe('account.all_accounts');
    expect(out.object).toBe('account');
    expect(out.viewKind).toBe('list');
    expect(out.config).toEqual(byName('account.all_accounts').config);
  });

  it('does not strip a prefix that is not this view\'s object', () => {
    // A bare name stays bare (the hand-constructed shape), and a name prefixed
    // with a DIFFERENT object is not truncated.
    const view = { name: 'other_object.all_accounts', object: 'account', label: 'All Accounts' };
    expect(resolveViewLabel(bundle, view, { locale: 'zh-CN' })).toBe('All Accounts');
  });

  it('still resolves the retargeting case via config.data.object', () => {
    // A named list view may bind another object through its own config data;
    // with no top-level `object`, `config.data.object` is the remaining source.
    const view = {
      name: 'all_accounts',
      label: 'All Accounts',
      config: { data: { object: 'account' } },
    };
    expect(resolveViewLabel(bundle, view, { locale: 'zh-CN' })).toBe('全部客户');
  });
});

describe('resolveActionLabel + confirm + success', () => {
  it('translates an object-bound action', () => {
    const action = {
      name: 'merge_accounts',
      label: 'Merge Accounts',
      objectName: 'account',
      confirmText: 'Merge selected accounts?',
      successMessage: 'Accounts merged.',
    };
    expect(resolveActionLabel(bundle, action, { locale: 'zh-CN' })).toBe('合并客户');
    expect(resolveActionConfirm(bundle, action, { locale: 'zh-CN' })).toBe(
      '确认合并选中的客户？',
    );
    expect(resolveActionSuccess(bundle, action, { locale: 'zh-CN' })).toBe('客户已合并。');
  });

  it('falls back to globalActions for object-less actions', () => {
    const action = {
      name: 'export_csv',
      label: 'Export to CSV',
      successMessage: 'Export completed!',
    };
    expect(resolveActionLabel(bundle, action, { locale: 'zh-CN' })).toBe('导出 CSV');
    expect(resolveActionSuccess(bundle, action, { locale: 'zh-CN' })).toBe('导出完成。');
    expect(resolveActionConfirm(bundle, action, { locale: 'zh-CN' })).toBeUndefined();
  });

  it('returns the literal label when no bundle entry matches', () => {
    expect(
      resolveActionLabel(
        bundle,
        { name: 'unknown_action', label: 'Mystery', objectName: 'account' },
        { locale: 'zh-CN' },
      ),
    ).toBe('Mystery');
  });

  it('returns the action name when neither bundle nor literal label exists', () => {
    expect(
      resolveActionLabel(undefined, { name: 'nameless_action' }),
    ).toBe('nameless_action');
  });
});

describe('resolveActionResultDialog + translateAction', () => {
  const dialogBundle: TranslationBundle = {
    'zh-CN': {
      objects: {
        sys_user: {
          label: '用户',
          _actions: {
            create_user: {
              resultDialog: {
                title: '用户已创建',
                description: '请立即复制临时密码——它只显示一次，不会被存储。',
                acknowledge: '我已保存该密码',
                fields: {
                  'user.email': '邮箱',
                  temporaryPassword: '临时密码',
                },
              },
            },
          },
        },
      },
      globalActions: {
        export_secrets: {
          resultDialog: { title: '密钥已导出' },
        },
      },
    },
  };

  const createUser = {
    name: 'create_user',
    label: 'Create User',
    objectName: 'sys_user',
    resultDialog: {
      title: 'User Created',
      description: 'Copy the temporary password now — it is shown only once and never stored.',
      acknowledge: 'I have saved this password',
      fields: [
        { path: 'user.email', label: 'Email', format: 'text' },
        { path: 'user.phoneNumber', label: 'Phone Number', format: 'text' },
        { path: 'temporaryPassword', label: 'Temporary Password', format: 'secret' },
      ],
    },
  };

  it('overlays title/description/acknowledge and per-path field labels', () => {
    const out = resolveActionResultDialog(dialogBundle, createUser, { locale: 'zh-CN' });
    expect(out?.title).toBe('用户已创建');
    expect(out?.description).toBe('请立即复制临时密码——它只显示一次，不会被存储。');
    expect(out?.acknowledge).toBe('我已保存该密码');
    expect(out?.fields?.[0]).toEqual({ path: 'user.email', label: '邮箱', format: 'text' });
    // Untranslated field keeps its literal label; formats survive the overlay.
    expect(out?.fields?.[1]).toEqual({ path: 'user.phoneNumber', label: 'Phone Number', format: 'text' });
    expect(out?.fields?.[2]).toEqual({ path: 'temporaryPassword', label: '临时密码', format: 'secret' });
    // Source spec is not mutated.
    expect(createUser.resultDialog.title).toBe('User Created');
    expect(createUser.resultDialog.fields[0].label).toBe('Email');
  });

  it('falls back to the literal spec when the locale has no entry', () => {
    const out = resolveActionResultDialog(dialogBundle, createUser, { locale: 'ja-JP', fallbackChain: [] });
    expect(out?.title).toBe('User Created');
    expect(out?.fields?.[0].label).toBe('Email');
  });

  it('resolves globalActions for object-less actions', () => {
    const out = resolveActionResultDialog(
      dialogBundle,
      { name: 'export_secrets', resultDialog: { title: 'Secrets exported' } },
      { locale: 'zh-CN' },
    );
    expect(out?.title).toBe('密钥已导出');
  });

  it('returns undefined when the action has no resultDialog', () => {
    expect(
      resolveActionResultDialog(dialogBundle, { name: 'create_user', objectName: 'sys_user' }, { locale: 'zh-CN' }),
    ).toBeUndefined();
  });

  it('translateAction carries the translated resultDialog', () => {
    const out = translateAction(createUser, dialogBundle, { locale: 'zh-CN' });
    expect(out.resultDialog?.title).toBe('用户已创建');
    expect(out.resultDialog?.fields?.[2].label).toBe('临时密码');
  });
});

describe('translateMetadataDocument', () => {
  it('translates a view document', () => {
    const view = {
      name: 'all_accounts',
      label: 'All Accounts',
      description: 'Every account',
      objectName: 'account',
      kind: 'list',
    };
    const out = translateMetadataDocument('view', view, bundle, { locale: 'zh-CN' });
    expect(out.label).toBe('全部客户');
    expect(out.description).toBe('所有客户');
    expect(out.kind).toBe('list');
    expect(view.label).toBe('All Accounts'); // not mutated
  });

  it('translates an action document with confirm + success', () => {
    const action = {
      name: 'merge_accounts',
      label: 'Merge Accounts',
      objectName: 'account',
      confirmText: 'Merge selected accounts?',
      successMessage: 'Accounts merged.',
    };
    const out = translateMetadataDocument('action', action, bundle, { locale: 'zh-CN' });
    expect(out.label).toBe('合并客户');
    expect(out.confirmText).toBe('确认合并选中的客户？');
    expect(out.successMessage).toBe('客户已合并。');
  });

  it('returns unknown types unchanged', () => {
    const doc = { name: 'foo', label: 'Bar' };
    const out = translateMetadataDocument('mystery', doc, bundle, { locale: 'zh-CN' });
    expect(out).toBe(doc);
  });

  it('returns literal labels when bundle is undefined', () => {
    const view = { name: 'all_accounts', label: 'All Accounts', objectName: 'account' };
    const out = translateMetadataDocument('view', view, undefined, { locale: 'zh-CN' });
    expect(out.label).toBe('All Accounts');
  });
});

// ────────────────────────────────────────────────────────────────────────────
// metadataForms namespace + resolver
// ────────────────────────────────────────────────────────────────────────────

import {
  resolveMetadataTypeLabel,
  resolveMetadataTypeDescription,
  resolveMetadataFormLabels,
} from './i18n-resolver';

describe('TranslationDataSchema metadataForms', () => {
  it('accepts a fully-populated metadataForms entry', () => {
    const data = TranslationDataSchema.parse({
      metadataForms: {
        object: {
          label: '对象',
          description: '业务对象定义',
          sections: {
            basics: { label: '基础信息', description: '标识与标签' },
            capabilities: { label: '功能开关' },
          },
          fields: {
            name: { label: '名称', helpText: 'snake_case 唯一标识符', placeholder: 'e.g. account' },
            'capabilities.trackHistory': { label: '历史追踪' },
          },
        },
      },
    });
    expect(data.metadataForms?.object?.label).toBe('对象');
    expect(data.metadataForms?.object?.sections?.basics?.label).toBe('基础信息');
    expect(data.metadataForms?.object?.fields?.['capabilities.trackHistory']?.label).toBe('历史追踪');
  });

  it('all metadataForms fields are optional', () => {
    expect(() => TranslationDataSchema.parse({ metadataForms: {} })).not.toThrow();
    expect(() => TranslationDataSchema.parse({ metadataForms: { object: {} } })).not.toThrow();
  });
});

describe('resolveMetadataTypeLabel', () => {
  const bundle: TranslationBundle = {
    'zh-CN': {
      metadataForms: { object: { label: '对象', description: '业务对象定义' } },
    },
    'en-US': {
      metadataForms: { object: { label: 'Object (en-US)' } },
    },
  };

  it('returns translated label when present', () => {
    expect(resolveMetadataTypeLabel(bundle, 'object', 'Object', { locale: 'zh-CN' })).toBe('对象');
  });

  it('falls back to the literal when no bundle entry', () => {
    expect(resolveMetadataTypeLabel(bundle, 'unknown', 'Unknown', { locale: 'zh-CN' })).toBe('Unknown');
  });

  it('walks the locale fallback chain', () => {
    expect(
      resolveMetadataTypeLabel(bundle, 'object', 'Object', {
        locale: 'fr-FR',
        fallbackChain: ['en-US'],
      }),
    ).toBe('Object (en-US)');
  });

  it('returns fallback when bundle is undefined', () => {
    expect(resolveMetadataTypeLabel(undefined, 'object', 'Object', { locale: 'zh-CN' })).toBe('Object');
  });
});

describe('resolveMetadataTypeDescription', () => {
  const bundle: TranslationBundle = {
    'zh-CN': { metadataForms: { object: { description: '业务对象定义' } } },
  };
  it('returns translated description', () => {
    expect(resolveMetadataTypeDescription(bundle, 'object', 'Business object definition', { locale: 'zh-CN' })).toBe(
      '业务对象定义',
    );
  });
  it('returns literal fallback when no translation', () => {
    expect(resolveMetadataTypeDescription(bundle, 'field', 'Field def', { locale: 'zh-CN' })).toBe('Field def');
  });
  it('passes through undefined fallback', () => {
    expect(resolveMetadataTypeDescription(bundle, 'field', undefined, { locale: 'zh-CN' })).toBeUndefined();
  });
});

describe('resolveMetadataFormLabels', () => {
  const bundle: TranslationBundle = {
    'zh-CN': {
      metadataForms: {
        object: {
          sections: {
            basics: { label: '基础信息', description: '标识与标签' },
            capabilities: { label: '功能开关' },
          },
          fields: {
            name: { label: '名称', helpText: 'snake_case 唯一标识符' },
            label: { label: '显示名' },
            'capabilities.trackHistory': { label: '历史追踪' },
            'fields.items.label': { label: '字段标签' },
          },
        },
      },
    },
  };

  const form = {
    schemaId: 'object',
    type: 'simple',
    sections: [
      {
        name: 'basics',
        label: 'Basics',
        description: 'Identity and labels.',
        fields: [
          { field: 'name', type: 'text', helpText: 'snake_case unique identifier' },
          { field: 'label', type: 'text' },
          { field: 'description', type: 'textarea' }, // No translation → unchanged
        ],
      },
      {
        name: 'capabilities',
        label: 'Capabilities',
        fields: [
          {
            field: 'capabilities',
            type: 'composite',
            fields: [
              { field: 'trackHistory', type: 'boolean' },
              { field: 'searchable', type: 'boolean' },
            ],
          },
        ],
      },
      {
        // No `name` → only field-level translations apply
        label: 'Untranslated section',
        fields: [{ field: 'something', type: 'text' }],
      },
      {
        name: 'fields',
        label: 'Fields',
        fields: [
          {
            field: 'fields',
            type: 'repeater',
            fields: [
              { field: 'items', type: 'composite', fields: [{ field: 'label', type: 'text' }] },
            ],
          },
        ],
      },
    ],
  };

  it('translates section labels keyed by section.name', () => {
    const out = resolveMetadataFormLabels(form, 'object', bundle, { locale: 'zh-CN' });
    expect(out.sections[0].label).toBe('基础信息');
    expect(out.sections[0].description).toBe('标识与标签');
    expect(out.sections[1].label).toBe('功能开关');
  });

  it('leaves sections without name unchanged at section level', () => {
    const out = resolveMetadataFormLabels(form, 'object', bundle, { locale: 'zh-CN' });
    expect(out.sections[2].label).toBe('Untranslated section');
  });

  it('translates top-level field label + helpText', () => {
    const out = resolveMetadataFormLabels(form, 'object', bundle, { locale: 'zh-CN' });
    const nameField = out.sections[0].fields[0];
    expect(nameField.label).toBe('名称');
    expect(nameField.helpText).toBe('snake_case 唯一标识符');
  });

  it('leaves untranslated fields untouched', () => {
    const out = resolveMetadataFormLabels(form, 'object', bundle, { locale: 'zh-CN' });
    expect(out.sections[0].fields[2].field).toBe('description');
    expect(out.sections[0].fields[2].label).toBeUndefined();
  });

  it('translates nested composite field via dot-notation path', () => {
    const out = resolveMetadataFormLabels(form, 'object', bundle, { locale: 'zh-CN' });
    const trackHistory = out.sections[1].fields[0].fields[0];
    expect(trackHistory.label).toBe('历史追踪');
    // sibling without translation stays untranslated
    expect(out.sections[1].fields[0].fields[1].label).toBeUndefined();
  });

  it('translates deeply-nested repeater sub-field via dot-notation path', () => {
    const out = resolveMetadataFormLabels(form, 'object', bundle, { locale: 'zh-CN' });
    const labelField = out.sections[3].fields[0].fields[0].fields[0];
    expect(labelField.label).toBe('字段标签');
  });

  it('returns the input unchanged when no bundle entry for type', () => {
    const out = resolveMetadataFormLabels(form, 'unknown_type', bundle, { locale: 'zh-CN' });
    expect(out).toBe(form);
  });

  it('returns the input unchanged when bundle is undefined', () => {
    expect(resolveMetadataFormLabels(form, 'object', undefined, { locale: 'zh-CN' })).toBe(form);
  });

  it('does not mutate the input form', () => {
    const snapshot = JSON.parse(JSON.stringify(form));
    resolveMetadataFormLabels(form, 'object', bundle, { locale: 'zh-CN' });
    expect(form).toEqual(snapshot);
  });

  it('respects locale fallback chain', () => {
    const fallbackBundle: TranslationBundle = {
      'en-US': {
        metadataForms: { object: { sections: { basics: { label: 'Basics (en)' } } } },
      },
    };
    const out = resolveMetadataFormLabels(form, 'object', fallbackBundle, {
      locale: 'fr-FR',
      fallbackChain: ['en-US'],
    });
    expect(out.sections[0].label).toBe('Basics (en)');
  });
});

import {
  translateApp,
  translateDashboard,
  resolveViewLabel as _resolveViewLabel,
  type DashboardLike,
} from './i18n-resolver';

describe('locale fallback resolution (BCP-47)', () => {
  const bundle: TranslationBundle = {
    'zh-CN': {
      objects: { account: { label: '客户' } },
    },
  };

  it('resolves base language to a registered region variant (zh → zh-CN)', () => {
    const out = translateMetadataDocument(
      'object',
      { name: 'account', label: 'Account' },
      bundle,
      { locale: 'zh' },
    );
    expect(out.label).toBe('客户');
  });

  it('resolves case-insensitively (zh-cn → zh-CN)', () => {
    const out = translateMetadataDocument(
      'object',
      { name: 'account', label: 'Account' },
      bundle,
      { locale: 'zh-cn' },
    );
    expect(out.label).toBe('客户');
  });

  it('resolves a region-qualified request down to base/other variant (zh-TW → zh-CN)', () => {
    const out = translateMetadataDocument(
      'object',
      { name: 'account', label: 'Account' },
      bundle,
      { locale: 'zh-TW' },
    );
    expect(out.label).toBe('客户');
  });

  it('falls back to literal when no related locale is registered', () => {
    const out = translateMetadataDocument(
      'object',
      { name: 'account', label: 'Account' },
      bundle,
      { locale: 'fr', fallbackChain: [] },
    );
    expect(out.label).toBe('Account');
  });
});

describe('translateApp', () => {
  const bundle: TranslationBundle = {
    'zh-CN': {
      apps: {
        setup: {
          label: '系统设置',
          description: '平台设置与管理',
          navigation: {
            group_overview: { label: '总览' },
            nav_users: { label: '用户' },
          },
        },
      },
    },
  };

  const app = {
    name: 'setup',
    label: 'Setup',
    description: 'Platform settings and administration',
    navigation: [
      {
        id: 'group_overview',
        type: 'group',
        label: 'Overview',
        children: [{ id: 'nav_users', type: 'object', label: 'Users' }],
      },
    ],
  };

  it('translates app label/description and nested navigation labels', () => {
    const out = translateApp(app, bundle, { locale: 'zh-CN' });
    expect(out.label).toBe('系统设置');
    expect(out.description).toBe('平台设置与管理');
    expect(out.navigation[0].label).toBe('总览');
    expect(out.navigation[0].children[0].label).toBe('用户');
  });

  it('works through translateMetadataDocument with app type', () => {
    const out = translateMetadataDocument('app', app, bundle, { locale: 'zh' });
    expect(out.navigation[0].children[0].label).toBe('用户');
  });

  it('does not mutate the input app', () => {
    const snapshot = JSON.parse(JSON.stringify(app));
    translateApp(app, bundle, { locale: 'zh-CN' });
    expect(app).toEqual(snapshot);
  });

  it('falls back to literal labels when no translation present', () => {
    const out = translateApp(app, undefined, { locale: 'zh-CN' });
    expect(out.label).toBe('Setup');
    expect(out.navigation[0].label).toBe('Overview');
  });
});

describe('translateDashboard', () => {
  const bundle: TranslationBundle = {
    'zh-CN': {
      dashboards: {
        system_overview: {
          label: '系统概览',
          widgets: {
            widget_total_users: { title: '用户总数', description: '系统中注册的用户总数' },
          },
        },
      },
    },
  };

  const dashboard = {
    name: 'system_overview',
    label: 'System Overview',
    widgets: [
      { id: 'widget_total_users', title: 'Total Users', description: 'Total registered users' },
      { id: 'widget_other', title: 'Other' },
    ],
  };

  it('translates dashboard label and widget title/description', () => {
    const out = translateDashboard(dashboard, bundle, { locale: 'zh-CN' });
    expect(out.label).toBe('系统概览');
    expect(out.widgets[0].title).toBe('用户总数');
    expect(out.widgets[0].description).toBe('系统中注册的用户总数');
  });

  it('leaves widgets without a translation entry unchanged', () => {
    const out = translateDashboard(dashboard, bundle, { locale: 'zh-CN' });
    expect(out.widgets[1].title).toBe('Other');
  });

  // #7862 — `subCaption` overlays the metric widget's `options.description`,
  // a DIFFERENT authored field from `widget.description` (#5428 item 4: two
  // authored fields, two keys).
  describe('widget subCaption (#7862)', () => {
    const subBundle: TranslationBundle = {
      'zh-CN': {
        dashboards: {
          system_overview: {
            widgets: {
              widget_total_users: {
                title: '用户总数',
                description: '系统中注册的用户总数',
                subCaption: '较上月',
              },
            },
          },
        },
      },
    };
    const metricDashboard = {
      name: 'system_overview',
      widgets: [
        {
          id: 'widget_total_users',
          type: 'metric',
          title: 'Total Users',
          description: 'Total registered users',
          options: { description: 'vs last month', sortBy: 'created' },
        },
        {
          id: 'widget_other',
          type: 'metric',
          title: 'Other',
          description: 'Other card copy',
          options: { description: 'untouched extra' },
        },
      ],
    };

    it('overlays `options.description` and carries the other options keys through', () => {
      const out = translateDashboard(metricDashboard, subBundle, { locale: 'zh-CN' });
      expect(out.widgets[0].options).toEqual({ description: '较上月', sortBy: 'created' });
    });

    it('keeps the two authored fields on their own keys — `description` never reaches `options.description`, `subCaption` never reaches `widget.description`', () => {
      const out = translateDashboard(metricDashboard, subBundle, { locale: 'zh-CN' });
      expect(out.widgets[0].description).toBe('系统中注册的用户总数');
      expect(out.widgets[0].options?.description).toBe('较上月');
    });

    it('leaves `options` of a widget without a subCaption entry untouched (same reference semantics as title)', () => {
      const out = translateDashboard(metricDashboard, subBundle, { locale: 'zh-CN' });
      expect(out.widgets[1].options).toEqual({ description: 'untouched extra' });
    });

    it('does not mutate the input document', () => {
      translateDashboard(metricDashboard, subBundle, { locale: 'zh-CN' });
      expect(metricDashboard.widgets[0].options.description).toBe('vs last month');
    });

    it('creates the options bag when the bundle carries a subCaption and the widget has none — mirroring how a bundle-only `title` renders', () => {
      const bare: DashboardLike = { name: 'system_overview', widgets: [{ id: 'widget_total_users' }] };
      const out = translateDashboard(bare, subBundle, { locale: 'zh-CN' });
      expect(out.widgets?.[0]?.options).toEqual({ description: '较上月' });
    });
  });

  it('works through translateMetadataDocument with dashboard type', () => {
    const out = translateMetadataDocument('dashboard', dashboard, bundle, { locale: 'zh-CN' });
    expect(out.label).toBe('系统概览');
  });
});

// ────────────────────────────────────────────────────────────────────────────
// translatePage — page label/description + `page:header` title/subtitle
// ────────────────────────────────────────────────────────────────────────────

import { translatePage } from './i18n-resolver';

describe('translatePage', () => {
  const bundle: TranslationBundle = {
    'zh-CN': {
      pages: {
        connect_agent: {
          label: '连接智能体',
          subtitle: '让任意支持 MCP 的 AI 客户端受控访问此环境。',
        },
        cloud_connection_settings: {
          label: '云连接',
          title: '云连接设置',
          description: '绑定控制平面',
        },
      },
    },
  };

  const page = {
    name: 'connect_agent',
    label: 'Connect an Agent',
    regions: [
      {
        name: 'header',
        components: [
          {
            type: 'page:header',
            properties: { title: 'Connect an Agent', subtitle: 'Give any MCP-capable client…', actions: ['connect_agent'] },
          },
        ],
      },
      {
        name: 'main',
        components: [{ type: 'mcp:connect-agent', properties: {} }],
      },
    ],
  };

  it('translates the page label and its page:header title/subtitle', () => {
    const out = translatePage(page, bundle, { locale: 'zh-CN' });
    expect(out.label).toBe('连接智能体');
    expect(out.regions[0].components[0].properties.title).toBe('连接智能体');
    expect(out.regions[0].components[0].properties.subtitle).toBe('让任意支持 MCP 的 AI 客户端受控访问此环境。');
  });

  it('preserves non-translatable header properties such as actions', () => {
    const out = translatePage(page, bundle, { locale: 'zh-CN' });
    expect(out.regions[0].components[0].properties.actions).toEqual(['connect_agent']);
  });

  it('leaves non-header components untouched', () => {
    const out = translatePage(page, bundle, { locale: 'zh-CN' });
    expect(out.regions[1].components[0]).toEqual({ type: 'mcp:connect-agent', properties: {} });
  });

  it('prefers an explicit title over the label fallback', () => {
    const settingsPage = {
      name: 'cloud_connection_settings',
      label: 'Cloud Connection',
      regions: [
        { name: 'header', components: [{ type: 'page:header', properties: { title: 'Cloud Connection' } }] },
      ],
    };
    const out = translatePage(settingsPage, bundle, { locale: 'zh-CN' });
    expect(out.label).toBe('云连接');
    expect(out.description).toBe('绑定控制平面');
    expect(out.regions[0].components[0].properties.title).toBe('云连接设置');
  });

  it('leaves pages without a translation entry unchanged', () => {
    const other = {
      name: 'some_other_page',
      label: 'Other',
      regions: [{ name: 'header', components: [{ type: 'page:header', properties: { title: 'Other' } }] }],
    };
    const out = translatePage(other, bundle, { locale: 'zh-CN' });
    expect(out.label).toBe('Other');
    expect(out.regions[0].components[0].properties.title).toBe('Other');
  });

  it('does not mutate the input page', () => {
    const snapshot = JSON.parse(JSON.stringify(page));
    translatePage(page, bundle, { locale: 'zh-CN' });
    expect(page).toEqual(snapshot);
  });

  it('falls back to literal copy when no bundle is present', () => {
    const out = translatePage(page, undefined, { locale: 'zh-CN' });
    expect(out.label).toBe('Connect an Agent');
    expect(out.regions[0].components[0].properties.title).toBe('Connect an Agent');
  });

  it('handles pages with no regions', () => {
    const bare = { name: 'connect_agent', label: 'Connect an Agent' };
    const out = translatePage(bare, bundle, { locale: 'zh-CN' });
    expect(out.label).toBe('连接智能体');
    expect(out).not.toHaveProperty('regions');
  });

  it('works through translateMetadataDocument with page type', () => {
    const out = translateMetadataDocument('page', page, bundle, { locale: 'zh-CN' });
    expect(out.regions[0].components[0].properties.title).toBe('连接智能体');
  });

  it('falls back through the BCP-47 locale chain (zh → zh-CN)', () => {
    const out = translatePage(page, bundle, { locale: 'zh' });
    expect(out.label).toBe('连接智能体');
  });

  // ──────────────────────────────────────────────────────────────────────────
  // #6080 — per-component copy, keyed by component id
  //
  // Modelled on the reported downstream case: hotcrm's `sales_home_page`
  // rendered a translated header above English cards and English KPI blocks,
  // because `pages` had four keys and none of them could reach a component.
  // ──────────────────────────────────────────────────────────────────────────
  describe('per-component copy (#6080)', () => {
    const homeBundle: TranslationBundle = {
      'zh-CN': {
        pages: {
          sales_home_page: {
            label: '销售看板',
            subtitle: '欢迎回来',
            components: {
              quick_create: { title: '快速新建' },
              kpi_revenue_won: { label: '已赢收入' },
              ai_briefing: { title: '询问 AI 助手', description: '从右侧边缘打开助手面板。' },
              lead_picker: { placeholder: '搜索线索…', emptyText: '暂无记录' },
              new_lead_form: { submitLabel: '创建' },
            },
          },
        },
      },
      en: {
        pages: {
          sales_home_page: {
            components: { ai_briefing: { title: 'Ask the AI Assistant', description: 'Open the assistant panel.' } },
          },
        },
      },
    };

    const homePage = () => ({
      name: 'sales_home_page',
      label: 'Sales Home',
      regions: [{
        name: 'main',
        components: [
          { type: 'page:header', properties: { title: 'Sales Home', subtitle: 'Welcome back' } },
          { type: 'page:card', id: 'quick_create', properties: { title: 'Quick Create', icon: 'plus' } },
          { type: 'element:kpi', id: 'kpi_revenue_won', properties: { label: 'Revenue (Won)', value: 42 } },
          { type: 'page:card', id: 'ai_briefing', properties: { title: 'Ask the AI Assistant', description: 'Open the assistant panel from the right edge…' } },
          { type: 'element:record_picker', id: 'lead_picker', properties: { object: 'lead', placeholder: 'Search leads…', emptyText: 'No records' } },
          { type: 'element:form', id: 'new_lead_form', properties: { object: 'lead', submitLabel: 'Create' } },
          { type: 'page:card', id: 'untranslated_card', properties: { title: 'Still English' } },
        ],
      }],
    });

    const byId = (doc: any, id: string) =>
      doc.regions[0].components.find((c: any) => c.id === id);

    it('translates card title, KPI label, and description by component id', () => {
      const out = translatePage(homePage(), homeBundle, { locale: 'zh-CN' });
      expect(byId(out, 'quick_create').properties.title).toBe('快速新建');
      expect(byId(out, 'kpi_revenue_won').properties.label).toBe('已赢收入');
      expect(byId(out, 'ai_briefing').properties.title).toBe('询问 AI 助手');
      expect(byId(out, 'ai_briefing').properties.description).toBe('从右侧边缘打开助手面板。');
    });

    it('covers the whole measured key face, not just title/description', () => {
      const out = translatePage(homePage(), homeBundle, { locale: 'zh-CN' });
      expect(byId(out, 'lead_picker').properties.placeholder).toBe('搜索线索…');
      expect(byId(out, 'lead_picker').properties.emptyText).toBe('暂无记录');
      expect(byId(out, 'new_lead_form').properties.submitLabel).toBe('创建');
    });

    it('preserves non-copy properties alongside the overlay', () => {
      const out = translatePage(homePage(), homeBundle, { locale: 'zh-CN' });
      expect(byId(out, 'quick_create').properties.icon).toBe('plus');
      expect(byId(out, 'kpi_revenue_won').properties.value).toBe(42);
      expect(byId(out, 'lead_picker').properties.object).toBe('lead');
    });

    it('leaves a component with no entry — and one with no id — untouched', () => {
      const out = translatePage(homePage(), homeBundle, { locale: 'zh-CN' });
      expect(byId(out, 'untranslated_card').properties.title).toBe('Still English');
      // The header carries no id, so only the page-name route applies to it.
      expect(out.regions[0].components[0].properties.title).toBe('销售看板');
      expect(out.regions[0].components[0].properties.subtitle).toBe('欢迎回来');
    });

    it("lands `label` on the component's own label slot when it declares one", () => {
      // `PageComponentSchema` has BOTH a top-level `label` and an open
      // `properties` bag; copy must land where the author actually wrote it.
      const doc = {
        name: 'sales_home_page',
        regions: [{
          name: 'main',
          components: [{ type: 'element:button', id: 'kpi_revenue_won', label: 'Revenue (Won)', properties: {} }],
        }],
      };
      const out = translatePage(doc, homeBundle, { locale: 'zh-CN' });
      expect(out.regions[0].components[0].label).toBe('已赢收入');
      // …and does not invent a second spelling in the props bag.
      expect(out.regions[0].components[0].properties).not.toHaveProperty('label');
    });

    it('resolves key by key across the locale chain, not entry by entry', () => {
      // `zh-CN` translates only `title` for this id; `description` must still
      // fall back to `en` rather than being dropped because the zh entry won.
      const partial: TranslationBundle = {
        'zh-CN': { pages: { sales_home_page: { components: { ai_briefing: { title: '询问 AI 助手' } } } } },
        en: { pages: { sales_home_page: { components: { ai_briefing: { description: 'Open the assistant panel.' } } } } },
      };
      const out = translatePage(homePage(), partial, { locale: 'zh-CN' });
      expect(byId(out, 'ai_briefing').properties.title).toBe('询问 AI 助手');
      expect(byId(out, 'ai_briefing').properties.description).toBe('Open the assistant panel.');
    });

    it('lets the id-addressed route win over the page-name route on a header that has an id', () => {
      const doc = {
        name: 'sales_home_page',
        regions: [{
          name: 'header',
          // `properties` widened to the open bag it is: the overlay adds keys
          // the literal does not spell out, and inferring it as `{title}` alone
          // would make reading the result a type error.
          components: [{
            type: 'page:header',
            id: 'quick_create',
            properties: { title: 'Sales Home' } as Record<string, string>,
          }],
        }],
      };
      const out = translatePage(doc, homeBundle, { locale: 'zh-CN' });
      // `components.quick_create.title` is more specific than `pages.<name>.label`.
      expect(out.regions[0].components[0].properties.title).toBe('快速新建');
      // The page-name route still supplies what the id route did not.
      expect(out.regions[0].components[0].properties.subtitle).toBe('欢迎回来');
    });

    it('does not mutate the input page', () => {
      const doc = homePage();
      const snapshot = JSON.parse(JSON.stringify(doc));
      translatePage(doc, homeBundle, { locale: 'zh-CN' });
      expect(doc).toEqual(snapshot);
    });
  });
});

// ────────────────────────────────────────────────────────────────────────────
// #5377 — filter-preset tab labels (`objects.<o>._tabs.<tab>.label`)
// ────────────────────────────────────────────────────────────────────────────

import { resolveTabLabel } from './i18n-resolver';

describe('resolveTabLabel (#5377)', () => {
  const bundle: TranslationBundle = {
    'zh-CN': {
      objects: {
        showcase_task: {
          _tabs: { urgent: { label: '紧急' } },
          _views: { my_open: { label: '我的待办' } },
        },
      },
    },
    en: {
      objects: {
        showcase_task: {
          _tabs: { done: { label: 'Completed' } },
          _views: { my_open: { label: 'My Open Tasks' } },
        },
      },
    },
  };

  // ── the gap this closes: a tab with a `filter` and NO `view` ─────────────
  //
  // The reported headline (a whole tab bar in English) did not reproduce on
  // rc.2 and is not what this fixes: a tab that carries `view` already renders
  // its referenced view's translated label. What had no path at all was the
  // filter-only tab — it references nothing to inherit from, `_tabs` did not
  // exist, and `ObjectTranslationDataSchema` is strict, so a translator who
  // invented the key had it rejected rather than ignored.

  it('translates a filter-only tab — the shape that had no path at all', () => {
    const tab = { name: 'urgent', label: 'Urgent', filter: [{ field: 'priority', operator: 'equals', value: 'urgent' }] };
    expect(resolveTabLabel(bundle, 'showcase_task', tab, { locale: 'zh-CN' })).toBe('紧急');
  });

  it('falls back to the literal label when the bundle has no entry', () => {
    const tab = { name: 'in_review', label: 'In Review' };
    expect(resolveTabLabel(bundle, 'showcase_task', tab, { locale: 'zh-CN' })).toBe('In Review');
  });

  it('falls back to the tab name when there is no literal label either', () => {
    expect(resolveTabLabel(bundle, 'showcase_task', { name: 'in_review' }, { locale: 'zh-CN' })).toBe('in_review');
  });

  // ── the pre-existing path is PRESERVED, not replaced ─────────────────────

  it('reads the referenced view label for a `view` tab with no `_tabs` entry', () => {
    const tab = { name: 'mine', label: 'Mine', view: 'my_open' };
    expect(resolveTabLabel(bundle, 'showcase_task', tab, { locale: 'zh-CN' })).toBe('我的待办');
  });

  it('an explicit `_tabs` entry outranks the referenced view label', () => {
    // The tab bar may deliberately name the same view differently ("Urgent"
    // over a view called "High-priority open tasks"); the specific key wins.
    const tab = { name: 'urgent', label: 'Urgent', view: 'my_open' };
    expect(resolveTabLabel(bundle, 'showcase_task', tab, { locale: 'zh-CN' })).toBe('紧急');
  });

  it('an explicit `_tabs` entry in a FALLBACK locale still outranks the view label', () => {
    // Both steps run the whole chain before the next one starts, so a `_tabs`
    // entry that only exists in `en` beats a `zh-CN` view label. Precedence is
    // by specificity of the key, not by position in the locale chain.
    const tab = { name: 'done', label: 'Done', view: 'my_open' };
    expect(resolveTabLabel(bundle, 'showcase_task', tab, { locale: 'zh-CN', fallbackChain: ['en'] }))
      .toBe('Completed');
  });

  it('degrades to the literal when there is no bundle or no object binding', () => {
    const tab = { name: 'urgent', label: 'Urgent' };
    expect(resolveTabLabel(undefined, 'showcase_task', tab, { locale: 'zh-CN' })).toBe('Urgent');
    expect(resolveTabLabel(bundle, undefined, tab, { locale: 'zh-CN' })).toBe('Urgent');
  });
});

describe('translatePage — filter-preset tab bar (#5377)', () => {
  const bundle: TranslationBundle = {
    'zh-CN': {
      objects: {
        showcase_task: { _tabs: { in_progress: { label: '进行中' }, urgent: { label: '紧急' } } },
      },
    },
  };

  const triagePage = () => ({
    name: 'showcase_task_triage',
    label: 'Task Triage',
    type: 'list',
    object: 'showcase_task',
    interfaceConfig: {
      source: 'showcase_task',
      userFilters: {
        element: 'tabs',
        showAllRecords: true,
        tabs: [
          { name: 'in_progress', label: 'In Progress' },
          { name: 'urgent', label: 'Urgent', icon: 'flame' },
          { name: 'done', label: 'Done' },
        ],
      },
    },
  });

  const tabs = (doc: any) => doc.interfaceConfig.userFilters.tabs;

  it('translates the tabs the bundle covers and leaves the rest literal', () => {
    const out = translatePage(triagePage(), bundle, { locale: 'zh-CN' });
    expect(tabs(out).map((t: any) => t.label)).toEqual(['进行中', '紧急', 'Done']);
  });

  it('keeps every other key on the tab intact', () => {
    const out = translatePage(triagePage(), bundle, { locale: 'zh-CN' });
    expect(tabs(out)[1].icon).toBe('flame');
    expect(out.interfaceConfig.userFilters.element).toBe('tabs');
    expect(out.interfaceConfig.userFilters.showAllRecords).toBe(true);
  });

  it('resolves the object from `interfaceConfig.source` before the page `object`', () => {
    // A list page retargeted at another object keys its presets under the
    // object whose records they filter — the same "component's own binding
    // first" rule `_sections` follows. With the page-level binding alone this
    // would look up `crm_lead._tabs` and find nothing.
    const retargeted = { ...triagePage(), object: 'crm_lead' };
    const out = translatePage(retargeted, bundle, { locale: 'zh-CN' });
    expect(tabs(out)[0].label).toBe('进行中');
  });

  it('falls back to the page `object` when `source` is absent', () => {
    const page = triagePage();
    delete (page.interfaceConfig as Record<string, unknown>).source;
    const out = translatePage(page, bundle, { locale: 'zh-CN' });
    expect(tabs(out)[0].label).toBe('进行中');
  });

  it('leaves an inline-locale-map label alone rather than flattening it (#5728)', () => {
    // Since the union widening a tab label may itself be multilingual. That is
    // the author's own resolution route (`pickLocalized` picks at render time);
    // overwriting it with a bundle miss would turn four languages into one.
    const page = triagePage();
    (page.interfaceConfig.userFilters.tabs as any[])[2].label = { en: 'Done', 'ja-JP': '完了' };
    const out = translatePage(page, bundle, { locale: 'ja-JP' });
    expect(tabs(out)[2].label).toEqual({ en: 'Done', 'ja-JP': '完了' });
  });

  it('leaves a page with no tab bar untouched', () => {
    const plain = { name: 'p', label: 'P', regions: [] };
    expect(translatePage(plain, bundle, { locale: 'zh-CN' })).not.toHaveProperty('interfaceConfig');
  });

  it('does not mutate the input page', () => {
    const doc = triagePage();
    const snapshot = JSON.parse(JSON.stringify(doc));
    translatePage(doc, bundle, { locale: 'zh-CN' });
    expect(doc).toEqual(snapshot);
  });
});

describe('ObjectTranslationDataSchema._tabs (#5377)', () => {
  it('accepts a `_tabs` entry — the key a strict schema used to reject', () => {
    const data = TranslationDataSchema.parse({
      objects: { showcase_task: { _tabs: { urgent: { label: '紧急' } } } },
    });
    expect(data.objects?.showcase_task?._tabs?.urgent?.label).toBe('紧急');
  });

  it('renames the spellings a translator reaches for first', () => {
    const r = TranslationDataSchema.safeParse({
      objects: { showcase_task: { _tabs: { urgent: { title: '紧急' } } } },
    });
    expect(r.success).toBe(false);
    expect(JSON.stringify(r.error?.issues)).toContain('`title` → `label`');
  });

  it('still rejects an undeclared key and names the surface', () => {
    const r = TranslationDataSchema.safeParse({
      objects: { showcase_task: { _tabs: { urgent: { label: '紧急', tooltip: 'x' } } } },
    });
    expect(r.success).toBe(false);
    expect(JSON.stringify(r.error?.issues)).toContain('this view tab translation');
  });
});

describe('TranslationDataSchema pages', () => {
  it('accepts a fully-populated pages entry', () => {
    const data = TranslationDataSchema.parse({
      pages: {
        connect_agent: {
          label: '连接智能体',
          description: '为 MCP 客户端授予访问权限',
          title: '连接智能体',
          subtitle: '每次调用都在调用者自身的权限范围内执行。',
        },
      },
    });
    expect(data.pages?.connect_agent?.title).toBe('连接智能体');
    expect(data.pages?.connect_agent?.subtitle).toBe('每次调用都在调用者自身的权限范围内执行。');
  });

  it('all pages fields are optional', () => {
    expect(() => TranslationDataSchema.parse({ pages: {} })).not.toThrow();
    expect(() => TranslationDataSchema.parse({ pages: { connect_agent: {} } })).not.toThrow();
  });
});

// ────────────────────────────────────────────────────────────────────────────
// translateObject — built-in system-field label fallback
// ────────────────────────────────────────────────────────────────────────────

import { translateObject } from './i18n-resolver';

describe('translateObject system-field label fallback', () => {
  const contract = {
    name: 'contracts',
    label: 'Contract',
    fields: {
      title: { name: 'title', type: 'text', label: '合同名称' },
      owner_id: { name: 'owner_id', type: 'lookup', label: 'Owner' },
      created_at: { name: 'created_at', type: 'datetime', label: 'Created At' },
      created_by: { name: 'created_by', type: 'lookup', label: 'Created By' },
      updated_at: { name: 'updated_at', type: 'datetime', label: 'Last Modified At' },
      updated_by: { name: 'updated_by', type: 'lookup', label: 'Last Modified By' },
    },
  };

  it('localizes injected system-field labels even without a bundle', () => {
    const out = translateObject(contract, undefined, { locale: 'zh-CN' });
    const fields = out.fields as Record<string, any>;
    expect(fields.owner_id.label).toBe('所有者');
    expect(fields.created_at.label).toBe('创建时间');
    expect(fields.created_by.label).toBe('创建人');
    expect(fields.updated_at.label).toBe('更新时间');
    expect(fields.updated_by.label).toBe('更新人');
    // Authored labels stay untouched.
    expect(fields.title.label).toBe('合同名称');
    // Input not mutated.
    expect((contract.fields as any).owner_id.label).toBe('Owner');
  });

  it('applies BCP-47 fallback for base-language and variant locales', () => {
    const zh = translateObject(contract, undefined, { locale: 'zh' });
    expect((zh.fields as any).owner_id.label).toBe('所有者');
    const ja = translateObject(contract, undefined, { locale: 'ja' });
    expect((ja.fields as any).created_by.label).toBe('作成者');
  });

  it('keeps English labels for en and unknown locales', () => {
    const en = translateObject(contract, undefined, { locale: 'en' });
    expect((en.fields as any).owner_id.label).toBe('Owner');
    const fr = translateObject(contract, undefined, { locale: 'fr-FR', fallbackChain: [] });
    expect((fr.fields as any).owner_id.label).toBe('Owner');
  });

  it('never overrides an author-customized system-field label', () => {
    const custom = {
      name: 'contracts',
      fields: { owner_id: { name: 'owner_id', type: 'lookup', label: '负责人' } },
    };
    const out = translateObject(custom, undefined, { locale: 'zh-CN' });
    expect((out.fields as any).owner_id.label).toBe('负责人');
  });

  it('prefers an explicit bundle entry over the built-in fallback', () => {
    const withBundle: TranslationBundle = {
      'zh-CN': {
        objects: {
          contracts: { fields: { owner_id: { label: '合同负责人' } } },
        },
      } as any,
    };
    const out = translateObject(contract, withBundle, { locale: 'zh-CN' });
    expect((out.fields as any).owner_id.label).toBe('合同负责人');
  });

  it('handles the array field shape', () => {
    const arrayDoc = {
      name: 'contracts',
      fields: [{ name: 'owner_id', type: 'lookup', label: 'Owner' }],
    };
    const out = translateObject(arrayDoc, undefined, { locale: 'zh-CN' });
    expect((out.fields as any)[0].label).toBe('所有者');
  });
});

describe('translateObject inline actions (objectstack#3370)', () => {
  // The `sys_approval_request` shape: decision actions declared inline on the
  // object. The plugin ships `_actions` translations for them, but the object
  // document used to go out with the English literals regardless of locale —
  // so anything that was not the Console (which re-resolves labels client-side
  // against its own bundle) rendered Approve / Reject in a zh-CN workspace.
  const approvalRequest = {
    name: 'sys_approval_request',
    label: 'Approval Request',
    actions: [
      { name: 'approval_approve', label: 'Approve', successMessage: 'Approved.' },
      { name: 'approval_reject', label: 'Reject', confirmText: 'Reject this request?' },
      { name: 'approval_remind', label: 'Send reminder' },
    ],
  };

  const bundle = {
    'zh-CN': {
      objects: {
        sys_approval_request: {
          label: '审批请求',
          _actions: {
            approval_approve: { label: '通过', successMessage: '已通过。' },
            approval_reject: { label: '拒绝', confirmText: '拒绝该请求？' },
          },
        },
      },
    },
  };

  it('translates inline action labels and copy', () => {
    const out = translateObject(approvalRequest, bundle, { locale: 'zh-CN' });
    const actions = out.actions as any[];

    expect(actions[0].label).toBe('通过');
    expect(actions[0].successMessage).toBe('已通过。');
    expect(actions[1].label).toBe('拒绝');
    expect(actions[1].confirmText).toBe('拒绝该请求？');
  });

  it('falls back to the authored literal for an untranslated action', () => {
    const out = translateObject(approvalRequest, bundle, { locale: 'zh-CN' });
    expect((out.actions as any[])[2].label).toBe('Send reminder');
  });

  it('does not stamp a synthetic objectName onto inline actions', () => {
    // The lookup needs the declaring object's name; the response should not
    // grow a field the document never carried.
    const out = translateObject(approvalRequest, bundle, { locale: 'zh-CN' });
    for (const action of out.actions as any[]) {
      expect(Object.hasOwn(action, 'objectName')).toBe(false);
    }
  });

  it('leaves the input document unmutated', () => {
    translateObject(approvalRequest, bundle, { locale: 'zh-CN' });
    expect(approvalRequest.actions[0].label).toBe('Approve');
  });

  it('honours an action that names its own object', () => {
    const doc = {
      name: 'sys_approval_request',
      actions: [{ name: 'approval_approve', label: 'Approve', objectName: 'sys_approval_request' }],
    };
    const out = translateObject(doc, bundle, { locale: 'zh-CN' });
    expect((out.actions as any[])[0].label).toBe('通过');
    expect((out.actions as any[])[0].objectName).toBe('sys_approval_request');
  });

  it('passes objects through untouched when they declare no actions', () => {
    const out = translateObject({ name: 'sys_approval_request', label: 'Approval Request' }, bundle, {
      locale: 'zh-CN',
    });
    expect(out.label).toBe('审批请求');
    expect(Object.hasOwn(out, 'actions')).toBe(false);
  });
});

// ==========================================
// resolveObjectFieldLabels — the `/i18n/labels/:object/:locale` body
// ==========================================

describe('resolveObjectFieldLabels (objectstack#3833, #3847)', () => {
  const data = TranslationDataSchema.parse({
    objects: {
      contact: {
        label: 'Contact',
        fields: {
          first_name: { label: 'First Name' },
          email: { label: 'Email', help: 'Primary address' },
          status: {
            label: 'Status',
            options: { open: 'Open', closed: 'Closed' },
          },
          phone: { help: 'Mobile preferred' },
        },
      },
    },
    messages: { save: 'Save' },
  });

  it('enumerates the labels a locale actually translates', () => {
    expect(resolveObjectFieldLabels(data, 'contact')).toEqual({
      first_name: { label: 'First Name' },
      email: { label: 'Email', help: 'Primary address' },
      status: { label: 'Status', options: { open: 'Open', closed: 'Closed' } },
    });
  });

  it('carries the help and options the bundle holds (#3847)', () => {
    // These are the translations the endpoint used to discard by emitting a
    // bare string per field. objectui needs exactly them, and had to read the
    // full-bundle route to get them.
    const out = resolveObjectFieldLabels(data, 'contact');
    expect(out.email?.help).toBe('Primary address');
    expect(out.status?.options).toEqual({ open: 'Open', closed: 'Closed' });
  });

  it('omits help/options entirely rather than emitting empty ones', () => {
    // An `options: {}` would claim the field has translated options and hand
    // back none; `help: ''` would erase a caller's source help text.
    const out = resolveObjectFieldLabels(data, 'contact');
    expect(out.first_name).toEqual({ label: 'First Name' });
    expect(Object.hasOwn(out.first_name!, 'help')).toBe(false);
    expect(Object.hasOwn(out.first_name!, 'options')).toBe(false);
  });

  it('omits fields carrying no label rather than emitting a blank one', () => {
    // Partial translation is the normal state (see ObjectTranslationDataSchema),
    // and callers merge this over their source labels — a '' would erase them.
    // `phone` has help but no label, so it yields no entry at all — which is
    // what lets `ResolvedFieldLabel.label` be a required string.
    expect(resolveObjectFieldLabels(data, 'contact')).not.toHaveProperty('phone');
  });

  it('returns {} for an untranslated object, a bundle with no objects, and no bundle', () => {
    expect(resolveObjectFieldLabels(data, 'account')).toEqual({});
    expect(resolveObjectFieldLabels({ messages: { save: 'Save' } }, 'contact')).toEqual({});
    expect(resolveObjectFieldLabels(undefined, 'contact')).toEqual({});
  });

  it('never matches the retired flat `o.<object>.fields.<field>` dialect', () => {
    // The shape the dispatcher scanned for until #3833. It is not a bundle
    // any producer writes, and reading it as one is what returned {} in
    // production while a test built on the same fiction stayed green.
    const flat = {
      'o.contact.fields.first_name': 'First Name',
      'o.contact.label': 'Contact',
    } as unknown as Parameters<typeof resolveObjectFieldLabels>[0];
    expect(resolveObjectFieldLabels(flat, 'contact')).toEqual({});
  });

  /**
   * The guard that would have caught #3847 on the day it was introduced:
   * build the response the surfaces actually send and parse it with the schema
   * that declares it. Both used to emit `Record<string, string>` against a
   * schema declaring `Record<string, { label, help?, options? }>` — a
   * mismatch no test compared, because none of them ever put the emitted
   * value and the declared contract in the same assertion.
   */
  it('produces a body that satisfies GetFieldLabelsResponseSchema (#3847)', () => {
    const response = {
      object: 'contact',
      locale: 'en-US',
      labels: resolveObjectFieldLabels(data, 'contact'),
    };
    const parsed = GetFieldLabelsResponseSchema.safeParse(response);
    expect(parsed.success).toBe(true);
    expect(parsed.data?.labels.status?.options?.open).toBe('Open');
  });

  it('an empty label map is still a valid response body', () => {
    const parsed = GetFieldLabelsResponseSchema.safeParse({
      object: 'account',
      locale: 'en-US',
      labels: resolveObjectFieldLabels(data, 'account'),
    });
    expect(parsed.success).toBe(true);
  });
});

// ==========================================
// toLocaleDescriptors — the `/i18n/locales` body
// ==========================================

describe('toLocaleDescriptors', () => {
  it('maps codes to the descriptors GetLocalesResponseSchema declares', () => {
    expect(toLocaleDescriptors(['en', 'zh-CN'], 'en')).toEqual([
      { code: 'en', label: 'en', isDefault: true },
      { code: 'zh-CN', label: 'zh-CN', isDefault: false },
    ]);
  });

  it('produces a body that satisfies GetLocalesResponseSchema', () => {
    // Same guard as the field-labels one above: emitted value vs DECLARED
    // contract, not vs a hand-written literal. `getLocales()` hands back a
    // bare `string[]`, and passing it through unmapped is what made one
    // endpoint answer in two shapes depending on the provider.
    const parsed = GetLocalesResponseSchema.safeParse({
      locales: toLocaleDescriptors(['en', 'ja-JP'], 'ja-JP'),
    });
    expect(parsed.success).toBe(true);
    expect(parsed.data?.locales.find((l) => l.code === 'ja-JP')?.isDefault).toBe(true);
  });

  it('marks nothing default when the provider has no default locale', () => {
    // `getDefaultLocale` is optional on `II18nService`. `isDefault` is
    // REQUIRED by the schema, so an absent default must yield `false`, never
    // `undefined` — which would fail the parse.
    const out = toLocaleDescriptors(['en', 'fr'], undefined);
    expect(out.every((l) => l.isDefault === false)).toBe(true);
    expect(GetLocalesResponseSchema.safeParse({ locales: out }).success).toBe(true);
  });

  it('returns [] for an absent or empty locale list', () => {
    expect(toLocaleDescriptors(undefined, 'en')).toEqual([]);
    expect(toLocaleDescriptors([], 'en')).toEqual([]);
  });

  it('sets `label` to the code, and the declaration promises exactly that (#7634)', () => {
    // The SUBSTANCE pin: producer output vs the DECLARED shape, both halves.
    //
    // `GetLocalesResponseSchema` described `label` as "Display name of the
    // locale" while this helper — the ONLY producer, shared by the
    // dispatcher's `/i18n` domain and service-i18n's route — echoed the code
    // back. Declared ≠ enforced, one field wide (ADR-0049), and it misleads in
    // exactly one direction: a client that trusts the describe renders `th`
    // where `ไทย` belongs. objectui#4039 hit that and routed around the field
    // (`apps/console/src/loadLocales.ts` reads `code` alone).
    //
    // Two assertions because the drift has two sides. Restoring `label: code`
    // to a real display name turns the first red; restoring the describe's
    // display-name promise turns the second red. Neither can move alone.
    const out = toLocaleDescriptors(['en', 'zh-CN', 'ja-JP', 'th'], 'en');
    expect(out).toHaveLength(4);
    for (const descriptor of out) {
      expect(
        descriptor.label,
        `toLocaleDescriptors must set label to the code (${descriptor.code}) — producing a real `
        + 'display name is a product decision nothing pulls for, and the describe promises the code (#7634)',
      ).toBe(descriptor.code);
    }

    const shape = (GetLocalesResponseSchema as unknown as {
      shape: { locales: { element: { shape: Record<string, { description?: string }> } } };
    }).shape;
    const description = shape.locales.element.shape.label?.description ?? '';
    expect(description.length, 'the `label` field must carry a describe at all').toBeGreaterThan(0);
    expect(
      description,
      'the `label` describe must not promise a display name while every producer sets the code (#7634)',
    ).not.toMatch(/display name/i);
    expect(
      description,
      'the `label` describe must state the code-equality convention it actually ships (#7634)',
    ).toMatch(/equals `code`/i);
  });
});

describe('normalizeSupportedLocales (#7679)', () => {
  // The narrowing rule both providers of the `i18n` slot share. Held here,
  // next to `toLocaleDescriptors`, because both of them can be the thing
  // mounting `GET /i18n/locales` and a second copy is how that route came to
  // answer in two shapes before.

  it('returns the declared codes in DECLARED order', () => {
    // Order is authored, so it is preserved: a picker rendering the app's own
    // ordering is the useful default. The loaded-key order it replaces was an
    // insertion-order accident of plugin registration.
    expect(normalizeSupportedLocales(['zh-CN', 'en', 'ja-JP'])).toEqual(['zh-CN', 'en', 'ja-JP']);
  });

  it('de-duplicates and trims, keeping first occurrence', () => {
    expect(normalizeSupportedLocales([' en ', 'zh-CN', 'en'])).toEqual(['en', 'zh-CN']);
  });

  it('DECISION 1 — absent means NO narrowing, never an empty set', () => {
    // An app that declared nothing must keep reporting every loaded locale.
    // Returning `[]` here instead of `undefined` would narrow every app that
    // predates #7679 down to zero locales — a silent, total regression on a
    // route whose only consumers are locale pickers.
    expect(normalizeSupportedLocales(undefined)).toBeUndefined();
    expect(normalizeSupportedLocales(null as unknown as string[])).toBeUndefined();
    expect(normalizeSupportedLocales('en' as unknown as string[])).toBeUndefined();
  });

  it('DECISION 1 — a declaration with no usable code is also NO narrowing', () => {
    // `[]` is read as an authoring accident, not as "serve no locales":
    // `TranslationConfigSchema` requires `supportedLocales` whenever `i18n` is
    // declared at all, so nothing in the spec asks an author to write the
    // empty array, while an empty REPORT breaks every client built on it.
    expect(normalizeSupportedLocales([])).toBeUndefined();
    expect(normalizeSupportedLocales(['', '   '])).toBeUndefined();
    expect(normalizeSupportedLocales([42, null] as unknown as string[])).toBeUndefined();
  });

  it('keeps the usable codes out of a partly-garbage declaration', () => {
    expect(normalizeSupportedLocales(['en', 42, '', 'zh-CN'] as unknown as string[]))
      .toEqual(['en', 'zh-CN']);
  });

  it('DECISION 2 — the declaration is passed through UNINTERSECTED', () => {
    // This function never sees what is loaded, and that is the point: a
    // declared locale with no bundle behind it survives to be REPORTED
    // (declared-but-unserved). An intersection is not merely less honest, it
    // is unstable — the platform plugins are still pushing bundles at
    // `kernel:ready`, so its result would depend on when it ran.
    expect(normalizeSupportedLocales(['en', 'fr-FR'])).toEqual(['en', 'fr-FR']);
  });

  it('feeds toLocaleDescriptors directly — the reported body for a narrowed app', () => {
    const declared = normalizeSupportedLocales(['en', 'zh-CN']);
    expect(toLocaleDescriptors(declared, 'en')).toEqual([
      { code: 'en', label: 'en', isDefault: true },
      { code: 'zh-CN', label: 'zh-CN', isDefault: false },
    ]);
  });
});
