import { describe, it, expect } from 'vitest';
import { z } from 'zod';
import {
  I18nLabelSchema,
  AriaPropsSchema,
  type I18nLabel,
  type AriaProps,
} from './i18n.zod';
import { measureDoors } from './door-reachability.testkit';
import { getMetadataTypeSchema } from '../kernel/metadata-type-schemas';
import { PageSchema } from './page.zod';

describe('I18nLabelSchema', () => {
  it('should accept plain string', () => {
    const result = I18nLabelSchema.parse('All Active');
    expect(result).toBe('All Active');
  });

  it('should accept empty string', () => {
    const result = I18nLabelSchema.parse('');
    expect(result).toBe('');
  });

  // ── #5728: the inline locale map is the SECOND authorized form ──────────
  //
  // Ruling B (maintainer, 2026-08-06). Three published platform pages author
  // 31 of these and objectui resolves them through `pickLocalized`; the schema
  // declared only the plain string, so the authoritative document was the
  // wrong one and the #5068 props gate reported the platform's own pages as
  // broken (42 findings: 34 label + 8 `element:text.content`).

  it('accepts an inline locale map — the shape the platform pages author', () => {
    const label = { en: 'Members', 'zh-CN': '成员', 'ja-JP': 'メンバー', 'es-ES': 'Miembros' };
    expect(I18nLabelSchema.parse(label)).toEqual(label);
  });

  it('accepts `default` as a map key — `pickLocalized` reads it as the untagged fallback', () => {
    expect(I18nLabelSchema.parse({ default: 'Members', 'zh-CN': '成员' }))
      .toEqual({ default: 'Members', 'zh-CN': '成员' });
  });

  it('accepts script- and region-qualified BCP-47 tags', () => {
    expect(I18nLabelSchema.safeParse({ en: 'Members', 'zh-Hans-CN': '成员', 'pt-BR': 'Membros' }).success).toBe(true);
  });

  it('rejects a map whose values are not strings', () => {
    expect(() => I18nLabelSchema.parse({ en: 42 })).toThrow();
  });

  // ── the widening does NOT resurrect the retired key-reference dialect ────
  //
  // The direction that would have: a bare `z.record(z.string(), z.string())`
  // accepts `{ key, defaultValue }` as "a map of strings", it parses clean, and
  // `pickLocalized`'s last resort ("first string value") then renders the i18n
  // KEY as the visible label in every locale. `INLINE_LOCALE_KEY` is what keeps
  // these two red — the #4667 / #5055 retirement and the #5728 widening are the
  // same declared = enforced principle pointing in two directions.

  it('still rejects the retired `{ key, defaultValue }` i18n object', () => {
    const r = I18nLabelSchema.safeParse({
      key: 'views.task_list.label',
      defaultValue: 'Task List',
    });
    expect(r.success).toBe(false);
    // Rejected for the RIGHT reason: `defaultValue` is not a locale tag, not
    // merely "the value is an object" (which the string branch would say).
    expect(JSON.stringify(r.error?.issues)).toContain('invalid_key');
  });

  it('still rejects the retired i18n object with params', () => {
    expect(() => I18nLabelSchema.parse({
      key: 'common.item_count',
      defaultValue: '{count} items',
      params: { count: 42 },
    })).toThrow();
  });

  it('should reject non-string, non-map values', () => {
    expect(() => I18nLabelSchema.parse(123)).toThrow();
    expect(() => I18nLabelSchema.parse(true)).toThrow();
    expect(() => I18nLabelSchema.parse(null)).toThrow();
    expect(() => I18nLabelSchema.parse(undefined)).toThrow();
  });

  // ── #5377 ②: the describe no longer promises keys nobody generates ───────
  it('does not claim i18n keys are auto-generated by the framework', () => {
    const description = (I18nLabelSchema as unknown as { description?: string }).description ?? '';
    expect(description.length).toBeGreaterThan(0);
    expect(
      description,
      'no key is generated for any label — a plain string is translatable only where a resolver + '
      + 'translation slot exist for its surface (#5377)',
    ).not.toMatch(/auto-generated/i);
  });
});

describe('AriaPropsSchema', () => {
  it('should accept empty ARIA props', () => {
    const result = AriaPropsSchema.parse({});
    expect(result.ariaLabel).toBeUndefined();
    expect(result.ariaDescribedBy).toBeUndefined();
    expect(result.role).toBeUndefined();
  });

  it('should accept ariaLabel as plain string', () => {
    const props: AriaProps = {
      ariaLabel: 'Close dialog',
    };

    const result = AriaPropsSchema.parse(props);
    expect(result.ariaLabel).toBe('Close dialog');
  });

  it('accepts ariaLabel as an inline locale map — it rides `I18nLabelSchema` (#5728)', () => {
    const result = AriaPropsSchema.parse({ ariaLabel: { en: 'Close dialog', 'zh-CN': '关闭对话框' } });
    expect(result.ariaLabel).toEqual({ en: 'Close dialog', 'zh-CN': '关闭对话框' });
  });

  it('still rejects ariaLabel as the retired key-reference i18n object', () => {
    expect(() => AriaPropsSchema.parse({
      ariaLabel: {
        key: 'common.close_dialog',
        defaultValue: 'Close dialog',
      },
    })).toThrow();
  });

  it('does not promise a generated translation key for `ariaLabel` either (#5377)', () => {
    // The reporter's second surviving point. `ariaLabel` overrides the shared
    // describe, so it never carried the "auto-generated" sentence verbatim —
    // but it inherited the assumption, and there is no bundle slot addressing
    // an `ariaLabel` anywhere in `TranslationDataSchema`. The describe now says
    // so instead of leaving the author to discover it.
    const shape = (AriaPropsSchema as unknown as { shape: Record<string, { description?: string }> }).shape;
    const description = shape.ariaLabel?.description ?? '';
    expect(description).not.toMatch(/auto-generated/i);
    expect(description).toMatch(/no translation-bundle slot/i);
  });

  it('should accept all ARIA properties', () => {
    const props: AriaProps = {
      ariaLabel: 'Navigation menu',
      ariaDescribedBy: 'nav-description',
      role: 'navigation',
    };

    const result = AriaPropsSchema.parse(props);
    expect(result.ariaLabel).toBe('Navigation menu');
    expect(result.ariaDescribedBy).toBe('nav-description');
    expect(result.role).toBe('navigation');
  });

  it('should accept common ARIA roles', () => {
    const roles = ['dialog', 'navigation', 'alert', 'button', 'form', 'main', 'complementary'];

    roles.forEach(role => {
      expect(() => AriaPropsSchema.parse({ role })).not.toThrow();
    });
  });
});

describe('I18n Integration', () => {
  it('accepts both authorized label forms', () => {
    const labels: I18nLabel[] = [
      'Plain String Label',
      'Another Plain String',
      'Setup',
      { en: 'Setup', 'zh-CN': '设置' },
    ];

    labels.forEach(label => {
      expect(() => I18nLabelSchema.parse(label)).not.toThrow();
    });
  });

  it('should reject key-reference i18n objects in label context', () => {
    expect(() => I18nLabelSchema.parse({ key: 'labels.translated', defaultValue: 'Translated Label' })).toThrow();
    expect(() => I18nLabelSchema.parse({ key: 'labels.with_params', params: { count: 10 } })).toThrow();
  });
});
// ============================================================================
// #4001 批 16 — the SPLIT verdict for this file, both halves pinned.
//
// `AriaPropsSchema` is closed on a measured door; the other five shapes are
// `no door` and stay open. Both halves can regress, in OPPOSITE directions:
// the closed half by someone reopening it, the open half by a later sweep
// "finishing the file" with a `strictObject` that gates nothing (#4583). The
// same split is recorded in `i18n.zod.ts`'s header and in the ui/ row of
// `docs/audits/2026-07-unknown-key-strictness-ledger.md`.
// ============================================================================

/** Reject `value` and hand back the serialized issues, so a pin reads what an author would. */
function reject(schema: { safeParse: (v: unknown) => { success: boolean; error?: { issues: unknown } } }, value: unknown): string {
  const r = schema.safeParse(value);
  expect(r.success, `expected ${JSON.stringify(value)} to be REJECTED`).toBe(false);
  return JSON.stringify(r.error?.issues ?? []);
}

describe('#4001 批 16 — AriaPropsSchema is closed (the door is real)', () => {
  it('the controls parse — this suite fails closed, not by rejecting everything', () => {
    expect(AriaPropsSchema.safeParse({}).success).toBe(true);
    expect(AriaPropsSchema.safeParse({ ariaLabel: 'Close dialog' }).success).toBe(true);
    expect(AriaPropsSchema.safeParse({ ariaLabel: 'x', ariaDescribedBy: 'y', role: 'dialog' }).success).toBe(true);
  });

  it('rejects an undeclared key and names the surface', () => {
    const msg = reject(AriaPropsSchema as never, { ariaLabel: 'x', notAnAriaKey: 1 });
    expect(msg).toContain('notAnAriaKey');
    expect(msg).toContain('these ARIA attributes');
  });

  // ---- the door: a strict schema nobody parses gates nothing --------------
  it('binds through the `view` metadata root, at the real carrier slot path', () => {
    const view = getMetadataTypeSchema('view');
    expect(view, 'the view root must resolve — this is the parse door').toBeTruthy();
    const doc = (aria: unknown) => ({ listViews: { my_view: { type: 'grid', columns: ['name'], aria } } });

    const control = view!.safeParse(doc({ ariaLabel: 'Accounts' }));
    expect(control.success, 'control: a declared key still parses through the root').toBe(true);

    const r = view!.safeParse(doc({ ariaLabel: 'Accounts', describedBy: 'accounts-help' }));
    expect(r.success).toBe(false);
    expect(JSON.stringify(r.error?.issues)).toContain('listViews');
  });

  it('is what was silently stripping BEFORE this batch — the legacy pair vanished whole', () => {
    // Regression narrative, asserted rather than told: this exact document used
    // to parse clean and come back `aria: {}`. The accessible name the author
    // wrote existed in the source file and nowhere else.
    const msg = reject(AriaPropsSchema as never, { label: 'Accounts', describedBy: 'accounts-help' });
    expect(msg).toContain('`label` → `ariaLabel`');
    expect(msg).toContain('`describedBy` → `ariaDescribedBy`');
  });

  // ---- curation, each entry anchored to a NAMED sibling contract ----------
  it('renames objectui\'s stored legacy spellings (its own ARIA_KEY_ALIASES)', () => {
    expect(reject(AriaPropsSchema as never, { label: 'x' })).toContain('`label` → `ariaLabel`');
    expect(reject(AriaPropsSchema as never, { describedBy: 'x' })).toContain('`describedBy` → `ariaDescribedBy`');
  });

  it('renames the shape\'s own over-generalised prefix (`ariaRole` → `role`)', () => {
    expect(reject(AriaPropsSchema as never, { ariaRole: 'dialog' })).toContain('`ariaRole` → `role`');
  });

  it('leaves the reachable typos to edit distance rather than hand-writing them', () => {
    // Measured before any alias was written: these four the fallback already
    // reaches, so an alias entry for them would be transcription, not judgement.
    expect(reject(AriaPropsSchema as never, { arialabel: 'x' })).toContain('`arialabel` → `ariaLabel`');
    expect(reject(AriaPropsSchema as never, { ariaLabell: 'x' })).toContain('`ariaLabell` → `ariaLabel`');
    expect(reject(AriaPropsSchema as never, { ariadescribedby: 'x' })).toContain('`ariadescribedby` → `ariaDescribedBy`');
    expect(reject(AriaPropsSchema as never, { roles: 'x' })).toContain('`roles` → `role`');
  });

  // ---- the two protocol gaps, prescribed WITHOUT a wrong rename ----------
  it('`live` gets a prescription, never a rename — it is a key this schema cannot accept', () => {
    // The ledger's finding 7: this campaign's own fix once signposted the way
    // into the failure mode it exists to kill. `live` is real and rendered — by
    // objectui's ListView alone — so the message says where it IS valid instead
    // of pointing at a declared key that means something else.
    const msg = reject(AriaPropsSchema as never, { live: 'polite' });
    expect(msg).toContain('objectui');
    expect(msg).toContain('#5058');
    expect(msg, 'must not suggest a rename for a key with no correct target').not.toContain('`live` →');
  });

  it('never offers `live` as a suggestion for a NEIGHBOURING typo either', () => {
    // `extraKeys: ['live']` would have made the objectui-extended surface's
    // suggestions richer and this surface's suggestions WRONG. It is deliberately
    // not used: `live` is not a key this schema accepts.
    for (const typo of ['liv', 'lives', 'Live']) {
      expect(reject(AriaPropsSchema as never, { [typo]: 'polite' })).not.toContain('→ `live`');
    }
  });

  it('`aria-labelledby` names the gap instead of renaming to a different concept', () => {
    for (const key of ['ariaLabelledBy', 'labelledBy']) {
      const msg = reject(AriaPropsSchema as never, { [key]: 'other-element' });
      expect(msg).toContain('#5058');
      expect(msg, 'labelledby references an id; ariaLabel is a literal string').not.toContain(`\`${key}\` → \`ariaLabel\``);
    }
  });

  // ---- what the strictness RIDES onto, in both directions -----------------
  it('rides `.extend()` onto objectui\'s list-view aria — which is why `live` still works there', () => {
    // objectui declares `SpecAriaPropsSchema.extend({ live })`. `.extend()`
    // inherits `.strict()` AND the error map, so that surface accepts exactly
    // `ariaLabel | ariaDescribedBy | role | live` and rejects the rest with this
    // batch's message. Asserted on a local reconstruction because objectui is a
    // separate repo — the mechanic is what matters and it is the finding-16 one.
    const objectuiAria = AriaPropsSchema.extend({ live: z.enum(['polite', 'assertive', 'off']).optional() });
    expect(objectuiAria.safeParse({ ariaLabel: 'x', live: 'polite' }).success).toBe(true);
    expect(reject(objectuiAria as never, { ariaLabel: 'x', bogus: 1 })).toContain('these ARIA attributes');
  });

  it('has no `.merge()` riders left at all — the four it had were retired at #4988', async () => {
    // REPLACED WHOLESALE at #4988, not re-spelled. This test used to name five
    // shapes in `animation` / `dnd` / `keyboard` / `touch` and assert each still
    // accepted an undeclared key, because `X.merge(AriaPropsSchema.partial())`
    // adopts the INCOMING posture and closing `AriaPropsSchema` would otherwise
    // have closed them silently. Those five modules are gone (ADR-0049
    // enforce-or-remove, `interaction-config-retirement.test.ts`), and they were
    // the ONLY `.merge(AriaPropsSchema…)` sites in the package.
    //
    // Simply dropping the five assertions would have left an empty test that
    // passes because nothing is produced rather than because the logic holds —
    // the PR #5046 trap. So the concern is re-pinned at the level it actually
    // lives on: the merge-rider count is zero, and a future rider has to make
    // the posture decision explicitly instead of inheriting `strictObject` by
    // accident.
    const fs = await import('node:fs');
    const path = await import('node:path');
    const { fileURLToPath } = await import('node:url');
    const srcRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

    const riders: string[] = [];
    let scanned = 0;
    const walk = (dir: string) => {
      for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const full = path.join(dir, entry.name);
        if (entry.isDirectory()) walk(full);
        else if (entry.name.endsWith('.zod.ts')) {
          scanned++;
          const src = fs.readFileSync(full, 'utf-8');
          if (/\.merge\(\s*AriaPropsSchema/.test(src)) riders.push(path.relative(srcRoot, full));
        }
      }
    };
    walk(srcRoot);

    // Anti-vacuity, both halves: the walk really visited the package, and the
    // matcher really fires — proven against a synthetic source, not by trusting
    // a zero.
    expect(scanned, 'the walk must have visited the schema files').toBeGreaterThan(100);
    expect(/\.merge\(\s*AriaPropsSchema\.partial\(\)\)/.test('X.merge(AriaPropsSchema.partial())')).toBe(true);

    expect(riders, 'a new `.merge(AriaPropsSchema…)` rider inherits strictObject silently — decide the posture in the file').toEqual([]);

    // The other direction stays live: `.optional()` CARRIERS of the shared
    // shape are the normal, intended pattern and must not have been swept away
    // with the riders.
    const pageShape = (PageSchema as never as { shape: Record<string, unknown> }).shape;
    expect(Object.keys(pageShape)).toContain('aria');
  });
});
