// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

import { z } from 'zod';

// ⚠️ #4001 批 16 measured this file as SPLIT across the ledger's classes, and the
// split is now resolved in BOTH directions. Read before editing.
//
// KEPT. `AriaPropsSchema` is a REAL DOOR and is closed (`strictObject`): it is
// carried as `aria:` on ~30 live shapes across six metadata-type roots —
// `ListViewSchema`, `PageSchema`, `PageComponentSchema`, `ChartConfigSchema`,
// `ActionSchema`, and 20 SDUI component defs — and a BFS from all 24 roots plus
// `defineStack` reaches it directly. (`DashboardWidgetSchema` was a seventh
// carrier when this was measured; its `aria` embed was retired later the same
// day — #5010, ADR-0049 — because no dashboard renderer applied it. The shape
// and every carrier above are unaffected.) It was silently stripping: through
// the `view` root, `aria: { label: 'Accounts', describedBy: 'x' }` parsed CLEAN
// and returned `aria: {}`, so the accessible name the author wrote simply did
// not exist. `I18nLabelSchema` is the live label primitive the whole `ui/` tree
// imports. Both stay, and `i18n.test.ts` pins their survival.
//
// REMOVED. `I18nObjectSchema` / `PluralRuleSchema` / `NumberFormatSchema` /
// `DateFormatSchema` / `LocaleConfigSchema` — per ADR-0049 enforce-or-remove
// (#5055, maintainer ruling 2026-08-06; window moved to protocol 17 on
// 2026-08-07). They had no carrier key anywhere, were unreachable in that same
// BFS, and were never parsed in objectstack / objectui / cloud outside this
// file's own tests — all three re-measured on `origin/main` immediately before
// the removal, controls passing in the same run.
//
// Two things worth keeping straight about what left:
//
//  - `NumberFormatSchema` / `DateFormatSchema` DID have a carrier key
//    (`LocaleConfig.numberFormat` / `.dateFormat`) — but the carrier was itself
//    doorless, so the subtree was `no door` rather than `no gate` and it goes as
//    one subtree. Leaving the two leaf shapes behind would strand exported
//    schemas with no consumer, which reads as a capability to whoever finds them
//    (#3950).
//  - `I18nObjectSchema` was a vocabulary SUPERSEDED BY ITS OWN NEIGHBOUR.
//    `I18nLabelSchema` below says so in prose: translation keys are generated by
//    the framework at registration time from a naming convention, the author
//    writes only the default-language string, and translations live in
//    translation files rather than inline i18n objects. The live translation
//    surface is `system/translation.zod.ts` (tightened in an earlier batch),
//    which uses none of these shapes.
//
// ⚠️ Route 3 of the retirement playbook ("nothing parses it → neither"): with no
// carrier key there is no shape for a `retiredKey()` tombstone to sit on and no
// author document for an ADR-0087 D2 conversion to rewrite. The declared record
// is the D3 `SemanticMigration` `ui-widget-i18n-family-retired` plus
// `RETIRED_DEFS_BY_MAJOR`. Localisation as authorable protocol metadata returns
// via the ENFORCE route of ADR-0049 through a new ADR — the formatter that reads
// a `LocaleConfig` first, the vocabulary second.

import { lazySchema } from '../shared/lazy-schema';
import { strictObject } from '../shared/strict-object';

/**
 * I18n Label Schema
 * 
 * A plain string label for display purposes.
 * i18n translation keys are auto-generated by the framework at registration time
 * based on a standardized naming convention (e.g., `apps.<packageId>.<name>.label`).
 * Developers only need to provide the default-language string; translations are
 * managed through translation files, not inline i18n objects.
 * 
 * @example
 * ```typescript
 * const label: I18nLabel = "All Active";
 * ```
 */
export const I18nLabelSchema = lazySchema(() => z.string().describe('Display label (plain string; i18n keys are auto-generated by the framework)'));

export type I18nLabel = z.infer<typeof I18nLabelSchema>;

// The one closed shape in this file (#4001 批 16). Everything below `AriaProps`
// stays open on the `no door` verdict recorded at the top.
//
// Curation is anchored to NAMED SIBLING CONTRACTS, never to edit distance —
// each entry below was measured against a real producer, and the distance
// fallback was measured first so nothing is hand-written that it already reaches
// (it reaches `arialabel`, `ariaLabell`, `ariadescribedby`, `aria-label`,
// `roles`; it does NOT reach any of the four aliases here).
const ARIA_HISTORY =
  'Until #4001 closed this shape an unknown key was dropped silently — the component still '
  + 'rendered, with no accessible name and nothing to say the one you wrote had been discarded.';

/**
 * ARIA Accessibility Properties Schema
 *
 * Common ARIA attributes for UI components to support screen readers
 * and assistive technologies.
 *
 * Aligned with WAI-ARIA 1.2 specification.
 *
 * @see https://www.w3.org/TR/wai-aria-1.2/
 *
 * @example
 * ```typescript
 * const aria: AriaProps = {
 *   ariaLabel: 'Close dialog',
 *   ariaDescribedBy: 'dialog-description',
 *   role: 'dialog',
 * };
 * ```
 */
export const AriaPropsSchema = lazySchema(() => strictObject({
  surface: 'these ARIA attributes',
  history: ARIA_HISTORY,
  aliases: {
    // objectui's `ARIA_KEY_ALIASES` (`packages/core/src/utils/normalize-list-view.ts`)
    // is the measured source for these two: they are the spellings stored view
    // metadata really carries, folded onto the canonical keys at the ListView
    // boundary (objectui#2890). A view authored the legacy way reached this
    // schema and lost BOTH keys — `aria: {}` — so the accessible name existed in
    // the source file and nowhere else.
    label: 'ariaLabel',
    describedBy: 'ariaDescribedBy',
    // Two of this shape's three keys carry the `aria` prefix and `role` does not.
    // An author who has just written `ariaLabel` and `ariaDescribedBy` generalises
    // to `ariaRole`; that is the shape's own inconsistency, not a typo, and the
    // distance fallback provably cannot bridge it (measured).
    ariaRole: 'role',
  },
  guidance: {
    // NOT an alias — `live` is not a key this schema accepts, and suggesting one
    // the schema cannot accept is the ledger's finding 7 (this campaign's own fix
    // signposting the way into the failure it exists to kill).
    live: '`live` is objectui\'s LIST-VIEW-ONLY extension, declared there as '
      + '`AriaPropsSchema.extend({ live })` and read by `ListView` alone — this shared shape is '
      + 'carried by ~30 renderers and only one of them applies `aria-live`, so declaring it here '
      + 'would advertise a capability the other 29 do not deliver. On an objectui list view the key '
      + 'is valid as-is; anywhere else, drop it. Promoting it into the protocol is #5058.',
    // `aria-labelledby` REFERENCES another element's id; `ariaLabel` is a literal
    // string. Renaming between them would be a wrong prescription, so this names
    // the gap instead of pretending there is a target.
    ariaLabelledBy: '`aria-labelledby` has no counterpart in this protocol — it references another '
      + 'element\'s id, which is not the same thing as `ariaLabel` (a literal accessible name), so '
      + 'there is nothing to rename it to. Use `ariaLabel` only if a literal string is what you meant. '
      + 'Declaring the referencing form is #5058.',
    labelledBy: '`aria-labelledby` has no counterpart in this protocol — see `ariaLabelledBy`. '
      + 'Use `ariaLabel` only if a literal accessible name is what you meant; #5058 tracks the gap.',
  },
}, {
  /** Accessible label for screen readers */
  ariaLabel: I18nLabelSchema.optional().describe('Accessible label for screen readers (WAI-ARIA aria-label)'),

  /** ID of element that describes this component */
  ariaDescribedBy: z.string().optional().describe('ID of element providing additional description (WAI-ARIA aria-describedby)'),

  /** WAI-ARIA role override */
  role: z.string().optional().describe('WAI-ARIA role attribute (e.g., "dialog", "navigation", "alert")'),
}).describe('ARIA accessibility attributes'));

export type AriaProps = z.infer<typeof AriaPropsSchema>;
