// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

import { z } from 'zod';

// ⚠️ #4001 批 16 — this file SPLITS across the ledger's classes. Read before editing.
//
// `AriaPropsSchema` is a REAL DOOR and is closed (`strictObject`). Every other
// shape here is `no door` and must NOT be tightened — see the per-schema notes.
//
// The split was measured on 2026-08-04, three independent ways with positive AND
// negative controls in the same run (`i18n.test.ts` pins both halves):
//
//  - `AriaPropsSchema` is carried as `aria:` on ~30 live shapes across six
//    metadata-type roots — `ListViewSchema`, `PageSchema`, `PageComponentSchema`,
//    `ChartConfigSchema`, `ActionSchema`, and 20 SDUI component defs — and a BFS
//    from all 24 roots plus `defineStack` reaches it directly. (`DashboardWidgetSchema`
//    was a seventh carrier when this was measured; its `aria` embed was retired
//    later the same day — #5010, ADR-0049 — because no dashboard renderer applied
//    it. The shape and every carrier above are unaffected.)
//    It was silently stripping: through the `view` root,
//    `aria: { label: 'Accounts', describedBy: 'x' }` parsed CLEAN and returned
//    `aria: {}`, so the accessible name the author wrote simply did not exist.
//  - `I18nObjectSchema` / `PluralRuleSchema` / `NumberFormatSchema` /
//    `DateFormatSchema` / `LocaleConfigSchema` have no carrier key anywhere, are
//    unreachable in that same BFS, and are never parsed in `objectstack`,
//    `objectui` or `cloud` outside this file's own tests. `.strict()` is a
//    property of a PARSE; with no parse it enforces nothing and only makes a dead
//    slot look load-bearing (#4583). ADR-0049 enforce-or-remove is #5055.
//
// Note `NumberFormatSchema` / `DateFormatSchema` DO have a carrier
// (`LocaleConfig.numberFormat` / `.dateFormat`) — but the carrier is itself
// doorless, so the whole subtree is `no door`, not `no gate`.
//
// The `z.record` slots stay open ON PURPOSE and are not sites this ratchet can
// close: `I18nObject.params` is an interpolation bag whose key space is whatever
// the message template names. Openness there is the contract.

/**
 * I18n Object Schema
 * Structured internationalization label with translation key and parameters.
 * 
 * @example
 * ```typescript
 * const label: I18nObject = {
 *   key: 'views.task_list.label',
 *   defaultValue: 'Task List',
 *   params: { count: 5 },
 * };
 * ```
 */
import { lazySchema } from '../shared/lazy-schema';
import { strictObject } from '../shared/strict-object';
export const I18nObjectSchema = lazySchema(() => z.object({
  /** Translation key (e.g., "views.task_list.label", "apps.crm.description") */
  key: z.string().describe('Translation key (e.g., "views.task_list.label")'),

  /** Default value when translation is not available */
  defaultValue: z.string().optional().describe('Fallback value when translation key is not found'),

  /** Interpolation parameters for dynamic translations */
  params: z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])).optional().describe('Interpolation parameters (e.g., { count: 5 })'),
}));

export type I18nObject = z.infer<typeof I18nObjectSchema>;

/**
 * I18n Label Schema
 * 
 * A plain string label for display purposes.
 * i18n translation keys are auto-generated by the framework at registration time
 * based on a standardized naming convention (e.g., `apps.<packageId>.<name>.label`).
 * Developers only need to provide the default-language string; translations are
 * managed through translation files, not inline i18n objects.
 * 
 * @example
 * ```typescript
 * const label: I18nLabel = "All Active";
 * ```
 */
export const I18nLabelSchema = lazySchema(() => z.string().describe('Display label (plain string; i18n keys are auto-generated by the framework)'));

export type I18nLabel = z.infer<typeof I18nLabelSchema>;

// The one closed shape in this file (#4001 批 16). Everything below `AriaProps`
// stays open on the `no door` verdict recorded at the top.
//
// Curation is anchored to NAMED SIBLING CONTRACTS, never to edit distance —
// each entry below was measured against a real producer, and the distance
// fallback was measured first so nothing is hand-written that it already reaches
// (it reaches `arialabel`, `ariaLabell`, `ariadescribedby`, `aria-label`,
// `roles`; it does NOT reach any of the four aliases here).
const ARIA_HISTORY =
  'Until #4001 closed this shape an unknown key was dropped silently — the component still '
  + 'rendered, with no accessible name and nothing to say the one you wrote had been discarded.';

/**
 * ARIA Accessibility Properties Schema
 *
 * Common ARIA attributes for UI components to support screen readers
 * and assistive technologies.
 *
 * Aligned with WAI-ARIA 1.2 specification.
 *
 * @see https://www.w3.org/TR/wai-aria-1.2/
 *
 * @example
 * ```typescript
 * const aria: AriaProps = {
 *   ariaLabel: 'Close dialog',
 *   ariaDescribedBy: 'dialog-description',
 *   role: 'dialog',
 * };
 * ```
 */
export const AriaPropsSchema = lazySchema(() => strictObject({
  surface: 'these ARIA attributes',
  history: ARIA_HISTORY,
  aliases: {
    // objectui's `ARIA_KEY_ALIASES` (`packages/core/src/utils/normalize-list-view.ts`)
    // is the measured source for these two: they are the spellings stored view
    // metadata really carries, folded onto the canonical keys at the ListView
    // boundary (objectui#2890). A view authored the legacy way reached this
    // schema and lost BOTH keys — `aria: {}` — so the accessible name existed in
    // the source file and nowhere else.
    label: 'ariaLabel',
    describedBy: 'ariaDescribedBy',
    // Two of this shape's three keys carry the `aria` prefix and `role` does not.
    // An author who has just written `ariaLabel` and `ariaDescribedBy` generalises
    // to `ariaRole`; that is the shape's own inconsistency, not a typo, and the
    // distance fallback provably cannot bridge it (measured).
    ariaRole: 'role',
  },
  guidance: {
    // NOT an alias — `live` is not a key this schema accepts, and suggesting one
    // the schema cannot accept is the ledger's finding 7 (this campaign's own fix
    // signposting the way into the failure it exists to kill).
    live: '`live` is objectui\'s LIST-VIEW-ONLY extension, declared there as '
      + '`AriaPropsSchema.extend({ live })` and read by `ListView` alone — this shared shape is '
      + 'carried by ~30 renderers and only one of them applies `aria-live`, so declaring it here '
      + 'would advertise a capability the other 29 do not deliver. On an objectui list view the key '
      + 'is valid as-is; anywhere else, drop it. Promoting it into the protocol is #5058.',
    // `aria-labelledby` REFERENCES another element's id; `ariaLabel` is a literal
    // string. Renaming between them would be a wrong prescription, so this names
    // the gap instead of pretending there is a target.
    ariaLabelledBy: '`aria-labelledby` has no counterpart in this protocol — it references another '
      + 'element\'s id, which is not the same thing as `ariaLabel` (a literal accessible name), so '
      + 'there is nothing to rename it to. Use `ariaLabel` only if a literal string is what you meant. '
      + 'Declaring the referencing form is #5058.',
    labelledBy: '`aria-labelledby` has no counterpart in this protocol — see `ariaLabelledBy`. '
      + 'Use `ariaLabel` only if a literal accessible name is what you meant; #5058 tracks the gap.',
  },
}, {
  /** Accessible label for screen readers */
  ariaLabel: I18nLabelSchema.optional().describe('Accessible label for screen readers (WAI-ARIA aria-label)'),

  /** ID of element that describes this component */
  ariaDescribedBy: z.string().optional().describe('ID of element providing additional description (WAI-ARIA aria-describedby)'),

  /** WAI-ARIA role override */
  role: z.string().optional().describe('WAI-ARIA role attribute (e.g., "dialog", "navigation", "alert")'),
}).describe('ARIA accessibility attributes'));

export type AriaProps = z.infer<typeof AriaPropsSchema>;

/**
 * Plural Rule Schema
 *
 * Defines plural forms for a translation key, following ICU MessageFormat / i18next conventions.
 * Supports zero, one, two, few, many, other forms per CLDR plural rules.
 *
 * @see https://unicode.org/reports/tr35/tr35-numbers.html#Language_Plural_Rules
 *
 * @example
 * ```typescript
 * const plural: PluralRule = {
 *   key: 'items.count',
 *   zero: 'No items',
 *   one: '{count} item',
 *   other: '{count} items',
 * };
 * ```
 */
export const PluralRuleSchema = lazySchema(() => z.object({
  /** Translation key for the plural form */
  key: z.string().describe('Translation key'),
  /** Form for zero quantity */
  zero: z.string().optional().describe('Zero form (e.g., "No items")'),
  /** Form for singular (1) */
  one: z.string().optional().describe('Singular form (e.g., "{count} item")'),
  /** Form for dual (2) — used in Arabic, Welsh, etc. */
  two: z.string().optional().describe('Dual form (e.g., "{count} items" for exactly 2)'),
  /** Form for few (2-4 in Slavic languages) */
  few: z.string().optional().describe('Few form (e.g., for 2-4 in some languages)'),
  /** Form for many (5+ in Slavic languages) */
  many: z.string().optional().describe('Many form (e.g., for 5+ in some languages)'),
  /** Default/fallback form */
  other: z.string().describe('Default plural form (e.g., "{count} items")'),
}).describe('ICU plural rules for a translation key'));

export type PluralRule = z.infer<typeof PluralRuleSchema>;

/**
 * Number Format Schema
 *
 * Defines number formatting rules for localization.
 *
 * @example
 * ```typescript
 * const format: NumberFormat = {
 *   style: 'currency',
 *   currency: 'USD',
 *   minimumFractionDigits: 2,
 * };
 * ```
 */
export const NumberFormatSchema = lazySchema(() => z.object({
  style: z.enum(['decimal', 'currency', 'percent', 'unit']).default('decimal')
    .describe('Number formatting style'),
  currency: z.string().optional().describe('ISO 4217 currency code (e.g., "USD", "EUR")'),
  unit: z.string().optional().describe('Unit for unit formatting (e.g., "kilometer", "liter")'),
  minimumFractionDigits: z.number().optional().describe('Minimum number of fraction digits'),
  maximumFractionDigits: z.number().optional().describe('Maximum number of fraction digits'),
  useGrouping: z.boolean().optional().describe('Whether to use grouping separators (e.g., 1,000)'),
}).describe('Number formatting rules'));

export type NumberFormat = z.infer<typeof NumberFormatSchema>;
/** Post-parse shape of {@link NumberFormat} — defaults applied, transforms run (ADR-0122). */
export type NumberFormatParsed = z.infer<typeof NumberFormatSchema>;

/**
 * Date Format Schema
 *
 * Defines date/time formatting rules for localization.
 *
 * @example
 * ```typescript
 * const format: DateFormat = {
 *   dateStyle: 'medium',
 *   timeStyle: 'short',
 *   timeZone: 'America/New_York',
 * };
 * ```
 */
export const DateFormatSchema = lazySchema(() => z.object({
  dateStyle: z.enum(['full', 'long', 'medium', 'short']).optional()
    .describe('Date display style'),
  timeStyle: z.enum(['full', 'long', 'medium', 'short']).optional()
    .describe('Time display style'),
  timeZone: z.string().optional().describe('IANA time zone (e.g., "America/New_York")'),
  hour12: z.boolean().optional().describe('Use 12-hour format'),
}).describe('Date/time formatting rules'));

export type DateFormat = z.infer<typeof DateFormatSchema>;

/**
 * Locale Configuration Schema
 *
 * Defines a complete locale configuration including language code,
 * fallback chain, and formatting preferences.
 *
 * @example
 * ```typescript
 * const locale: LocaleConfig = {
 *   code: 'zh-CN',
 *   fallbackChain: ['zh-TW', 'en'],
 *   direction: 'ltr',
 *   numberFormat: { style: 'decimal', useGrouping: true },
 *   dateFormat: { dateStyle: 'medium', timeStyle: 'short' },
 * };
 * ```
 */
export const LocaleConfigSchema = lazySchema(() => z.object({
  /** BCP 47 language code (e.g., "en-US", "zh-CN", "ar-SA") */
  code: z.string().describe('BCP 47 language code (e.g., "en-US", "zh-CN")'),

  /** Ordered fallback chain for missing translations */
  fallbackChain: z.array(z.string()).optional()
    .describe('Fallback language codes in priority order (e.g., ["zh-TW", "en"])'),

  /** Text direction */
  direction: z.enum(['ltr', 'rtl']).default('ltr')
    .describe('Text direction: left-to-right or right-to-left'),

  /** Default number formatting */
  numberFormat: NumberFormatSchema.optional().describe('Default number formatting rules'),

  /** Default date formatting */
  dateFormat: DateFormatSchema.optional().describe('Default date/time formatting rules'),
}).describe('Locale configuration'));

export type LocaleConfig = z.infer<typeof LocaleConfigSchema>;
/** Post-parse shape of {@link LocaleConfig} — defaults applied, transforms run (ADR-0122). */
export type LocaleConfigParsed = z.infer<typeof LocaleConfigSchema>;
