// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'en'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const enObjects: NonNullable<TranslationData['objects']> = {
  sys_webhook: {
    label: "Webhook",
    pluralLabel: "Webhooks",
    description: "Outbound HTTP webhook subscription. Authored via defineWebhook() in code or the Studio editor; executed by the HTTP connector plugin.",
    fields: {
      id: {
        label: "Webhook ID"
      },
      name: {
        label: "Name",
        help: "Unique snake_case name — referenced in logs and audit"
      },
      label: {
        label: "Display Label"
      },
      object_name: {
        label: "Object",
        help: "Short object name whose record events (create/update/delete) fire this webhook"
      },
      triggers: {
        label: "Triggers",
        help: "Comma-separated event list: create,update,delete"
      },
      url: {
        label: "Target URL",
        help: "External endpoint that receives the POST"
      },
      method: {
        label: "HTTP Method",
        help: "GET / POST / PUT / PATCH / DELETE"
      },
      description: {
        label: "Description"
      },
      active: {
        label: "Active",
        help: "Inactive webhooks are skipped by the dispatcher"
      },
      definition_json: {
        label: "Definition",
        help: "Serialised Webhook JSON (see @objectstack/spec/automation/webhook) — full headers/auth/retry/payload config"
      },
      created_at: {
        label: "Created At"
      },
      updated_at: {
        label: "Updated At"
      }
    },
    _views: {
      active: {
        label: "Active"
      },
      inactive: {
        label: "Inactive"
      },
      by_object: {
        label: "By Object"
      },
      all_webhooks: {
        label: "All"
      }
    }
  }
};
