// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'en'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const enObjects: NonNullable<TranslationData['objects']> = {
  sys_webhook: {
    label: "Webhook",
    pluralLabel: "Webhooks",
    description: "Outbound HTTP webhook subscription. Authored via defineWebhook() in code or the Studio editor; executed by the HTTP connector plugin.",
    fields: {
      id: {
        label: "Webhook ID"
      },
      name: {
        label: "Name",
        help: "Unique snake_case name — referenced in logs and audit"
      },
      label: {
        label: "Display Label"
      },
      object_name: {
        label: "Object",
        help: "Short object name whose record events (create/update/delete) fire this webhook"
      },
      triggers: {
        label: "Triggers",
        help: "Record events that fire this webhook. bulk_update / bulk_delete fire on predicate writes and deliver a count, not a record.",
        options: {
          create: "create",
          update: "update",
          delete: "delete",
          bulk_update: "bulk_update",
          bulk_delete: "bulk_delete"
        }
      },
      url: {
        label: "Target URL",
        help: "External endpoint that receives the POST"
      },
      method: {
        label: "HTTP Method",
        help: "GET / POST / PUT / PATCH / DELETE",
        options: {
          get: "GET",
          post: "POST",
          put: "PUT",
          patch: "PATCH",
          delete: "DELETE"
        }
      },
      description: {
        label: "Description"
      },
      active: {
        label: "Active",
        help: "Inactive webhooks are skipped by the dispatcher"
      },
      definition_json: {
        label: "Definition",
        help: "Serialised Webhook JSON (see @objectstack/spec/automation/webhook) — full headers/auth/retry/payload config"
      },
      signing_secret: {
        label: "Signing Secret",
        help: "HMAC-SHA256 key used to sign deliveries (X-Objectstack-Signature). Encrypted at rest into sys_secret; reads return a mask, never the key. Leave the mask untouched to keep the current value."
      },
      managed_by: {
        label: "Managed By",
        help: "Record provenance: platform = framework built-in / package = app/package-declared (boot-seeded from defineStack webhooks) / admin = created in Setup.",
        options: {
          platform: "platform",
          package: "package",
          admin: "admin"
        }
      },
      customized: {
        label: "Customized",
        help: "Set when an admin edits a package-declared webhook; boot seeding will no longer overwrite the row (a deactivated noisy webhook survives redeploys). Meaningless on admin rows."
      },
      created_at: {
        label: "Created At"
      },
      updated_at: {
        label: "Updated At"
      }
    },
    _views: {
      active: {
        label: "Active"
      },
      inactive: {
        label: "Inactive"
      },
      by_object: {
        label: "By Object"
      },
      all_webhooks: {
        label: "All"
      }
    }
  }
};
