// Copyright (c) 2026 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'es-ES'. Do not hand-edit.
 *
 * Each entry is the digest of the SOURCE REVISION that this locale's leaf at
 * that path is still a byte copy of — provenance for the generated half of the
 * bundles (#11671, maintainer ruling #12069 Option A, extending #8765 Option B).
 *
 * An entry exists only while the leaf IS such a copy. Re-translate the leaf in
 * `<locale>.objects.generated.ts` and the next extract drops its entry by
 * itself — the table makes no claim about text a translator wrote. A path with
 * no entry is LEGACY-TRUSTED and never reported stale.
 *
 * ⚠️ Do not "fix" a staleness report by editing this file. Refreshing a digest
 * records that the current text was copied from the current source, which is
 * the false claim the mechanism exists to detect. Fix the TRANSLATION.
 */

export const esESGeneratedSourceHashes: Readonly<Record<string, string>> = {
  "objects.sys_webhook.fields.method.options.delete": "f59e059ed51f9bfc",
  "objects.sys_webhook.fields.method.options.get": "470848255971c548",
  "objects.sys_webhook.fields.method.options.patch": "7de3603749decb30",
  "objects.sys_webhook.fields.method.options.post": "004b24eab36d26a4",
  "objects.sys_webhook.fields.method.options.put": "04d929ecae7aa435",
  "objects.sys_webhook.label": "b608f1636b7e8184",
  "objects.sys_webhook.pluralLabel": "8fdd81bc76459a6a",
};
