// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'ja-JP'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const jaJPObjects: NonNullable<TranslationData['objects']> = {
  sys_webhook: {
    label: "Webhook",
    pluralLabel: "Webhook",
    description: "送信 HTTP Webhook サブスクリプション。defineWebhook() またはスタジオエディタで作成し、HTTP コネクタプラグインが実行します。",
    fields: {
      id: {
        label: "Webhook ID"
      },
      name: {
        label: "名前",
        help: "一意の snake_case 名 — ログおよび監査で参照"
      },
      label: {
        label: "表示名"
      },
      object_name: {
        label: "オブジェクト",
        help: "このウェブフックを発火するレコードイベント（create/update/delete）のオブジェクト短縮名"
      },
      triggers: {
        label: "トリガー",
        help: "カンマ区切りのイベントリスト: create,update,delete",
        options: {
          create: "作成",
          update: "更新",
          delete: "削除"
        }
      },
      url: {
        label: "ターゲット URL",
        help: "POST を受信する外部エンドポイント"
      },
      method: {
        label: "HTTP メソッド",
        help: "GET / POST / PUT / PATCH / DELETE",
        options: {
          get: "GET",
          post: "POST",
          put: "PUT",
          patch: "PATCH",
          delete: "DELETE"
        }
      },
      description: {
        label: "説明"
      },
      active: {
        label: "有効",
        help: "無効にするとディスパッチャにスキップされます"
      },
      definition_json: {
        label: "定義",
        help: "シリアライズされた Webhook JSON（@objectstack/spec/automation/webhook 参照）— ヘッダー/認証/リトライ/ペイロード設定を含む"
      },
      managed_by: {
        label: "管理元",
        help: "レコードの出所: platform = フレームワーク組み込み / package = アプリ・パッケージ宣言（defineStack の webhooks から起動時シード）/ admin = Setup で作成。",
        options: {
          platform: "プラットフォーム",
          package: "パッケージ",
          admin: "管理者"
        }
      },
      customized: {
        label: "カスタマイズ済み",
        help: "管理者がパッケージ宣言の webhook を編集すると設定されます。以後、起動時シードはこの行を上書きしません（無効化したノイジーな webhook は再デプロイ後も保持）。admin 行では意味を持ちません。"
      },
      created_at: {
        label: "作成日時"
      },
      updated_at: {
        label: "更新日時"
      }
    },
    _views: {
      active: {
        label: "有効"
      },
      inactive: {
        label: "無効"
      },
      by_object: {
        label: "オブジェクト別"
      },
      all_webhooks: {
        label: "すべて"
      }
    }
  }
};
