// Copyright (c) 2026 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'es-ES'. Do not hand-edit.
 *
 * Each entry is the digest of the SOURCE REVISION that this locale's leaf at
 * that path is still a byte copy of — provenance for the generated half of the
 * bundles (#11671, maintainer ruling #12069 Option A, extending #8765 Option B).
 *
 * An entry exists only while the leaf IS such a copy. Re-translate the leaf in
 * `<locale>.objects.generated.ts` and the next extract drops its entry by
 * itself — the table makes no claim about text a translator wrote. A path with
 * no entry is LEGACY-TRUSTED and never reported stale.
 *
 * ⚠️ Do not "fix" a staleness report by editing this file. Refreshing a digest
 * records that the current text was copied from the current source, which is
 * the false claim the mechanism exists to detect. Fix the TRANSLATION.
 */

export const esESGeneratedSourceHashes: Readonly<Record<string, string>> = {
  "objects.sys_approval_action.fields.actor_id.label": "b155813f8a7f06e3",
  "objects.sys_approval_delegation._views.active.emptyState.message": "1095d61c017b6db2",
  "objects.sys_approval_delegation._views.active.emptyState.title": "799d28e51d88963e",
  "objects.sys_approval_delegation._views.active.label": "eee107cf4e466779",
  "objects.sys_approval_delegation.description": "432b0435aa15f6b9",
  "objects.sys_approval_delegation.fields.created_at.label": "1f02d416befb595b",
  "objects.sys_approval_delegation.fields.delegate_id.help": "9cfc641f7b0b04f9",
  "objects.sys_approval_delegation.fields.delegate_id.label": "afd6d8733dc5bc14",
  "objects.sys_approval_delegation.fields.delegator_id.help": "c4686c5c9f24e0be",
  "objects.sys_approval_delegation.fields.delegator_id.label": "f76b1f95f2fdabff",
  "objects.sys_approval_delegation.fields.id.label": "3383564051b4b76d",
  "objects.sys_approval_delegation.fields.organization_id.help": "f02982e88229d9ca",
  "objects.sys_approval_delegation.fields.organization_id.label": "3e55836156e1c1de",
  "objects.sys_approval_delegation.fields.reason.help": "712516f1461dff2b",
  "objects.sys_approval_delegation.fields.reason.label": "ac399f03d7f2e64d",
  "objects.sys_approval_delegation.fields.updated_at.label": "aba63dc2a9c79b8d",
  "objects.sys_approval_delegation.fields.valid_from.help": "01386010c454bfbd",
  "objects.sys_approval_delegation.fields.valid_from.label": "02eaf201e57c9eda",
  "objects.sys_approval_delegation.fields.valid_until.help": "a48ea34e65933e9d",
  "objects.sys_approval_delegation.fields.valid_until.label": "a68db5bd4fc72a13",
  "objects.sys_approval_delegation.label": "4389c4fe5f5c9746",
  "objects.sys_approval_delegation.pluralLabel": "f07fec3ffd74e6db",
  "objects.sys_approval_request.fields.flow_node_id.help": "154aa23b4eee4cae",
  "objects.sys_approval_request.fields.flow_node_id.label": "052ad568aa41227c",
  "objects.sys_approval_request.fields.flow_run_id.help": "35c92818f5e11090",
  "objects.sys_approval_request.fields.flow_run_id.label": "d0124e323da966f9",
  "objects.sys_approval_request.fields.node_config_json.help": "7ee00ef9b3ca7e80",
  "objects.sys_approval_request.fields.node_config_json.label": "e64eb4bf7d7ea033",
};
