// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'es-ES'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const esESObjects: NonNullable<TranslationData['objects']> = {
  sys_approval_request: {
    label: "Solicitud de aprobación",
    pluralLabel: "Solicitudes de aprobación",
    description: "Instancia activa de aprobación registrada por envío",
    fields: {
      id: {
        label: "ID de solicitud"
      },
      organization_id: {
        label: "Organización",
        help: "Tenant que posee esta solicitud de aprobación (propagado desde el contexto del solicitante)."
      },
      process_name: {
        label: "Origen",
        help: "Origen de la solicitud — `flow:<flowName|nodeId>` para aprobaciones por nodo"
      },
      object_name: {
        label: "Objeto"
      },
      record_id: {
        label: "ID de registro"
      },
      submitter_id: {
        label: "Solicitante"
      },
      submitter_comment: {
        label: "Comentario del solicitante"
      },
      status: {
        label: "Estado",
        help: "Estado del ciclo de vida de la solicitud.",
        options: {
          pending: "Pendiente",
          approved: "Aprobada",
          rejected: "Rechazada",
          recalled: "Retirada",
          returned: "Devuelta para revisión"
        }
      },
      current_step: {
        label: "Paso actual",
        help: "Nombre técnico del paso pendiente de aprobación."
      },
      current_step_index: {
        label: "Índice del paso actual"
      },
      pending_approvers: {
        label: "Aprobadores pendientes",
        help: "ID de usuario separados por comas que pueden actuar en el paso actual."
      },
      payload_json: {
        label: "Instantánea",
        help: "Instantánea del registro en el momento del envío."
      },
      flow_run_id: {
        label: "Flow Run",
        help: "Suspended automation run id this request gates (ADR-0019). The decision resumes it."
      },
      flow_node_id: {
        label: "Flow Node",
        help: "Approval node id within the flow that opened this request (ADR-0019)."
      },
      node_config_json: {
        label: "Node Config",
        help: "Snapshot of the Approval node config (approvers/behavior) for node-driven requests (ADR-0019)."
      },
      completed_at: {
        label: "Completado el"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    },
    _views: {
      my_pending: {
        label: "Mis pendientes",
        emptyState: {
          title: "Sin aprobaciones pendientes",
          message: "Estás al día: nada espera tu aprobación."
        }
      },
      submitted_by_me: {
        label: "Enviadas por mí"
      },
      completed: {
        label: "Completadas"
      },
      all_requests: {
        label: "Todas"
      }
    },
    _actions: {
      approval_approve: {
        label: "Aprobar",
        successMessage: "Aprobada.",
        params: {
          comment: {
            label: "Comentario"
          },
          attachments: {
            label: "Adjuntos"
          }
        }
      },
      approval_reject: {
        label: "Rechazar",
        confirmText: "¿Rechazar esta solicitud? Un rechazo es definitivo para todos los aprobadores.",
        successMessage: "Rechazada.",
        params: {
          comment: {
            label: "Comentario"
          },
          attachments: {
            label: "Adjuntos"
          }
        }
      },
      approval_reassign: {
        label: "Reasignar",
        successMessage: "Reasignada.",
        params: {
          to: {
            label: "Nuevo aprobador",
            helpText: "Usuario al que se entrega este paso"
          },
          comment: {
            label: "Comentario"
          }
        }
      },
      approval_send_back: {
        label: "Devolver",
        successMessage: "Devuelta para revisión.",
        params: {
          comment: {
            label: "Motivo"
          }
        }
      },
      approval_request_info: {
        label: "Pedir información",
        successMessage: "Información solicitada.",
        params: {
          comment: {
            label: "¿Qué necesitas?"
          }
        }
      },
      approval_remind: {
        label: "Enviar recordatorio",
        successMessage: "Recordatorio enviado.",
        params: {
          comment: {
            label: "Nota"
          }
        }
      },
      approval_recall: {
        label: "Retirar",
        confirmText: "¿Retirar esta solicitud? Los aprobadores ya no podrán actuar sobre ella y el registro se desbloqueará.",
        successMessage: "Retirada.",
        params: {
          comment: {
            label: "Comentario"
          }
        }
      },
      approval_resubmit: {
        label: "Reenviar",
        successMessage: "Reenviada.",
        params: {
          comment: {
            label: "¿Qué ha cambiado?"
          }
        }
      }
    }
  },
  sys_approval_action: {
    label: "Acción de aprobación",
    pluralLabel: "Acciones de aprobación",
    description: "Registro de auditoría append-only para acciones de aprobación",
    fields: {
      id: {
        label: "ID de acción"
      },
      organization_id: {
        label: "Organización",
        help: "Tenant que posee esta acción (refleja la solicitud principal)."
      },
      request_id: {
        label: "Solicitud"
      },
      step_name: {
        label: "Paso",
        help: "Nombre técnico del paso en el momento de la acción."
      },
      step_index: {
        label: "Índice del paso"
      },
      action: {
        label: "Acción",
        options: {
          submit: "Enviar",
          approve: "Aprobar",
          reject: "Rechazar",
          recall: "Retirar",
          escalate: "Escalar",
          reassign: "Reasignación",
          remind: "Recordatorio",
          request_info: "Petición de información",
          comment: "Comentario",
          revise: "Devolución",
          resubmit: "Reenvío",
          ooo_substitute: "Sustitución por ausencia"
        }
      },
      actor_id: {
        label: "Actor"
      },
      comment: {
        label: "Comentario"
      },
      attachments: {
        label: "Adjuntos",
        help: "Archivos que respaldan esta acción, p. ej. un contrato firmado o pruebas (#3266)."
      },
      created_at: {
        label: "Creado el"
      }
    },
    _views: {
      recent: {
        label: "Recientes",
        emptyState: {
          title: "Aún no hay acciones de aprobación",
          message: "Las acciones se registran automáticamente a medida que avanza la aprobación."
        }
      },
      by_actor: {
        label: "Por actor"
      },
      all_actions: {
        label: "Todas"
      }
    }
  },
  sys_approval_delegation: {
    label: "Approval Delegation",
    pluralLabel: "Approval Delegations",
    description: "Self-service out-of-office rule: route this user's approver slots to a delegate within a time window (#1322 M1).",
    fields: {
      id: {
        label: "Delegation ID"
      },
      delegator_id: {
        label: "Delegator",
        help: "The user going out of office; their individually-routed approver slots are rerouted while active."
      },
      delegate_id: {
        label: "Delegate",
        help: "The backup who receives the delegator's approvals while this rule is active. Acts under their own identity."
      },
      valid_from: {
        label: "Valid From",
        help: "Rule is inactive before this instant. Null = active immediately. Enforced at resolution time via isGrantActive (ADR-0091 D2 predicate) — never by a background job."
      },
      valid_until: {
        label: "Valid Until",
        help: "Rule is inactive AT and AFTER this instant (half-open [from, until), UTC). Null = never expires."
      },
      reason: {
        label: "Reason",
        help: "Why the delegation exists (e.g. \"Annual leave 5/26–5/30\"). Recorded on the substitution audit row."
      },
      organization_id: {
        label: "Organization",
        help: "Tenant that owns this rule; null = applies across tenants for this delegator."
      },
      created_at: {
        label: "Created At"
      },
      updated_at: {
        label: "Updated At"
      }
    },
    _views: {
      active: {
        label: "Active",
        emptyState: {
          title: "No delegations",
          message: "Declare an out-of-office delegation so approvals route to a backup while you are away."
        }
      }
    }
  }
};
