import { getMetadataTypeSchema } from '../src/kernel/metadata-type-schemas';
import { ObjectSchema } from '../src/data/object.zod';
import { zodChildSchemas, zodDefOf } from './lib/zod-graph.js';
const root = getMetadataTypeSchema('object');
console.log('identity root===ObjectSchema:', root === (ObjectSchema as unknown));
console.log('root def type:', zodDefOf(root as never)?.type);
console.log('root children:', zodChildSchemas(root as never).length);
console.log('ObjectSchema def type:', zodDefOf(ObjectSchema as never)?.type);
console.log('ObjectSchema children:', zodChildSchemas(ObjectSchema as never).length);
console.log('def identity:', zodDefOf(root as never) === zodDefOf(ObjectSchema as never));
