#!/usr/bin/env tsx
// Copyright (c) 2026 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Generate (and gate) `src/meta-spelling/meta-url-data.generated.ts` — the
 * schema-free materialization of the `/meta` URL-spelling contract (#10096).
 *
 * ## Why the map is generated instead of derived at module load
 *
 * The map's two sources are heavy on purpose-unrelated weight:
 * `DEFAULT_METADATA_TYPE_REGISTRY` lives in the kernel zod graph, and
 * `PLURAL_TO_SINGULAR` sits in a module that reaches the ADR-0087 conversion
 * layer. Deriving at module load therefore made ONE string fold cost a
 * browser consumer +60.1 KB gzipped (#10096's measurement). The 2026-08-20
 * maintainer ruling minted the standing principle 「浏览器可达的 spec 导出面必
 * 须 schema-free」 and approved moving the derivation to build time: this
 * script derives the union HERE, writes it as a pure data module, and the
 * `/meta-spelling` entry ships vocabulary with no schema closure.
 *
 * ## This check is the enforcement home of `assertMetaUrlSpellingsAgree()`
 *
 * The module-load assertion that pinned the derived limb against the manifest
 * limb moved here, per the same ruling (⛔ dropping it to save bytes was
 * explicitly forbidden — the agreement must keep an enforcement home). Both
 * modes of this script run it, so a disagreement fails generation AND fails
 * CI's `check:meta-url-spelling` — loudly, before any artifact is written.
 *
 * The pluralization/camelCase rules are IMPORTED from the runtime module
 * (`restPluralOfMetaType` / `camelCaseOf`) rather than copied, so the checked
 * refusal `hint`s and the checked-in map can never drift from the one rule.
 *
 * Usage:
 *   pnpm --filter @objectstack/spec gen:meta-url-spelling      # rewrite the artifact
 *   pnpm --filter @objectstack/spec check:meta-url-spelling    # verify it is current
 * Exit: 0 = OK; 1 = spelling disagreement, or (--check) stale artifact.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { DEFAULT_METADATA_TYPE_REGISTRY } from '../src/kernel/metadata-plugin.zod';
import { PLURAL_TO_SINGULAR } from '../src/shared/metadata-collection.zod';
import { restPluralOfMetaType, camelCaseOf } from '../src/meta-spelling/metadata-url-spelling';

const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  '..',
  'src',
  'meta-spelling',
  'meta-url-data.generated.ts',
);

/**
 * The three-limb union, exactly as `shared/metadata-url-spelling.ts` built it
 * at module load before #10096 (limb 1 manifest spellings verbatim; limb 2
 * registry-derived REST plurals; limb 3 camelCase spellings for snake_case
 * registry types). Order is load-bearing only for output stability.
 */
function buildMetaUrlMap(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [plural, singular] of Object.entries(PLURAL_TO_SINGULAR)) out[plural] = singular;
  for (const entry of DEFAULT_METADATA_TYPE_REGISTRY) {
    out[restPluralOfMetaType(entry.type)] = entry.type;
    const camel = camelCaseOf(entry.type);
    if (camel !== entry.type) out[restPluralOfMetaType(camel)] = entry.type;
  }
  return out;
}

/**
 * Fail the build rather than serve two answers for one spelling. A
 * disagreement here means the derived limb and the manifest limb have
 * drifted, which is the same class of silent divergence #7894 is about.
 * (Formerly asserted at module load in `shared/metadata-url-spelling.ts`;
 * moved to this build-time home by the 2026-08-20 ruling on #10096.)
 */
function assertMetaUrlSpellingsAgree(map: Record<string, string>): void {
  for (const [plural, singular] of Object.entries(PLURAL_TO_SINGULAR)) {
    const derived = map[plural];
    if (derived !== singular) {
      console.error(
        `✗ [metadata-url-spelling] '${plural}' resolves to '${derived}' in the URL map but ` +
          `'${singular}' in PLURAL_TO_SINGULAR. One spelling may not name two types.`,
      );
      process.exit(1);
    }
  }
}

function render(map: Record<string, string>, declared: string[]): string {
  const mapLines = Object.entries(map)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join('\n');
  const declaredLines = declared.map((t) => `  ${JSON.stringify(t)},`).join('\n');
  return `// Copyright (c) 2026 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * AUTO-GENERATED by \`pnpm --filter @objectstack/spec gen:meta-url-spelling\`
 * (scripts/build-meta-url-spelling.ts) — ❌ never edit by hand.
 *
 * Schema-free materialization of the \`/meta\` URL-spelling contract (#10096):
 * the three-limb union of \`PLURAL_TO_SINGULAR\` and the REST plurals derived
 * from \`DEFAULT_METADATA_TYPE_REGISTRY\`, frozen at build time so the
 * \`@objectstack/spec/meta-spelling\` entry links no zod machinery.
 * \`check:meta-url-spelling\` re-derives this union from the live sources on
 * every CI lap — including the manifest/derived agreement assertion that used
 * to run at module load — so this file cannot silently lag or drift.
 *
 * @module
 */

/** Plural (and camelCase) URL spelling → canonical singular metadata type. */
export const META_URL_TO_SINGULAR: Readonly<Record<string, string>> = Object.freeze({
${mapLines}
});

/**
 * Every metadata type with a STATIC \`DEFAULT_METADATA_TYPE_REGISTRY\` entry,
 * in registry order. Read only by the refusal predicates one module over.
 */
export const REGISTRY_DECLARED_META_TYPES: ReadonlyArray<string> = Object.freeze([
${declaredLines}
]);
`;
}

const map = buildMetaUrlMap();
assertMetaUrlSpellingsAgree(map);
const declared = DEFAULT_METADATA_TYPE_REGISTRY.map((e) => e.type);
const next = render(map, declared);

const check = process.argv.includes('--check');
const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';

if (check) {
  if (current === next) {
    console.log(
      `✓ meta-url-spelling data is current (${Object.keys(map).length} spellings, ` +
        `${declared.length} registry-declared types; manifest/derived agreement holds).`,
    );
    process.exit(0);
  }
  console.error(
    `✗ src/meta-spelling/meta-url-data.generated.ts is stale relative to its sources\n` +
      `  (PLURAL_TO_SINGULAR and/or DEFAULT_METADATA_TYPE_REGISTRY changed).\n` +
      `  Regenerate with: pnpm --filter @objectstack/spec gen:meta-url-spelling`,
  );
  process.exit(1);
}

if (current === next) {
  console.log('✓ meta-url-spelling data already current — nothing written.');
} else {
  writeFileSync(OUT, next);
  console.log(
    `✓ wrote src/meta-spelling/meta-url-data.generated.ts ` +
      `(${Object.keys(map).length} spellings, ${declared.length} registry-declared types).`,
  );
}
