// Copyright (c) 2026 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * build-retired-after-census.ts — derive, from the PUBLISHED `@objectstack/spec`
 * tarballs, which ADR-0087 conversion entries each stable release carried as
 * retired, and write that census to `src/conversions/retired-after.census.json`.
 *
 *   pnpm --filter @objectstack/spec exec tsx scripts/build-retired-after-census.ts           # re-derive + write
 *   pnpm --filter @objectstack/spec exec tsx scripts/build-retired-after-census.ts --check   # re-derive + compare
 *
 * Behind a proxy, Node's `fetch` needs `NODE_USE_ENV_PROXY=1` to use it.
 *
 * ## Why a committed census, and why this is not a CI step
 *
 * `MetadataConversion.retiredAfter` is the last published spec version whose
 * authoring surface still accepted a retired entry's old shape. For every entry
 * a release has already shipped, that is a FACT about the published tarballs:
 * the stable release just before the first tarball that carries the entry
 * retired. `src/conversions/retired-after.census.test.ts` pins every entry's
 * value against those facts, offline, on every run. The facts themselves come
 * from here, because reading them means downloading every stable tarball since
 * the registry first shipped (hundreds of MB), which no unit suite should do per
 * run and no suite here does.
 *
 * The census holds RAW facts only — per stable release: its version, the
 * tarball's `dist.integrity`, and the sorted ids its `ALL_CONVERSIONS` marks
 * `retiredFromLoadPath`. Every derived value (which release first retired an
 * entry, what its `retiredAfter` must be) is the test's, so a wrong derivation
 * cannot hide inside the committed file.
 *
 * ## When to run it
 *
 * After every stable `@objectstack/spec` publish. Until then the census's last
 * release trails the published line, and the test's rule for entries the census
 * never saw retired stays the release-pending tolerance (`[last censused
 * release, package.json label]`) instead of the exact label — see the test's
 * docblock. `--check` names a missing stable release as drift, so running it is
 * how you find out.
 *
 * ## How a release is read
 *
 * Stable releases only (no prerelease segment): an `engines.protocol` caret
 * floor never names a prerelease, and the artifact door compares `x.y.z`
 * triples. The census starts at the first stable release whose root entry
 * exports `ALL_CONVERSIONS` — and proves the release before it exports none, so
 * no retirement can predate the census. Each tarball is verified against the
 * packument's `dist.integrity` before it is read; its `dist/` is unpacked under
 * `node_modules/.cache/` (so its bare imports resolve through this package's own
 * `node_modules`) and its `dist/index.mjs` is imported to read `ALL_CONVERSIONS`
 * as that release built it. Any failure — offline, a 404, an integrity mismatch,
 * an unreadable export — exits non-zero, loudly: ⛔ never a partial census.
 */

import { createHash } from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const PKG_DIR = resolve(HERE, '..');
const CENSUS_PATH = join(PKG_DIR, 'src/conversions/retired-after.census.json');
const CACHE_DIR = join(PKG_DIR, 'node_modules/.cache/retired-after-census');
const PACKAGE = '@objectstack/spec';
const REGISTRY = 'https://registry.npmjs.org';

interface CensusRelease {
  version: string;
  integrity: string;
  retired: string[];
}

interface RetiredAfterCensus {
  $comment: string[];
  package: string;
  registry: string;
  /** The stable release just before `releases[0]`, proven to export no `ALL_CONVERSIONS`. */
  precedingRelease: string;
  releases: CensusRelease[];
}

const COMMENT = [
  'GENERATED by scripts/build-retired-after-census.ts from the published @objectstack/spec tarballs.',
  'Do not edit by hand. Re-run the script after every stable publish; see its header.',
  'Per stable release: the tarball integrity and the ids its ALL_CONVERSIONS marks retiredFromLoadPath.',
  'Pinned against the registry by src/conversions/retired-after.census.test.ts.',
];

type Triple = [number, number, number];

function parseStable(v: string): Triple | null {
  const m = /^(\d+)\.(\d+)\.(\d+)$/.exec(v);
  return m ? [Number(m[1]), Number(m[2]), Number(m[3])] : null;
}

function compare(a: Triple, b: Triple): number {
  for (let i = 0; i < 3; i++) if (a[i] !== b[i]) return a[i]! < b[i]! ? -1 : 1;
  return 0;
}

async function fetchOk(url: string): Promise<Response> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`GET ${url} answered ${res.status} ${res.statusText}`);
  return res;
}

interface PackumentVersion {
  dist: { tarball: string; integrity: string };
}

async function readRelease(version: string, meta: PackumentVersion): Promise<string[] | null> {
  const tgz = Buffer.from(await (await fetchOk(meta.dist.tarball)).arrayBuffer());
  const [algo, expected] = meta.dist.integrity.split('-', 2) as [string, string];
  const actual = createHash(algo).update(tgz).digest('base64');
  if (actual !== expected) {
    throw new Error(`${PACKAGE}@${version}: tarball integrity mismatch (${algo} ${actual} != ${expected})`);
  }
  const dir = join(CACHE_DIR, version);
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  const tgzPath = join(dir, 'package.tgz');
  writeFileSync(tgzPath, tgz);
  const tar = spawnSync('tar', ['xzf', tgzPath, '-C', dir, 'package/package.json', 'package/dist'], {
    encoding: 'utf8',
  });
  if (tar.status !== 0) throw new Error(`${PACKAGE}@${version}: tar failed: ${tar.stderr || tar.error}`);
  const entry = join(dir, 'package/dist/index.mjs');
  if (!existsSync(entry)) throw new Error(`${PACKAGE}@${version}: no dist/index.mjs in the tarball`);
  const mod = (await import(pathToFileURL(entry).href)) as { ALL_CONVERSIONS?: unknown };
  const all = mod.ALL_CONVERSIONS;
  if (all === undefined) return null;
  if (!Array.isArray(all)) throw new Error(`${PACKAGE}@${version}: ALL_CONVERSIONS is not an array`);
  return all
    .filter((c: { retiredFromLoadPath?: unknown }) => c.retiredFromLoadPath === true)
    .map((c: { id: unknown }) => {
      if (typeof c.id !== 'string') throw new Error(`${PACKAGE}@${version}: a conversion has no string id`);
      return c.id;
    })
    .sort();
}

async function deriveCensus(): Promise<RetiredAfterCensus> {
  const packument = (await (await fetchOk(`${REGISTRY}/${PACKAGE.replace('/', '%2F')}`)).json()) as {
    versions: Record<string, PackumentVersion>;
  };
  const stable = Object.keys(packument.versions)
    .map((v) => ({ v, t: parseStable(v) }))
    .filter((x): x is { v: string; t: Triple } => x.t !== null)
    .sort((a, b) => compare(a.t, b.t))
    .map((x) => x.v);

  // Walk DOWN from the newest stable release until one exports no registry.
  const releases: CensusRelease[] = [];
  let precedingRelease: string | null = null;
  for (let i = stable.length - 1; i >= 0; i--) {
    const version = stable[i]!;
    const retired = await readRelease(version, packument.versions[version]!);
    if (retired === null) {
      precedingRelease = version;
      break;
    }
    releases.unshift({ version, integrity: packument.versions[version]!.dist.integrity, retired });
    process.stdout.write(`  ${version}: ${retired.length} retired\n`);
  }
  if (precedingRelease === null) throw new Error('every stable release exports ALL_CONVERSIONS — no census floor');
  if (releases.length === 0) throw new Error('the newest stable release exports no ALL_CONVERSIONS');
  return { $comment: COMMENT, package: PACKAGE, registry: REGISTRY, precedingRelease, releases };
}

function serialize(census: RetiredAfterCensus): string {
  return JSON.stringify(census, null, 2) + '\n';
}

async function main(): Promise<void> {
  const check = process.argv.includes('--check');
  try {
    const census = await deriveCensus();
    const next = serialize(census);
    if (check) {
      const committed = existsSync(CENSUS_PATH) ? readFileSync(CENSUS_PATH, 'utf8') : '';
      if (committed !== next) {
        console.error(
          `retired-after census drift: ${CENSUS_PATH} is not what the published tarballs say ` +
            `(newest stable release on npm: ${census.releases.at(-1)!.version}). ` +
            'Re-run without --check and commit the result.',
        );
        process.exit(1);
      }
      console.log(`retired-after census matches the published tarballs (${census.releases.length} releases) ✓`);
      return;
    }
    writeFileSync(CENSUS_PATH, next);
    console.log(`wrote ${CENSUS_PATH} (${census.releases.length} releases, from ${census.releases[0]!.version})`);
  } finally {
    rmSync(CACHE_DIR, { recursive: true, force: true });
  }
}

main().catch((err: unknown) => {
  console.error(`build-retired-after-census: ${err instanceof Error ? err.message : String(err)}`);
  process.exit(1);
});
