// Copyright (c) 2026 ObjectStack. Licensed under the Apache-2.0 license.
//
// Pins the command-line contract of the two ADR-0087 D4 projections
// (`lib/projection-cli.ts`), which since the #22449 B′ ruling are generated at
// publish and generated IN MEMORY on a pull request:
//
//   - `--check` reads and writes no committed copy, so a pull request that only
//     adds a registry entry needs no regeneration commit;
//   - a generation failure is red in every mode and writes nothing;
//   - `--out` writes the generated bytes where it is told, and nowhere else.
//
// The runner returns its verdict instead of exiting, so these cases drive it
// with a stub `build` — no seam is added to either generator. The second block
// spawns the two REAL generators, which proves they route through the runner
// and that generation is deterministic: the publish lane's `--verify` compares
// the packed copy with a second, fresh generation and depends on that.

import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { runProjectionCli, type ProjectionCliOptions } from './lib/projection-cli';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const PKG = path.resolve(HERE, '..');
const TSX = path.join(PKG, 'node_modules', '.bin', 'tsx');
const SPAWN_TIMEOUT_MS = 120_000;

let tmp: string;
beforeEach(() => {
  tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'projection-cli-'));
});
afterEach(() => {
  fs.rmSync(tmp, { recursive: true, force: true });
});

function options(over: Partial<ProjectionCliOptions> & { argv: string[] }): ProjectionCliOptions {
  return {
    name: 'fixture.json',
    committedPath: path.join(tmp, 'committed', 'fixture.json'),
    build: () => '{"generated":true}\n',
    ...over,
  };
}

function writeCommitted(text: string): string {
  const file = path.join(tmp, 'committed', 'fixture.json');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, text);
  return file;
}

describe('runProjectionCli — the two projections’ command-line contract', () => {
  it('--check generates in memory and neither reads nor writes a STALE committed copy', () => {
    const committed = writeCommitted('{"stale":"a registry entry was added since this was written"}\n');
    const before = fs.readFileSync(committed, 'utf8');

    const result = runProjectionCli(options({ argv: ['--check'] }));

    expect(result.code).toBe(0);
    expect(result.wrote).toBeNull();
    expect(fs.readFileSync(committed, 'utf8')).toBe(before);
    expect(result.stdout.join('\n')).toContain('fixture.json generates from the ADR-0087 registries, in memory');
  });

  it('--check is green with no committed copy at all (the copies are deleted later)', () => {
    const result = runProjectionCli(options({ argv: ['--check'] }));

    expect(result.code).toBe(0);
    expect(fs.existsSync(path.join(tmp, 'committed'))).toBe(false);
  });

  it('a generation failure is red in --check, names the projection and the cause, and writes nothing', () => {
    const result = runProjectionCli(
      options({
        argv: ['--check'],
        build: () => {
          throw new Error('migration 18.example: acceptanceCriteria is empty');
        },
      }),
    );

    expect(result.code).toBe(1);
    expect(result.stdout).toEqual([]);
    const said = result.stderr.join('\n');
    expect(said).toContain('fixture.json could not be generated from the ADR-0087 registries');
    expect(said).toContain('migration 18.example: acceptanceCriteria is empty');
    expect(result.wrote).toBeNull();
  });

  it('a generation failure is red in the write modes too, and leaves every file as it was', () => {
    const committed = writeCommitted('{"before":true}\n');
    const out = path.join(tmp, 'out', 'fixture.json');
    const failing = () => {
      throw new Error('boom');
    };

    const written = runProjectionCli(options({ argv: [], build: failing }));
    const toOut = runProjectionCli(options({ argv: ['--out', out], build: failing }));

    expect(written.code).toBe(1);
    expect(toOut.code).toBe(1);
    expect(fs.readFileSync(committed, 'utf8')).toBe('{"before":true}\n');
    expect(fs.existsSync(out)).toBe(false);
  });

  it('--out writes exactly the generated bytes there and leaves the committed copy alone', () => {
    const committed = writeCommitted('{"before":true}\n');
    const out = path.join(tmp, 'nested', 'dir', 'fixture.json');

    const result = runProjectionCli(options({ argv: ['--out', out] }));

    expect(result.code).toBe(0);
    expect(result.wrote).toBe(out);
    expect(fs.readFileSync(out, 'utf8')).toBe('{"generated":true}\n');
    expect(fs.readFileSync(committed, 'utf8')).toBe('{"before":true}\n');
  });

  it('with no flag it writes the committed copy', () => {
    const result = runProjectionCli(options({ argv: [] }));

    expect(result.code).toBe(0);
    expect(fs.readFileSync(path.join(tmp, 'committed', 'fixture.json'), 'utf8')).toBe('{"generated":true}\n');
  });

  it('with no flag and no committed copy it refuses as a usage error, builds nothing and writes nothing', () => {
    let builds = 0;
    const result = runProjectionCli({
      name: 'fixture.json',
      build: () => {
        builds += 1;
        return '{}\n';
      },
      argv: [],
    });

    expect(result.code).toBe(2);
    expect(result.stderr.join('\n')).toContain('fixture.json has no committed copy');
    expect(result.wrote).toBeNull();
    expect(builds).toBe(0);
    expect(fs.readdirSync(tmp)).toEqual([]);
  });

  it('--check with --out, and --out with no path, are usage errors that build nothing', () => {
    let builds = 0;
    const build = () => {
      builds += 1;
      return '{}\n';
    };

    expect(runProjectionCli(options({ argv: ['--check', '--out', path.join(tmp, 'x')], build })).code).toBe(2);
    expect(runProjectionCli(options({ argv: ['--out'], build })).code).toBe(2);
    expect(runProjectionCli(options({ argv: ['--out', '--check'], build })).code).toBe(2);
    expect(builds).toBe(0);
  });
});

describe('the two real generators route through it, and generate deterministically', () => {
  const generators = [
    { script: 'build-spec-changes.ts', name: 'spec-changes.json' },
    { script: 'build-upgrade-guide.ts', name: 'protocol-upgrade-guide.md' },
  ];

  function run(script: string, args: string[]): { status: number; output: string } {
    const r = spawnSync(TSX, [path.join(HERE, script), ...args], {
      cwd: PKG,
      encoding: 'utf8',
      timeout: SPAWN_TIMEOUT_MS,
      stdio: ['ignore', 'pipe', 'pipe'],
    });
    return { status: r.status ?? -1, output: `${r.stdout ?? ''}${r.stderr ?? ''}` };
  }

  for (const { script, name } of generators) {
    it(`${script} --check is green from the registries and names ${name}`, () => {
      const r = run(script, ['--check']);

      expect(r.output).toContain(`${name} generates from the ADR-0087 registries, in memory`);
      expect(r.status).toBe(0);
    });

    it(`${script} --out twice writes byte-identical ${name}`, () => {
      const first = path.join(tmp, 'first', name);
      const second = path.join(tmp, 'second', name);

      expect(run(script, ['--out', first]).status).toBe(0);
      expect(run(script, ['--out', second]).status).toBe(0);

      const bytes = fs.readFileSync(first);
      expect(bytes.length).toBeGreaterThan(0);
      expect(fs.readFileSync(second).equals(bytes)).toBe(true);
    });
  }
});
