// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'es-ES'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const esESObjects: NonNullable<TranslationData['objects']> = {
  sys_presence: {
    label: "Presencia",
    pluralLabel: "Presencias",
    description: "Seguimiento en tiempo real de presencia y actividad de usuarios",
    fields: {
      id: {
        label: "ID de presencia"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      },
      user_id: {
        label: "Usuario"
      },
      session_id: {
        label: "Sesión"
      },
      status: {
        label: "Estado",
        options: {
          online: "En línea",
          away: "Ausente",
          busy: "Ocupado",
          offline: "Desconectado"
        }
      },
      last_seen: {
        label: "Visto por última vez"
      },
      current_location: {
        label: "Ubicación actual"
      },
      device: {
        label: "Dispositivo",
        options: {
          desktop: "Escritorio",
          mobile: "Móvil",
          tablet: "Tableta",
          other: "Otro"
        }
      },
      custom_status: {
        label: "Estado personalizado"
      },
      metadata: {
        label: "Metadatos",
        help: "Metadatos JSON arbitrarios asociados al estado de presencia (coincide con PresenceStateSchema.metadata)."
      }
    }
  }
};
