// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'zh-CN'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const zhCNObjects: NonNullable<TranslationData['objects']> = {
  sys_presence: {
    label: "在线状态",
    pluralLabel: "在线状态",
    description: "实时用户在线与活动跟踪",
    fields: {
      id: {
        label: "在线状态 ID"
      },
      created_at: {
        label: "创建时间"
      },
      updated_at: {
        label: "更新时间"
      },
      user_id: {
        label: "用户"
      },
      session_id: {
        label: "会话"
      },
      status: {
        label: "状态",
        options: {
          online: "在线",
          away: "离开",
          busy: "忙碌",
          offline: "离线"
        }
      },
      last_seen: {
        label: "最近在线时间"
      },
      current_location: {
        label: "当前位置"
      },
      device: {
        label: "设备",
        options: {
          desktop: "桌面端",
          mobile: "移动端",
          tablet: "平板端",
          other: "其他"
        }
      },
      custom_status: {
        label: "自定义状态"
      },
      metadata: {
        label: "元数据",
        help: "与在线状态关联的任意 JSON 元数据（对应 PresenceStateSchema.metadata）。"
      }
    }
  }
};
