// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'en'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const enObjects: NonNullable<TranslationData['objects']> = {
  sys_audit_log: {
    label: "Audit Log",
    pluralLabel: "Audit Logs",
    description: "Immutable audit trail for platform events",
    fields: {
      created_at: {
        label: "Timestamp"
      },
      action: {
        label: "Action",
        help: "Action type (snake_case)",
        options: {
          create: "create",
          update: "update",
          delete: "delete",
          login: "login",
          logout: "logout",
          config_change: "config_change",
          import: "import"
        }
      },
      user_id: {
        label: "User",
        help: "User who performed the action (null for non-user / service actions — see actor)"
      },
      actor: {
        label: "Actor",
        help: "Principal that performed the action: a user id, svc:<name>, or null"
      },
      object_name: {
        label: "Object",
        help: "Target object (e.g. sys_user, project_task)"
      },
      record_id: {
        label: "Record ID",
        help: "ID of the affected record"
      },
      old_value: {
        label: "Old Value",
        help: "JSON-serialized previous state"
      },
      new_value: {
        label: "New Value",
        help: "JSON-serialized new state"
      },
      ip_address: {
        label: "IP Address"
      },
      user_agent: {
        label: "User Agent"
      },
      tenant_id: {
        label: "Tenant",
        help: "Tenant context for multi-tenant isolation"
      },
      metadata: {
        label: "Metadata",
        help: "JSON-serialized additional context"
      },
      id: {
        label: "Audit Log ID"
      }
    },
    _views: {
      recent: {
        label: "Recent",
        emptyState: {
          title: "No audit events",
          message: "Activity will appear here as users interact with the platform."
        }
      },
      writes_only: {
        label: "Writes"
      },
      auth_events: {
        label: "Auth"
      },
      config_changes: {
        label: "Config"
      },
      all_events: {
        label: "All"
      }
    }
  },
  sys_activity: {
    label: "Activity",
    pluralLabel: "Activities",
    description: "Recent activity stream entries (lightweight, denormalized)",
    fields: {
      id: {
        label: "Activity ID"
      },
      timestamp: {
        label: "Timestamp"
      },
      type: {
        label: "Type",
        options: {
          created: "created",
          updated: "updated",
          deleted: "deleted",
          commented: "commented",
          mentioned: "mentioned",
          shared: "shared",
          assigned: "assigned",
          completed: "completed",
          login: "login",
          logout: "logout",
          system: "system"
        }
      },
      summary: {
        label: "Summary",
        help: "Human-readable one-line summary"
      },
      actor_id: {
        label: "Actor"
      },
      actor_name: {
        label: "Actor Name"
      },
      actor_avatar_url: {
        label: "Actor Avatar"
      },
      object_name: {
        label: "Object",
        help: "Target object short name (e.g. account, sys_user)"
      },
      record_id: {
        label: "Record ID"
      },
      record_label: {
        label: "Record Label",
        help: "Display label of the target record at write time"
      },
      source_object: {
        label: "Source Object",
        help: "Object name of the rich source entity this activity was derived from (e.g. \"sys_email\"). Null when the activity is about the target record itself."
      },
      source_id: {
        label: "Source ID",
        help: "Record id of the rich source entity (paired with source_object) — lets the timeline drill to the full email/call/meeting record."
      },
      url: {
        label: "URL",
        help: "Optional deep-link to the activity target"
      },
      environment_id: {
        label: "Environment",
        help: "Environment context (multi-environment deployments)"
      },
      metadata: {
        label: "Metadata",
        help: "JSON-serialized additional context"
      }
    }
  },
  sys_comment: {
    label: "Comment",
    pluralLabel: "Comments",
    description: "Threaded comments attached to records via thread_id",
    fields: {
      id: {
        label: "Comment ID"
      },
      thread_id: {
        label: "Thread",
        help: "Thread identifier — conventionally `{object}:{record_id}` (e.g. `sys_user:abc123`)"
      },
      parent_id: {
        label: "Parent Comment",
        help: "Optional parent comment for nested replies"
      },
      author_id: {
        label: "Author"
      },
      author_name: {
        label: "Author Name"
      },
      author_avatar_url: {
        label: "Author Avatar"
      },
      body: {
        label: "Body",
        help: "Comment text (Markdown supported)"
      },
      mentions: {
        label: "Mentions",
        help: "JSON array of @mention objects"
      },
      reactions: {
        label: "Reactions",
        help: "JSON array of emoji reaction objects"
      },
      is_edited: {
        label: "Edited"
      },
      edited_at: {
        label: "Edited At"
      },
      created_at: {
        label: "Created At"
      },
      updated_at: {
        label: "Updated At"
      }
    }
  }
};
