// Copyright (c) 2026 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * The one command-line contract of the two ADR-0087 D4 projections —
 * `spec-changes.json` (`build-spec-changes.ts`) and the protocol upgrade guide
 * (`build-upgrade-guide.ts`).
 *
 * Both are pure functions of the D2 conversion table and the D3 migration chain.
 * Since the #22449 B′ ruling they are generated where they ship — at publish, by
 * `scripts/release-spec-changes.sh` — and the pull-request stage generates them
 * IN MEMORY instead of comparing a committed copy:
 *
 *   (no flag)       write the bytes to the committed path. Kept only until the
 *                   committed copies are deleted; nothing gates on that copy.
 *                   A projection with no committed copy (the upgrade guide,
 *                   whose no-flag mode writes its docs pages instead) passes
 *                   no `committedPath`, and a bare run here is a usage error.
 *   --check         generate in memory and write NOTHING. Green means the
 *                   registries project; red means they do not. ⛔ No committed
 *                   copy is read, so a pull request that only adds a registry
 *                   entry needs no regeneration commit.
 *   --out <path>    write the bytes to `<path>`. The publish lane uses it to put
 *                   the guide inside the package, and the pull-request diff
 *                   renderer (`render-projection-diff.ts`) to generate both sides
 *                   of the rendered diff with the SAME generator.
 *
 * A generation failure is loud in every mode: exit 1, the projection named, and
 * nothing written. A registry that cannot be projected is a red check, never a
 * stale-but-green artifact — that is condition (1) of the ruling.
 *
 * The runner RETURNS its verdict instead of exiting, so the contract is pinned
 * by `projection-cli.test.ts` without a test-only seam in either generator.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

export interface ProjectionCliOptions {
  /** The projection's name in every message, e.g. `spec-changes.json`. */
  name: string;
  /**
   * The committed copy the no-flag mode writes. Absent when the projection has
   * none — the upgrade guide's no-flag mode is its own (the docs pages,
   * `build-upgrade-guide.ts`) — and then a bare run is a usage error.
   */
  committedPath?: string;
  /** The projection's bytes, from the registries. Throws when it cannot. */
  build: () => string;
  /** One clause describing generated bytes, for `--check`'s success line. */
  describe?: (bytes: string) => string;
  argv: readonly string[];
}

export interface ProjectionCliResult {
  /** 0 generated, 1 generation failed, 2 the command line is wrong. */
  code: 0 | 1 | 2;
  stdout: string[];
  stderr: string[];
  /** The absolute path written, or `null` when nothing was. */
  wrote: string | null;
}

/** The `--out` value, `undefined` when the flag is absent, `null` when it has no value. */
function outArg(argv: readonly string[]): string | null | undefined {
  const at = argv.indexOf('--out');
  if (at < 0) return undefined;
  const value = argv[at + 1];
  return value === undefined || value.startsWith('--') ? null : value;
}

function message(err: unknown): string {
  if (err instanceof Error) return err.stack ?? err.message;
  return String(err);
}

export function runProjectionCli(opts: ProjectionCliOptions): ProjectionCliResult {
  const check = opts.argv.includes('--check');
  const out = outArg(opts.argv);
  const usage = (line: string): ProjectionCliResult => ({ code: 2, stdout: [], stderr: [line], wrote: null });

  if (out === null) return usage(`--out needs a path: --out <file> (${opts.name}).`);
  if (!check && out === undefined && opts.committedPath === undefined) {
    return usage(`${opts.name} has no committed copy: pass --check (generate in memory) or --out <file>.`);
  }
  if (check && out !== undefined) {
    return usage(
      `--check generates ${opts.name} in memory and writes nothing; --out writes it. Pass one, not both.`,
    );
  }

  let bytes: string;
  try {
    bytes = opts.build();
  } catch (err) {
    return {
      code: 1,
      stdout: [],
      stderr: [
        `✗ ${opts.name} could not be generated from the ADR-0087 registries. Nothing was written.`,
        '  A registry that does not project is a red check — the publish lane would fail on the same input.',
        `  ${message(err).split('\n').join('\n  ')}`,
      ],
      wrote: null,
    };
  }

  if (check) {
    const detail = opts.describe ? `: ${opts.describe(bytes)}` : '';
    return {
      code: 0,
      stdout: [
        `✓ ${opts.name} generates from the ADR-0087 registries, in memory${detail}.`,
        '  No committed copy is compared: the publish lane generates the shipped one and verifies it from the tarball.',
      ],
      stderr: [],
      wrote: null,
    };
  }

  // `out ?? committedPath` is never undefined here: the usage check above refused that.
  const target = resolve((out ?? opts.committedPath) as string);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, bytes);
  return { code: 0, stdout: [`Wrote ${target}`], stderr: [], wrote: target };
}

/** Print a verdict and exit with its code — the generators' last statement. */
export function exitWith(result: ProjectionCliResult): never {
  for (const line of result.stdout) console.log(line);
  for (const line of result.stderr) console.error(line);
  process.exit(result.code);
}
