// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'es-ES'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const esESObjects: NonNullable<TranslationData['objects']> = {
  sys_inbox_message: {
    label: "Mensaje de bandeja de entrada",
    pluralLabel: "Mensajes de bandeja de entrada",
    description: "Filas de notificación en la aplicación, orientadas al usuario final, materializadas por el canal de bandeja de entrada.",
    fields: {
      id: {
        label: "ID del mensaje"
      },
      user_id: {
        label: "Usuario destinatario"
      },
      notification_id: {
        label: "Evento de notificación",
        help: "FK → sys_notification (el evento L2 que materializa esta fila)"
      },
      delivery_id: {
        label: "Entrega",
        help: "FK → sys_notification_delivery (fila de outbox); nulo hasta P1"
      },
      topic: {
        label: "Tema"
      },
      title: {
        label: "Título"
      },
      body_md: {
        label: "Cuerpo"
      },
      severity: {
        label: "Severidad",
        options: {
          info: "Información",
          warning: "Advertencia",
          critical: "Crítica"
        }
      },
      action_url: {
        label: "URL de acción"
      },
      created_at: {
        label: "Fecha de creación"
      }
    },
    _views: {
      mine: {
        label: "Notificaciones",
        emptyState: {
          title: "Sin notificaciones",
          message: "No hay notificaciones."
        }
      }
    }
  },
  sys_notification_receipt: {
    label: "Notification Receipt",
    pluralLabel: "Notification Receipts",
    description: "Per-recipient × channel receipt; the source of truth for notification read-state.",
    fields: {
      id: {
        label: "Receipt ID"
      },
      notification_id: {
        label: "Notification Event",
        help: "FK → sys_notification (L2 event)"
      },
      delivery_id: {
        label: "Delivery",
        help: "FK → sys_notification_delivery (outbox row); null until P1"
      },
      user_id: {
        label: "Recipient User"
      },
      channel: {
        label: "Channel",
        help: "Channel id this receipt is for (inbox / email / push / …)"
      },
      state: {
        label: "State",
        options: {
          delivered: "delivered",
          read: "read",
          clicked: "clicked",
          dismissed: "dismissed"
        }
      },
      at: {
        label: "At",
        help: "When the receipt reached its current state"
      },
      created_at: {
        label: "Created At"
      }
    }
  },
  sys_notification_delivery: {
    label: "Notification Delivery",
    pluralLabel: "Notification Deliveries",
    description: "Durable per-recipient × channel delivery outbox (ADR-0030 Layer 4).",
    fields: {
      id: {
        label: "Delivery ID"
      },
      notification_id: {
        label: "Notification Event",
        help: "FK → sys_notification (L2 event)"
      },
      recipient_id: {
        label: "Recipient User"
      },
      channel: {
        label: "Channel"
      },
      topic: {
        label: "Topic"
      },
      digest_key: {
        label: "Digest Key",
        help: "recipient|channel|window grouping key for batched (digest) deliveries; null for normal sends."
      },
      payload: {
        label: "Payload",
        help: "Snapshot of the rendered notification content for dispatch."
      },
      status: {
        label: "Status",
        options: {
          pending: "pending",
          in_flight: "in_flight",
          success: "success",
          failed: "failed",
          dead: "dead",
          suppressed: "suppressed"
        }
      },
      attempts: {
        label: "Attempts"
      },
      partition_key: {
        label: "Partition Key"
      },
      claimed_by: {
        label: "Claimed By",
        help: "Node id while in_flight"
      },
      claimed_at: {
        label: "Claimed At (ms)"
      },
      next_attempt_at: {
        label: "Next Attempt At (ms)"
      },
      last_attempted_at: {
        label: "Last Attempted At (ms)"
      },
      error: {
        label: "Error"
      },
      created_at: {
        label: "Created At"
      },
      updated_at: {
        label: "Updated At"
      }
    }
  },
  sys_notification_preference: {
    label: "Notification Preference",
    pluralLabel: "Notification Preferences",
    description: "Per-user × topic × channel notification toggle (mute/allow), with admin-global defaults.",
    fields: {
      id: {
        label: "Preference ID"
      },
      user_id: {
        label: "User",
        help: "Recipient user id, or '*' for the admin-global default."
      },
      topic: {
        label: "Topic",
        help: "Notification topic, or '*' for all topics."
      },
      channel: {
        label: "Channel",
        help: "Channel id (inbox/email/push/…), or '*' for all channels."
      },
      enabled: {
        label: "Enabled",
        help: "When false, this (user, topic, channel) is muted."
      },
      digest: {
        label: "Digest",
        help: "Batch cadence (P3 digest middleware).",
        options: {
          none: "none",
          daily: "daily",
          weekly: "weekly"
        }
      },
      quiet_hours: {
        label: "Quiet Hours",
        help: "Optional { tz, start, end } window (P3 quiet-hours middleware)."
      },
      created_at: {
        label: "Created At"
      },
      updated_at: {
        label: "Updated At"
      }
    }
  },
  sys_notification_subscription: {
    label: "Notification Subscription",
    pluralLabel: "Notification Subscriptions",
    description: "Standing subscription of a principal (role/team/user) to a notification topic.",
    fields: {
      id: {
        label: "Subscription ID"
      },
      topic: {
        label: "Topic",
        help: "Notification topic this principal subscribes to."
      },
      principal: {
        label: "Principal",
        help: "Subscriber selector: 'role:x' | 'team:x' | 'user:id' | bare user id."
      },
      enabled: {
        label: "Enabled",
        help: "When false, the subscription is inactive."
      },
      created_at: {
        label: "Created At"
      }
    }
  },
  sys_notification_template: {
    label: "Notification Template",
    pluralLabel: "Notification Templates",
    description: "Per (topic × channel × locale) render template for notifications.",
    fields: {
      id: {
        label: "Template ID"
      },
      topic: {
        label: "Topic"
      },
      channel: {
        label: "Channel",
        help: "Channel id this template renders for (email/inbox/push/…)."
      },
      locale: {
        label: "Locale",
        help: "BCP-47 locale, e.g. 'en' / 'en-US' / 'zh-CN'."
      },
      version: {
        label: "Version"
      },
      subject: {
        label: "Subject / Title",
        help: "Rendered into the email subject / inbox title. Supports {{ payload.x }}."
      },
      body: {
        label: "Body",
        help: "Template body. Supports {{ payload.x }}. Interpreted per `format`."
      },
      format: {
        label: "Body Format",
        options: {
          markdown: "markdown",
          html: "html",
          text: "text",
          mjml: "mjml"
        }
      },
      is_active: {
        label: "Active",
        help: "Only active templates are selected at render time."
      },
      created_at: {
        label: "Created At"
      },
      updated_at: {
        label: "Updated At"
      }
    }
  },
  sys_http_delivery: {
    label: "HTTP Delivery",
    pluralLabel: "HTTP Deliveries",
    description: "Durable outbox row for one outbound-HTTP attempt (ADR-0018). Managed by @objectstack/service-messaging; do not write directly.",
    fields: {
      id: {
        label: "Delivery ID",
        help: "UUID — also doubles as the receiver-side idempotency key"
      },
      source: {
        label: "Source",
        help: "Provenance domain, e.g. 'webhook' | 'flow'. UNIQUE(source, dedup_key)."
      },
      ref_id: {
        label: "Ref ID",
        help: "Partition/ordering anchor within source (webhook id, flow id, …)"
      },
      dedup_key: {
        label: "Dedup Key",
        help: "UNIQUE(source, dedup_key) for at-most-once enqueue"
      },
      label: {
        label: "Label",
        help: "Diagnostic label / event type — surfaced on X-Objectstack-Event"
      },
      url: {
        label: "Target URL",
        help: "Snapshotted at enqueue so config edits do not rewrite live rows"
      },
      method: {
        label: "Method"
      },
      headers_json: {
        label: "Headers JSON"
      },
      signing_secret: {
        label: "HMAC Secret"
      },
      timeout_ms: {
        label: "Timeout (ms)"
      },
      payload_json: {
        label: "Payload JSON"
      },
      partition_key: {
        label: "Partition",
        help: "hash(ref_id) mod partitionCount — precomputed for cheap WHERE"
      },
      status: {
        label: "Status",
        help: "pending | in_flight | success | failed | dead"
      },
      attempts: {
        label: "Attempts",
        help: "Number of attempts made so far"
      },
      claimed_by: {
        label: "Claimed By"
      },
      claimed_at: {
        label: "Claimed At (ms)"
      },
      next_retry_at: {
        label: "Next Retry At (ms)"
      },
      last_attempted_at: {
        label: "Last Attempted At (ms)"
      },
      response_code: {
        label: "HTTP Status"
      },
      response_body: {
        label: "Response Body (capped)"
      },
      error: {
        label: "Error"
      },
      created_at: {
        label: "Created At"
      },
      updated_at: {
        label: "Updated At"
      }
    },
    _views: {
      recent: {
        label: "Recent"
      },
      failures: {
        label: "Failures"
      },
      pending: {
        label: "Pending"
      }
    }
  }
};
