// Copyright (c) 2026 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'zh-CN'. Do not hand-edit.
 *
 * Each entry is the digest of the SOURCE REVISION that this locale's leaf at
 * that path is still a byte copy of — provenance for the generated half of the
 * bundles (#11671, maintainer ruling #12069 Option A, extending #8765 Option B).
 *
 * An entry exists only while the leaf IS such a copy. Re-translate the leaf in
 * `<locale>.objects.generated.ts` and the next extract drops its entry by
 * itself — the table makes no claim about text a translator wrote. A path with
 * no entry is LEGACY-TRUSTED and never reported stale.
 *
 * ⚠️ Do not "fix" a staleness report by editing this file. Refreshing a digest
 * records that the current text was copied from the current source, which is
 * the false claim the mechanism exists to detect. Fix the TRANSLATION.
 */

export const zhCNGeneratedSourceHashes: Readonly<Record<string, string>> = {
  "objects.sys_http_delivery.fields.error.help": "3edd3406757bedcf",
  "objects.sys_http_delivery.fields.headers_json.help": "b14e8e640874e0a6",
  "objects.sys_http_delivery.fields.status.help": "e437ecf81dfb4715",
  "objects.sys_notification_delivery.fields.display_title.help": "0803d3f90a14907c",
  "objects.sys_notification_delivery.fields.display_title.label": "70f7aadecce647a5",
  "objects.sys_notification_preference.fields.display_title.help": "13aff17d09067e30",
  "objects.sys_notification_preference.fields.display_title.label": "70f7aadecce647a5",
  "objects.sys_notification_subscription.fields.display_title.help": "1100bd46caf9cb17",
  "objects.sys_notification_subscription.fields.display_title.label": "70f7aadecce647a5",
};
