// Copyright (c) 2026 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'es-ES'. Do not hand-edit.
 *
 * Each entry is the digest of the SOURCE REVISION that this locale's leaf at
 * that path is still a byte copy of — provenance for the generated half of the
 * bundles (#11671, maintainer ruling #12069 Option A, extending #8765 Option B).
 *
 * An entry exists only while the leaf IS such a copy. Re-translate the leaf in
 * `<locale>.objects.generated.ts` and the next extract drops its entry by
 * itself — the table makes no claim about text a translator wrote. A path with
 * no entry is LEGACY-TRUSTED and never reported stale.
 *
 * ⚠️ Do not "fix" a staleness report by editing this file. Refreshing a digest
 * records that the current text was copied from the current source, which is
 * the false claim the mechanism exists to detect. Fix the TRANSLATION.
 */

export const esESGeneratedSourceHashes: Readonly<Record<string, string>> = {
  "objects.sys_account._actions.link_social.params.provider.options.apple": "cfdc41e15ed6699b",
  "objects.sys_account._actions.link_social.params.provider.options.discord": "12f931cc062e76ae",
  "objects.sys_account._actions.link_social.params.provider.options.facebook": "7eea009178f5b807",
  "objects.sys_account._actions.link_social.params.provider.options.github": "2971d247eb4e6abc",
  "objects.sys_account._actions.link_social.params.provider.options.gitlab": "bc3dbbf4b650e600",
  "objects.sys_account._actions.link_social.params.provider.options.google": "6fadcd05bb8da367",
  "objects.sys_account._actions.link_social.params.provider.options.microsoft": "17309efbdb1ec122",
  "objects.sys_email.fields.cc_addresses.label": "02946d952cf15623",
  "objects.sys_email.fields.error.label": "786fed84bd8d5a32",
  "objects.sys_email.fields.message_id.label": "14cd089a4062f4b1",
  "objects.sys_email_template.fields.id.label": "00b0385c9c152888",
  "objects.sys_email_template.fields.variables_json.label": "c2cfff50e8151e3d",
  "objects.sys_job_run.fields.error.label": "786fed84bd8d5a32",
  "objects.sys_metadata.fields.checksum.label": "4fe7cc0967282ec9",
  "objects.sys_metadata.fields.id.label": "00b0385c9c152888",
  "objects.sys_metadata_audit.fields.actor.label": "b155813f8a7f06e3",
  "objects.sys_metadata_audit.fields.id.label": "00b0385c9c152888",
  "objects.sys_metadata_history.fields.checksum.label": "4fe7cc0967282ec9",
  "objects.sys_metadata_history.fields.id.label": "00b0385c9c152888",
  "objects.sys_notification.fields.actor_id.label": "b155813f8a7f06e3",
  "objects.sys_oauth_access_token.fields.id.label": "00b0385c9c152888",
  "objects.sys_oauth_access_token.fields.token.label": "6e8de3393d2cee54",
  "objects.sys_oauth_application._actions.create_oauth_application.params.type.options.web": "2a7ead3da8c035c5",
  "objects.sys_oauth_application.fields.id.label": "00b0385c9c152888",
  "objects.sys_oauth_application.fields.jwks.label": "b2cf79f9d66c0dbc",
  "objects.sys_oauth_application.fields.jwks_uri.label": "2a4339df734ab269",
  "objects.sys_oauth_client_assertion.fields.id.label": "00b0385c9c152888",
  "objects.sys_oauth_client_resource.fields.id.label": "00b0385c9c152888",
  "objects.sys_oauth_consent.fields.id.label": "00b0385c9c152888",
  "objects.sys_oauth_refresh_token.fields.id.label": "00b0385c9c152888",
  "objects.sys_oauth_refresh_token.fields.token.label": "6e8de3393d2cee54",
  "objects.sys_oauth_resource.fields.id.label": "00b0385c9c152888",
  "objects.sys_organization.fields.slug.label": "fe4132df05ec637b",
  "objects.sys_scim_connection_binding.fields.id.label": "00b0385c9c152888",
  "objects.sys_scim_connection_credential.fields.id.label": "00b0385c9c152888",
  "objects.sys_scim_group.fields.id.label": "00b0385c9c152888",
  "objects.sys_scim_group_member.fields.id.label": "00b0385c9c152888",
  "objects.sys_scim_identity_tombstone.fields.id.label": "00b0385c9c152888",
  "objects.sys_scim_projection_grant.fields.id.label": "00b0385c9c152888",
  "objects.sys_scim_subject.fields.id.label": "00b0385c9c152888",
  "objects.sys_scim_user.fields.id.label": "00b0385c9c152888",
  "objects.sys_secret.fields.id.label": "00b0385c9c152888",
  "objects.sys_setting.fields.scope.options.global": "5e377106508d2ecd",
  "objects.sys_setting_audit.fields.actor_id.label": "b155813f8a7f06e3",
  "objects.sys_setting_audit.fields.id.label": "00b0385c9c152888",
  "objects.sys_setting_audit.fields.scope.options.global": "5e377106508d2ecd",
  "objects.sys_setting_audit.fields.source.options.api": "4baeeff968e192d1",
  "objects.sys_setting_audit.fields.source.options.ui": "95caad102a5c97ba",
  "objects.sys_sso_provider._actions.register_saml_provider.params.identifierFormat.placeholder": "5945ff9a6b644855",
  "objects.sys_sso_provider._actions.register_sso_provider.params.mapEmail.placeholder": "66309c7adf5c9436",
  "objects.sys_sso_provider._actions.register_sso_provider.params.mapName.placeholder": "a484c34aaf624bd6",
  "objects.sys_sso_provider._actions.register_sso_provider.params.scopes.placeholder": "58ac90cde28c764d",
  "objects.sys_sso_provider.fields.id.label": "00b0385c9c152888",
  "objects.sys_view_definition.fields.id.label": "00b0385c9c152888",
};
