// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'es-ES'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 * Merge only fills gaps: correcting a source label/description does not
 * push the correction into a leaf here that already holds a translation —
 * a present-but-stale string is not a gap, so it is left as-is. Re-translate
 * it by hand when its source changes; nothing here or in `os i18n check`
 * tells a leaf a translator updated on purpose from one nobody has looked
 * at since the source moved.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const esESMetadataForms: NonNullable<TranslationData['metadataForms']> = {
  object: {
    label: "Objeto",
    sections: {
      basics: {
        label: "Aspectos básicos",
        description: "Identidad, etiquetas y taxonomía."
      },
      fields: {
        label: "Campos",
        description: "Define el modelo de datos — cada fila se convierte en una columna de la tabla de base de datos."
      },
      capabilities: {
        label: "Capacidades",
        description: "Funciones del sistema y exposición de API."
      },
      advanced: {
        label: "Avanzado",
        description: "Máquinas de estado, acciones y almacenamiento."
      }
    },
    fields: {
      name: {
        label: "Nombre",
        helpText: "Identificador único snake_case (inmutable tras la creación)"
      },
      label: {
        label: "Etiqueta",
        helpText: "Nombre mostrado en singular (p. ej. \"Account\")"
      },
      pluralLabel: {
        label: "Etiqueta plural",
        helpText: "Nombre mostrado en plural (p. ej. \"Accounts\")"
      },
      icon: {
        label: "Icono",
        helpText: "Nombre de icono Lucide (p. ej. \"building\", \"users\")"
      },
      description: {
        label: "Descripción",
        helpText: "Documentación para desarrolladores"
      },
      nameField: {
        label: "Campo de título",
        helpText: "Campo cuyo valor titula cada registro (p. ej. \"name\", \"subject\"). Puntero canónico de ADR-0079: lo leen la presentación del registro, la búsqueda de ObjectQL y las vistas previas de registros relacionados."
      },
      isSystem: {
        label: "Integrado del sistema",
        helpText: "Objeto de sistema (protegido contra eliminación; el uso compartido predeterminado es público)"
      },
      fields: {
        label: "Campos",
        helpText: "Añade las columnas que almacenará este objeto"
      },
      "fields.label": {
        label: "Etiqueta",
        helpText: "Etiqueta mostrada"
      },
      "fields.type": {
        label: "Tipo",
        helpText: "Tipo de campo"
      },
      "fields.description": {
        label: "Descripción",
        helpText: "Documentación para desarrolladores de esta columna"
      },
      "fields.required": {
        label: "Obligatorio",
        helpText: "Debe estar definido en cada registro"
      },
      "fields.unique": {
        label: "Único",
        helpText: "No permite valores duplicados"
      },
      "fields.readonly": {
        label: "Solo lectura",
        helpText: "Visible, pero nunca editable por usuarios"
      },
      "fields.hidden": {
        label: "Oculto",
        helpText: "Oculto en la UI predeterminada"
      },
      "fields.maskingRule": {
        label: "Regla de enmascaramiento",
        helpText: "Enmascaramiento parcial: preset ('phone', 'id_card', 'bank_account', 'email', 'name') o {\"keepHead\": n, \"keepTail\": m}. Enmascarado salvo que el llamante tenga los requiredPermissions del campo"
      },
      "fields.searchable": {
        label: "Buscable",
        helpText: "Incluir en búsqueda de texto completo"
      },
      "fields.sortable": {
        label: "Ordenable",
        helpText: "Permitir ordenar por esta columna"
      },
      "fields.defaultValue": {
        label: "Valor predeterminado",
        helpText: "Valor predeterminado para registros nuevos (literal JSON)"
      },
      "fields.placeholder": {
        label: "Marcador de posición",
        helpText: "Texto de ayuda que se muestra dentro del campo vacío; desaparece al introducir un valor"
      },
      "fields.maxLength": {
        label: "Longitud máxima",
        helpText: "Máximo de caracteres"
      },
      "fields.minLength": {
        label: "Longitud mínima",
        helpText: "Mínimo de caracteres"
      },
      "fields.valueDomain": {
        label: "Dominio de valores",
        helpText: "Estándar al que debe pertenecer el valor escrito; se rechaza una escritura con un valor que no pertenezca"
      },
      "fields.rows": {
        label: "Filas",
        helpText: "Altura del editor en línea (filas de texto)"
      },
      "fields.min": {
        label: "Mínimo",
        helpText: "Valor mínimo"
      },
      "fields.max": {
        label: "Máximo",
        helpText: "Valor máximo"
      },
      "fields.precision": {
        label: "Precisión",
        helpText: "Total de dígitos"
      },
      "fields.scale": {
        label: "Decimales",
        helpText: "Decimales"
      },
      "fields.options": {
        label: "Opciones",
        helpText: "Opciones disponibles"
      },
      "fields.options.label": {
        label: "Etiqueta"
      },
      "fields.options.value": {
        label: "Valor"
      },
      "fields.options.color": {
        label: "Color de opción"
      },
      "fields.options.description": {
        label: "Descripción"
      },
      "fields.reference": {
        label: "Referencia",
        helpText: "Nombre del objeto de destino. En un campo tree es opcional y, si se indica, debe ser este mismo objeto (un árbol es una jerarquía dentro de su propio objeto — para enlazar con otro objeto, usa un lookup)"
      },
      "fields.lookupFilters": {
        label: "Filtros de lookup",
        helpText: "Reglas de filtro aplicadas al selector ({field, operator, value})"
      },
      "fields.deleteBehavior": {
        label: "Comportamiento al eliminar",
        helpText: "Qué ocurre cuando se elimina el registro referenciado"
      },
      "fields.multiple": {
        label: "Selección múltiple",
        helpText: "Permitir seleccionar varios registros"
      },
      "fields.expression": {
        label: "Expresión",
        helpText: "Expresión de fórmula CEL"
      },
      "fields.returnType": {
        label: "Tipo de retorno",
        helpText: "Tipo de resultado para fórmulas"
      },
      "fields.summaryOperations": {
        label: "Operaciones de resumen",
        helpText: "Roll-up: qué objeto hijo, qué campo y qué agregación"
      },
      "fields.summaryOperations.object": {
        label: "Objeto",
        helpText: "Nombre del objeto hijo de origen"
      },
      "fields.summaryOperations.field": {
        label: "Campo",
        helpText: "Campo del objeto hijo que se agrega (se ignora para count)"
      },
      "fields.summaryOperations.function": {
        label: "Función",
        helpText: "Función de agregación"
      },
      "fields.autonumberFormat": {
        label: "Formato de autonumeración",
        helpText: "p. ej. \"INV-{0000}\"; admite tokens de fecha {YYYY}/{MM}/{DD} e interpolación de {field_name}"
      },
      "fields.language": {
        label: "Idioma",
        helpText: "Lenguaje del editor (p. ej. sql, javascript)"
      },
      "fields.trackHistory": {
        label: "Seguimiento de historial",
        helpText: "Resume este campo en la cronología de actividad del registro"
      },
      "fields.visibleWhen": {
        label: "Condición de visibilidad",
        helpText: "Predicado CEL: el campo solo se muestra cuando es TRUE"
      },
      "fields.readonlyWhen": {
        label: "Condición de solo lectura",
        helpText: "Predicado CEL: el campo es de solo lectura cuando es TRUE (aplicado en el servidor)"
      },
      "fields.requiredWhen": {
        label: "Condición de obligatoriedad",
        helpText: "Predicado CEL: el campo es obligatorio cuando es TRUE (aplicado en el servidor)"
      },
      enable: {
        label: "Habilitar",
        helpText: "Activa/desactiva funciones del sistema"
      },
      "enable.trackHistory": {
        label: "Seguimiento de historial"
      },
      "enable.searchable": {
        label: "Buscable"
      },
      "enable.apiEnabled": {
        label: "API habilitada"
      },
      "enable.files": {
        label: "Archivos"
      },
      "enable.feeds": {
        label: "Publicaciones"
      },
      "enable.activities": {
        label: "Actividades"
      },
      "enable.clone": {
        label: "Clonación"
      },
      validations: {
        label: "Validaciones",
        helpText: "Reglas de validación a nivel de objeto — un array de objetos de regla, p. ej. [{ \"type\": \"script\", \"name\": \"amount_positive\", \"condition\": \"amount > 0\", \"message\": \"Amount must be positive\" }]. Las tablas de transición de máquinas de estado también se declaran aquí (ADR-0020)"
      },
      datasource: {
        label: "Fuente de datos",
        helpText: "ID de fuente de datos de destino (valor predeterminado: \"default\")"
      },
      ownership: {
        label: "Propiedad",
        helpText: "Modelo de propiedad del registro. Si se omite, se resuelve como user."
      },
      sharingModel: {
        label: "Modelo de uso compartido",
        helpText: "Visibilidad predeterminada de la organización (OWD) para usuarios internos. Un objeto personalizado que lo omita se resuelve como private en tiempo de ejecución (ADR-0090 D1)."
      },
      managedBy: {
        label: "Gestionado por",
        helpText: "Categoría de ciclo de vida: platform (CRUD de usuario), config (escrito por el administrador), system-data (esquema definido por la plataforma con datos escribibles por administrador o usuario), engine-owned (sin escrituras de usuario), append-only (auditoría), better-auth (identidad). Los clientes de UI derivan de aquí las acciones CRUD disponibles, así que decide qué se ofrece al usuario en los registros de este objeto."
      },
      editMode: {
        label: "Modo de edición",
        helpText: "Intención de interacción al editar registros de este objeto. Si se omite, el renderizador elige su propio valor predeterminado. Es una intención entre renderizadores, no un estilo."
      },
      fileAccessDelegate: {
        label: "Delegado de acceso a archivos",
        helpText: "Servicio del kernel que autoriza la descarga de archivos pertenecientes a los campos multimedia de este objeto, en lugar de comprobar si quien llama puede leer la fila propietaria. Para objetos cuyo acceso media un servicio. Falla cerrado."
      },
      lifecycle: {
        label: "Ciclo de vida de los datos",
        helpText: "Contrato de ciclo de vida de los datos (ADR-0057): cuánto viven las filas y cómo se recupera el espacio. Déjalo en blanco para una semántica record permanente. Las clases distintas de record requieren al menos una política acotante (retención, TTL o rotación)."
      },
      "lifecycle.class": {
        label: "Clase de ciclo de vida",
        helpText: "Contrato de persistencia de las filas de este objeto"
      },
      "lifecycle.retention": {
        label: "Retención",
        helpText: "Ventana de retención basada en la antigüedad de las filas"
      },
      "lifecycle.retention.maxAge": {
        label: "Antigüedad máxima",
        helpText: "Las filas más antiguas que este valor (según created_at) se eliminan. Literal de duración: h/d/w/y, p. ej. \"30d\""
      },
      "lifecycle.ttl": {
        label: "Caducidad por TTL",
        helpText: "Caducidad por TTL de cada fila"
      },
      "lifecycle.ttl.field": {
        label: "Campo de marca temporal",
        helpText: "Campo de marca temporal desde el que se mide el TTL (p. ej. expires_at)"
      },
      "lifecycle.ttl.expireAfter": {
        label: "Plazo de caducidad",
        helpText: "Las filas caducan este tiempo después del campo, p. ej. \"1d\""
      },
      "lifecycle.storage": {
        label: "Almacenamiento",
        helpText: "Rotación física para telemetría de alta frecuencia (SQLite: DROP de fragmento en O(1))"
      },
      "lifecycle.storage.strategy": {
        label: "Estrategia",
        helpText: "Estrategia de almacenamiento"
      },
      "lifecycle.storage.shards": {
        label: "Número de fragmentos",
        helpText: "Número de fragmentos que se conservan; ventana total = fragmentos × unidad"
      },
      "lifecycle.storage.unit": {
        label: "Unidad de fragmento",
        helpText: "Amplitud temporal de un fragmento"
      },
      "lifecycle.archive": {
        label: "Archivado",
        helpText: "Traspaso al almacenamiento en frío (clase audit). Las filas nunca se eliminan en caliente antes de que la copia de archivado haya finalizado correctamente."
      },
      "lifecycle.archive.after": {
        label: "Antigüedad de archivado",
        helpText: "Archiva las filas más antiguas que este valor — debe coincidir con retention.maxAge"
      },
      "lifecycle.archive.to": {
        label: "Fuente de datos de archivado",
        helpText: "Nombre de la fuente de datos de destino para el almacenamiento en frío"
      },
      "lifecycle.archive.keep": {
        label: "Retención en archivado",
        helpText: "Cuánto tiempo conserva las filas el archivado (en blanco = para siempre), p. ej. \"7y\""
      },
      "lifecycle.reclaim": {
        label: "Recuperación de espacio",
        helpText: "Recupera el espacio del driver después de los barridos (activado de forma predeterminada en las clases distintas de record)"
      }
    }
  },
  field: {
    label: "Campo",
    sections: {
      basics: {
        label: "Aspectos básicos",
        description: "Identidad y restricciones básicas del campo."
      },
      configuration: {
        label: "Configuración",
        description: "Ajustes específicos del tipo de campo (los bloques visibles dependen del tipo elegido)."
      },
      formula: {
        label: "Fórmula y calculado",
        description: "Valores calculados y resúmenes roll-up."
      },
      advanced: {
        label: "Avanzado",
        description: "Ajustes de base de datos, UI, auditoría y seguridad."
      }
    },
    fields: {
      name: {
        label: "Nombre",
        helpText: "Identificador único (snake_case, inmutable tras la creación)"
      },
      label: {
        label: "Etiqueta",
        helpText: "Nombre mostrado a los usuarios"
      },
      type: {
        label: "Tipo",
        helpText: "Tipo de datos de este campo"
      },
      group: {
        label: "Grupo",
        helpText: "Nombre de grupo para el diseño del formulario"
      },
      description: {
        label: "Descripción",
        helpText: "Texto de ayuda mostrado a los usuarios"
      },
      required: {
        label: "Obligatorio",
        helpText: "El usuario debe proporcionar un valor"
      },
      unique: {
        label: "Único",
        helpText: "No puede haber dos registros con el mismo valor"
      },
      multiple: {
        label: "Selección múltiple",
        helpText: "Permite varios valores (para select/lookup)"
      },
      defaultValue: {
        label: "Valor predeterminado",
        helpText: "Valor predeterminado para registros nuevos"
      },
      placeholder: {
        label: "Marcador de posición",
        helpText: "Texto de ayuda que se muestra dentro del campo vacío (desaparece al introducir un valor); usa inlineHelpText para ayuda siempre visible"
      },
      inlineHelpText: {
        label: "Texto de ayuda fijo",
        helpText: "Ayuda siempre visible bajo el campo, a diferencia de `placeholder`, que desaparece en cuanto se escribe un valor."
      },
      minLength: {
        label: "Longitud mínima",
        helpText: "Longitud mínima de caracteres"
      },
      maxLength: {
        label: "Longitud máxima",
        helpText: "Longitud máxima de caracteres"
      },
      valueDomain: {
        label: "Dominio de valores",
        helpText: "Estándar al que debe pertenecer el valor escrito: iana_time_zone, iso_4217_currency o iso_3166_alpha2; se rechaza una escritura con un valor que no pertenezca"
      },
      rows: {
        label: "Filas",
        helpText: "Altura del editor en línea, en filas de texto"
      },
      min: {
        label: "Mínimo",
        helpText: "Valor mínimo"
      },
      max: {
        label: "Máximo",
        helpText: "Valor máximo"
      },
      precision: {
        label: "Precisión",
        helpText: "Decimales (p. ej., 2 para $10.50)"
      },
      scale: {
        label: "Decimales",
        helpText: "Número de dígitos decimales"
      },
      step: {
        label: "Incremento",
        helpText: "Incremento del control deslizante (1 por defecto). Solo lo usa el renderizador: la ruta de escritura no rechaza un valor fuera de la cuadrícula."
      },
      maxSize: {
        label: "Tamaño máximo",
        helpText: "Tamaño máximo permitido en BYTES (entero positivo). Se aplica en el servidor al escribir, contra el tamaño registrado del archivo; un archivo sin tamaño registrado no puede incumplirlo."
      },
      dimensions: {
        label: "Dimensiones",
        helpText: "Dimensionalidad del vector: un entero entre 1 y 10000 (p. ej. 1536 para los embeddings de OpenAI)."
      },
      language: {
        label: "Lenguaje",
        helpText: "Lenguaje del editor para el resaltado de sintaxis (p. ej. javascript, python, sql)."
      },
      autonumberFormat: {
        label: "Formato de numeración",
        helpText: "Texto literal más un contador {0000}, tokens de fecha {YYYY}/{MM}/{DD}/{YYYYMMDD} en la zona horaria del negocio e interpolación {field_name}. El contador se reinicia por cada prefijo generado. Si se omite en un campo autonumber, el valor predeterminado es {0000}."
      },
      referenceVia: {
        label: "Referencia mediante",
        helpText: "Convierte este campo de texto en la mitad de id de un puntero polimórfico: nombra el campo HERMANO del mismo objeto que guarda, fila a fila, el nombre del objeto destino (ADR-0052 §5). En snake_case; solo campos de texto y excluyente con `reference`."
      },
      options: {
        label: "Opciones",
        helpText: "Opciones disponibles (pares label/value)"
      },
      "options.label": {
        label: "Etiqueta"
      },
      "options.value": {
        label: "Valor"
      },
      "options.description": {
        label: "Descripción"
      },
      "options.color": {
        label: "Color de opción"
      },
      "options.default": {
        label: "Opción predeterminada"
      },
      "options.visibleWhen": {
        label: "Condición de visibilidad"
      },
      reference: {
        label: "Referencia",
        helpText: "Nombre del objeto referenciado"
      },
      deleteBehavior: {
        label: "Comportamiento al eliminar",
        helpText: "Qué ocurre cuando se elimina el registro referenciado"
      },
      relatedListFilter: {
        label: "Filtro de lista relacionada",
        helpText: "Filtro predeterminado para la lista relacionada de esta relación en la página de detalle del registro padre: combinado con AND con la coincidencia del registro padre, y el distintivo de la pestaña cuenta el mismo conjunto"
      },
      displayField: {
        label: "Campo mostrado",
        helpText: "Campo que se muestra como etiqueta de cada candidato en el selector. Si se omite, se usa el campo de título del objeto referenciado."
      },
      descriptionField: {
        label: "Campo de descripción",
        helpText: "Campo secundario que se muestra bajo la etiqueta en el menú emergente de selección rápida."
      },
      allowCreate: {
        label: "Permitir crear",
        helpText: "Permite crear un registro a partir del texto escrito cuando el selector no encuentra coincidencias. Recomendado para objetos cuyo único campo obligatorio es el campo mostrado."
      },
      lookupPageSize: {
        label: "Filas por página",
        helpText: "Filas por página en el diálogo del selector de registros: un entero positivo; 10 por defecto."
      },
      relatedListTitle: {
        label: "Título de la lista relacionada",
        helpText: "Título de la lista relacionada de esta relación en la página de detalle del registro padre."
      },
      inlineTitle: {
        label: "Título en línea",
        helpText: "Título de la cuadrícula maestro-detalle incrustada en el registro padre."
      },
      inlineAmountField: {
        label: "Campo de importe en línea",
        helpText: "Campo numérico del objeto hijo que se suma para el total de la cuadrícula en línea."
      },
      expression: {
        label: "Expresión",
        helpText: "Expresión CEL para calcular este campo (lo hace de solo lectura)"
      },
      returnType: {
        label: "Tipo de retorno",
        helpText: "Tipo de valor declarado de la fórmula, registrado a partir del tipo CEL inferido. Los consumidores lo leen en vez de volver a analizar la expresión."
      },
      summaryOperations: {
        label: "Operaciones de resumen",
        helpText: "Configuración de resumen roll-up (para relaciones padre-hijo)"
      },
      "summaryOperations.object": {
        label: "Objeto",
        helpText: "Objeto hijo que se agrega"
      },
      "summaryOperations.function": {
        label: "Función",
        helpText: "Función de agregación"
      },
      "summaryOperations.field": {
        label: "Campo",
        helpText: "Campo del objeto hijo que se agrega (se ignora para count)"
      },
      "summaryOperations.relationshipField": {
        label: "Campo de relación",
        helpText: "Clave foránea del hijo que apunta de vuelta a este padre (se detecta automáticamente si se omite)"
      },
      "summaryOperations.filter": {
        label: "Filtro",
        helpText: "Solo se agregan las filas hijas que coinciden con este predicado (p. ej. status == received)"
      },
      externalId: {
        label: "ID externo",
        helpText: "Marca como ID externo para operaciones upsert"
      },
      readonly: {
        label: "Solo lectura",
        helpText: "El campo es de solo lectura en formularios"
      },
      hidden: {
        label: "Oculto",
        helpText: "Oculta el campo en las vistas UI predeterminadas"
      },
      searchable: {
        label: "Buscable",
        helpText: "Incluye en los resultados de búsqueda global"
      },
      sortable: {
        label: "Ordenable",
        helpText: "Permite ordenar listas por este campo"
      },
      maskingRule: {
        label: "Regla de enmascaramiento",
        helpText: "Enmascaramiento parcial: preset ('phone', 'id_card', 'bank_account', 'email', 'name') o {\"keepHead\": n, \"keepTail\": m}. Enmascarado salvo que el llamante tenga los requiredPermissions del campo"
      },
      internal: {
        label: "Interno",
        helpText: "Nunca devuelve el valor de este campo por la ruta de datos genérica: el motor omite la clave en los resultados de find/findOne y en los cuerpos de respuesta de creación y actualización, tanto en la proyección predeterminada como cuando un cliente la nombra en ?select=. El almacenamiento, el filtrado y los índices no se ven afectados."
      },
      trackHistory: {
        label: "Registrar historial",
        helpText: "Muestra los cambios de valor de este campo como entradas en la línea de actividad del registro (ADR-0052 §5b). Se activa campo a campo."
      },
      widget: {
        label: "Control del campo",
        helpText: "Sustituye el control del formulario: nombra un componente de campo registrado, que se resuelve como `field:` más este nombre, para dibujar el campo en lugar del control derivado del type. Un nombre no registrado vuelve al control del type."
      },
      ackPlaintextMasking: {
        label: "Confirmar texto sin cifrar",
        helpText: "Confirma que el contrato de este campo password genérico — texto sin cifrar en reposo y enmascarado al leer — es intencionado, y silencia la advertencia de autoría (ADR-0100). No afecta a ningún otro tipo."
      }
    }
  },
  hook: {
    label: "Gancho",
    sections: {
      identity: {
        label: "Identidad",
        description: "Qué es este hook y cuándo se dispara."
      },
      body: {
        label: "Cuerpo",
        description: "Expresión en línea o JavaScript en sandbox ejecutado cuando se dispara el hook."
      },
      legacy_handler: {
        label: "Manejador heredado",
        description: "Referencia de nombre de función — obsoleta en favor de body."
      },
      execution: {
        label: "Ejecución"
      }
    },
    fields: {
      name: {
        label: "Nombre",
        helpText: "Identificador snake_case (inmutable tras la creación)"
      },
      label: {
        label: "Etiqueta"
      },
      description: {
        label: "Descripción"
      },
      object: {
        label: "Objeto",
        helpText: "Nombre del objeto de destino (o \"*\" para global)"
      },
      events: {
        label: "Eventos",
        helpText: "Eventos de ciclo de vida (p. ej. beforeInsert, afterUpdate)"
      },
      priority: {
        label: "Prioridad",
        helpText: "Los números menores se ejecutan primero"
      },
      body: {
        label: "Cuerpo",
        helpText: "Una expresión L1 o un body JS L2 en sandbox"
      },
      "body.language": {
        label: "Idioma",
        helpText: "expression = fórmula pura; js = JavaScript en sandbox"
      },
      "body.source": {
        label: "Código fuente",
        helpText: "Código fuente del body de la función — sin imports de nivel superior"
      },
      "body.capabilities": {
        label: "Capacidades",
        helpText: "API ctx permitidas (api.read, api.write, crypto.uuid, log, …)"
      },
      "body.timeoutMs": {
        label: "Tiempo de espera (ms)",
        helpText: "Tiempo de espera por invocación (ms)"
      },
      "body.memoryMb": {
        label: "Memoria (MB)",
        helpText: "Límite de memoria por invocación (MB, máx. 256)"
      },
      handler: {
        label: "Manejador",
        helpText: "Nombre de función manejadora (obsoleto — preferir `body`)"
      },
      async: {
        label: "Asíncrono",
        helpText: "Ejecutar en segundo plano, sin bloquear la transacción"
      },
      onError: {
        label: "Al error"
      },
      timeoutMs: {
        label: "Tiempo de espera (ms)",
        helpText: "Abortar el hook después de N milisegundos"
      },
      runAs: {
        label: "Ejecutar como",
        helpText: "Identidad de las operaciones de datos de ctx.api: inherit hereda el contexto de la escritura que lo disparó (predeterminado), system eleva, user lo fija al usuario que lo disparó"
      },
      condition: {
        label: "Condición",
        helpText: "Fórmula opcional — omite el hook cuando evalúa a false"
      },
      retryPolicy: {
        label: "Política de reintentos",
        helpText: "Reintentar al fallar — especialmente útil para hooks asíncronos"
      },
      "retryPolicy.maxRetries": {
        label: "Reintentos máximos",
        helpText: "Número máximo de reintentos"
      },
      "retryPolicy.backoffMs": {
        label: "Retroceso (ms)",
        helpText: "Retraso entre reintentos (ms)"
      }
    }
  },
  seed: {
    label: "Datos semilla",
    description: "Datos predefinidos / de inicialización aplicados al publicar"
  },
  mapping: {
    label: "Mapeo de importación",
    description: "Mapeo de campos de importación/exportación reutilizable (renombrado + transformaciones), referenciado por nombre al importar"
  },
  view: {
    label: "Vista",
    sections: {
      basics: {
        label: "Aspectos básicos",
        description: "Identidad y superficie principal."
      },
      columns_filters: {
        label: "Columnas y filtros",
        description: "Qué filas se muestran y cómo las filtran los usuarios."
      },
      table_options: {
        label: "Opciones de tabla",
        description: "Opciones de visualización solo de cuadrícula."
      },
      kanban: {
        label: "Tablero Kanban",
        description: "Configuración de tablero específica de Kanban."
      },
      calendar: {
        label: "Calendario",
        description: "Configuración específica de calendario."
      },
      gantt: {
        label: "Diagrama de Gantt",
        description: "Configuración específica de Gantt."
      },
      gallery: {
        label: "Galería",
        description: "Configuración específica de galería."
      },
      timeline: {
        label: "Cronología",
        description: "Configuración específica de cronología."
      },
      chart: {
        label: "Gráfico",
        description: "Configuración específica de gráfico."
      },
      end_user_controls: {
        label: "Controles de usuario final",
        description: "Lo que los usuarios finales pueden hacer en esta vista: filtros rápidos, pestañas de filtro, cambio de visualización (ADR-0047, paridad con Airtable Interface)."
      },
      navigation_sharing: {
        label: "Navegación y uso compartido",
        description: "Dónde aparece esta vista y quién puede verla."
      }
    },
    fields: {
      name: {
        label: "Nombre",
        helpText: "snake_case, único por environment"
      },
      label: {
        label: "Etiqueta"
      },
      description: {
        label: "Descripción"
      },
      type: {
        label: "Tipo",
        helpText: "Superficie principal de la vista"
      },
      data: {
        label: "Datos",
        helpText: "Fuente de datos — p. ej. {\"provider\":\"object\",\"object\":\"task\"}"
      },
      columns: {
        label: "Columnas",
        helpText: "Columnas que mostrar (nombres de campo del objeto seleccionado)"
      },
      filter: {
        label: "Filtro",
        helpText: "Condiciones de filtro — el mismo constructor visual que la barra de herramientas de la lista, con operadores y entradas de valor según el tipo de campo"
      },
      sort: {
        label: "Orden",
        helpText: "Orden predeterminado"
      },
      searchableFields: {
        label: "Campos buscables",
        helpText: "Nombres de campo disponibles para búsqueda rápida"
      },
      filterableFields: {
        label: "Campos filtrables",
        helpText: "Nombres de campo disponibles para filtrado"
      },
      resizable: {
        label: "Redimensionable"
      },
      compactToolbar: {
        label: "Barra compacta"
      },
      rowHeight: {
        label: "Altura de fila"
      },
      selection: {
        label: "Selección"
      },
      pagination: {
        label: "Paginación"
      },
      kanban: {
        label: "Configuración Kanban"
      },
      calendar: {
        label: "Calendario"
      },
      gantt: {
        label: "Configuración Gantt"
      },
      gallery: {
        label: "Galería"
      },
      timeline: {
        label: "Cronología"
      },
      chart: {
        label: "Gráfico"
      },
      userFilters: {
        label: "Filtros de usuario",
        helpText: "Barra de filtros rápidos: estilo de elemento (dropdown / tabs / toggle) + campos expuestos o preajustes de pestañas"
      },
      tabs: {
        label: "Pestañas",
        helpText: "Pestañas de filtro en la vista: cada pestaña aplica sus propias reglas de filtro"
      },
      appearance: {
        label: "Apariencia",
        helpText: "allowedVisualizations: qué renderizadores pueden alternar los usuarios"
      },
      userActions: {
        label: "Acciones de usuario",
        helpText: "Conmutadores de la barra de herramientas: ordenar / buscar / filtrar / altura de fila"
      },
      addRecord: {
        label: "Agregar registro"
      },
      showRecordCount: {
        label: "Mostrar recuento de registros"
      },
      navigation: {
        label: "Navegación"
      },
      sharing: {
        label: "Compartición"
      }
    }
  },
  page: {
    label: "Página",
    sections: {
      basics: {
        label: "Aspectos básicos",
        description: "Identidad y plantilla de página."
      },
      data_context: {
        label: "Contexto de datos",
        description: "Vinculación de registros y estado local de página."
      },
      layout: {
        label: "Diseño",
        description: "Regiones de página y componentes colocados en ellas."
      },
      interface: {
        label: "Interface (páginas de lista)",
        description: "Modo Interface (paridad con Airtable): la página define directamente su propia superficie de datos — columnas, filtros, visualizaciones y barra de herramientas — sin heredar de una vista aparte."
      },
      advanced: {
        label: "Avanzado",
        description: "Activación, audiencia y accesibilidad."
      }
    },
    fields: {
      name: {
        label: "Nombre",
        helpText: "Identificador único (snake_case)"
      },
      label: {
        label: "Etiqueta",
        helpText: "Título de página mostrado a los usuarios"
      },
      icon: {
        label: "Icono",
        helpText: "Icono para el menú de navegación"
      },
      type: {
        label: "Tipo",
        helpText: "Tipo de página. \"List / Interface\" vincula una vista de origen a una superficie curada — cómo se ve (grid / kanban / calendar / …) es una visualización configurada en Interface, no un tipo de página."
      },
      template: {
        label: "Plantilla",
        helpText: "Plantilla de diseño (p. ej., \"header-sidebar-main\")"
      },
      description: {
        label: "Descripción",
        helpText: "Descripción de página para navegación"
      },
      source: {
        label: "Código fuente",
        helpText: "Texto fuente de la página. Con kind 'html' (alias 'jsx') es JSX restringido que se compila al árbol de componentes al guardar: se analiza, nunca se ejecuta. Con kind 'react' es React real que el runtime de confianza ejecuta al renderizar."
      },
      object: {
        label: "Objeto",
        helpText: "Objeto vinculado (para páginas Record)"
      },
      variables: {
        label: "Variables de página",
        helpText: "Variables de estado local de página"
      },
      "variables.name": {
        label: "Nombre",
        helpText: "Nombre de la variable — expuesta en expresiones como `page.<name>`"
      },
      "variables.type": {
        label: "Tipo",
        helpText: "Tipo de valor"
      },
      "variables.defaultValue": {
        label: "Valor predeterminado",
        helpText: "Valor inicial (por defecto, un valor vacío según el tipo)"
      },
      "variables.source": {
        label: "Escrito por",
        helpText: "Componente (por id) que escribe esta variable — p. ej. un element:record_picker"
      },
      regions: {
        label: "Regiones",
        helpText: "Regiones de diseño (header, main, sidebar, footer) con componentes"
      },
      "regions.name": {
        label: "Región"
      },
      "regions.width": {
        label: "Ancho"
      },
      "regions.components": {
        label: "Componentes"
      },
      interfaceConfig: {
        label: "Configuración de Interface",
        helpText: "La página ES la vista: source elige el objeto, columns/filterBy se definen directamente aquí; appearance.allowedVisualizations restringe los renderizadores (una sola entrada = bloqueado); userActions conmuta la barra de herramientas."
      },
      "interfaceConfig.source": {
        label: "Origen de datos",
        helpText: "Objeto del que lee esta página"
      },
      "interfaceConfig.columns": {
        label: "Columnas",
        helpText: "Columnas que mostrar — definidas directamente en la página (en blanco = todos los campos del objeto)"
      },
      "interfaceConfig.filterBy": {
        label: "Filtrar por",
        helpText: "Filtro base siempre activo para la página — el mismo constructor visual que la barra de herramientas de la lista."
      },
      "interfaceConfig.sort": {
        label: "Orden",
        helpText: "Orden predeterminado de la página, definido directamente en la página."
      },
      "interfaceConfig.sort.field": {
        label: "Campo"
      },
      "interfaceConfig.sort.order": {
        label: "Dirección"
      },
      "interfaceConfig.levels": {
        label: "Niveles",
        helpText: "Niveles de jerarquía que mostrar (orígenes de tipo árbol)"
      },
      "interfaceConfig.appearance": {
        label: "Apariencia",
        helpText: "Visualizaciones permitidas (Grid / Kanban / Calendar / …) y visibilidad de la descripción"
      },
      "interfaceConfig.userFilters": {
        label: "Filtros de usuario",
        helpText: "Barra de filtros para el usuario final: None (sin barra) / Tabs (preajustes con nombre) / Dropdown (por campo). None elimina la configuración."
      },
      "interfaceConfig.userActions": {
        label: "Acciones de usuario",
        helpText: "Conmutadores de la barra de herramientas (buscar, ordenar, filtrar, altura de fila)"
      },
      "interfaceConfig.addRecord": {
        label: "Agregar registro",
        helpText: "Punto de entrada para agregar registros"
      },
      "interfaceConfig.buttons": {
        label: "Botones",
        helpText: "Botones de la barra de herramientas — elige entre las acciones de este objeto"
      },
      "interfaceConfig.recordAction": {
        label: "Acción de registro",
        helpText: "Cómo se abre el detalle al hacer clic en un registro"
      },
      "interfaceConfig.showRecordCount": {
        label: "Mostrar recuento de registros",
        helpText: "Mostrar la barra de recuento de registros"
      },
      "interfaceConfig.allowPrinting": {
        label: "Permitir impresión",
        helpText: "Permitir que los usuarios impriman esta página"
      },
      isDefault: {
        label: "Predeterminado",
        helpText: "Establece como página predeterminada para este tipo de página"
      },
      kind: {
        label: "Modo",
        helpText: "Modo de anulación de página: full o slotted (para páginas record)"
      },
      aria: {
        label: "Accesibilidad",
        helpText: "Atributos de accesibilidad (etiquetas ARIA, roles)"
      }
    }
  },
  dashboard: {
    label: "Panel",
    sections: {
      basics: {
        label: "Aspectos básicos",
        description: "Identidad y descripción del panel."
      },
      layout: {
        label: "Diseño",
        description: "Tamaño de cuadrícula y cadencia de actualización."
      },
      widgets: {
        label: "Widgets del panel",
        description: "Tarjetas y gráficos colocados en la cuadrícula."
      },
      filters: {
        label: "Filtros",
        description: "Filtros predeterminados y globales aplicados a todos los widgets."
      },
      advanced: {
        label: "Avanzado",
        description: "Ajustes de accesibilidad y rendimiento."
      }
    },
    fields: {
      name: {
        label: "Nombre",
        helpText: "Identificador único snake_case"
      },
      label: {
        label: "Etiqueta",
        helpText: "Nombre mostrado"
      },
      description: {
        label: "Descripción"
      },
      columns: {
        label: "Columnas",
        helpText: "Columnas de cuadrícula (predeterminado 12)"
      },
      gap: {
        label: "Separación",
        helpText: "Espacio entre widgets, en incrementos de 0.25rem (4 = 1rem)"
      },
      refreshIntervalSeconds: {
        label: "Intervalo de actualización",
        helpText: "Actualización automática (segundos)"
      },
      header: {
        label: "Encabezado",
        helpText: "Configuración de cabecera del panel (title, subtitle, actions)"
      },
      "header.showTitle": {
        label: "Mostrar título",
        helpText: "Mostrar el título del panel en la cabecera"
      },
      "header.showDescription": {
        label: "Mostrar descripción",
        helpText: "Mostrar la descripción del panel en la cabecera"
      },
      "header.actions": {
        label: "Botones de acción",
        helpText: "Botones de acción mostrados en la cabecera"
      },
      "header.actions.label": {
        label: "Etiqueta"
      },
      "header.actions.actionUrl": {
        label: "URL de la acción"
      },
      "header.actions.actionType": {
        label: "Tipo de acción"
      },
      "header.actions.icon": {
        label: "Icono"
      },
      widgets: {
        label: "Widgets del panel",
        helpText: "Widgets del panel con posición y tamaño"
      },
      "widgets.id": {
        label: "ID del widget"
      },
      "widgets.title": {
        label: "Título"
      },
      "widgets.description": {
        label: "Descripción"
      },
      "widgets.type": {
        label: "Tipo de visualización"
      },
      "widgets.chartConfig": {
        label: "Configuración del gráfico"
      },
      "widgets.colorVariant": {
        label: "Variante de color"
      },
      "widgets.requiresObject": {
        label: "Requiere objeto"
      },
      "widgets.requiresService": {
        label: "Requiere servicio"
      },
      "widgets.filter": {
        label: "Filtro"
      },
      "widgets.compareTo": {
        label: "Comparar con"
      },
      "widgets.dataset": {
        label: "Conjunto de datos"
      },
      "widgets.dimensions": {
        label: "Dimensiones"
      },
      "widgets.values": {
        label: "Medidas"
      },
      "widgets.layout": {
        label: "Diseño"
      },
      "widgets.options": {
        label: "Opciones"
      },
      "widgets.filterBindings": {
        label: "Vínculos de filtro"
      },
      "widgets.suppressWarnings": {
        label: "Advertencias suprimidas"
      },
      dateRange: {
        label: "Rango de fechas",
        helpText: "Selector predeterminado de intervalo de fechas"
      },
      globalFilters: {
        label: "Filtros globales",
        helpText: "Filtros aplicados a todos los widgets"
      },
      "globalFilters.name": {
        label: "Nombre"
      },
      "globalFilters.field": {
        label: "Campo"
      },
      "globalFilters.object": {
        label: "Objeto"
      },
      "globalFilters.label": {
        label: "Etiqueta"
      },
      "globalFilters.type": {
        label: "Tipo de entrada"
      },
      "globalFilters.options": {
        label: "Opciones"
      },
      "globalFilters.optionsFrom": {
        label: "Origen de las opciones"
      },
      "globalFilters.defaultValue": {
        label: "Valor predeterminado"
      },
      "globalFilters.scope": {
        label: "Ámbito"
      },
      "globalFilters.targetWidgets": {
        label: "Widgets de destino"
      }
    }
  },
  app: {
    label: "Aplicación",
    sections: {
      basics: {
        label: "Aspectos básicos",
        description: "Identidad y activación de la app."
      },
      navigation: {
        label: "Navegación",
        description: "Elementos de barra lateral y agrupación de áreas."
      },
      content: {
        label: "Contenido",
        description: "Asignación del asistente ambiental. Los objetos y endpoints se declaran en el stack, no en la app."
      },
      branding: {
        label: "Marca",
        description: "Colores de tema y logotipo."
      },
      access_and_sharing: {
        label: "Acceso y uso compartido",
        description: "Quién puede acceder a esta app. El acceso público y la incrustación son por vista de formulario, no a nivel de app."
      }
    },
    fields: {
      name: {
        label: "Nombre",
        helpText: "snake_case, único"
      },
      label: {
        label: "Etiqueta"
      },
      description: {
        label: "Descripción"
      },
      icon: {
        label: "Icono",
        helpText: "Nombre de icono Lucide (p. ej. \"users\", \"briefcase\")"
      },
      active: {
        label: "Activo"
      },
      isDefault: {
        label: "Predeterminado",
        helpText: "Convierte esta app en la predeterminada para usuarios nuevos"
      },
      hidden: {
        label: "Oculta",
        helpText: "Mantiene la aplicación fuera del conmutador de aplicaciones: el shell la ofrece desde el menú del avatar. Solo afecta a la navegación: una aplicación oculta sigue siendo enrutable y con permisos comprobados."
      },
      navigation: {
        label: "Navegación",
        helpText: "Árbol de navegación — estructura recursiva"
      },
      areas: {
        label: "Áreas",
        helpText: "Agrupa elementos en áreas plegables"
      },
      "areas.id": {
        label: "ID de área"
      },
      "areas.label": {
        label: "Etiqueta"
      },
      "areas.icon": {
        label: "Icono"
      },
      "areas.description": {
        label: "Descripción"
      },
      "areas.navigation": {
        label: "Navegación"
      },
      defaultAgent: {
        label: "Agente predeterminado",
        helpText: "Agente de IA para el botón de asistente ambiental"
      },
      branding: {
        label: "Marca",
        helpText: "Colores primario/secundario, logotipo, tema"
      },
      requiredPermissions: {
        label: "Permisos requeridos",
        helpText: "Permisos necesarios para acceder a esta app"
      }
    }
  },
  action: {
    label: "Acción",
    sections: {
      basics: {
        label: "Aspectos básicos",
        description: "Identidad y presentación de la acción."
      },
      behavior: {
        label: "Comportamiento",
        description: "Configura qué ocurre cuando se dispara la acción."
      },
      placement: {
        label: "Ubicación",
        description: "Dónde y cuándo aparece el botón de acción."
      },
      advanced: {
        label: "Avanzado",
        description: "Exposición a IA y forma de la solicitud API."
      }
    },
    fields: {
      name: {
        label: "Nombre",
        helpText: "Identificador único (snake_case)"
      },
      label: {
        label: "Etiqueta",
        helpText: "Texto de botón mostrado a los usuarios"
      },
      objectName: {
        label: "Nombre de objeto",
        helpText: "Objeto al que pertenece esta acción (opcional)"
      },
      icon: {
        label: "Icono",
        helpText: "Nombre de icono Lucide (p. ej., \"check\", \"x-circle\")"
      },
      type: {
        label: "Tipo",
        helpText: "Qué ocurre al hacer clic"
      },
      variant: {
        label: "Variante visual",
        helpText: "Estilo de botón (primary=blue, danger=red, ghost=transparent)"
      },
      mode: {
        label: "Modo",
        helpText: "Modo semántico de la acción. Hoy solo lo lee la heurística de intervención humana de la IA; ningún renderizador se ramifica por él."
      },
      order: {
        label: "Orden",
        helpText: "Orden dentro de un grupo de ubicación: cuanto menor, más arriba, y la cabecera del registro toma la primera como botón principal. Sin valor se mantiene el orden de registro."
      },
      target: {
        label: "Destino",
        helpText: "URL, nombre de flujo o endpoint API que llamar"
      },
      method: {
        label: "Método",
        helpText: "Método HTTP (GET, POST, PUT, DELETE)"
      },
      body: {
        label: "Cuerpo",
        helpText: "Una expresión L1 o un body JS L2 en sandbox"
      },
      "body.language": {
        label: "Idioma",
        helpText: "expression = fórmula pura; js = JavaScript en sandbox"
      },
      "body.source": {
        label: "Código fuente",
        helpText: "Código fuente del body de la función — sin imports de nivel superior"
      },
      "body.capabilities": {
        label: "Capacidades",
        helpText: "API ctx permitidas (api.read, api.write, crypto.uuid, log, …)"
      },
      "body.timeoutMs": {
        label: "Tiempo de espera (ms)",
        helpText: "Tiempo de espera por invocación (ms)"
      },
      "body.memoryMb": {
        label: "Memoria (MB)",
        helpText: "Límite de memoria por invocación (MB, máx. 256)"
      },
      params: {
        label: "Parámetros",
        helpText: "Parámetros de entrada de usuario (muestra el formulario antes de ejecutar)"
      },
      "params.name": {
        label: "Nombre"
      },
      "params.field": {
        label: "Campo"
      },
      "params.objectOverride": {
        label: "Sobrescritura de objeto"
      },
      "params.label": {
        label: "Etiqueta"
      },
      "params.type": {
        label: "Tipo"
      },
      "params.required": {
        label: "Obligatorio"
      },
      "params.options": {
        label: "Opciones"
      },
      "params.placeholder": {
        label: "Marcador de posición"
      },
      "params.helpText": {
        label: "Texto de ayuda"
      },
      "params.defaultValue": {
        label: "Valor predeterminado"
      },
      "params.multiple": {
        label: "Selección múltiple"
      },
      "params.accept": {
        label: "Tipos aceptados"
      },
      "params.maxSize": {
        label: "Tamaño máximo (bytes)"
      },
      "params.reference": {
        label: "Objeto de referencia"
      },
      "params.defaultFromRow": {
        label: "Predeterminado desde la fila"
      },
      "params.carryOver": {
        label: "Heredar de la fila"
      },
      "params.visible": {
        label: "Condición de visibilidad"
      },
      "params.requiresFeature": {
        label: "Requiere función"
      },
      operation: {
        label: "Operación",
        helpText: "Escritura declarativa de campos sobre un único registro: 'update' aplica `patch`, fusionado bajo los `params` recogidos, al registro actual EN NOMBRE DE QUIEN LLAMA — nunca con privilegios del sistema, así que los permisos de quien llama, los hooks del objeto y sus validaciones se ejecutan igual que en una edición de usuario."
      },
      undoable: {
        label: "Reversible",
        helpText: "Ofrece deshacer después de que la actualización se complete. El deshacer captura el valor previo de cada campo que la acción escribe: el conjunto fusionado, `patch` bajo los `params` recogidos. Una acción sin `operation` no declara conjunto de escritura, así que no hay nada que capturar."
      },
      execution: {
        label: "Ejecución",
        helpText: "Contrato de despacho masivo para el que está escrito el cuerpo de esta acción: 'perRecord' envía un despacho por cada fila seleccionada, con el recordId de esa fila; 'aggregate' envía UN solo despacho para toda la selección, con todos los id en params._selectedIds. Si se omite, la acción se despacha por registro."
      },
      confirmText: {
        label: "Texto de confirmación",
        helpText: "Mensaje de confirmación (p. ej., \"Are you sure?\")"
      },
      successMessage: {
        label: "Mensaje de éxito",
        helpText: "Mensaje de éxito tras completar"
      },
      refreshAfter: {
        label: "Actualizar después",
        helpText: "Actualiza la lista/página tras completar la acción"
      },
      openIn: {
        label: "Abrir en",
        helpText: "Dónde abrir una URL estática de `target`: 'self' navega en la misma pestaña y 'new-tab' abre una pestaña nueva. Si se omite, una URL absoluta o externa se abre en pestaña nueva y una relativa navega en el sitio."
      },
      opensInNewTab: {
        label: "Abre en pestaña nueva",
        helpText: "Abre el RESULTADO de la acción en una pestaña nueva: el renderizador la abre de forma síncrona al hacer clic (a prueba de bloqueadores de ventanas emergentes) y luego la lleva a la redirectUrl del manejador. Distinto de `openIn`, que enruta un destino de URL estática."
      },
      newTabUrl: {
        label: "URL de pestaña nueva",
        helpText: "Plantilla de URL directa para la pestaña nueva, con un marcador {recordId}. Junto con `opensInNewTab`, el renderizador lleva la pestaña preabierta aquí de inmediato y no envía nada, así que el endpoint debe aplicar la autenticación por su cuenta."
      },
      locations: {
        label: "Ubicaciones",
        helpText: "Dónde mostrar esta acción (toolbar, row menu, etc.)"
      },
      component: {
        label: "Componente",
        helpText: "Cómo renderizar (button, icon, menu item)"
      },
      visible: {
        label: "Condición de visibilidad",
        helpText: "Expresión CEL: mostrar solo cuando la condición sea true"
      },
      disabled: {
        label: "Deshabilitado",
        helpText: "Expresión CEL: desactivar cuando la condición sea true"
      },
      requiresFeature: {
        label: "Requiere función",
        helpText: "Indicador público de función de autenticación que condiciona esta acción. Se traslada al predicado `visible` durante el análisis y se elimina de la salida, así que ningún consumidor posterior llega a ver la clave."
      },
      ai: {
        label: "Exposición a IA",
        helpText: "Exposición a IA (voluntaria): establece ai.exposed=true y escribe ai.description (≥40 caracteres) para que los agentes puedan llamarla."
      },
      recordIdParam: {
        label: "Parámetro de ID de registro",
        helpText: "Nombre del parámetro body para ID de registro"
      },
      recordIdField: {
        label: "Campo de ID de registro",
        helpText: "Campo que usar como ID de registro (valor predeterminado: \"id\")"
      },
      bodyShape: {
        label: "Forma del cuerpo",
        helpText: "Estructura del cuerpo de solicitud (flat o nested)"
      }
    }
  },
  report: {
    label: "Informe",
    sections: {
      basics: {
        label: "Aspectos básicos",
        description: "Identidad y tipo de informe."
      },
      dataset_binding: {
        label: "Vinculación del conjunto de datos",
        description: "El conjunto de datos de la capa semántica que renderiza este informe. Las medidas y las filas provienen, respectivamente, de las medidas y las dimensiones del conjunto de datos."
      },
      joined_blocks: {
        label: "Bloques unidos",
        description: "Bloques adicionales unidos en un solo informe (solo informes joined)."
      },
      filter_and_chart: {
        label: "Filtro y gráfico",
        description: "Filtros a nivel de informe y presentación del gráfico."
      }
    },
    fields: {
      name: {
        label: "Nombre",
        helpText: "Identificador único snake_case"
      },
      label: {
        label: "Etiqueta"
      },
      description: {
        label: "Descripción"
      },
      type: {
        label: "Tipo",
        helpText: "Tipo de informe: tabular/summary/matrix/joined"
      },
      dataset: {
        label: "Conjunto de datos",
        helpText: "Conjunto de datos a vincular (las medidas/dimensiones provienen de su capa semántica)"
      },
      values: {
        label: "Medidas",
        helpText: "Nombres de medida (del conjunto de datos) que se mostrarán"
      },
      rows: {
        label: "Filas",
        helpText: "Nombres de dimensión (del conjunto de datos) por los que agrupar las filas"
      },
      columns: {
        label: "Columnas",
        helpText: "Nombres de dimensión en horizontal (solo matrix)"
      },
      order: {
        label: "Orden",
        helpText: "Claves de ordenación, la más significativa primero (una dimensión de rows/columns o una medida de values). Las dimensiones de tiempo son cronológicas de forma predeterminada."
      },
      "order.by": {
        label: "Ordenar por"
      },
      "order.direction": {
        label: "Dirección"
      },
      drilldown: {
        label: "Desglose",
        helpText: "Haz clic en una fila/celda agregada para abrir los registros subyacentes"
      },
      blocks: {
        label: "Bloques",
        helpText: "Une varios objetos (solo informe joined)"
      },
      "blocks.name": {
        label: "Nombre"
      },
      "blocks.label": {
        label: "Etiqueta"
      },
      "blocks.description": {
        label: "Descripción"
      },
      "blocks.type": {
        label: "Tipo de bloque"
      },
      "blocks.chart": {
        label: "Gráfico"
      },
      "blocks.dataset": {
        label: "Conjunto de datos"
      },
      "blocks.rows": {
        label: "Filas"
      },
      "blocks.columns": {
        label: "Columnas"
      },
      "blocks.values": {
        label: "Medidas"
      },
      "blocks.runtimeFilter": {
        label: "Filtro en tiempo de ejecución"
      },
      "blocks.order": {
        label: "Orden"
      },
      runtimeFilter: {
        label: "Filtro en tiempo de ejecución",
        helpText: "Filtro de ámbito en tiempo de renderizado, combinado con AND en el momento de la consulta"
      },
      chart: {
        label: "Gráfico",
        helpText: "Configuración de gráfico (type, legend, colors)"
      }
    }
  },
  dataset: {
    label: "Conjunto de datos",
    description: "Capa semántica de analítica — dimensiones y medidas",
    sections: {
      basics: {
        label: "Aspectos básicos",
        description: "Identidad del conjunto de datos."
      },
      source: {
        label: "Origen de datos",
        description: "El objeto base, las relaciones a unir y el ámbito intrínseco del conjunto de datos. Las uniones se derivan del grafo de objetos: elige nombres de relación (lookup / master_detail), nunca escribas una cláusula ON."
      },
      dimensions: {
        label: "Dimensiones",
        description: "Ejes agrupables. Usa un campo del objeto base o, para una relación incluida arriba, `relationship.field` (p. ej. account.region)."
      },
      measures: {
        label: "Medidas",
        description: "Valores agregables definidos una vez y referenciados por nombre. Una medida es sum/avg/count/… de un campo; una medida derivada combina otras medidas (ratio/sum/difference/product). Los filtros por medida y las operaciones derivadas se editan por fila en el diseñador de conjuntos de datos."
      }
    },
    fields: {
      name: {
        label: "Nombre",
        helpText: "Identificador único snake_case"
      },
      label: {
        label: "Etiqueta",
        helpText: "Nombre mostrado"
      },
      description: {
        label: "Descripción",
        helpText: "Qué mide este conjunto de datos"
      },
      object: {
        label: "Objeto",
        helpText: "Objeto base: el FROM"
      },
      include: {
        label: "Relaciones a incluir",
        helpText: "Nombres de campo de relación (lookup / master_detail) a unir — habilita dimensiones/medidas `relationship.field` (p. ej. incluir \"account\" → agrupar por account.region)"
      },
      filter: {
        label: "Filtro",
        helpText: "Filtro de ámbito intrínseco (p. ej. excluir registros eliminados de forma lógica), combinado con AND en cada consulta"
      },
      dimensions: {
        label: "Dimensiones",
        helpText: "Cada dimensión: nombre (referenciado por las presentaciones), campo, tipo y, para fechas, una granularidad de agrupación predeterminada"
      },
      "dimensions.name": {
        label: "Nombre"
      },
      "dimensions.label": {
        label: "Etiqueta"
      },
      "dimensions.field": {
        label: "Campo"
      },
      "dimensions.type": {
        label: "Tipo"
      },
      "dimensions.dateGranularity": {
        label: "Granularidad de fecha"
      },
      measures: {
        label: "Medidas",
        helpText: "Cada medida: nombre, agregación, campo (opcional para count) y formato de visualización/moneda"
      },
      "measures.name": {
        label: "Nombre"
      },
      "measures.label": {
        label: "Etiqueta"
      },
      "measures.aggregate": {
        label: "Agregación"
      },
      "measures.field": {
        label: "Campo"
      },
      "measures.filter": {
        label: "Filtro"
      },
      "measures.format": {
        label: "Formato"
      },
      "measures.currency": {
        label: "Moneda"
      },
      "measures.derived": {
        label: "Derivada de"
      }
    }
  },
  flow: {
    label: "Flujo",
    sections: {
      basics: {
        label: "Aspectos básicos",
        description: "Identidad del flujo y cómo se inicia."
      },
      canvas: {
        label: "Lienzo",
        description: "Nodos, aristas y variables de flujo — considera el diseñador visual para flujos complejos."
      },
      execution: {
        label: "Ejecución",
        description: "Estado de despliegue, identidad y gestión de errores."
      }
    },
    fields: {
      name: {
        label: "Nombre",
        helpText: "Identificador único (snake_case)"
      },
      label: {
        label: "Etiqueta",
        helpText: "Nombre mostrado a los usuarios"
      },
      type: {
        label: "Tipo",
        helpText: "Cómo se inicia el flujo (autolaunched, record_change, schedule, screen, api)"
      },
      description: {
        label: "Descripción",
        helpText: "Qué hace este flujo"
      },
      nodes: {
        label: "Nodos",
        helpText: "⚠️ Considera usar el editor visual Flow Designer en lugar de JSON"
      },
      "nodes.id": {
        label: "ID de nodo"
      },
      "nodes.type": {
        label: "Tipo de nodo"
      },
      "nodes.label": {
        label: "Etiqueta"
      },
      "nodes.config": {
        label: "Configuración"
      },
      "nodes.connectorConfig": {
        label: "Acción del conector"
      },
      "nodes.position": {
        label: "Posición en el lienzo"
      },
      "nodes.timeoutMs": {
        label: "Tiempo de espera (ms)"
      },
      "nodes.inputSchema": {
        label: "Esquema de entrada"
      },
      "nodes.waitEventConfig": {
        label: "Evento de espera"
      },
      "nodes.boundaryConfig": {
        label: "Evento de límite"
      },
      edges: {
        label: "Conexiones",
        helpText: "Conexiones entre nodos — usa Flow Designer para editar más fácilmente"
      },
      "edges.id": {
        label: "ID de conexión"
      },
      "edges.source": {
        label: "Nodo de origen"
      },
      "edges.target": {
        label: "Nodo de destino"
      },
      "edges.condition": {
        label: "Condición"
      },
      "edges.type": {
        label: "Tipo de conexión"
      },
      "edges.label": {
        label: "Etiqueta"
      },
      "edges.isDefault": {
        label: "Ruta predeterminada"
      },
      variables: {
        label: "Variables de flujo",
        helpText: "Variables de flujo (inputs/outputs)"
      },
      "variables.name": {
        label: "Nombre"
      },
      "variables.type": {
        label: "Tipo"
      },
      "variables.isInput": {
        label: "Entrada"
      },
      "variables.isOutput": {
        label: "Salida"
      },
      "variables.defaultValue": {
        label: "Valor predeterminado"
      },
      status: {
        label: "Estado",
        helpText: "Estado de despliegue: draft → active → obsolete"
      },
      version: {
        label: "Versión",
        helpText: "Número de versión (autoincrementado)"
      },
      runAs: {
        label: "Ejecutar como",
        helpText: "Ejecutar como system (admin) o user (permisos del usuario actual)"
      },
      errorHandling: {
        label: "Manejo de errores",
        helpText: "Qué hacer cuando falla un nodo (fail, retry, continue)"
      },
      successMessage: {
        label: "Mensaje de éxito",
        helpText: "Mensaje que viaja en el resultado de la ejecución cuando el flujo termina bien; la interfaz de flujo de pantalla lo muestra como aviso en lugar de un \"Done\" genérico."
      },
      errorMessage: {
        label: "Mensaje de error",
        helpText: "Mensaje que viaja en el resultado de la ejecución cuando el flujo falla; la interfaz de flujo de pantalla lo muestra como aviso en lugar del error en bruto."
      }
    }
  },
  job: {
    label: "Trabajo en segundo plano"
  },
  datasource: {
    label: "Fuente de datos"
  },
  external_catalog: {
    label: "Catálogo externo"
  },
  api: {
    label: "Endpoint API",
    description: "Endpoint HTTP declarativo — una URL estable y una capa de política sobre un pipeline existente (ADR-0121)"
  },
  translation: {
    label: "Traducción"
  },
  email_template: {
    label: "Plantilla de email",
    sections: {
      identity: {
        label: "Identidad",
        description: "Identificador y tipo de contenido. El id se referencia con sendTemplate({ template: id, ... })."
      },
      subject: {
        label: "Asunto",
        description: "Línea de asunto. Admite interpolación {{var.path}}."
      },
      html_body: {
        label: "Cuerpo HTML",
        description: "Cuerpo HTML enriquecido. La mayoría de clientes elimina <head>, así que usa estilos en línea."
      },
      plain_text_body: {
        label: "Cuerpo en texto plano",
        description: "Alternativa opcional en texto plano. Si se omite, el servicio elimina etiquetas del HTML para derivarla; proporcionarla mejora la puntuación antispam."
      },
      variables: {
        label: "Variables declaradas",
        description: "Variables declaradas. Studio las muestra como ayudas y sendTemplate() las valida cuando son obligatorias."
      },
      delivery_overrides: {
        label: "Sobrescrituras de entrega",
        description: "Sobrescrituras opcionales por plantilla para From / Reply-To."
      },
      status: {
        label: "Estado"
      }
    },
    fields: {
      name: {
        label: "Nombre",
        helpText: "snake_case con puntos (p. ej. auth.password_reset, crm.welcome)"
      },
      label: {
        label: "Etiqueta"
      },
      category: {
        label: "Categoría"
      },
      locale: {
        label: "Configuración regional",
        helpText: "Etiqueta BCP-47, p. ej. en-US, zh-CN"
      },
      description: {
        label: "Descripción"
      },
      subject: {
        label: "Asunto"
      },
      bodyHtml: {
        label: "Cuerpo HTML"
      },
      bodyText: {
        label: "Cuerpo de texto"
      },
      variables: {
        label: "Variables de plantilla",
        helpText: "Ejemplo: [{ \"name\": \"user.name\", \"type\": \"string\", \"required\": true, \"description\": \"...\" }]"
      },
      fromOverride: {
        label: "Sobrescritura de remitente",
        helpText: "Ejemplo: { \"name\": \"Acme Sales\", \"address\": \"sales@acme.com\" }"
      },
      replyTo: {
        label: "Responder a",
        helpText: "Dirección de email Reply-To"
      },
      active: {
        label: "Activo",
        helpText: "Si no está marcado, sendTemplate() devuelve TEMPLATE_INACTIVE."
      },
      isSystem: {
        label: "Integrado del sistema",
        helpText: "Plantilla integrada; los tenants pueden sobrescribirla, pero no deberían eliminarla."
      }
    }
  },
  doc: {
    label: "Documentación",
    description: "Documentación del paquete — elementos Markdown planos (ADR-0046)"
  },
  book: {
    label: "Libro de documentación",
    description: "Columna vertebral de navegación de la documentación — grupos ordenados con pertenencia derivada (ADR-0046 §6)"
  },
  permission: {
    label: "Conjunto de permisos",
    sections: {
      identity: {
        label: "Identidad",
        description: "Los conjuntos de permisos son el único contenedor de capacidades: un usuario obtiene la unión de todos los conjuntos que tiene, así que un conjunto solo puede añadir acceso. Las posiciones distribuyen los conjuntos a las personas."
      },
      system_permissions: {
        label: "Permisos del sistema",
        description: "Capacidades de alto nivel no vinculadas a un objeto específico — p. ej. manage_users, view_audit_logs."
      },
      object_and_field_permissions: {
        label: "Permisos de objeto y campo",
        description: "CRUD por objeto + FLS por campo. Edita mediante el editor matricial o pega JSON aquí."
      },
      tab_and_row_level_security: {
        label: "Pestaña y seguridad a nivel de fila",
        description: "Visibilidad de pestañas, políticas RLS y variables de contexto personalizadas para evaluar predicados."
      }
    },
    fields: {
      name: {
        label: "Nombre",
        helpText: "Nombre de máquina (snake_case)"
      },
      label: {
        label: "Etiqueta",
        helpText: "Etiqueta mostrada para administradores"
      },
      description: {
        label: "Descripción",
        helpText: "Descripción legible que se muestra en Setup (se guarda como sys_permission_set.description)."
      },
      isDefault: {
        label: "Predeterminado",
        helpText: "Línea base de la aplicación para la posición everyone (ADR-0090 D5): un conjunto de nivel de aplicación se vincula automáticamente al arrancar; uno de nivel de paquete se convierte en una sugerencia que el administrador confirma al instalar. false por defecto."
      },
      managedBy: {
        label: "Gestionado por",
        helpText: "Procedencia del registro (ADR-0086 D3): quién es el propietario de este conjunto entre actualizaciones."
      },
      packageId: {
        label: "ID de paquete",
        helpText: "Id del paquete propietario de un conjunto distribuido con un paquete (ADR-0086 D3). Déjalo vacío para un conjunto creado en el entorno."
      },
      systemPermissions: {
        label: "Permisos del sistema",
        helpText: "Lista de claves de capacidades del sistema"
      },
      objects: {
        label: "Permisos de objeto",
        helpText: "Ejemplo: { \"account\": { allowRead: true, allowEdit: true, ... } }"
      },
      fields: {
        label: "Campos",
        helpText: "Ejemplo: { \"account.amount\": { readable: true, editable: false } }"
      },
      tabPermissions: {
        label: "Permisos de pestaña",
        helpText: "Ejemplo: { \"app_crm\": \"visible\", \"app_admin\": \"hidden\" }"
      },
      rowLevelSecurity: {
        label: "Seguridad a nivel de fila",
        helpText: "Array de políticas RLS (ver rls.zod.ts)"
      }
    }
  },
  position: {
    label: "Posición",
    sections: {
      position: {
        label: "Posición",
        description: "Una posición es un conjunto plano y asignable de permission sets (p. ej. sales_rep, sales_manager). La capacidad reside en los permission sets; la profundidad de visibilidad en el árbol de unidades de negocio."
      }
    },
    fields: {
      name: {
        label: "Nombre",
        helpText: "Formato snake_case"
      },
      label: {
        label: "Etiqueta"
      },
      description: {
        label: "Descripción"
      },
      delegatable: {
        label: "Delegable",
        helpText: "Quienes la ocupan pueden delegar esta posición por sí mismos, con un plazo y un motivo (ADR-0091 D3). false por defecto: la delegación es solo para administradores."
      }
    }
  },
  capability: {
    label: "Capacidad",
    description: "Capacidad de autorización declarada por el paquete — el lado de la DEFINICIÓN de ADR-0066 D1 (las concesiones residen en los conjuntos de permisos; los requisitos, en los recursos)"
  },
  agent: {
    label: "Agente de IA",
    sections: {
      identity: {
        label: "Identidad",
        description: "Cómo ven y referencian este agente los usuarios."
      },
      ai_configuration: {
        label: "Configuración de IA",
        description: "Selección de modelo, instrucciones, planificación y memoria."
      },
      capabilities: {
        label: "Capacidades",
        description: "Skills, herramientas y fuentes de conocimiento que puede usar el agente."
      },
      access: {
        label: "Acceso y seguridad",
        description: "Quién puede usar este agente y qué salvaguardas se aplican."
      }
    },
    fields: {
      name: {
        label: "Nombre",
        helpText: "Identificador único (snake_case)"
      },
      label: {
        label: "Etiqueta",
        helpText: "Nombre mostrado (p. ej., \"Sales Assistant\")"
      },
      role: {
        label: "Rol del agente",
        helpText: "Persona del agente (p. ej., \"Customer Support Specialist\")"
      },
      avatar: {
        label: "Avatar del agente",
        helpText: "URL de imagen de avatar"
      },
      active: {
        label: "Activo",
        helpText: "Activa/desactiva este agente"
      },
      surface: {
        label: "Superficie",
        helpText: "Superficie de producto a la que se vincula este agente (ADR-0063 §1). Solo se adjuntan las habilidades cuya propia superficie coincide — o es 'both' — y el conjunto de herramientas del agente es la unión de las de esas habilidades. 'ask' por defecto."
      },
      instructions: {
        label: "Instrucciones",
        helpText: "Prompt del sistema — indica al agente cómo comportarse y qué puede hacer"
      },
      model: {
        label: "Modelo",
        helpText: "Configuración del modelo de IA (provider, model name, temperature, etc.)"
      },
      planning: {
        label: "Planificación",
        helpText: "Configuración de razonamiento autónomo (strategy, max iterations, replan)"
      },
      memory: {
        label: "Memoria",
        helpText: "Gestión de memoria (short-term, long-term, reflection)"
      },
      lifecycle: {
        label: "Ciclo de vida",
        helpText: "Máquina de estado que define el flujo de conversación"
      },
      skills: {
        label: "Habilidades",
        helpText: "Nombres de skill (arquitectura Agent→Skill→Tool)"
      },
      access: {
        label: "Acceso",
        helpText: "IDs de usuario o nombres de rol que pueden chatear con este agente"
      },
      permissions: {
        label: "Permisos",
        helpText: "Permisos necesarios para usar este agente"
      },
      guardrails: {
        label: "Reglas de protección",
        helpText: "Reglas de seguridad y políticas de contenido"
      }
    }
  },
  tool: {
    label: "Herramienta de IA",
    sections: {
      basics: {
        label: "Aspectos básicos",
        description: "Identidad de herramienta y descripción para IA."
      },
      schemas: {
        label: "Esquemas",
        description: "Entradas que acepta la herramienta y forma de su salida."
      }
    },
    fields: {
      name: {
        label: "Nombre",
        helpText: "Identificador único (snake_case)"
      },
      label: {
        label: "Etiqueta",
        helpText: "Nombre mostrado para Studio UI"
      },
      description: {
        label: "Descripción",
        helpText: "Indica a IA cuándo usar esta herramienta — sé específico."
      },
      objectName: {
        label: "Nombre de objeto",
        helpText: "Objeto relacionado (si esta herramienta opera sobre un objeto específico)"
      },
      parameters: {
        label: "Parámetros",
        helpText: "Parámetros de entrada — define propiedades como: {name: {type: \"string\", description: \"...\"}}"
      },
      outputSchema: {
        label: "Esquema de salida",
        helpText: "Esquema de salida para validación (opcional)"
      }
    }
  },
  skill: {
    label: "Habilidad de IA",
    sections: {
      basics: {
        label: "Aspectos básicos",
        description: "Identidad de skill y descripción legible."
      },
      ai_instructions: {
        label: "Instrucciones de IA",
        description: "Cómo debe razonar el agente con esta skill."
      },
      triggers: {
        label: "Disparadores",
        description: "Cuándo debe activarse esta skill."
      }
    },
    fields: {
      name: {
        label: "Nombre",
        helpText: "Identificador único (snake_case)"
      },
      label: {
        label: "Etiqueta",
        helpText: "Nombre mostrado (p. ej., \"Case Management\")"
      },
      description: {
        label: "Descripción",
        helpText: "Qué hace esta skill"
      },
      active: {
        label: "Activo",
        helpText: "Activa/desactiva esta skill"
      },
      surface: {
        label: "Superficie",
        helpText: "Superficie de agente a la que se vincula esta habilidad (ADR-0063 §3). Vincularla a un agente con una superficie distinta falla de forma explícita al resolver, no se omite en silencio. 'ask' por defecto."
      },
      instructions: {
        label: "Instrucciones",
        helpText: "Instrucciones para IA — indica cómo usar estas herramientas juntas"
      },
      tools: {
        label: "Herramientas",
        helpText: "Nombres de herramienta (admite comodín: action_*)"
      },
      triggerConditions: {
        label: "Condiciones disparadoras",
        helpText: "Condiciones programáticas (p. ej., objectName == \"case\")"
      },
      "triggerConditions.field": {
        label: "Campo de contexto"
      },
      "triggerConditions.operator": {
        label: "Operador"
      },
      "triggerConditions.value": {
        label: "Valor"
      }
    }
  }
};
