// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'es-ES'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const esESObjects: NonNullable<TranslationData['objects']> = {
  sys_user: {
    label: "Usuario",
    pluralLabel: "Usuarios",
    description: "Cuentas de usuario para autenticación",
    fields: {
      name: {
        label: "Nombre"
      },
      email: {
        label: "Correo electrónico"
      },
      email_verified: {
        label: "Correo electrónico verificado"
      },
      two_factor_enabled: {
        label: "Doble factor habilitado",
        help: "Indica si la autenticación de doble factor está habilitada para este usuario. Lo mantiene el plugin `twoFactor` de better-auth."
      },
      role: {
        label: "Rol de plataforma",
        help: "Rol a nivel de plataforma (admin, user, …). Se establece mediante la acción Establecer rol de plataforma."
      },
      banned: {
        label: "Bloqueado",
        help: "Si es verdadero, el usuario no puede iniciar sesión. Se alterna mediante las acciones Bloquear usuario / Desbloquear usuario."
      },
      ban_reason: {
        label: "Motivo del bloqueo"
      },
      ban_expires: {
        label: "El bloqueo caduca el",
        help: "Si se establece, el bloqueo se elimina automáticamente en ese momento."
      },
      failed_login_count: {
        label: "Intentos fallidos consecutivos",
        help: "Intentos de inicio de sesión fallidos consecutivos; se restablece a 0 tras un inicio correcto. Lo mantiene el gestor de autenticación."
      },
      locked_until: {
        label: "Bloqueado hasta",
        help: "Si está establecido y es una fecha futura, el inicio de sesión se rechaza (bloqueo por fuerza bruta). Se limpia automáticamente pasado ese momento; un administrador puede levantarlo antes con «Desbloquear cuenta»."
      },
      password_changed_at: {
        label: "Contraseña cambiada el",
        help: "Fecha y hora del último cambio de contraseña. Sirve de base a password_expiry_days; gestionado por el sistema."
      },
      phone_number: {
        label: "Número de teléfono",
        help: "Número de teléfono para iniciar sesión (se recomienda E.164). Único por usuario; lo gestiona better-auth cuando el plugin phoneNumber está habilitado."
      },
      phone_number_verified: {
        label: "Teléfono verificado",
        help: "Indica si el número de teléfono se ha verificado (la verificación OTP requiere infraestructura de SMS; false hasta que esté disponible). Gestionado por el sistema."
      },
      must_change_password: {
        label: "Debe cambiar la contraseña",
        help: "Si es true, el usuario queda bloqueado (403 PASSWORD_EXPIRED) hasta que cambie su contraseña. Lo establecen las rutas de administración de usuarios; gestionado por el sistema."
      },
      mfa_required_at: {
        label: "MFA exigido desde",
        help: "Cuándo se aplicó por primera vez el MFA obligatorio a este usuario (inicio del período de gracia). Sirve de base a mfa_required; gestionado por el sistema."
      },
      last_login_at: {
        label: "Último inicio de sesión",
        help: "Fecha y hora del último inicio de sesión correcto. Lo registra el gestor de autenticación; gestionado por el sistema."
      },
      last_login_ip: {
        label: "IP del último inicio de sesión",
        help: "IP del cliente del último inicio de sesión correcto (de la cabecera reenviada por el proxy de confianza). Gestionado por el sistema."
      },
      ai_access: {
        label: "Acceso a IA",
        help: "Indica si este usuario dispone de una plaza de IA: otorga acceso a los agentes de IA integrados en la interfaz (build / ask). El framework sintetiza la capacidad `ai_seat` a partir de este indicador (plugin-hono-server resolveCtx). La asignación está limitada por el número de plazas licenciadas o compradas (aplicado por AiSeatPlugin de @objectstack/security-enterprise). Propiedad de objectql (better-auth ignora esta columna)."
      },
      image: {
        label: "Imagen de perfil"
      },
      manager_id: {
        label: "Gerente",
        help: "This user's direct manager. Forms the reporting chain the `own_and_reports` hierarchy scope walks (ADR-0057 / @objectstack/security-enterprise)."
      },
      primary_business_unit_id: {
        label: "Unidad de negocio principal",
        help: "The user's primary business unit — a denormalised projection of sys_business_unit_member.is_primary, maintained by plugin-sharing (ADR-0057 addendum D12). Lets a user-lookup filter candidates by business unit without traversing the membership junction. Do not edit directly; set it via business-unit membership."
      },
      source: {
        label: "Origen de la identidad",
        help: "Cómo se creó esta identidad: idp_provisioned (JIT de SSO federado) o env_native (registro local / usuario final de la aplicación). Gestionado por el sistema; no editar.",
        options: {
          idp_provisioned: "Aprovisionada por IdP",
          env_native: "Nativa del entorno"
        }
      },
      id: {
        label: "ID de usuario"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    },
    _views: {
      me: {
        label: "Mi perfil"
      },
      all_users: {
        label: "Todos los usuarios"
      },
      unverified: {
        label: "No verificados"
      },
      two_factor: {
        label: "2FA habilitado"
      },
      banned: {
        label: "Bloqueado"
      }
    },
    _actions: {
      invite_user: {
        label: "Invitar usuario",
        successMessage: "Invitación enviada"
      },
      ban_user: {
        label: "Bloquear usuario",
        description: "¿Bloquear a este usuario? Cerrará sesión y no podrá volver a iniciarla hasta que se desbloquee.",
        successMessage: "Usuario bloqueado",
        params: {
          banReason: {
            label: "Motivo del bloqueo"
          }
        }
      },
      unban_user: {
        label: "Desbloquear usuario",
        successMessage: "Usuario desbloqueado"
      },
      unlock_user: {
        label: "Desbloquear cuenta",
        successMessage: "Cuenta desbloqueada"
      },
      create_user: {
        label: "Crear usuario",
        successMessage: "Usuario creado",
        params: {
          phoneNumber: {
            label: "Número de teléfono",
            helpText: "Número de teléfono para iniciar sesión (E.164, p. ej. +8613800000000). Obligatorio si no se indica un correo."
          },
          generatePassword: {
            label: "Generar contraseña temporal"
          },
          password: {
            label: "Contraseña (dejar en blanco para generarla)"
          },
          mustChangePassword: {
            label: "Exigir cambio de contraseña en el primer inicio de sesión"
          }
        },
        resultDialog: {
          title: "Usuario creado",
          description: "Copie la contraseña temporal ahora: se muestra una sola vez y no se almacena.",
          acknowledge: "He guardado esta contraseña",
          fields: {
            "user.email": "Correo electrónico",
            "user.phoneNumber": "Número de teléfono",
            temporaryPassword: "Contraseña temporal"
          }
        }
      },
      set_user_password: {
        label: "Establecer contraseña",
        successMessage: "Contraseña actualizada",
        params: {
          generatePassword: {
            label: "Generar contraseña temporal"
          },
          newPassword: {
            label: "Nueva contraseña (dejar en blanco para generarla)"
          },
          mustChangePassword: {
            label: "Exigir cambio de contraseña en el próximo inicio de sesión"
          }
        },
        resultDialog: {
          title: "Contraseña actualizada",
          description: "Si se generó una contraseña temporal, cópiela ahora: se muestra una sola vez y no se almacena.",
          acknowledge: "Hecho",
          fields: {
            temporaryPassword: "Contraseña temporal"
          }
        }
      },
      set_user_role: {
        label: "Establecer rol de plataforma",
        successMessage: "Rol actualizado",
        params: {
          role: {
            label: "Rol de plataforma"
          }
        }
      },
      impersonate_user: {
        label: "Suplantar usuario",
        confirmText: "¿Iniciar una sesión de suplantación para este usuario? Úsela solo para casos legítimos de soporte; las acciones se registrarán.",
        successMessage: "Ahora está suplantando al usuario"
      },
      update_my_profile: {
        label: "Actualizar perfil",
        successMessage: "Perfil actualizado"
      },
      change_my_password: {
        label: "Cambiar contraseña",
        successMessage: "Contraseña cambiada",
        params: {
          currentPassword: {
            label: "Contraseña actual"
          },
          newPassword: {
            label: "Nueva contraseña"
          },
          revokeOtherSessions: {
            label: "Cerrar sesión en los demás dispositivos"
          }
        }
      },
      change_my_email: {
        label: "Cambiar correo",
        successMessage: "Correo de verificación enviado; revisa la nueva dirección para confirmar.",
        params: {
          newEmail: {
            label: "Nuevo correo"
          }
        }
      },
      resend_verification_email: {
        label: "Reenviar correo de verificación",
        successMessage: "Correo de verificación enviado; revisa tu bandeja de entrada."
      },
      delete_my_account: {
        label: "Eliminar mi cuenta",
        description: "¿Eliminar tu cuenta de forma permanente? Esta acción no se puede deshacer: se cerrarán todas tus sesiones y se eliminarán todos los datos de tu propiedad según la política de retención configurada.",
        successMessage: "Cuenta eliminada",
        params: {
          password: {
            label: "Contraseña actual"
          }
        }
      },
      enable_two_factor: {
        label: "Habilitar autenticación de dos factores",
        successMessage: "Autenticación de dos factores habilitada. Escanea el código QR o pega el URI otpauth en tu aplicación de autenticación y verifica un código para completar la configuración.",
        params: {
          password: {
            label: "Contraseña actual"
          }
        }
      },
      disable_two_factor: {
        label: "Deshabilitar autenticación de dos factores",
        description: "¿Desactivar la autenticación de dos factores? Tu cuenta será menos segura.",
        successMessage: "Autenticación de dos factores deshabilitada.",
        params: {
          password: {
            label: "Contraseña actual"
          }
        }
      },
      generate_backup_codes: {
        label: "Regenerar códigos de respaldo",
        description: "¿Generar un nuevo juego de códigos de respaldo? Los códigos generados anteriormente dejarán de funcionar.",
        successMessage: "Nuevos códigos de respaldo generados; guárdalos en un lugar seguro.",
        params: {
          password: {
            label: "Contraseña actual"
          }
        }
      }
    }
  },
  sys_session: {
    label: "Sesión",
    pluralLabel: "Sesiones",
    description: "Sesiones de usuario activas",
    fields: {
      user_id: {
        label: "Usuario"
      },
      expires_at: {
        label: "Caduca el"
      },
      last_activity_at: {
        label: "Last Activity At",
        help: "Timestamp of the last request on this session; drives idle-timeout. System-managed."
      },
      revoked_at: {
        label: "Revoked At",
        help: "When set, this session was revoked (idle / absolute-max / concurrent-cap / admin). System-managed."
      },
      revoke_reason: {
        label: "Revoke Reason",
        help: "Why the session was revoked (idle_timeout, absolute_max, concurrent_cap, …)."
      },
      active_organization_id: {
        label: "Organización activa"
      },
      active_team_id: {
        label: "Equipo activo"
      },
      ip_address: {
        label: "Dirección IP"
      },
      user_agent: {
        label: "Agente de usuario"
      },
      impersonated_by: {
        label: "Suplantado por",
        help: "ID del administrador que inició esta sesión de suplantación, si existe."
      },
      token: {
        label: "Token de sesión",
        help: "Token de sesión opaco; nunca se muestra en la UI."
      },
      id: {
        label: "ID de sesión"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    },
    _views: {
      mine: {
        label: "Mis sesiones"
      },
      all_sessions: {
        label: "Todas"
      },
      revoked: {
        label: "Revocadas"
      }
    },
    _actions: {
      revoke_my_other_sessions: {
        label: "Cerrar sesión en otros dispositivos",
        confirmText: "¿Cerrar sesión en todos los demás dispositivos en los que ha iniciado sesión? Su sesión actual seguirá activa.",
        successMessage: "Se han revocado todas las demás sesiones"
      },
      revoke_session: {
        label: "Revocar sesión",
        confirmText: "¿Revocar esta sesión? El usuario cerrará sesión en ese dispositivo.",
        successMessage: "Sesión revocada"
      }
    }
  },
  sys_account: {
    label: "Cuenta de autenticación",
    pluralLabel: "Cuentas de autenticación",
    description: "Cuentas de proveedores de OAuth y autenticación",
    fields: {
      id: {
        label: "ID de cuenta de autenticación"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      },
      provider_id: {
        label: "ID del proveedor",
        help: "Identificador del proveedor OAuth (google, github, etc.)."
      },
      issuer: {
        label: "Emisor",
        help: "Autoridad que avaló el id de cuenta del proveedor: un emisor OIDC, o local:… para proveedores que no tienen uno"
      },
      account_id: {
        label: "ID de cuenta del proveedor",
        help: "ID del usuario en el sistema del proveedor."
      },
      user_id: {
        label: "Usuario",
        help: "Enlace a la tabla de usuarios."
      },
      access_token: {
        label: "Token de acceso"
      },
      refresh_token: {
        label: "Token de actualización"
      },
      id_token: {
        label: "Token de ID"
      },
      access_token_expires_at: {
        label: "El token de acceso caduca el"
      },
      refresh_token_expires_at: {
        label: "El token de actualización caduca el"
      },
      scope: {
        label: "Ámbito de OAuth"
      },
      password: {
        label: "Hash de la contraseña",
        help: "Hash de la contraseña para el proveedor de correo electrónico/contraseña."
      },
      previous_password_hashes: {
        label: "Previous Password Hashes",
        help: "JSON array of prior password hashes (bounded by password_history_count); reuse-prevention only. System-managed."
      }
    },
    _views: {
      mine: {
        label: "Mis enlaces"
      },
      by_provider: {
        label: "Por proveedor"
      },
      all_links: {
        label: "Todos"
      }
    },
    _actions: {
      link_social: {
        label: "Vincular cuenta social",
        params: {
          provider: {
            label: "Proveedor",
            options: {
              google: "Google",
              github: "GitHub",
              microsoft: "Microsoft",
              apple: "Apple",
              facebook: "Facebook",
              gitlab: "GitLab",
              discord: "Discord"
            }
          }
        }
      },
      unlink_account: {
        label: "Desvincular cuenta",
        description: "¿Desvincular este vínculo de identidad? El usuario ya no podrá iniciar sesión con este proveedor hasta que lo vuelva a vincular desde la configuración de su cuenta.",
        successMessage: "Vínculo de identidad eliminado"
      }
    }
  },
  sys_verification: {
    label: "Verificación",
    pluralLabel: "Verificaciones",
    description: "Tokens de verificación de correo electrónico y teléfono",
    fields: {
      id: {
        label: "ID de verificación"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      },
      value: {
        label: "Token de verificación",
        help: "Token o código para la verificación."
      },
      expires_at: {
        label: "Caduca el"
      },
      identifier: {
        label: "Identificador",
        help: "Dirección de correo electrónico o número de teléfono."
      }
    }
  },
  sys_organization: {
    label: "Organización",
    pluralLabel: "Organizaciones",
    description: "Organizaciones para agrupación multi-tenant",
    fields: {
      name: {
        label: "Nombre"
      },
      slug: {
        label: "Slug",
        help: "Identificador compatible con URL."
      },
      logo: {
        label: "Logotipo"
      },
      metadata: {
        label: "Metadatos",
        help: "Metadatos de la organización serializados en JSON."
      },
      require_mfa: {
        label: "Exigir autenticación multifactor",
        help: "Si es true, todos los miembros de esta organización deben registrar una aplicación de autenticación para acceder a los datos."
      },
      parent_organization_id: {
        label: "Parent Organization",
        help: "Reporting/grouping parent. Grants NOTHING — visibility across organizations comes from membership, never from this reference (ADR-0105 D6)."
      },
      sort_order: {
        label: "Sort Order",
        help: "Display order among sibling organizations. Presentation only."
      },
      id: {
        label: "ID de organización"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    },
    _views: {
      all_orgs: {
        label: "Todas"
      }
    },
    _actions: {
      create_organization: {
        label: "Crear organización",
        successMessage: "Organización creada"
      },
      update_organization: {
        label: "Editar organización",
        successMessage: "Organización actualizada"
      },
      delete_organization: {
        label: "Eliminar organización",
        confirmText: "¿Eliminar esta organización? Todos los miembros perderán el acceso inmediatamente. Esta acción no se puede deshacer.",
        successMessage: "Organización eliminada"
      },
      set_active_organization: {
        label: "Establecer como activa",
        successMessage: "Organización activa cambiada"
      },
      leave_organization: {
        label: "Abandonar organización",
        confirmText: "¿Abandonar esta organización? Perderá el acceso a todos sus recursos.",
        successMessage: "Ha abandonado la organización"
      },
      change_slug: {
        label: "Cambiar slug",
        description: "Renombrar el slug reescribe todos los subdominios de la plataforma para esta organización y reserva el slug anterior durante 90 días. ¿Continuar?",
        successMessage: "Slug de la organización cambiado"
      }
    }
  },
  sys_member: {
    label: "Miembro",
    pluralLabel: "Miembros",
    description: "Registros de membresía de la organización",
    fields: {
      id: {
        label: "ID de miembro"
      },
      created_at: {
        label: "Creado el"
      },
      organization_id: {
        label: "Organización"
      },
      user_id: {
        label: "Usuario"
      },
      role: {
        label: "Rol",
        help: "Rol del miembro dentro de la organización.",
        options: {
          owner: "Propietario",
          admin: "Administrador",
          delegated_admin: "Delegated Admin",
          member: "Miembro"
        }
      }
    },
    _views: {
      mine: {
        label: "My Memberships",
        emptyState: {
          title: "No organizations yet",
          message: "You haven't joined any organizations."
        }
      }
    },
    _actions: {
      add_member: {
        label: "Añadir miembro",
        successMessage: "Miembro añadido"
      },
      update_member_role: {
        label: "Cambiar rol",
        successMessage: "Rol del miembro actualizado"
      },
      remove_member: {
        label: "Eliminar miembro",
        confirmText: "¿Eliminar a este miembro de la organización? Perderá el acceso a todos los recursos de la organización.",
        successMessage: "Miembro eliminado"
      },
      transfer_ownership: {
        label: "Transferir propiedad",
        confirmText: "¿Transferir la propiedad de esta organización al miembro seleccionado? Pasarás a ser administrador y perderás los privilegios exclusivos del propietario.",
        successMessage: "Propiedad transferida"
      }
    }
  },
  sys_invitation: {
    label: "Invitación",
    pluralLabel: "Invitaciones",
    description: "Invitaciones de organización para la incorporación de usuarios",
    fields: {
      id: {
        label: "ID de invitación"
      },
      created_at: {
        label: "Creado el"
      },
      organization_id: {
        label: "Organización"
      },
      email: {
        label: "Correo electrónico",
        help: "Dirección de correo electrónico del usuario invitado."
      },
      role: {
        label: "Rol",
        help: "Rol que se asignará al aceptar.",
        options: {
          owner: "Propietario",
          admin: "Administrador",
          delegated_admin: "Delegated Admin",
          member: "Miembro"
        }
      },
      status: {
        label: "Estado",
        options: {
          pending: "Pendiente",
          accepted: "Aceptada",
          rejected: "Rechazada",
          expired: "Caducada",
          canceled: "Cancelada"
        }
      },
      inviter_id: {
        label: "Invitador",
        help: "Usuario que envió la invitación."
      },
      expires_at: {
        label: "Caduca el"
      },
      team_id: {
        label: "Equipo",
        help: "Equipo opcional que se asignará al aceptar."
      },
      business_unit_id: {
        label: "Placement Business Unit",
        help: "Business unit the invitee is placed under on acceptance (ADR-0105 D8). Must lie inside the issuer's delegated subtree."
      },
      positions: {
        label: "Placement Positions",
        help: "sys_position names assigned on acceptance (ADR-0105 D8). Every position's permission sets must be allowlisted by the issuer's adminScope."
      }
    },
    _views: {
      pending: {
        label: "Pendientes"
      },
      accepted: {
        label: "Aceptadas"
      },
      expired: {
        label: "Caducadas / canceladas"
      },
      all_invitations: {
        label: "Todas"
      }
    },
    _actions: {
      invite_user: {
        label: "Invitar usuario",
        successMessage: "Invitación enviada"
      },
      cancel_invitation: {
        label: "Cancelar invitación",
        confirmText: "¿Cancelar esta invitación? El destinatario ya no podrá aceptarla.",
        successMessage: "Invitación cancelada"
      },
      resend_invitation: {
        label: "Reenviar invitación",
        successMessage: "Invitación reenviada"
      },
      accept_invitation: {
        label: "Aceptar invitación",
        successMessage: "Invitación aceptada"
      },
      reject_invitation: {
        label: "Rechazar invitación",
        confirmText: "¿Rechazar esta invitación? Se notificará a quien la envió y necesitarás una nueva invitación para unirte.",
        successMessage: "Invitación rechazada"
      }
    }
  },
  sys_team: {
    label: "Equipo",
    pluralLabel: "Equipos",
    description: "Equipos dentro de las organizaciones para una agrupación detallada",
    fields: {
      name: {
        label: "Nombre"
      },
      organization_id: {
        label: "Organización",
        help: "Organización principal de este equipo."
      },
      member_count: {
        label: "Member Count",
        help: "Seat counter maintained by better-auth; do not write directly."
      },
      id: {
        label: "ID de equipo"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    },
    _views: {
      by_org: {
        label: "Por organización"
      },
      all_teams: {
        label: "Todos"
      }
    },
    _actions: {
      create_team: {
        label: "Crear equipo",
        successMessage: "Equipo creado"
      },
      update_team: {
        label: "Editar equipo",
        successMessage: "Equipo actualizado"
      },
      remove_team: {
        label: "Eliminar equipo",
        confirmText: "¿Eliminar este equipo? Los miembros perderán cualquier acceso con ámbito de equipo. Esta acción no se puede deshacer.",
        successMessage: "Equipo eliminado"
      }
    }
  },
  sys_team_member: {
    label: "Miembro del equipo",
    pluralLabel: "Miembros del equipo",
    description: "Registros de membresía de equipo que vinculan usuarios con equipos",
    fields: {
      id: {
        label: "ID de miembro del equipo"
      },
      created_at: {
        label: "Creado el"
      },
      team_id: {
        label: "Equipo"
      },
      user_id: {
        label: "Usuario"
      },
      membership_key: {
        label: "Membership Key",
        help: "Derived membership digest maintained by better-auth; do not write directly."
      }
    },
    _actions: {
      add_team_member: {
        label: "Añadir miembro",
        successMessage: "Miembro del equipo añadido"
      },
      remove_team_member: {
        label: "Eliminar del equipo",
        description: "¿Eliminar a este usuario del equipo? Perderá cualquier acceso con ámbito de equipo.",
        successMessage: "Miembro del equipo eliminado"
      }
    }
  },
  sys_business_unit: {
    label: "Unidad de negocio",
    pluralLabel: "Unidades de negocio",
    description: "Nodo jerárquico de la estructura organizativa (departamento / división / unidad de negocio / oficina).",
    fields: {
      name: {
        label: "Nombre"
      },
      code: {
        label: "Código",
        help: "Código corto y estable (p. ej. EMEA-SALES). Único dentro del tenant."
      },
      kind: {
        label: "Tipo",
        help: "Pista de categorización; no cambia la semántica del grafo.",
        options: {
          company: "Empresa",
          division: "División",
          department: "Departamento",
          office: "Oficina",
          cost_center: "Centro de coste"
        }
      },
      parent_business_unit_id: {
        label: "Unidad de negocio principal",
        help: "Autorreferencia para el árbol organizativo. Null = raíz del tenant."
      },
      organization_id: {
        label: "Organización",
        help: "Ámbito del tenant."
      },
      manager_user_id: {
        label: "Responsable del departamento",
        help: "Usuario responsable de esta unidad organizativa (responsable o jefe de departamento)."
      },
      active: {
        label: "Activo",
        help: "Si es falso, los miembros no se expanden en las consultas del grafo."
      },
      effective_from: {
        label: "Vigente desde",
        help: "Momento en que este departamento entró en funcionamiento (sincronización HRIS)."
      },
      effective_to: {
        label: "Vigente hasta",
        help: "Momento en que este departamento se retiró (sincronización HRIS)."
      },
      external_ref: {
        label: "Referencia externa",
        help: "ID en el HRIS ascendente (Workday / SAP HR / 北森)."
      },
      id: {
        label: "ID de departamento"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    },
    _views: {
      org_chart: {
        label: "Organigrama"
      },
      active: {
        label: "Activo"
      },
      inactive: {
        label: "Inactivo"
      },
      by_kind: {
        label: "Por tipo"
      },
      all_departments: {
        label: "Todos"
      }
    }
  },
  sys_business_unit_member: {
    label: "Miembro de unidad de negocio",
    pluralLabel: "Miembros de unidad de negocio",
    description: "Asignación de usuario a un departamento (compatible con organizaciones matriciales y con vigencia temporal).",
    fields: {
      id: {
        label: "ID de miembro"
      },
      business_unit_id: {
        label: "Unidad de negocio"
      },
      user_id: {
        label: "Usuario"
      },
      function_in_business_unit: {
        label: "Función en la unidad de negocio",
        help: "`lead` es el responsable del día a día; `deputy` puede sustituir al responsable en el enrutamiento de aprobaciones.",
        options: {
          member: "Miembro",
          lead: "Responsable",
          deputy: "Sustituto"
        }
      },
      is_primary: {
        label: "Asignación principal",
        help: "Cuando el usuario pertenece a varios departamentos, este marca el canónico para los informes."
      },
      effective_from: {
        label: "Vigente desde"
      },
      effective_to: {
        label: "Vigente hasta"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    }
  },
  sys_api_key: {
    label: "Clave de API",
    pluralLabel: "Claves de API",
    description: "Claves de API para acceso programático",
    fields: {
      name: {
        label: "Nombre",
        help: "Nombre visible para la clave de API."
      },
      prefix: {
        label: "Prefijo",
        help: "Prefijo visible para identificar la clave (p. ej., \"osk_\")."
      },
      user_id: {
        label: "Propietario",
        help: "Usuario que posee esta clave de API."
      },
      scopes: {
        label: "Ámbitos",
        help: "Matriz JSON de ámbitos de permisos."
      },
      expires_at: {
        label: "Caduca el"
      },
      last_used_at: {
        label: "Último uso el",
        help: "Se actualiza automáticamente en cada llamada a la API."
      },
      revoked: {
        label: "Revocado"
      },
      key: {
        label: "Clave con hash",
        help: "Valor de la clave de API con hash; nunca se expone a los clientes."
      },
      id: {
        label: "ID de clave de API"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    },
    _views: {
      mine: {
        label: "Mis claves"
      },
      active: {
        label: "Activo"
      },
      revoked: {
        label: "Revocado"
      },
      all_keys: {
        label: "Todas"
      }
    },
    _actions: {
      revoke_api_key: {
        label: "Revocar clave de API",
        confirmText: "¿Revocar esta clave de API? Los clientes que la utilicen perderán el acceso inmediatamente.",
        successMessage: "Clave de API revocada"
      },
      restore_api_key: {
        label: "Restaurar clave de API",
        confirmText: "¿Restaurar esta clave de API revocada? Los clientes existentes que la conserven recuperarán el acceso.",
        successMessage: "Clave de API restaurada"
      }
    }
  },
  sys_two_factor: {
    label: "Doble factor",
    pluralLabel: "Credenciales de doble factor",
    description: "Credenciales de autenticación de doble factor",
    fields: {
      id: {
        label: "ID de doble factor"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      },
      user_id: {
        label: "Usuario"
      },
      secret: {
        label: "Secreto",
        help: "Clave secreta TOTP."
      },
      backup_codes: {
        label: "Códigos de respaldo",
        help: "Códigos de recuperación de respaldo serializados en JSON."
      },
      verified: {
        label: "Verified",
        help: "Whether the enrollment was confirmed with a valid TOTP code (managed by better-auth)"
      },
      failed_verification_count: {
        label: "Failed Verification Count",
        help: "Consecutive failed 2FA verifications; reset on success. Maintained by better-auth."
      },
      locked_until: {
        label: "Locked Until",
        help: "Set when failed 2FA verifications cross the lockout threshold. Maintained by better-auth."
      }
    },
    _views: {
      mine: {
        label: "Mi configuración"
      },
      all_enrollments: {
        label: "Todas"
      }
    },
    _actions: {
      enable_two_factor: {
        label: "Habilitar 2FA",
        params: {
          password: {
            label: "Contraseña actual"
          }
        },
        resultDialog: {
          title: "Autenticación de doble factor habilitada",
          description: "Escanee el código QR con su aplicación de autenticación y guarde los códigos de respaldo en un lugar seguro. Los códigos de respaldo se muestran una sola vez.",
          acknowledge: "He guardado mis códigos de respaldo",
          fields: {
            totpURI: "URI del autenticador",
            backupCodes: "Códigos de respaldo"
          }
        }
      },
      disable_two_factor: {
        label: "Deshabilitar 2FA",
        description: "¿Deshabilitar la autenticación de doble factor en su cuenta?",
        successMessage: "2FA deshabilitado",
        params: {
          password: {
            label: "Contraseña actual"
          }
        }
      },
      regenerate_backup_codes: {
        label: "Regenerar códigos de respaldo",
        description: "¿Regenerar los códigos de respaldo? Todos los códigos de respaldo anteriores dejarán de funcionar de inmediato.",
        params: {
          password: {
            label: "Contraseña actual"
          }
        },
        resultDialog: {
          title: "Nuevos códigos de respaldo generados",
          description: "Los códigos de respaldo anteriores ya no son válidos. Guarde estos nuevos códigos en un lugar seguro: se muestran una sola vez.",
          acknowledge: "He guardado los nuevos códigos",
          fields: {
            backupCodes: "Códigos de respaldo"
          }
        }
      }
    }
  },
  sys_device_code: {
    label: "Código de dispositivo",
    pluralLabel: "Códigos de dispositivo",
    description: "Solicitudes pendientes de la concesión de autorización de dispositivos OAuth 2.0 (RFC 8628)",
    fields: {
      id: {
        label: "ID de código de dispositivo"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      },
      device_code: {
        label: "Código de dispositivo",
        help: "Token de alta entropía devuelto al dispositivo que realiza el sondeo."
      },
      user_code: {
        label: "Código de usuario",
        help: "Código corto visible para el usuario (p. ej. ABCD-EFGH)."
      },
      user_id: {
        label: "Usuario",
        help: "Usuario que aprobó la autorización del dispositivo."
      },
      expires_at: {
        label: "Caduca el",
        help: "Momento en que los códigos de dispositivo y de usuario dejan de ser válidos."
      },
      status: {
        label: "Estado",
        help: "Estado actual: 'pending' | 'approved' | 'denied'."
      },
      last_polled_at: {
        label: "Último sondeo el",
        help: "Marca temporal del sondeo /device/token más reciente."
      },
      polling_interval: {
        label: "Intervalo de sondeo (ms)",
        help: "Intervalo mínimo de sondeo recomendado por el servidor, en ms."
      },
      client_id: {
        label: "ID de cliente",
        help: "Identificador de cliente OAuth del dispositivo solicitante."
      },
      scope: {
        label: "Ámbito",
        help: "Ámbitos OAuth solicitados por el dispositivo, separados por espacios."
      }
    }
  },
  sys_user_preference: {
    label: "Preferencia de usuario",
    pluralLabel: "Preferencias de usuario",
    description: "Preferencias clave-valor por usuario (tema, idioma, etc.)",
    fields: {
      id: {
        label: "ID de preferencia"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      },
      user_id: {
        label: "Usuario",
        help: "Usuario propietario de esta preferencia."
      },
      key: {
        label: "Clave",
        help: "Clave de preferencia (p. ej., theme, locale, plugin.ai.auto_save)."
      },
      value: {
        label: "Valor",
        help: "Valor de la preferencia (cualquier tipo serializable en JSON)."
      }
    },
    _views: {
      mine: {
        label: "Mis preferencias"
      },
      by_user: {
        label: "Por usuario"
      },
      all_preferences: {
        label: "Todas"
      }
    }
  },
  sys_oauth_application: {
    label: "Aplicación OAuth",
    pluralLabel: "Aplicaciones OAuth",
    description: "Aplicaciones cliente OAuth/OIDC registradas",
    fields: {
      id: {
        label: "ID"
      },
      name: {
        label: "Nombre"
      },
      icon: {
        label: "Icono",
        help: "URL del logotipo que se muestra en la pantalla de consentimiento."
      },
      uri: {
        label: "URI de inicio",
        help: "Página principal pública del cliente registrado."
      },
      contacts: {
        label: "Contactos",
        help: "Lista serializada en JSON de direcciones de correo electrónico de contacto."
      },
      tos: {
        label: "Términos del servicio"
      },
      policy: {
        label: "Política de privacidad"
      },
      metadata: {
        label: "Metadatos",
        help: "Metadatos de la aplicación serializados en JSON."
      },
      client_id: {
        label: "ID de cliente",
        help: "Identificador público del cliente OAuth."
      },
      client_secret: {
        label: "Secreto de cliente",
        help: "Secreto del cliente OAuth (con hash/cifrado en reposo)."
      },
      redirect_uris: {
        label: "URI de redirección",
        help: "Lista serializada en JSON de URI de redirección permitidas."
      },
      post_logout_redirect_uris: {
        label: "URI de redirección tras el cierre de sesión",
        help: "Lista serializada en JSON de URI de redirección permitidas tras el cierre de sesión."
      },
      type: {
        label: "Tipo de cliente",
        options: {
          web: "Web",
          native: "Nativa",
          useragentbased: "Basada en agente de usuario",
          public: "Público"
        }
      },
      public: {
        label: "Cliente público",
        help: "Marca al cliente como cliente OAuth público (no confidencial)."
      },
      require_pkce: {
        label: "Requerir PKCE"
      },
      token_endpoint_auth_method: {
        label: "Método de autenticación del endpoint de token",
        help: "p. ej. client_secret_basic, client_secret_post, none"
      },
      grant_types: {
        label: "Tipos de concesión",
        help: "Lista serializada en JSON de tipos de concesión permitidos."
      },
      response_types: {
        label: "Tipos de respuesta",
        help: "Lista serializada en JSON de tipos de respuesta permitidos."
      },
      scopes: {
        label: "Ámbitos permitidos",
        help: "Lista serializada en JSON de ámbitos que el cliente puede solicitar."
      },
      subject_type: {
        label: "Tipo de sujeto",
        help: "Tipo de sujeto OIDC (p. ej. public, pairwise)."
      },
      jwks: {
        label: "JWKS",
        help: "Client JSON Web Key Set (for private_key_jwt / signed-request verification)"
      },
      jwks_uri: {
        label: "JWKS URI",
        help: "URL of the client JSON Web Key Set"
      },
      dpop_bound_access_tokens: {
        label: "DPoP-bound Access Tokens",
        help: "Require access tokens issued to this client to be DPoP-bound (RFC 9449)"
      },
      disabled: {
        label: "Deshabilitado"
      },
      skip_consent: {
        label: "Omitir consentimiento",
        help: "Tratar como cliente de confianza y omitir la pantalla de consentimiento."
      },
      enable_end_session: {
        label: "Habilitar finalización de sesión",
        help: "Permitir que el cliente llame al endpoint OIDC de finalización de sesión."
      },
      backchannel_logout_uri: {
        label: "Back-channel Logout URI",
        help: "OIDC back-channel logout endpoint of the client"
      },
      backchannel_logout_session_required: {
        label: "Back-channel Logout Session Required",
        help: "Whether the back-channel logout token must include a sid claim"
      },
      software_id: {
        label: "ID de software"
      },
      software_version: {
        label: "Versión del software"
      },
      software_statement: {
        label: "Declaración de software",
        help: "JWT firmado que declara los metadatos del cliente (RFC 7591 §2.3)."
      },
      user_id: {
        label: "Usuario propietario",
        help: "Usuario que registró esta aplicación."
      },
      reference_id: {
        label: "ID de referencia",
        help: "Identificador de correlación proporcionado por quien llama."
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    },
    _views: {
      mine: {
        label: "My Applications"
      },
      active: {
        label: "Activo"
      },
      disabled_apps: {
        label: "Deshabilitado"
      },
      all_apps: {
        label: "Todas"
      }
    },
    _actions: {
      disable_oauth_application: {
        label: "Deshabilitar aplicación OAuth",
        description: "¿Deshabilitar esta aplicación OAuth? Los tokens de acceso/actualización activos emitidos para ella seguirán siendo rechazados en los endpoints token, authorize e introspect. Las integraciones existentes dejarán de funcionar de inmediato.",
        successMessage: "Aplicación OAuth deshabilitada"
      },
      enable_oauth_application: {
        label: "Habilitar aplicación OAuth",
        description: "¿Volver a habilitar esta aplicación OAuth? La emisión de tokens, la autorización y la introspección se reanudarán de inmediato.",
        successMessage: "Aplicación OAuth habilitada"
      },
      create_oauth_application: {
        label: "Registrar aplicación OAuth",
        params: {
          name: {
            label: "Nombre de la aplicación"
          },
          redirectURLs: {
            label: "URLs de redirección",
            helpText: "Una URL por línea. Debe usar https:// en producción."
          },
          type: {
            label: "Tipo de aplicación",
            options: {
              web: "Web",
              native: "Nativa",
              "user-agent-based": "Basada en user-agent",
              public: "Pública"
            }
          }
        },
        resultDialog: {
          title: "Aplicación OAuth registrada",
          description: "Guarde el client_secret ahora: se muestra una sola vez y no se puede recuperar. Puede rotarlo más adelante si se filtra.",
          acknowledge: "He guardado el secreto de cliente",
          fields: {
            "client.client_id": "ID de cliente",
            "client.client_secret": "Secreto de cliente"
          }
        }
      },
      rotate_client_secret: {
        label: "Rotar Client Secret",
        description: "¿Rotar el secreto de este cliente OAuth? El secreto anterior dejará de funcionar de inmediato y cualquier integración que lo utilice fallará hasta que se actualice con el nuevo secreto. El nuevo secreto se muestra una sola vez.",
        resultDialog: {
          title: "Secreto de cliente rotado",
          description: "Guarde el nuevo secreto ahora: se muestra una sola vez. Actualice todas las integraciones antes de que termine el periodo de gracia del secreto anterior.",
          acknowledge: "He actualizado mis integraciones",
          fields: {
            client_secret: "Nuevo secreto de cliente"
          }
        }
      },
      delete_oauth_application: {
        label: "Eliminar aplicación OAuth",
        description: "¿Eliminar de forma permanente esta aplicación OAuth? Todos los tokens y consentimientos emitidos quedarán invalidados y las integraciones que usen este client_id dejarán de funcionar de inmediato. Esta acción no se puede deshacer.",
        successMessage: "Aplicación OAuth eliminada"
      }
    }
  },
  sys_oauth_access_token: {
    label: "Token de acceso OAuth",
    pluralLabel: "Tokens de acceso OAuth",
    description: "Tokens de acceso OAuth opacos emitidos a aplicaciones cliente.",
    fields: {
      id: {
        label: "ID"
      },
      token: {
        label: "Token",
        help: "Valor opaco del token de acceso."
      },
      client_id: {
        label: "ID de cliente",
        help: "Clave foránea a sys_oauth_application.client_id."
      },
      session_id: {
        label: "Sesión",
        help: "Clave foránea a sys_session.id."
      },
      user_id: {
        label: "Usuario",
        help: "Clave foránea a sys_user.id."
      },
      refresh_id: {
        label: "Token de actualización",
        help: "Clave foránea a sys_oauth_refresh_token.id."
      },
      reference_id: {
        label: "ID de referencia",
        help: "Identificador de correlación proporcionado por quien llama."
      },
      authorization_code_id: {
        label: "Authorization Code ID",
        help: "ID of the authorization-code grant this token originates from"
      },
      resources: {
        label: "Resources",
        help: "JSON-serialized list of RFC 8707 resource indicators bound to this token"
      },
      requested_user_info_claims: {
        label: "Requested UserInfo Claims",
        help: "JSON-serialized list of OIDC claims requested for the userinfo endpoint"
      },
      scopes: {
        label: "Ámbitos",
        help: "Lista serializada en JSON de ámbitos concedidos a este token."
      },
      expires_at: {
        label: "Caduca el"
      },
      created_at: {
        label: "Creado el"
      },
      revoked: {
        label: "Revoked At",
        help: "Timestamp at which this access token was revoked"
      },
      confirmation: {
        label: "Confirmation",
        help: "JSON RFC 7800 cnf claim (e.g. DPoP key thumbprint) binding this token to a key"
      }
    }
  },
  sys_oauth_refresh_token: {
    label: "Token de actualización OAuth",
    pluralLabel: "Tokens de actualización OAuth",
    description: "Tokens de actualización OAuth opacos (vinculados a una sesión).",
    fields: {
      id: {
        label: "ID"
      },
      token: {
        label: "Token",
        help: "Valor opaco del token de actualización."
      },
      client_id: {
        label: "ID de cliente",
        help: "Clave foránea a sys_oauth_application.client_id."
      },
      session_id: {
        label: "Sesión",
        help: "Clave foránea a sys_session.id."
      },
      user_id: {
        label: "Usuario",
        help: "Clave foránea a sys_user.id."
      },
      reference_id: {
        label: "ID de referencia",
        help: "Identificador de correlación proporcionado por quien llama."
      },
      authorization_code_id: {
        label: "Authorization Code ID",
        help: "ID of the authorization-code grant this token chain originates from"
      },
      resources: {
        label: "Resources",
        help: "JSON-serialized list of RFC 8707 resource indicators bound to this token"
      },
      requested_user_info_claims: {
        label: "Requested UserInfo Claims",
        help: "JSON-serialized list of OIDC claims requested for the userinfo endpoint"
      },
      scopes: {
        label: "Ámbitos",
        help: "Lista serializada en JSON de ámbitos concedidos a este token."
      },
      expires_at: {
        label: "Caduca el"
      },
      created_at: {
        label: "Creado el"
      },
      revoked: {
        label: "Revocado el",
        help: "Marca temporal en la que se revocó este token de actualización."
      },
      rotated_at: {
        label: "Rotated At",
        help: "Timestamp at which this token was rotated (superseded by a new row)"
      },
      rotation_replay_response: {
        label: "Rotation Replay Response",
        help: "Cached token response replayed when the old token is re-presented within the reuse interval"
      },
      rotation_replay_expires_at: {
        label: "Rotation Replay Expires At",
        help: "End of the post-rotation reuse interval during which the replay response is served"
      },
      auth_time: {
        label: "Hora de autenticación",
        help: "Momento en que el usuario se autenticó originalmente para esta cadena de tokens."
      },
      confirmation: {
        label: "Confirmation",
        help: "JSON RFC 7800 cnf claim (e.g. DPoP key thumbprint) binding this token to a key"
      }
    }
  },
  sys_oauth_consent: {
    label: "Consentimiento OAuth",
    pluralLabel: "Consentimientos OAuth",
    description: "Registros de consentimiento de usuario para aplicaciones cliente OAuth.",
    fields: {
      id: {
        label: "ID"
      },
      client_id: {
        label: "ID de cliente",
        help: "Clave foránea a sys_oauth_application.client_id."
      },
      user_id: {
        label: "Usuario",
        help: "Clave foránea a sys_user.id."
      },
      reference_id: {
        label: "ID de referencia",
        help: "Identificador de correlación proporcionado por quien llama."
      },
      resources: {
        label: "Resources",
        help: "JSON-serialized list of RFC 8707 resource indicators the consent covers"
      },
      requested_user_info_claims: {
        label: "Requested UserInfo Claims",
        help: "JSON-serialized list of OIDC claims the user consented to expose"
      },
      scopes: {
        label: "Ámbitos",
        help: "Lista serializada en JSON de ámbitos a los que el usuario dio consentimiento."
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    }
  },
  sys_oauth_resource: {
    label: "OAuth Resource",
    pluralLabel: "OAuth Resources",
    description: "Registered OAuth protected resources (RFC 8707 resource indicators)",
    fields: {
      id: {
        label: "ID"
      },
      identifier: {
        label: "Identifier",
        help: "Resource indicator URI presented in the RFC 8707 resource parameter"
      },
      name: {
        label: "Name"
      },
      access_token_ttl: {
        label: "Access Token TTL",
        help: "Access-token lifetime in seconds for this resource (overrides the server default)"
      },
      refresh_token_ttl: {
        label: "Refresh Token TTL",
        help: "Refresh-token lifetime in seconds for this resource (overrides the server default)"
      },
      signing_algorithm: {
        label: "Signing Algorithm",
        help: "JWS algorithm used to sign access tokens for this resource"
      },
      signing_key_id: {
        label: "Signing Key ID",
        help: "Key id (kid) used to sign access tokens for this resource"
      },
      allowed_scopes: {
        label: "Allowed Scopes",
        help: "JSON-serialized list of scopes clients may request for this resource"
      },
      custom_claims: {
        label: "Custom Claims",
        help: "JSON object of extra claims stamped on access tokens for this resource"
      },
      dpop_bound_access_tokens_required: {
        label: "DPoP Required",
        help: "Require access tokens for this resource to be DPoP-bound (RFC 9449)"
      },
      disabled: {
        label: "Disabled"
      },
      policy_version: {
        label: "Policy Version",
        help: "Monotonic version of the resource token policy"
      },
      metadata: {
        label: "Metadata",
        help: "JSON object of additional resource metadata"
      },
      created_at: {
        label: "Created At"
      },
      updated_at: {
        label: "Updated At"
      }
    }
  },
  sys_oauth_client_resource: {
    label: "OAuth Client Resource",
    pluralLabel: "OAuth Client Resources",
    description: "Grants allowing an OAuth client to request tokens for a protected resource",
    fields: {
      id: {
        label: "ID"
      },
      client_id: {
        label: "Client ID",
        help: "Foreign key to sys_oauth_application.client_id"
      },
      resource_id: {
        label: "Resource ID",
        help: "Foreign key to sys_oauth_resource.identifier"
      },
      metadata: {
        label: "Metadata",
        help: "JSON object of additional grant metadata"
      },
      created_at: {
        label: "Created At"
      }
    }
  },
  sys_oauth_client_assertion: {
    label: "OAuth Client Assertion",
    pluralLabel: "OAuth Client Assertions",
    description: "Consumed OAuth client-assertion JTIs (RFC 7523 replay prevention)",
    fields: {
      id: {
        label: "ID"
      },
      expires_at: {
        label: "Expires At",
        help: "Assertion expiry — rows past this instant are safe to prune"
      }
    }
  },
  sys_jwks: {
    label: "Clave de firma (JWKS)",
    pluralLabel: "Claves de firma (JWKS)",
    description: "Pares de claves asimétricas utilizados para firmar y verificar los JWT emitidos.",
    fields: {
      id: {
        label: "ID de clave",
        help: "Valor `kid` de JWK."
      },
      public_key: {
        label: "Clave pública",
        help: "Clave pública JWK serializada en JSON."
      },
      private_key: {
        label: "Clave privada",
        help: "Clave privada JWK serializada en JSON (cifrada en reposo)."
      },
      alg: {
        label: "Algoritmo",
        help: "Algoritmo de firma JWK, p. ej. `EdDSA` (better-auth 1.7+)"
      },
      crv: {
        label: "Curva",
        help: "Curva JWK para claves EdDSA/EC, p. ej. `Ed25519` (better-auth 1.7+)"
      },
      created_at: {
        label: "Creado el"
      },
      expires_at: {
        label: "Caduca el",
        help: "Momento en que la clave ya no podrá utilizarse para verificar tokens."
      }
    }
  },
  sys_sso_provider: {
    label: "Proveedor SSO",
    pluralLabel: "Proveedores SSO",
    description: "Proveedores de identidad SSO externos (OIDC / SAML) a los que este entorno federa el inicio de sesión",
    fields: {
      id: {
        label: "ID"
      },
      provider_id: {
        label: "ID de proveedor",
        help: "Identificador de proveedor estable (único dentro del entorno)"
      },
      issuer: {
        label: "Emisor",
        help: "URL del emisor del IdP"
      },
      domain: {
        label: "Dominio de correo",
        help: "Dominio de correo enrutado a este IdP (p. ej. acme.com)"
      },
      domain_verified: {
        label: "Dominio verificado",
        help: "Si se ha probado la propiedad DNS del dominio de correo (ADR-0024 ②). Lo establece «Verificar dominio» tras resolverse el registro DNS TXT. Gestionado por better-auth: no editable directamente. Solo se aplica cuando la verificación de dominio está habilitada para el entorno."
      },
      oidc_config: {
        label: "Configuración OIDC",
        help: "JSON: clientId, clientSecret, endpoints, scopes, mapeo, pkce (gestionado por better-auth)"
      },
      saml_config: {
        label: "Configuración SAML",
        help: "JSON: entryPoint, cert, identifierFormat, mapeo (gestionado por better-auth)"
      },
      user_id: {
        label: "Registrado por",
        help: "Usuario que registró este proveedor"
      },
      organization_id: {
        label: "Organización",
        help: "Ámbito de organización (cuando se usa SSO por organización)"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    },
    _views: {
      all: {
        label: "Todos",
        emptyState: {
          title: "Aún no hay proveedores SSO",
          message: "Registre el IdP externo de su organización: OIDC (Okta, Entra, Auth0, …) con «Registrar proveedor SSO», o SAML 2.0 con «Registrar proveedor SAML». Los miembros cuyo dominio de correo coincida podrán iniciar sesión a través de él."
        }
      }
    },
    _actions: {
      register_sso_provider: {
        label: "Registrar proveedor SSO",
        params: {
          providerId: {
            label: "ID de proveedor",
            helpText: "Identificador estable, p. ej. «okta» o «acme-entra»."
          },
          issuer: {
            label: "URL del emisor",
            helpText: "Emisor del IdP, p. ej. https://acme.okta.com. El descubrimiento se obtiene de aquí salvo que se indique una URL explícita abajo."
          },
          domain: {
            label: "Dominio de correo",
            helpText: "Los usuarios con este dominio de correo se enrutan a este IdP, p. ej. acme.com."
          },
          clientId: {
            label: "ID de cliente",
            helpText: "ID de cliente OAuth emitido por el IdP para este entorno."
          },
          clientSecret: {
            label: "Secreto de cliente",
            helpText: "Secreto de cliente OAuth (almacenado cifrado por better-auth)."
          },
          discoveryEndpoint: {
            label: "URL de descubrimiento",
            helpText: "Opcional. URL del documento de descubrimiento OIDC. Déjelo en blanco para derivar `<issuer>/.well-known/openid-configuration`."
          },
          scopes: {
            label: "Ámbitos (scopes)",
            helpText: "Opcional. Ámbitos OAuth separados por espacios o comas. Valor predeterminado: «openid email profile».",
            placeholder: "openid email profile"
          },
          mapId: {
            label: "Mapeo: reclamo de ID de usuario",
            helpText: "Opcional. Reclamo del token de ID asignado al ID de usuario. Valor predeterminado: «sub».",
            placeholder: "sub"
          },
          mapEmail: {
            label: "Mapeo: reclamo de correo",
            helpText: "Opcional. Reclamo asignado al correo. Valor predeterminado: «email».",
            placeholder: "email"
          },
          mapName: {
            label: "Mapeo: reclamo de nombre",
            helpText: "Opcional. Reclamo asignado al nombre visible. Valor predeterminado: «name».",
            placeholder: "name"
          }
        }
      },
      register_saml_provider: {
        label: "Registrar proveedor SAML",
        params: {
          providerId: {
            label: "ID de proveedor",
            helpText: "Identificador estable, p. ej. «acme-saml»."
          },
          issuer: {
            label: "ID de entidad del IdP",
            helpText: "El EntityID SAML del IdP (emisor), p. ej. https://saml.acme.com/entityid."
          },
          domain: {
            label: "Dominio de correo",
            helpText: "Los usuarios con este dominio de correo se enrutan a este IdP, p. ej. acme.com."
          },
          entryPoint: {
            label: "URL de SSO del IdP",
            helpText: "Endpoint de inicio de sesión único (redirección) SAML del IdP que recibe la SAMLRequest."
          },
          cert: {
            label: "Certificado de firma del IdP",
            helpText: "Certificado de firma X.509 del IdP (cuerpo PEM). Se usa para verificar las firmas de las aserciones."
          },
          identifierFormat: {
            label: "Formato de NameID",
            helpText: "Opcional. Formato de NameID SAML solicitado. Por defecto, el formato configurado en el IdP.",
            placeholder: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"
          }
        }
      },
      request_domain_verification: {
        label: "Solicitar verificación de dominio",
        resultDialog: {
          title: "Verifique su dominio",
          description: "Añada el siguiente registro DNS TXT en el proveedor DNS de su dominio y luego ejecute «Verificar dominio». El token se muestra una sola vez.",
          acknowledge: "Hecho",
          fields: {
            dnsRecordType: "Tipo de registro",
            dnsRecordName: "Nombre / Host",
            dnsRecordValue: "Valor"
          }
        }
      },
      verify_domain: {
        label: "Verificar dominio",
        successMessage: "Propiedad del dominio verificada"
      },
      delete_sso_provider: {
        label: "Eliminar proveedor SSO",
        description: "¿Eliminar este proveedor SSO? Los usuarios de su dominio ya no podrán iniciar sesión a través de él.",
        successMessage: "Proveedor SSO eliminado"
      }
    }
  },
  sys_scim_provider: {
    label: "Proveedor SCIM",
    pluralLabel: "Proveedores SCIM",
    description: "Conexiones SCIM 2.0 (tokens bearer) que los IdP externos usan para aprovisionar/desaprovisionar los usuarios de este entorno",
    fields: {
      id: {
        label: "ID"
      },
      provider_id: {
        label: "ID de proveedor",
        help: "Identificador de proveedor SCIM estable (p. ej. «okta-scim»)"
      },
      provider_key: {
        label: "Provider Key",
        help: "Derived <organization>:<provider_id> uniqueness key maintained by @better-auth/scim; do not write directly."
      },
      scim_token: {
        label: "Token SCIM (hash)",
        help: "Credencial bearer con hash de esta conexión SCIM: el texto plano se muestra una sola vez al generar el token. Sensible; no lo exponga."
      },
      organization_id: {
        label: "Organización",
        help: "Ámbito de organización de este token (los tokens por organización limitan el aprovisionamiento a esa organización)"
      },
      user_id: {
        label: "Propiedad de",
        help: "Usuario que generó este token (cuando la propiedad de proveedor está habilitada)"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    },
    _views: {
      all: {
        label: "Todos"
      }
    }
  },
  sys_notification: {
    label: "Notificación",
    pluralLabel: "Notificaciones",
    description: "Entradas del buzón de notificaciones por usuario",
    fields: {
      id: {
        label: "ID de notificación"
      },
      topic: {
        label: "Topic",
        help: "Notification topic, e.g. task.assigned, collab.mention"
      },
      payload: {
        label: "Payload",
        help: "Template inputs carried to channels (title/body/url/actor/source/…)"
      },
      severity: {
        label: "Severity",
        help: "Severity hint for rendering / filtering",
        options: {
          info: "info",
          warning: "warning",
          critical: "critical"
        }
      },
      dedup_key: {
        label: "Dedup Key",
        help: "Idempotency key within a topic window; a repeat emit is a no-op"
      },
      source_object: {
        label: "Objeto de origen",
        help: "Nombre del objeto del registro relacionado (p. ej. lead, opportunity)."
      },
      source_id: {
        label: "Registro de origen",
        help: "ID del registro dentro de source_object."
      },
      actor_id: {
        label: "Actor",
        help: "Usuario que provocó la notificación (quien menciona, quien asigna)."
      },
      created_at: {
        label: "Creado el"
      }
    },
    _views: {
      recent: {
        label: "Recent",
        emptyState: {
          title: "No events",
          message: "No notification events have been emitted."
        }
      },
      by_topic: {
        label: "By Topic"
      }
    }
  },
  sys_attachment: {
    label: "Adjunto",
    pluralLabel: "Adjuntos",
    description: "Vínculo polimórfico entre un sys_file y cualquier otro registro.",
    fields: {
      id: {
        label: "ID de adjunto"
      },
      parent_object: {
        label: "Objeto principal",
        help: "Nombre corto del objeto del registro adjunto (p. ej. account, lead)."
      },
      parent_id: {
        label: "Registro principal",
        help: "Clave primaria del registro al que se adjunta."
      },
      file_id: {
        label: "Archivo",
        help: "Entrada de almacenamiento sys_file que se está adjuntando."
      },
      file_name: {
        label: "Nombre del archivo",
        help: "Copia desnormalizada de sys_file.name para renderizado rápido de listas."
      },
      mime_type: {
        label: "Tipo MIME"
      },
      size: {
        label: "Tamaño (bytes)"
      },
      uploaded_by: {
        label: "Subido por"
      },
      description: {
        label: "Descripción"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    }
  },
  sys_email: {
    label: "Correo",
    pluralLabel: "Correos",
    description: "Registro de envíos de correo salientes",
    fields: {
      id: {
        label: "ID de correo"
      },
      message_id: {
        label: "Message-ID",
        help: "Message-ID RFC-5322 asignado por el transporte."
      },
      from_address: {
        label: "De"
      },
      to_addresses: {
        label: "Para",
        help: "Direcciones de destinatarios separadas por comas."
      },
      cc_addresses: {
        label: "Cc"
      },
      bcc_addresses: {
        label: "Cco"
      },
      reply_to: {
        label: "Responder a"
      },
      subject: {
        label: "Asunto"
      },
      body_text: {
        label: "Contenido (texto)"
      },
      body_html: {
        label: "Contenido (HTML)"
      },
      headers_json: {
        label: "Cabeceras (JSON)",
        help: "Cabeceras personalizadas facilitadas a IEmailService.send, como un objeto JSON de nombre → valor. Se escriben en ambos modos de entrega (son tanto evidencia de auditoría como entrada de la entrega). Ausentes en las filas escritas antes de que existiera esta columna, que se leen como «sin cabeceras personalizadas»."
      },
      attachments_json: {
        label: "Adjuntos (JSON)",
        help: "Adjuntos como un array JSON de { filename, contentType?, size, hash, cid?, contentForm, inline?, storageKey?, contentReclaimedAt? }. El contenido que cabe en el presupuesto de plugin-email (SYS_EMAIL_ATTACHMENT_LIMIT_BYTES, 256 KiB brutos combinados — ~350 KB de base64 en el peor caso) va en base64 en `inline`; el contenido mayor se guarda en la capacidad file-storage y el elemento lleva `storageKey` en su lugar, de modo que la fila permanece acotada en ambos casos. filename/contentType/size/hash son evidencia de auditoría PERMANENTE; el contenido fuera de la fila es un artefacto de entrega y se elimina tras un periodo de gracia una vez que la fila alcanza un estado terminal, momento en el que `storageKey` se sustituye por `contentReclaimedAt`."
      },
      status: {
        label: "Estado",
        help: "Estado del ciclo de vida; se pone en cola mediante IEmailService.send antes de la llamada al transporte.",
        options: {
          queued: "En cola",
          sent: "Enviado",
          failed: "Fallido"
        }
      },
      error: {
        label: "Error",
        help: "Mensaje de error del transporte cuando status=failed."
      },
      attempt_count: {
        label: "Intentos",
        help: "Número de intentos de entrega realizados por el servicio."
      },
      sent_at: {
        label: "Enviado el",
        help: "Se establece cuando el estado pasa a \"sent\"."
      },
      related_object: {
        label: "Objeto relacionado",
        help: "Nombre del objeto del registro relacionado (p. ej. lead, opportunity)."
      },
      related_id: {
        label: "Registro relacionado",
        help: "ID del registro dentro de related_object."
      },
      sent_by: {
        label: "Enviado por"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    }
  },
  sys_email_template: {
    label: "Plantilla de correo",
    pluralLabel: "Plantillas de correo",
    description: "Plantilla de correo saliente (asunto + contenido + variables) resuelta por nombre+idioma",
    fields: {
      id: {
        label: "ID"
      },
      name: {
        label: "Nombre",
        help: "Identificador snake_case con puntos (p. ej. auth.password_reset)."
      },
      label: {
        label: "Nombre visible",
        help: "Nombre legible que se muestra en Studio."
      },
      category: {
        label: "Categoría",
        options: {
          auth: "Autenticación",
          notification: "Notificación",
          workflow: "Flujo de trabajo",
          marketing: "Marketing",
          custom: "Personalizado"
        }
      },
      locale: {
        label: "Idioma",
        help: "Etiqueta de idioma BCP-47 (en-US, zh-CN, …)."
      },
      description: {
        label: "Descripción"
      },
      subject: {
        label: "Asunto",
        help: "Plantilla de asunto; admite marcadores {{var.path}}."
      },
      body_html: {
        label: "Contenido HTML",
        help: "Plantilla HTML del contenido; admite marcadores {{var.path}}."
      },
      body_text: {
        label: "Contenido de texto sin formato",
        help: "Alternativa opcional en texto sin formato (se deriva automáticamente del HTML cuando está vacía)."
      },
      from_name: {
        label: "Nombre del remitente"
      },
      from_address: {
        label: "Dirección del remitente"
      },
      reply_to: {
        label: "Responder a"
      },
      active: {
        label: "Activo"
      },
      is_system: {
        label: "Plantilla del sistema",
        help: "La proporciona un plugin o la plataforma; los tenants pueden editarla, pero no deberían eliminarla."
      },
      variables_json: {
        label: "Variables (JSON)",
        help: "Matriz JSON de {name,type,required,description}."
      },
      managed_by: {
        label: "Managed By",
        help: "Record provenance: platform = framework built-in / package = app/package-declared (boot-seeded from declared email_template metadata) / admin = created in Studio.",
        options: {
          platform: "platform",
          package: "package",
          admin: "admin"
        }
      },
      customized: {
        label: "Customized",
        help: "Set when an admin edits a package-declared template; boot seeding will no longer overwrite the row (a reworded password-reset mail survives redeploys). Meaningless on admin rows."
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    }
  },
  sys_saved_report: {
    label: "Informe guardado",
    pluralLabel: "Informes guardados",
    description: "Definición de informe ObjectQL persistida; se puede volver a ejecutar y programar",
    fields: {
      id: {
        label: "ID de informe"
      },
      name: {
        label: "Nombre"
      },
      description: {
        label: "Descripción"
      },
      object_name: {
        label: "Objeto",
        help: "Nombre corto del objeto que consulta el informe."
      },
      query_json: {
        label: "Consulta",
        help: "Envoltorio de consulta ObjectQL: { filter, fields, orderBy, limit, groupBy }."
      },
      format: {
        label: "Formato",
        help: "Renderizado utilizado por IReportService.run() y los resúmenes por correo.",
        options: {
          csv: "CSV",
          json: "JSON",
          html_table: "Tabla HTML"
        }
      },
      owner_id: {
        label: "Propietario",
        help: "Usuario propietario de la definición del informe (controla la compartición)."
      },
      last_run_at: {
        label: "Última ejecución",
        help: "Marcado por IReportService.run() tras una ejecución correcta."
      },
      last_row_count: {
        label: "Último recuento de filas"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    }
  },
  sys_report_schedule: {
    label: "Programación de informe",
    pluralLabel: "Programaciones de informes",
    description: "Entrega recurrente de un sys_saved_report por correo electrónico",
    fields: {
      id: {
        label: "ID de programación"
      },
      report_id: {
        label: "Informe"
      },
      name: {
        label: "Nombre",
        help: "Nombre visible opcional para el resumen; se usa en el asunto del correo."
      },
      interval_minutes: {
        label: "Intervalo (minutos)",
        help: "Frecuencia de envío (1440 = diario, 10080 = semanal)."
      },
      cron_expression: {
        label: "Expresión Cron",
        help: "Cron opcional de 5/6 campos; sustituye a interval_minutes cuando está presente."
      },
      timezone: {
        label: "Zona horaria"
      },
      active: {
        label: "Activo"
      },
      recipients: {
        label: "Destinatarios",
        help: "Direcciones de correo electrónico separadas por comas."
      },
      format: {
        label: "Formato",
        help: "Formato de renderizado; csv se adjunta y html_table se inserta en línea.",
        options: {
          csv: "CSV",
          html_table: "Tabla HTML"
        }
      },
      subject_template: {
        label: "Plantilla de asunto",
        help: "Asunto del correo; se sustituyen {{name}} / {{date}} / {{rows}}."
      },
      owner_id: {
        label: "Propietario"
      },
      next_run_at: {
        label: "Próxima ejecución",
        help: "El despachador carga las programaciones cuyo next_run_at <= now."
      },
      last_sent_at: {
        label: "Último envío"
      },
      last_status: {
        label: "Último estado",
        options: {
          ok: "Correcto",
          failed: "Fallido",
          skipped: "Omitido"
        }
      },
      last_error: {
        label: "Último error"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    }
  },
  sys_job: {
    label: "Tarea en segundo plano",
    pluralLabel: "Tareas en segundo plano",
    description: "Catálogo de tareas en segundo plano registradas",
    fields: {
      id: {
        label: "ID de tarea"
      },
      name: {
        label: "Nombre de la tarea",
        help: "Identificador único de tarea (snake_case)."
      },
      schedule_type: {
        label: "Tipo de programación",
        options: {
          cron: "Cron",
          interval: "Intervalo",
          once: "Una vez"
        }
      },
      schedule_expression: {
        label: "Expresión",
        help: "Expresión Cron / intervalo en ms / fecha-hora ISO."
      },
      timezone: {
        label: "Zona horaria"
      },
      active: {
        label: "Activo",
        help: "Indica si el programador está ejecutando actualmente esta tarea."
      },
      last_run_at: {
        label: "Última ejecución el"
      },
      last_status: {
        label: "Último estado",
        options: {
          success: "Correcto",
          failed: "Fallido",
          timeout: "Tiempo de espera agotado",
          running: "En ejecución",
          degraded: "Degradado"
        }
      },
      last_error: {
        label: "Último error"
      },
      run_count: {
        label: "Número de ejecuciones"
      },
      failure_count: {
        label: "Número de fallos"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    }
  },
  sys_job_run: {
    label: "Ejecución de tarea",
    pluralLabel: "Ejecuciones de tarea",
    description: "Registro de auditoría de ejecución de tareas en segundo plano",
    fields: {
      id: {
        label: "ID de ejecución"
      },
      job_name: {
        label: "Tarea"
      },
      status: {
        label: "Estado",
        options: {
          running: "En ejecución",
          success: "Correcto",
          failed: "Fallido",
          timeout: "Tiempo de espera agotado",
          degraded: "Degradado"
        }
      },
      started_at: {
        label: "Iniciada el"
      },
      completed_at: {
        label: "Completado el"
      },
      duration_ms: {
        label: "Duración (ms)"
      },
      attempt: {
        label: "Intento",
        help: "1 para la primera ejecución, >1 para reintentos/repeticiones."
      },
      trigger: {
        label: "Desencadenante",
        options: {
          schedule: "Programación",
          manual: "Manual",
          replay: "Repetición"
        }
      },
      error: {
        label: "Error"
      },
      created_at: {
        label: "Creado el"
      }
    }
  },
  sys_job_queue: {
    label: "Mensaje de la cola de tareas",
    pluralLabel: "Mensajes de la cola de tareas",
    description: "Cola duradera de tareas/mensajes, incluidos los mensajes fallidos (dead letters).",
    fields: {
      id: {
        label: "ID de mensaje"
      },
      queue: {
        label: "Cola",
        help: "Nombre lógico de la cola (snake_case)."
      },
      idempotency_key: {
        label: "Clave de idempotencia",
        help: "Clave de deduplicación dentro de (queue, window)."
      },
      payload_json: {
        label: "Carga útil (JSON)",
        help: "Cuerpo del mensaje serializado."
      },
      metadata_json: {
        label: "Metadatos (JSON)",
        help: "Bolsa de metadatos serializada (tenant_id, source_record, ...)."
      },
      status: {
        label: "Estado",
        help: "Estado del ciclo de vida.",
        options: {
          pending: "Pendiente",
          running: "En ejecución",
          completed: "Completado",
          failed: "Fallido",
          dlq: "DLQ"
        }
      },
      priority: {
        label: "Prioridad",
        help: "Menor = mayor prioridad."
      },
      attempts: {
        label: "Intentos"
      },
      max_attempts: {
        label: "Intentos máximos"
      },
      backoff_type: {
        label: "Retroceso",
        options: {
          fixed: "Fijo",
          exponential: "Exponencial"
        }
      },
      backoff_delay_ms: {
        label: "Base de backoff (ms)"
      },
      backoff_max_delay_ms: {
        label: "Límite de backoff (ms)"
      },
      scheduled_for: {
        label: "Programado para",
        help: "Momento más temprano en que un worker puede tomar este mensaje en arrendamiento."
      },
      locked_by: {
        label: "Bloqueado por",
        help: "ID del worker que mantiene el arrendamiento."
      },
      locked_until: {
        label: "Bloqueado hasta",
        help: "Caducidad del arrendamiento; si ha pasado, otro worker puede reclamarlo."
      },
      last_error: {
        label: "Último error"
      },
      completed_at: {
        label: "Completado el"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      }
    }
  },
  sys_import_job: {
    label: "Trabajo de importación",
    pluralLabel: "Trabajos de importación",
    description: "Estado, progreso e historial de trabajos de importación masiva asíncrona",
    fields: {
      id: {
        label: "ID de trabajo"
      },
      object_name: {
        label: "Objeto",
        help: "Nombre de API del objeto en el que se importa"
      },
      status: {
        label: "Estado",
        options: {
          pending: "Pendiente",
          running: "En ejecución",
          succeeded: "Completado",
          failed: "Fallido",
          cancelled: "Cancelado"
        }
      },
      total_rows: {
        label: "Filas totales"
      },
      processed_rows: {
        label: "Filas procesadas"
      },
      created_count: {
        label: "Creados"
      },
      updated_count: {
        label: "Actualizados"
      },
      skipped_count: {
        label: "Omitidos"
      },
      error_count: {
        label: "Errores"
      },
      write_mode: {
        label: "Modo de escritura",
        options: {
          insert: "Insertar",
          update: "Actualizar",
          upsert: "Insertar o actualizar"
        }
      },
      dry_run: {
        label: "Simulación"
      },
      run_automations: {
        label: "Ejecutar automatizaciones"
      },
      treat_as_historical: {
        label: "Tratar como histórico"
      },
      error: {
        label: "Error fatal"
      },
      results: {
        label: "Resultados por fila (muestra)",
        help: "Muestra limitada de resultados por fila (primero los fallos) para la interfaz"
      },
      undo_log: {
        label: "Registro de deshacer",
        help: "Instrucciones de reversión ({created:[ids], updated:[{id,before}]}) capturadas para trabajos pequeños que no son simulación, de modo que la importación pueda deshacerse"
      },
      reverted_at: {
        label: "Deshecho el",
        help: "Se establece cuando se deshizo la importación (los registros creados se eliminan, los actualizados se restauran)"
      },
      started_at: {
        label: "Iniciado el"
      },
      completed_at: {
        label: "Completado el"
      },
      created_by: {
        label: "Creado por"
      },
      created_at: {
        label: "Creado el"
      }
    }
  },
  sys_metadata: {
    label: "Metadatos del sistema",
    pluralLabel: "Metadatos del sistema",
    description: "Almacena registros de metadatos de la plataforma y del ámbito de usuario (objetos, vistas, flujos, etc.)",
    fields: {
      id: {
        label: "ID"
      },
      name: {
        label: "Nombre"
      },
      type: {
        label: "Tipo de metadatos"
      },
      namespace: {
        label: "Espacio de nombres"
      },
      package_id: {
        label: "ID del paquete",
        help: "Cadena de ID heredada del manifiesto del paquete. Use package_version_id para los registros nuevos."
      },
      package_version_id: {
        label: "Versión del paquete",
        help: "Clave foránea a sys_package_version (UUID). Null = incorporado en la plataforma o sobrescritura a nivel de entorno."
      },
      managed_by: {
        label: "Gestionado por",
        options: {
          package: "Paquete",
          platform: "Plataforma",
          user: "Usuario"
        }
      },
      scope: {
        label: "Ámbito",
        options: {
          system: "Sistema",
          platform: "Plataforma",
          user: "Usuario"
        }
      },
      metadata: {
        label: "Metadatos",
        help: "Payload de metadatos serializado en JSON."
      },
      extends: {
        label: "Extiende"
      },
      strategy: {
        label: "Estrategia",
        options: {
          merge: "Fusionar",
          replace: "Reemplazar"
        }
      },
      owner: {
        label: "Propietario"
      },
      state: {
        label: "Estado",
        options: {
          draft: "Borrador",
          active: "Activo",
          archived: "Archivado",
          deprecated: "Obsoleto"
        }
      },
      organization_id: {
        label: "Organización",
        help: "Organización para el aislamiento multi-tenant."
      },
      environment_id: {
        label: "Proyecto (obsoleto)",
        help: "OBSOLETO. Use organization_id para el aislamiento del tenant."
      },
      version: {
        label: "Versión"
      },
      checksum: {
        label: "Checksum"
      },
      source: {
        label: "Origen",
        options: {
          filesystem: "Sistema de archivos",
          database: "Base de datos",
          api: "API",
          migration: "Migración"
        }
      },
      tags: {
        label: "Etiquetas",
        help: "Matriz serializada en JSON de etiquetas de clasificación."
      },
      created_by: {
        label: "Creado por"
      },
      created_at: {
        label: "Creado el"
      },
      updated_by: {
        label: "Actualizado por"
      },
      updated_at: {
        label: "Actualizado el"
      }
    },
    _views: {
      only_objects: {
        label: "Objetos"
      },
      only_fields: {
        label: "Campos"
      },
      all_metadata: {
        label: "Todos"
      }
    }
  },
  sys_metadata_history: {
    label: "Historial de metadatos",
    pluralLabel: "Historial de metadatos",
    description: "Historial de versiones y registro de auditoría de cambios de metadatos",
    fields: {
      id: {
        label: "ID"
      },
      event_seq: {
        label: "Secuencia de eventos",
        help: "Cursor monotónico del registro de eventos por organización."
      },
      name: {
        label: "Nombre"
      },
      type: {
        label: "Tipo de metadatos"
      },
      version: {
        label: "Versión"
      },
      operation_type: {
        label: "Tipo de operación",
        options: {
          create: "Crear",
          update: "Actualizar",
          publish: "Publicar",
          revert: "Revertir",
          delete: "Eliminar"
        }
      },
      metadata: {
        label: "Metadatos",
        help: "Instantánea de metadatos serializada en JSON para esta versión."
      },
      checksum: {
        label: "Checksum"
      },
      previous_checksum: {
        label: "Checksum anterior"
      },
      change_note: {
        label: "Nota de cambio",
        help: "Descripción de lo que cambió en esta versión."
      },
      source: {
        label: "Origen"
      },
      organization_id: {
        label: "Organización",
        help: "Organización para el aislamiento multi-tenant."
      },
      recorded_by: {
        label: "Registrado por",
        help: "User who made this change. NULL = system-initiated (boot sync, migration, scheduled job) — never a sentinel string."
      },
      recorded_at: {
        label: "Registrado el"
      }
    }
  },
  sys_view_definition: {
    label: "Definición de vista",
    pluralLabel: "Definiciones de vista",
    description: "Definiciones de vista creadas en tiempo de ejecución (capas compartida / personal). La capa de paquete se distribuye desde el código fuente.",
    fields: {
      id: {
        label: "ID"
      },
      name: {
        label: "Nombre"
      },
      object: {
        label: "Objeto"
      },
      view_kind: {
        label: "Tipo de vista",
        options: {
          list: "Lista",
          form: "Formulario"
        }
      },
      label: {
        label: "Etiqueta"
      },
      is_default: {
        label: "Es predeterminada"
      },
      view_order: {
        label: "Orden"
      },
      scope: {
        label: "Ámbito",
        options: {
          shared: "Compartida",
          personal: "Personal"
        }
      },
      owner: {
        label: "Propietario"
      },
      hidden: {
        label: "Oculta"
      },
      config: {
        label: "Configuración",
        help: "Configuración de ListView o FormView (coincide con ViewItem.config de la especificación)."
      },
      organization_id: {
        label: "Organización",
        help: "Organización para el aislamiento multiinquilino."
      },
      state: {
        label: "Estado",
        options: {
          draft: "Borrador",
          active: "Activa",
          archived: "Archivada"
        }
      },
      created_by: {
        label: "Creado por"
      },
      created_at: {
        label: "Creado el"
      },
      updated_by: {
        label: "Actualizado por"
      },
      updated_at: {
        label: "Actualizado el"
      }
    }
  },
  sys_metadata_audit: {
    label: "Auditoría de metadatos",
    pluralLabel: "Auditoría de metadatos",
    description: "Registro de auditoría de solo adición de las decisiones de escritura de metadatos (ADR-0010).",
    fields: {
      id: {
        label: "ID"
      },
      occurred_at: {
        label: "Ocurrido el"
      },
      actor: {
        label: "Actor",
        help: "Principal que actúa: ID de usuario, ID de sistema o \"system\"."
      },
      source: {
        label: "Origen"
      },
      type: {
        label: "Tipo de metadatos"
      },
      name: {
        label: "Nombre"
      },
      organization_id: {
        label: "Organización"
      },
      operation: {
        label: "Operación",
        options: {
          save: "Guardar",
          publish: "Publicar",
          rollback: "Revertir",
          delete: "Eliminar",
          reset: "Restablecer"
        }
      },
      outcome: {
        label: "Resultado",
        options: {
          allowed: "Permitido",
          denied: "Denegado",
          forced: "Forzado"
        }
      },
      code: {
        label: "Código"
      },
      lock_state: {
        label: "Estado de bloqueo",
        options: {
          none: "Ninguno",
          nooverlay: "no-overlay",
          nodelete: "no-delete",
          full: "Bloqueo total"
        }
      },
      lock_overridden: {
        label: "Bloqueo anulado"
      },
      request_id: {
        label: "ID de solicitud"
      },
      note: {
        label: "Nota"
      }
    }
  },
  sys_setting: {
    label: "Ajuste",
    pluralLabel: "Ajustes",
    description: "Almacén K/V genérico que respalda el contrato SettingsManifest.",
    fields: {
      id: {
        label: "ID de ajuste"
      },
      created_at: {
        label: "Creado el"
      },
      updated_at: {
        label: "Actualizado el"
      },
      namespace: {
        label: "Espacio de nombres",
        help: "Espacio de nombres del manifiesto (p. ej. mail, branding, feature_flags)."
      },
      key: {
        label: "Clave",
        help: "Clave del especificador dentro del espacio de nombres (snake_case)."
      },
      scope: {
        label: "Ámbito",
        help: "Capa de la jerarquía de resolución de configuración a la que pertenece esta fila.",
        options: {
          global: "Global",
          tenant: "Inquilino",
          user: "Usuario"
        }
      },
      user_id: {
        label: "Usuario",
        help: "Usuario propietario cuando scope=user; null en caso contrario."
      },
      value: {
        label: "Valor",
        help: "Valor codificado en JSON. Null cuando encrypted=true (véase value_enc)."
      },
      encrypted: {
        label: "Cifrado",
        help: "Si es verdadero, el valor se almacena cifrado en reposo en value_enc; la columna value es null."
      },
      locked: {
        label: "Bloqueado",
        help: "Si es verdadero, las filas de ámbitos inferiores no pueden sobrescribir este valor; las escrituras contra ámbitos inferiores devuelven 409. Lo utilizan los administradores de la plataforma para fijar un valor global para todos los tenants (cascada Fase 2)."
      },
      locked_reason: {
        label: "Motivo del bloqueo",
        help: "Explicación legible que se muestra en el tooltip de la UI cuando locked=true."
      },
      value_enc: {
        label: "Valor cifrado",
        help: "Payload de texto cifrado (envuelto con KMS). Se establece solo cuando encrypted=true."
      },
      updated_by: {
        label: "Actualizado por",
        help: "Último actor que escribió esta fila mediante SettingsService.set()."
      }
    },
    _views: {
      by_namespace: {
        label: "Por espacio de nombres"
      },
      tenant_only: {
        label: "Inquilino"
      },
      user_only: {
        label: "Usuario"
      },
      all_settings: {
        label: "Todos"
      }
    }
  },
  sys_secret: {
    label: "Secreto",
    pluralLabel: "Secretos",
    description: "Almacén cifrado al que hacen referencia los identificadores de sys_setting. Nunca contiene texto sin formato.",
    fields: {
      id: {
        label: "ID",
        help: "Identificador opaco al que hace referencia `sys_setting.value_enc`."
      },
      created_at: {
        label: "Creado el",
        help: "Momento en que se escribió por primera vez el cifrado."
      },
      rotated_at: {
        label: "Rotado el",
        help: "Momento en que el cifrado se volvió a envolver por última vez con una nueva clave KMS."
      },
      namespace: {
        label: "Espacio de nombres",
        help: "Espacio de nombres de ajustes al que pertenece este secreto."
      },
      key: {
        label: "Clave",
        help: "Clave del especificador dentro del espacio de nombres."
      },
      kms_key_id: {
        label: "ID de clave KMS",
        help: "Identificador externo de KMS (ARN, ID de recurso de GCP o `local`)."
      },
      alg: {
        label: "Algoritmo",
        help: "Etiqueta del algoritmo de cifrado/AEAD."
      },
      version: {
        label: "Versión",
        help: "Se incrementa cada vez que rotateKey() vuelve a envolver esta fila."
      },
      ciphertext: {
        label: "Texto cifrado",
        help: "Blob de texto cifrado codificado por el proveedor (base64 / JSON). La implementación lo define; solo el ICryptoProvider correspondiente puede leerlo."
      }
    },
    _views: {
      all: {
        label: "All Secrets"
      }
    }
  },
  sys_setting_audit: {
    label: "Registro de auditoría de ajustes",
    pluralLabel: "Auditoría de ajustes",
    description: "Registro de auditoría append-only para mutaciones de SettingsService.",
    fields: {
      id: {
        label: "ID"
      },
      created_at: {
        label: "Creado el",
        help: "Momento en que se registró la mutación."
      },
      namespace: {
        label: "Espacio de nombres"
      },
      key: {
        label: "Clave"
      },
      scope: {
        label: "Ámbito",
        help: "Capa de cascada en la que se escribió la fila.",
        options: {
          global: "Global",
          tenant: "Inquilino",
          user: "Usuario"
        }
      },
      action: {
        label: "Acción",
        help: "Tipo de mutación.",
        options: {
          set: "Establecer",
          reset: "Restablecer",
          lock: "Bloquear",
          unlock: "Desbloquear",
          rotate: "Rotar"
        }
      },
      actor_id: {
        label: "Actor",
        help: "Usuario que realizó la mutación; null para tareas del sistema."
      },
      source: {
        label: "Origen",
        help: "Punto de entrada de la mutación.",
        options: {
          ui: "UI",
          api: "API",
          migration: "Migración",
          import: "Importar",
          system: "Sistema"
        }
      },
      reason: {
        label: "Motivo",
        help: "Justificación en texto libre proporcionada por el actor (opcional)."
      },
      old_hash: {
        label: "Hash anterior",
        help: "SHA-256 del valor anterior (canonicalizado). Null cuando antes no estaba establecido."
      },
      new_hash: {
        label: "Hash nuevo",
        help: "SHA-256 del valor nuevo (canonicalizado). Null al restablecer."
      },
      encrypted: {
        label: "Cifrado",
        help: "Verdadero cuando el campo contiene material secreto (la rotación es relevante)."
      },
      request_id: {
        label: "ID de solicitud",
        help: "Se correlaciona con sys_audit_log / tracing."
      }
    },
    _views: {
      recent: {
        label: "Recent"
      }
    }
  },
  sys_migration: {
    label: "Data Migration",
    pluralLabel: "Data Migrations",
    description: "Deployment-level data-migration flags: which gated data migrations ran here and whether their self-check passed.",
    fields: {
      id: {
        label: "Migration ID",
        help: "Well-known migration id (e.g. adr-0104-file-references). One row per migration."
      },
      last_run_at: {
        label: "Last Run At",
        help: "When this migration last completed a gated (apply-mode) run on this deployment."
      },
      verified_at: {
        label: "Verified At",
        help: "When the self-check last PASSED. Null until it does, and cleared again by a later failing run — a regression closes the gate. Consumers require this to be set AND blocking = 0."
      },
      applied_at: {
        label: "Applied At",
        help: "When the backfill last ran in apply mode (writes enabled)."
      },
      blocking: {
        label: "Blocking Discrepancies",
        help: "Blocking discrepancies reported by the last self-check. The gate requires 0."
      },
      advisory: {
        label: "Advisory Findings",
        help: "Advisory findings from the last run (external URLs, stale owners, …) — cost storage or need a modelling decision, never block the gate."
      },
      details: {
        label: "Details (JSON)",
        help: "JSON-encoded counts from the last run, for diagnostics."
      },
      deviation_observed_at: {
        label: "Deviation Observed At",
        help: "When this deployment last ADMITTED a value its own verified contract rejects, through an OS_ALLOW_LAX_* escape hatch. Deliberately does NOT clear verified_at: it withdraws only the irreversible half of what the certificate authorises — byte deletion stops, validation and tombstoning continue. Cleared by the next apply-mode run."
      },
      deviation_detail: {
        label: "Deviation Detail (JSON)",
        help: "JSON-encoded first counterexample behind deviation_observed_at (object, field, type, parse issue), so an operator can find the value that closed the irreversible gate."
      },
      created_at: {
        label: "Created At"
      },
      updated_at: {
        label: "Updated At"
      }
    }
  }
};
