// Copyright (c) 2025 ObjectStack. Licensed under the Apache-2.0 license.

/**
 * Auto-generated by 'os i18n extract' for locale 'ja-JP'.
 * Edit translations in place; re-run extract (with --merge) to fill new gaps.
 * Do not hand-edit the structure — only the leaf string values.
 */

import type { TranslationData } from '@objectstack/spec/system';

export const jaJPMetadataForms: NonNullable<TranslationData['metadataForms']> = {
  object: {
    label: "オブジェクト",
    sections: {
      basics: {
        label: "基本",
        description: "ID、ラベル、分類。"
      },
      fields: {
        label: "フィールド",
        description: "データモデルを定義 — 各行がデータベーステーブルの列になる。"
      },
      capabilities: {
        label: "機能",
        description: "システム機能と API 公開。"
      },
      advanced: {
        label: "詳細",
        description: "ステートマシン、アクション、ストレージ。"
      }
    },
    fields: {
      name: {
        helpText: "snake_case の一意識別子（作成後は変更不可）"
      },
      label: {
        helpText: "単数表示名（例: \"Account\"）"
      },
      pluralLabel: {
        helpText: "複数表示名（例: \"Accounts\"）"
      },
      icon: {
        helpText: "Lucide アイコン名（例: \"building\", \"users\"）"
      },
      description: {
        helpText: "開発者向けドキュメント"
      },
      tags: {
        helpText: "分類タグ（例: \"sales\", \"system\"）"
      },
      active: {
        helpText: "オブジェクトが有効で使用可能か"
      },
      isSystem: {
        helpText: "システムオブジェクト（削除から保護）"
      },
      abstract: {
        helpText: "抽象ベース（インスタンス化不可）"
      },
      fields: {
        helpText: "このオブジェクトが保存する列を追加"
      },
      "fields.name": {
        helpText: "snake_case 識別子"
      },
      "fields.label": {
        helpText: "表示ラベル"
      },
      "fields.type": {
        helpText: "フィールド型"
      },
      "fields.reference": {
        helpText: "対象オブジェクト（lookup/master_detail 用）"
      },
      capabilities: {
        helpText: "システム機能の有効/無効"
      },
      datasource: {
        helpText: "対象データソース ID（既定: \"default\"）"
      }
    }
  },
  field: {
    label: "フィールド",
    sections: {
      basics: {
        label: "基本",
        description: "フィールドの基本 ID と制約。"
      },
      configuration: {
        label: "設定",
        description: "フィールド型別の設定（表示ブロックは選択した型による）。"
      },
      formula: {
        label: "数式と計算",
        description: "計算値とロールアップ集計。"
      },
      advanced: {
        label: "詳細",
        description: "データベース、UI、監査、セキュリティ設定。"
      }
    },
    fields: {
      name: {
        helpText: "一意識別子（snake_case、作成後は変更不可）"
      },
      label: {
        helpText: "ユーザー向け表示名"
      },
      type: {
        helpText: "このフィールドのデータ型"
      },
      group: {
        helpText: "フォームレイアウトのグループ名"
      },
      description: {
        helpText: "ユーザーに表示するヘルプテキスト"
      },
      required: {
        helpText: "ユーザーによる値入力が必須"
      },
      unique: {
        helpText: "複数レコードで同じ値を不可"
      },
      multiple: {
        helpText: "複数値を許可（select/lookup 用）"
      },
      defaultValue: {
        helpText: "新規レコードの既定値"
      },
      minLength: {
        helpText: "最小文字数"
      },
      maxLength: {
        helpText: "最大文字数"
      },
      min: {
        helpText: "最小値"
      },
      max: {
        helpText: "最大値"
      },
      precision: {
        helpText: "小数桁数（例: $10.50 なら 2）"
      },
      scale: {
        helpText: "小数部の桁数"
      },
      options: {
        helpText: "使用可能な選択肢（label/value ペア）"
      },
      reference: {
        helpText: "参照先オブジェクト名"
      },
      referenceFilters: {
        helpText: "フィルター式（例: \"active = true\"）"
      },
      deleteBehavior: {
        helpText: "参照先レコード削除時の動作"
      },
      expression: {
        helpText: "このフィールドを計算する CEL 式（読み取り専用化）"
      },
      summaryOperations: {
        helpText: "ロールアップ集計設定（親子関係用）"
      },
      cached: {
        helpText: "計算フィールドのキャッシュ設定"
      },
      columnName: {
        helpText: "データベース上の物理列名（既定はフィールド名）"
      },
      index: {
        helpText: "高速クエリ用のデータベースインデックスを作成"
      },
      externalId: {
        helpText: "upsert 操作用の外部 ID としてマーク"
      },
      readonly: {
        helpText: "フォームでフィールドを読み取り専用にする"
      },
      hidden: {
        helpText: "既定 UI ビューからフィールドを非表示"
      },
      searchable: {
        helpText: "グローバル検索結果に含める"
      },
      sortable: {
        helpText: "このフィールドでリストの並べ替えを許可"
      },
      auditTrail: {
        helpText: "ユーザーとタイムスタンプ付きで詳細変更を追跡"
      },
      trackFeedHistory: {
        helpText: "アクティビティフィードに変更を表示"
      },
      encryptionConfig: {
        helpText: "フィールドレベル暗号化（GDPR/HIPAA/PCI-DSS）"
      },
      maskingRule: {
        helpText: "PII 保護用データマスキングルール"
      }
    }
  },
  trigger: {
    label: "トリガー"
  },
  validation: {
    label: "検証ルール"
  },
  hook: {
    label: "フック",
    sections: {
      identity: {
        label: "ID",
        description: "このフックの内容と発火タイミング。"
      },
      body: {
        label: "本文",
        description: "フック発火時に実行されるインライン式またはサンドボックス化 JavaScript。"
      },
      legacy_handler: {
        label: "レガシーハンドラー",
        description: "関数名参照 — body を推奨、非推奨。"
      },
      execution: {
        label: "実行"
      }
    },
    fields: {
      name: {
        helpText: "snake_case 識別子（作成後は変更不可）"
      },
      object: {
        helpText: "対象オブジェクト名（グローバルは \"*\"）"
      },
      events: {
        helpText: "ライフサイクルイベント（例: beforeInsert, afterUpdate）"
      },
      priority: {
        helpText: "小さい数値ほど先に実行"
      },
      body: {
        helpText: "L1 式または L2 サンドボックス JS body"
      },
      "body.language": {
        helpText: "expression = 純粋な数式; js = サンドボックス化 JavaScript"
      },
      "body.source": {
        helpText: "関数 body ソース — トップレベル import 不可"
      },
      "body.capabilities": {
        helpText: "許可する ctx API（api.read, api.write, crypto.uuid, log, …）"
      },
      "body.timeoutMs": {
        helpText: "呼び出しごとのタイムアウト（ms）"
      },
      handler: {
        helpText: "ハンドラー関数名（非推奨 — `body` を推奨）"
      },
      async: {
        helpText: "バックグラウンドで実行し、トランザクションをブロックしない"
      },
      condition: {
        helpText: "任意の数式 — false 評価時はフックをスキップ"
      }
    }
  },
  view: {
    label: "ビュー",
    sections: {
      basics: {
        label: "基本",
        description: "ID と主要サーフェス。"
      },
      columns_filters: {
        label: "列とフィルター",
        description: "表示する行とユーザーのフィルター方法。"
      },
      table_options: {
        label: "テーブルオプション",
        description: "グリッド専用の表示オプション。"
      },
      kanban: {
        label: "カンバン",
        description: "カンバン専用のボード設定。"
      },
      calendar: {
        label: "カレンダー",
        description: "カレンダー専用設定。"
      },
      gantt: {
        label: "ガント",
        description: "ガント専用設定。"
      },
      gallery: {
        label: "ギャラリー",
        description: "ギャラリー専用設定。"
      },
      timeline: {
        label: "タイムライン",
        description: "タイムライン専用設定。"
      },
      chart: {
        label: "チャート",
        description: "チャート専用設定。"
      },
      navigation_sharing: {
        label: "ナビゲーションと共有",
        description: "このビューの表示場所と閲覧可能者。"
      }
    },
    fields: {
      name: {
        helpText: "snake_case、environment ごとに一意"
      },
      type: {
        helpText: "主要ビューサーフェス"
      },
      data: {
        helpText: "データソース — 例: {\"provider\":\"object\",\"object\":\"task\"}"
      },
      columns: {
        helpText: "表示する列（選択オブジェクトのフィールド名）"
      },
      filter: {
        helpText: "フィルター条件"
      },
      sort: {
        helpText: "既定の並び順"
      },
      searchableFields: {
        helpText: "クイック検索で使用可能なフィールド名"
      },
      filterableFields: {
        helpText: "フィルターで使用可能なフィールド名"
      }
    }
  },
  page: {
    label: "ページ",
    sections: {
      basics: {
        label: "基本",
        description: "ページ ID とテンプレート。"
      },
      data_context: {
        label: "データコンテキスト",
        description: "レコードバインドとページローカル状態。"
      },
      layout: {
        label: "レイアウト",
        description: "ページ領域とそこに配置するコンポーネント。"
      },
      advanced: {
        label: "詳細",
        description: "有効化、対象ユーザー、アクセシビリティ。"
      }
    },
    fields: {
      name: {
        helpText: "一意識別子（snake_case）"
      },
      label: {
        helpText: "ユーザーに表示するページタイトル"
      },
      icon: {
        helpText: "ナビゲーションメニューのアイコン"
      },
      type: {
        helpText: "ページ種別（record, home, app, dashboard など）"
      },
      template: {
        helpText: "レイアウトテンプレート（例: \"header-sidebar-main\"）"
      },
      description: {
        helpText: "ナビゲーション用ページ説明"
      },
      object: {
        helpText: "バインド先オブジェクト（Record ページ用）"
      },
      variables: {
        helpText: "ページローカル状態変数"
      },
      regions: {
        helpText: "コンポーネントを含むレイアウト領域（header, main, sidebar, footer）"
      },
      isDefault: {
        helpText: "このページ種別の既定ページに設定"
      },
      kind: {
        helpText: "ページ上書きモード: full または slotted（record ページ用）"
      },
      assignedProfiles: {
        helpText: "このページにアクセス可能なプロファイル"
      },
      aria: {
        helpText: "アクセシビリティ属性（ARIA ラベル、ロール）"
      }
    }
  },
  dashboard: {
    label: "ダッシュボード",
    sections: {
      basics: {
        label: "基本",
        description: "ダッシュボード ID と説明。"
      },
      layout: {
        label: "レイアウト",
        description: "グリッドサイズと更新間隔。"
      },
      widgets: {
        label: "ウィジェット",
        description: "グリッドに配置するカードとチャート。"
      },
      filters: {
        label: "フィルター",
        description: "ウィジェット全体に適用する既定およびグローバルフィルター。"
      },
      advanced: {
        label: "詳細",
        description: "アクセシビリティとパフォーマンス調整。"
      }
    },
    fields: {
      name: {
        helpText: "snake_case の一意識別子"
      },
      label: {
        helpText: "表示名"
      },
      columns: {
        helpText: "グリッド列（既定 12）"
      },
      gap: {
        helpText: "グリッド間隔（Tailwind 単位）"
      },
      refreshInterval: {
        helpText: "自動更新（秒）"
      },
      header: {
        helpText: "ダッシュボードヘッダー設定（title, subtitle, actions）"
      },
      widgets: {
        helpText: "位置とサイズを持つダッシュボードウィジェット"
      },
      dateRange: {
        helpText: "既定の日付範囲セレクター"
      },
      globalFilters: {
        helpText: "全ウィジェットに適用するフィルター"
      },
      aria: {
        helpText: "アクセシビリティラベル"
      },
      performance: {
        helpText: "キャッシュと最適化設定"
      }
    }
  },
  app: {
    label: "アプリケーション",
    sections: {
      basics: {
        label: "基本",
        description: "アプリ ID と有効化。"
      },
      navigation: {
        label: "ナビゲーション",
        description: "サイドバー項目とエリアグループ化。"
      },
      content: {
        label: "コンテンツ",
        description: "このアプリが使用するオブジェクトと API。"
      },
      branding: {
        label: "ブランディング",
        description: "テーマカラーとロゴ。"
      },
      access_and_sharing: {
        label: "アクセスと共有",
        description: "このアプリにアクセス可能なユーザーと埋め込み方法。"
      }
    },
    fields: {
      name: {
        helpText: "snake_case、一意"
      },
      icon: {
        helpText: "Lucide アイコン名（例: \"users\", \"briefcase\"）"
      },
      isDefault: {
        helpText: "新規ユーザーの既定アプリにする"
      },
      navigation: {
        helpText: "ナビツリー — 再帰構造"
      },
      areas: {
        helpText: "項目を折りたたみ可能なエリアにグループ化"
      },
      homePageId: {
        helpText: "アプリ起動時のランディングページ"
      },
      mobileNavigation: {
        helpText: "モバイル用ボトムタブバー設定"
      },
      objects: {
        helpText: "このアプリが公開するオブジェクト名"
      },
      apis: {
        helpText: "API エンドポイント定義"
      },
      defaultAgent: {
        helpText: "常駐アシスタントボタン用 AI エージェント"
      },
      branding: {
        helpText: "プライマリ/セカンダリカラー、ロゴ、テーマ"
      },
      requiredPermissions: {
        helpText: "このアプリへのアクセスに必要な権限"
      },
      sharing: {
        helpText: "公開/内部/制限付きアクセス制御"
      },
      embed: {
        helpText: "iFrame 埋め込み設定"
      },
      aria: {
        helpText: "アクセシビリティラベル"
      }
    }
  },
  action: {
    label: "アクション",
    sections: {
      basics: {
        label: "基本",
        description: "アクション ID と表示。"
      },
      behavior: {
        label: "動作",
        description: "アクション発火時の動作を設定。"
      },
      placement: {
        label: "配置",
        description: "アクションボタンの表示場所とタイミング。"
      },
      advanced: {
        label: "詳細",
        description: "一括操作、AI 公開、API リクエスト形状。"
      }
    },
    fields: {
      name: {
        helpText: "一意識別子（snake_case）"
      },
      label: {
        helpText: "ユーザーに表示するボタンテキスト"
      },
      objectName: {
        helpText: "このアクションが属するオブジェクト（任意）"
      },
      icon: {
        helpText: "Lucide アイコン名（例: \"check\", \"x-circle\"）"
      },
      type: {
        helpText: "クリック時の動作"
      },
      variant: {
        helpText: "ボタンスタイル（primary=blue, danger=red, ghost=transparent）"
      },
      target: {
        helpText: "呼び出す URL、フロー名、または API エンドポイント"
      },
      method: {
        helpText: "HTTP メソッド（GET, POST, PUT, DELETE）"
      },
      body: {
        helpText: "実行する JavaScript コード"
      },
      params: {
        helpText: "ユーザー入力パラメーター（実行前にフォームを表示）"
      },
      confirmText: {
        helpText: "確認メッセージ（例: \"Are you sure?\"）"
      },
      successMessage: {
        helpText: "完了後の成功メッセージ"
      },
      refreshAfter: {
        helpText: "アクション完了後にリスト/ページを更新"
      },
      locations: {
        helpText: "このアクションの表示場所（toolbar, row menu など）"
      },
      component: {
        helpText: "レンダリング方法（button, icon, menu item）"
      },
      visible: {
        helpText: "CEL 式: 条件が true の場合のみ表示"
      },
      disabled: {
        helpText: "CEL 式: 条件が true の場合に無効化"
      },
      shortcut: {
        helpText: "キーボードショートカット（例: \"Ctrl+S\", \"Cmd+Enter\"）"
      },
      bulkEnabled: {
        helpText: "選択した複数レコードへの適用を許可"
      },
      aiExposed: {
        helpText: "AI エージェントによるこのアクションの呼び出しを許可"
      },
      recordIdParam: {
        helpText: "レコード ID 用 body パラメーター名"
      },
      recordIdField: {
        helpText: "レコード ID として使用するフィールド（既定: \"id\"）"
      },
      bodyShape: {
        helpText: "リクエスト body 構造（flat または nested）"
      }
    }
  },
  report: {
    label: "レポート",
    sections: {
      basics: {
        label: "基本",
        description: "ID とデータソース。"
      },
      columns: {
        label: "列",
        description: "レポート出力に表示する列。"
      },
      groupings: {
        label: "グループ化",
        description: "行（matrix レポートでは列も）のグループ化方法。"
      },
      joined_blocks: {
        label: "結合ブロック",
        description: "1 つのレポートに結合する追加ブロック（joined レポートのみ）。"
      },
      filter_and_chart: {
        label: "フィルターとチャート",
        description: "レポートレベルのフィルターとチャート表示。"
      },
      advanced: {
        label: "詳細",
        description: "アクセシビリティとパフォーマンス調整。"
      }
    },
    fields: {
      name: {
        helpText: "snake_case の一意識別子"
      },
      objectName: {
        helpText: "データソースオブジェクト"
      },
      type: {
        helpText: "レポート種別: tabular/summary/matrix/joined"
      },
      columns: {
        helpText: "レポートに表示する列"
      },
      groupingsDown: {
        helpText: "行グループ化レベル"
      },
      groupingsAcross: {
        helpText: "列グループ化レベル（matrix のみ）"
      },
      blocks: {
        helpText: "複数オブジェクトを結合（joined レポートのみ）"
      },
      filter: {
        helpText: "レポートレベルのフィルター"
      },
      chart: {
        helpText: "チャート設定（type, legend, colors）"
      },
      aria: {
        helpText: "アクセシビリティラベル"
      },
      performance: {
        helpText: "キャッシュと最適化"
      }
    }
  },
  flow: {
    label: "フロー",
    sections: {
      basics: {
        label: "基本",
        description: "フロー ID と開始方法。"
      },
      canvas: {
        label: "キャンバス",
        description: "ノード、エッジ、フロー変数 — 複雑なフローはビジュアルデザイナーを検討。"
      },
      execution: {
        label: "実行",
        description: "デプロイ状態、ID、エラー処理。"
      }
    },
    fields: {
      name: {
        helpText: "一意識別子（snake_case）"
      },
      label: {
        helpText: "ユーザー向け表示名"
      },
      type: {
        helpText: "フローの開始方法（autolaunched, record_change, schedule, screen, api）"
      },
      template: {
        helpText: "再利用可能なサブフローか（他のフローから呼び出し可）"
      },
      description: {
        helpText: "このフローの処理内容"
      },
      nodes: {
        helpText: "⚠️ JSON ではなく Flow Designer ビジュアルエディターの利用を検討"
      },
      edges: {
        helpText: "ノード間の接続 — 編集しやすい Flow Designer を使用"
      },
      variables: {
        helpText: "フロー変数（inputs/outputs）"
      },
      status: {
        helpText: "デプロイ状態: draft → active → obsolete"
      },
      version: {
        helpText: "バージョン番号（自動インクリメント）"
      },
      runAs: {
        helpText: "system（admin）または user（現在のユーザー権限）として実行"
      },
      errorHandling: {
        helpText: "ノード失敗時の処理（fail, retry, continue）"
      }
    }
  },
  workflow: {
    label: "ワークフロー",
    sections: {
      basics: {
        label: "基本",
        description: "ID と発火元のオブジェクト/イベント。"
      },
      actions: {
        label: "アクション",
        description: "発火時にこのワークフローが行う処理。"
      },
      advanced: {
        label: "詳細",
        description: "順序と実行動作。"
      }
    },
    fields: {
      name: {
        helpText: "一意識別子（snake_case）"
      },
      objectName: {
        helpText: "このワークフローを発火するオブジェクト"
      },
      triggerType: {
        helpText: "実行タイミング: on_create, on_update, on_delete, schedule"
      },
      active: {
        helpText: "このワークフローの有効/無効"
      },
      description: {
        helpText: "このワークフローの処理内容"
      },
      criteria: {
        helpText: "CEL 式: この条件が true の場合のみ実行"
      },
      actions: {
        helpText: "即時実行するアクション（field update, email, API call など）"
      },
      timeTriggers: {
        helpText: "スケジュールアクション（例: 期限 1 日前にリマインダー送信）"
      },
      executionOrder: {
        helpText: "複数ワークフロー一致時の実行順（小さいほど早い）"
      }
    }
  },
  job: {
    label: "バックグラウンドジョブ"
  },
  datasource: {
    label: "データソース"
  },
  translation: {
    label: "翻訳"
  },
  router: {
    label: "ルーター"
  },
  function: {
    label: "関数"
  },
  service: {
    label: "サービス"
  },
  email_template: {
    label: "メールテンプレート",
    sections: {
      identity: {
        label: "ID",
        description: "識別子とコンテンツ型。id は sendTemplate({ template: id, ... }) で参照される。"
      },
      subject: {
        label: "件名",
        description: "件名行。{{var.path}} 補間をサポート。"
      },
      body: {
        label: "本文",
        description: "メール本文。変数には {{var}} を使用。エディターは body 型に基づきハイライト。"
      },
      variables_and_attachments: {
        label: "変数と添付ファイル",
        description: "宣言済みテンプレート変数と任意の添付ファイル。"
      }
    },
    fields: {
      id: {
        helpText: "テンプレート id（例: auth.password_reset）"
      },
      body: {
        helpText: "本文コンテンツ。Body Type に基づき HTML、プレーンテキスト、Markdown としてレンダリング。"
      },
      variables: {
        helpText: "subject/body で参照する変数名リスト"
      },
      attachments: {
        helpText: "[{ \"name\": \"...\", \"url\": \"...\" }]"
      }
    }
  },
  permission: {
    label: "権限セット",
    sections: {
      identity: {
        label: "ID",
        description: "権限セットはプロファイルに追加アクセス権を重ねる。プロファイルは各ユーザーに 1:1 で割り当てる基本セット。"
      },
      system_permissions: {
        label: "システム権限",
        description: "特定オブジェクトに紐づかない高レベル機能 — 例: manage_users, view_audit_logs。"
      },
      object_and_field_permissions: {
        label: "オブジェクトとフィールド権限",
        description: "オブジェクト単位の CRUD + フィールド単位の FLS。マトリックスエディターで編集、またはここに JSON を貼り付け。"
      },
      tab_and_row_level_security: {
        label: "タブと行レベルセキュリティ",
        description: "タブ表示、RLS ポリシー、述語評価用カスタムコンテキスト変数。"
      }
    },
    fields: {
      name: {
        helpText: "マシン名（snake_case）"
      },
      label: {
        helpText: "管理者向け表示ラベル"
      },
      isProfile: {
        helpText: "Profile = ユーザーに割り当てる基本セット。Permission Set = 追加権限。"
      },
      systemPermissions: {
        helpText: "システム機能キーのリスト"
      },
      objects: {
        helpText: "{ \"account\": { allowRead: true, allowEdit: true, ... } }"
      },
      fields: {
        helpText: "{ \"account.amount\": { readable: true, editable: false } }"
      },
      tabPermissions: {
        helpText: "{ \"app_crm\": \"visible\", \"app_admin\": \"hidden\" }"
      },
      rowLevelSecurity: {
        helpText: "RLS ポリシーの配列（rls.zod.ts 参照）"
      },
      contextVariables: {
        helpText: "RLS 述語で参照するカスタム変数"
      }
    }
  },
  profile: {
    label: "プロファイル",
    sections: {
      identity: {
        label: "ID",
        description: "権限セットはプロファイルに追加アクセス権を重ねる。プロファイルは各ユーザーに 1:1 で割り当てる基本セット。"
      },
      system_permissions: {
        label: "システム権限",
        description: "特定オブジェクトに紐づかない高レベル機能 — 例: manage_users, view_audit_logs。"
      },
      object_and_field_permissions: {
        label: "オブジェクトとフィールド権限",
        description: "オブジェクト単位の CRUD + フィールド単位の FLS。マトリックスエディターで編集、またはここに JSON を貼り付け。"
      },
      tab_and_row_level_security: {
        label: "タブと行レベルセキュリティ",
        description: "タブ表示、RLS ポリシー、述語評価用カスタムコンテキスト変数。"
      }
    },
    fields: {
      name: {
        helpText: "マシン名（snake_case）"
      },
      label: {
        helpText: "管理者向け表示ラベル"
      },
      isProfile: {
        helpText: "Profile = ユーザーに割り当てる基本セット。Permission Set = 追加権限。"
      },
      systemPermissions: {
        helpText: "システム機能キーのリスト"
      },
      objects: {
        helpText: "{ \"account\": { allowRead: true, allowEdit: true, ... } }"
      },
      fields: {
        helpText: "{ \"account.amount\": { readable: true, editable: false } }"
      },
      tabPermissions: {
        helpText: "{ \"app_crm\": \"visible\", \"app_admin\": \"hidden\" }"
      },
      rowLevelSecurity: {
        helpText: "RLS ポリシーの配列（rls.zod.ts 参照）"
      },
      contextVariables: {
        helpText: "RLS 述語で参照するカスタム変数"
      }
    }
  },
  role: {
    label: "ロール",
    sections: {
      role: {
        label: "ロール",
        description: "ロールはレコード共有に使う階層を構成（sales VP → sales mgr → sales rep）。権限自体は Permission Sets と Profiles に存在。"
      }
    },
    fields: {
      name: {
        helpText: "snake_case"
      },
      parent: {
        helpText: "親ロールのマシン名（Reports To）"
      }
    }
  },
  agent: {
    label: "AI エージェント",
    sections: {
      identity: {
        label: "ID",
        description: "ユーザーから見たこのエージェントの表示と参照。"
      },
      ai_configuration: {
        label: "AI 設定",
        description: "モデル選択、指示、計画、メモリ。"
      },
      capabilities: {
        label: "機能",
        description: "エージェントが使用できるスキル、ツール、ナレッジソース。"
      },
      access: {
        label: "アクセスとセキュリティ",
        description: "このエージェントを使用できるユーザーと適用する安全対策。"
      }
    },
    fields: {
      name: {
        helpText: "一意識別子（snake_case）"
      },
      label: {
        helpText: "表示名（例: \"Sales Assistant\"）"
      },
      role: {
        helpText: "エージェントペルソナ（例: \"Customer Support Specialist\"）"
      },
      avatar: {
        helpText: "アバター画像 URL"
      },
      active: {
        helpText: "このエージェントの有効/無効"
      },
      instructions: {
        helpText: "システムプロンプト — エージェントの振る舞いと可能な操作を指定"
      },
      model: {
        helpText: "AI モデル設定（provider, model name, temperature など）"
      },
      planning: {
        helpText: "自律推論設定（strategy, max iterations, replan）"
      },
      memory: {
        helpText: "メモリ管理（short-term, long-term, reflection）"
      },
      lifecycle: {
        helpText: "会話フローを定義するステートマシン"
      },
      skills: {
        helpText: "スキル名（Agent→Skill→Tool アーキテクチャ）"
      },
      tools: {
        helpText: "直接ツール参照（レガシーモード）"
      },
      knowledge: {
        helpText: "RAG ナレッジアクセス設定"
      },
      visibility: {
        helpText: "スコープ: global, organization, または private"
      },
      access: {
        helpText: "このエージェントとチャット可能なユーザー ID またはロール名"
      },
      permissions: {
        helpText: "このエージェントの使用に必要な権限"
      },
      tenantId: {
        helpText: "特定 organization ID に制限"
      },
      guardrails: {
        helpText: "安全ルールとコンテンツポリシー"
      }
    }
  },
  tool: {
    label: "AI ツール",
    sections: {
      basics: {
        label: "基本",
        description: "ツール ID と AI 向け説明。"
      },
      schemas: {
        label: "スキーマ",
        description: "ツールが受け取る入力と出力の形状。"
      },
      access_and_safety: {
        label: "アクセスと安全性",
        description: "権限と確認要件。"
      }
    },
    fields: {
      name: {
        helpText: "一意識別子（snake_case）"
      },
      label: {
        helpText: "Studio UI 向け表示名"
      },
      description: {
        helpText: "AI にこのツールの使用タイミングを指示 — 具体的に！"
      },
      category: {
        helpText: "ツールカテゴリ（data, action, flow, integration など）"
      },
      objectName: {
        helpText: "関連オブジェクト（このツールが特定オブジェクトを扱う場合）"
      },
      active: {
        helpText: "このツールの有効/無効"
      },
      builtIn: {
        helpText: "プラットフォーム組み込みツール（ユーザー定義との対比）"
      },
      parameters: {
        helpText: "入力パラメーター — 次のようなプロパティを定義: {name: {type: \"string\", description: \"...\"}}"
      },
      outputSchema: {
        helpText: "検証用出力スキーマ（任意）"
      },
      requiresConfirmation: {
        helpText: "実行前にユーザー承認を求める（破壊的アクション用）"
      },
      permissions: {
        helpText: "このツールの使用に必要な権限"
      }
    }
  },
  skill: {
    label: "AI スキル",
    sections: {
      basics: {
        label: "基本",
        description: "スキル ID と人間向け説明。"
      },
      ai_instructions: {
        label: "AI 指示",
        description: "エージェントがこのスキルで推論する方法。"
      },
      triggers: {
        label: "トリガー",
        description: "このスキルの起動タイミング。"
      },
      access: {
        label: "アクセス",
        description: "このスキルの使用に必要な権限。"
      }
    },
    fields: {
      name: {
        helpText: "一意識別子（snake_case）"
      },
      label: {
        helpText: "表示名（例: \"Case Management\"）"
      },
      description: {
        helpText: "このスキルの処理内容"
      },
      active: {
        helpText: "このスキルの有効/無効"
      },
      instructions: {
        helpText: "AI への指示 — これらのツールを併用する方法を指定"
      },
      tools: {
        helpText: "ツール名（ワイルドカード対応: action_*）"
      },
      triggerPhrases: {
        helpText: "このスキルを起動する自然言語フレーズ"
      },
      triggerConditions: {
        helpText: "プログラム条件（例: objectName == \"case\"）"
      },
      permissions: {
        helpText: "このスキルの使用に必要な権限"
      }
    }
  }
};
